import { ReadingCard } from "@/components/seo/ReadingCard";

const principles = [
  ["Prudence", "We prefer sober readings over attention-grabbing conclusions."],
  ["Traceability", "Each module declares source, state, frequency and main limit."],
  ["Privacy", "No personal answers, portfolios or wealth data are stored."],
  ["No prediction", "The system organizes context; it does not forecast prices."],
  ["Education", "Tools help users think better, not delegate judgment."],
  ["Separation", "Market context is not the same as personalized advice."],
];

const systemMap = [
  ["Public data / sources", "Market data, volatility, flows, quantitative outputs and educational criteria."],
  ["Processing", "Server-side adapters, static calculations, validations and prudent fallbacks."],
  ["Statistical readings", "Regime, rotation, levels, drawdowns, metrics and relative signals."],
  ["Educational tools", "Diagnostic, protection, trends, methodology and reading labs."],
  ["Human decision", "The person contrasts, asks, documents and decides outside the platform."],
];

const tools = [
  {
    name: "Market Regime Dashboard",
    does: "Organizes volatility, sector rotation and BTC ETF flows.",
    doesNot: "Does not provide execution signals.",
    source: "Alpha Vantage, FRED/VIX, Bitbo and pending states where applicable.",
    limit: "External sources may be delayed, fail or change format.",
  },
  {
    name: "Investor Diagnostic",
    does: "Helps organize horizon, tolerance, behavior and experience.",
    doesNot: "Does not replace a formal regulatory suitability assessment.",
    source: "Internal educational questionnaire.",
    limit: "Does not store answers or build a legal user profile.",
  },
  {
    name: "Statistical Levels",
    does: "Calculates levels, extremes, drawdowns and historical patterns by asset.",
    doesNot: "Does not predict breakouts or future support levels.",
    source: "Static historical dataset generated locally.",
    limit: "Quality depends on available history for each asset.",
  },
  {
    name: "DRL Evaluation Protocol",
    does: "Presents the protocol, assumptions, costs, cash, comparable benchmarks, bootstrap, White Reality Check and practical limits.",
    doesNot: "Does not prove that TD3 always wins, does not claim broad statistical superiority and does not recommend allocations.",
    source: "Interactive research paper. TD3 is used as a DRL case study, not as a superiority claim for the algorithm.",
    limit: "Historical and experimental results do not guarantee future behavior.",
  },
  {
    name: "Trends",
    does: "Turns technological, economic and social changes into educational observation hypotheses.",
    doesNot: "Does not recommend assets, validate that a trend is a good investment or replace analysis of price, vehicle, horizon and risk.",
    source: "Editorial framework using sector sources, macro data, institutional reports, Google Trends as an attention signal and holdings/13F as delayed observation with limitations.",
    limit: "A real trend can still be a poor investment if it is expensive, lacks a clear vehicle, is already priced in or does not fit the portfolio.",
  },
  {
    name: "Protect Your Money",
    does: "Organizes educational red flags before trusting a proposal.",
    doesNot: "Does not officially verify entities or declare fraud.",
    source: "Public CNMV / MiFID II criteria.",
    limit: "Should be complemented with official source checks.",
  },
];

const sourceNotes = [
  ["Market", "Alpha Vantage for sector ETFs, FRED/VIX, Bitbo, State Street / GLD and pending data where applicable."],
  ["Statistical levels", "The current dataset is a static snapshot generated by script and committed; the repo does not show evidence of a deploy cron that regenerates it automatically."],
  ["Updates", "Some modules update server-side with cache; others require explicit regeneration through static scripts."],
  ["Fallbacks", "If a source fails, the module should show a prudent state instead of presenting demo data as real."],
  ["FedWatch", "It remains pending or zero-weighted until the automated source is correctly enabled."],
];

const privacyItems = ["No accounts", "No current cookies", "No real analytics", "No personal answers stored", "No portfolios stored", "No browser persistence"];

const limits = [
  "This platform does not provide financial, legal, tax or wealth advice.",
  "It does not recommend assets, products, weights or execution timing.",
  "It does not predict future prices, returns, volatility or flows.",
  "It does not replace a formal regulatory suitability or appropriateness assessment.",
  "Data may fail, be delayed, revised or temporarily unavailable.",
  "Quantitative models show historical results, not future guarantees.",
];

const researchQuestion =
  "Can a disciplined evaluation protocol distinguish statistically credible and practically feasible DRL portfolio performance from apparent backtest strength?";

function Eyebrow({ children }: { children: React.ReactNode }) {
  return <p className="text-xs font-semibold uppercase tracking-[0.18em] text-brass">{children}</p>;
}

export default function EnglishMethodologyPage() {
  return (
    <div className="mx-auto max-w-7xl px-5 py-10 md:py-14">
      <section className="border-b border-line pb-9">
        <Eyebrow>How the system works</Eyebrow>
        <h1 className="mt-4 max-w-4xl text-4xl font-semibold leading-[1.02] text-ink md:text-6xl">Methodology</h1>
        <p className="mt-5 max-w-3xl text-lg leading-8 text-muted">
          How the readings are built, what data they use and where their limits are.
        </p>
      </section>

      <ReadingCard title="Reading card" items={[
        { label: "What it is", value: "A traceability page explaining how readings are built, which sources they use and what their limits are." },
        { label: "What it is for", value: "It helps audit the method before relying on a tool, report or market reading." },
        { label: "Main sources", value: "Documented public sources: Alpha Vantage, FRED/VIX, Bitbo, State Street / GLD, precomputed historical data and tool-specific sources." },
        { label: "Limits", value: "The methodology reduces ambiguity but does not remove source errors, delays, API changes or proxy limitations." },
      ]} />

      <section className="mt-8 border border-line bg-panel p-5 md:p-6">
        <Eyebrow>DRL research</Eyebrow>
        <h2 className="mt-2 text-2xl font-semibold text-ink md:text-3xl">DRL Evaluation Protocol</h2>
        <p className="mt-4 max-w-4xl text-base leading-7 text-muted">{researchQuestion}</p>
        <p className="mt-4 max-w-4xl border-l border-petrol/30 pl-4 text-sm leading-6 text-muted">
          TD3 is used as a DRL case study, not as a claim that the algorithm is superior.
        </p>
      </section>

      <section className="mt-8">
        <Eyebrow>Principles</Eyebrow>
        <div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
          {principles.map(([title, text]) => (
            <article key={title} className="border border-line bg-panel p-4">
              <h2 className="font-semibold text-ink">{title}</h2>
              <p className="mt-2 text-sm leading-6 text-muted">{text}</p>
            </article>
          ))}
        </div>
      </section>

      <section className="mt-8 border border-line bg-panel p-5 md:p-6">
        <div className="max-w-3xl">
          <Eyebrow>System map</Eyebrow>
          <h2 className="mt-2 text-2xl font-semibold text-ink md:text-3xl">From public data to human decision</h2>
        </div>
        <div className="mt-6 grid gap-3 lg:grid-cols-5">
          {systemMap.map(([title, text], index) => (
            <article key={title} className="relative border border-line bg-panelSoft p-4">
              <span className="text-xs font-semibold text-brass">{String(index + 1).padStart(2, "0")}</span>
              <h3 className="mt-3 font-semibold text-ink">{title}</h3>
              <p className="mt-2 text-sm leading-6 text-muted">{text}</p>
              {index < systemMap.length - 1 ? <span className="absolute right-3 top-3 hidden text-muted lg:block">→</span> : null}
            </article>
          ))}
        </div>
      </section>

      <section className="mt-8">
        <div className="max-w-3xl">
          <Eyebrow>Tool by tool</Eyebrow>
          <h2 className="mt-2 text-2xl font-semibold text-ink md:text-3xl">What each tool does, does not do and where it ends</h2>
        </div>
        <div className="mt-6 overflow-x-auto">
          <table className="w-full min-w-[980px] border-collapse text-left text-[13px]">
            <thead className="text-muted">
              <tr className="border-b border-line">
                <th className="py-3 pr-4 font-medium">Tool</th>
                <th className="py-3 pr-4 font-medium">What it does</th>
                <th className="py-3 pr-4 font-medium">What it does not do</th>
                <th className="py-3 pr-4 font-medium">Source / criterion</th>
                <th className="py-3 pr-4 font-medium">Main limit</th>
              </tr>
            </thead>
            <tbody>
              {tools.map((tool) => (
                <tr key={tool.name} className="border-b border-line/70 align-top">
                  <td className="py-4 pr-4 font-semibold text-ink">{tool.name}</td>
                  <td className="py-4 pr-4 text-muted">{tool.does}</td>
                  <td className="py-4 pr-4 text-muted">{tool.doesNot}</td>
                  <td className="py-4 pr-4 text-muted">{tool.source}</td>
                  <td className="py-4 pr-4 text-muted">{tool.limit}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>

      <section className="mt-8 grid gap-5 lg:grid-cols-[0.95fr_1.05fr]">
        <div className="border border-line bg-panel p-5 md:p-6">
          <Eyebrow>Sources and updates</Eyebrow>
          <h2 className="mt-2 text-2xl font-semibold text-ink">Data needs visible state</h2>
          <p className="mt-4 text-sm leading-6 text-muted">
            The platform distinguishes automated data, manual data, educational demo data and pending sources. Source state matters as much as the number.
          </p>
        </div>
        <div className="grid gap-3 sm:grid-cols-2">
          {sourceNotes.map(([title, text]) => (
            <article key={title} className="border border-line bg-panelSoft p-4">
              <h3 className="font-semibold text-ink">{title}</h3>
              <p className="mt-2 text-sm leading-6 text-muted">{text}</p>
            </article>
          ))}
        </div>
      </section>

      <section className="mt-8 grid gap-5 lg:grid-cols-[1fr_1fr]">
        <div className="border border-line bg-panel p-5 md:p-6">
          <Eyebrow>Privacy</Eyebrow>
          <h2 className="mt-2 text-2xl font-semibold text-ink">The reading happens without storing your financial life</h2>
          <div className="mt-5 flex flex-wrap gap-2">
            {privacyItems.map((item) => (
              <span key={item} className="border border-line bg-panelSoft px-3 py-2 text-xs font-semibold uppercase tracking-[0.12em] text-muted">
                {item}
              </span>
            ))}
          </div>
          <p className="mt-5 text-sm leading-6 text-muted">
            Some selections may live temporarily in the interface or URL so a view can be reproduced, but personal answers and wealth profiles are not stored.
          </p>
        </div>

        <div className="border border-line bg-panel p-5 md:p-6">
          <Eyebrow>Limits</Eyebrow>
          <h2 className="mt-2 text-2xl font-semibold text-ink">What the platform does not promise</h2>
          <ul className="mt-5 grid gap-2 text-sm leading-6 text-muted">
            {limits.map((item) => (
              <li key={item} className="border-l border-line pl-3">{item}</li>
            ))}
          </ul>
        </div>
      </section>
    </div>
  );
}
