import { TrendsAnalytics } from "./TrendsAnalytics";
import Link from "next/link";
import { trendsMethodologyCopy } from "@/lib/trends/methodology-copy";
import { trendsCopy } from "@/lib/trends/copy";
import { capitalCopy } from "@/lib/trends/capital/copy";
import { trendsMethodologyPath, trendsPath, type TrendEvidence, type TrendPhase } from "@/lib/trends/catalog";
import { getCapitalData } from "@/lib/trends/capital/get-capital-data";
import { capitalPeriodLabel } from "./CapitalDisclosureSection";
import type { Movement } from "@/lib/trends/capital/types";
import { JsonLd } from "@/components/seo/JsonLd";
import { buildBreadcrumbJsonLd, buildWebPageJsonLd } from "@/lib/seo/structured-data";
import styles from "./trends.module.css";
const heading = "text-2xl font-semibold leading-tight text-ink";
const section = "scroll-mt-24 border-t border-line py-8 md:py-10";
export async function TrendsMethodologyPage({ locale }: { locale: "es" | "en" }) {
  const copy = trendsMethodologyCopy[locale], labels = trendsCopy[locale].radar, capital = capitalCopy[locale];
  const dataset = await getCapitalData(), pathname = trendsMethodologyPath(locale);
  return <article data-trends-page className={`${styles.page} mx-auto max-w-7xl px-4 py-8 md:px-5 md:py-12`}>
    <TrendsAnalytics />
    <JsonLd data={[buildWebPageJsonLd({ pathname, name: copy.title, description: copy.intro, language: locale }), buildBreadcrumbJsonLd(locale, [{ name: locale === "es" ? "Inicio" : "Home", pathname: locale === "es" ? "/" : "/en" }, { name: trendsCopy[locale].hero.eyebrow, pathname: trendsPath(locale) }, { name: trendsCopy[locale].capital.methodology, pathname }])]} />
    <Link href={trendsPath(locale)} className="inline-flex min-h-11 items-center text-sm font-semibold text-petrol underline decoration-line underline-offset-4">← {copy.back}</Link>
    <header className="max-w-4xl pb-10 pt-5"><p className="text-[11px] font-semibold uppercase tracking-[0.2em] text-brass">{trendsCopy[locale].hero.eyebrow}</p><h1 className="mt-4 text-balance text-[clamp(2rem,5vw,4.25rem)] font-semibold leading-[1.02] tracking-[-0.045em] text-ink">{copy.title}</h1><p className="mt-5 text-lg leading-8 text-muted">{copy.intro}</p></header>
    <div className="max-w-4xl">
      <section id="editorial" className={section}><h2 className={heading}>{copy.editorial}</h2><p className="mt-4 text-base leading-8 text-muted">{copy.editorialNote}</p><div className="mt-6 grid gap-8 md:grid-cols-2"><div><h3 className="text-lg font-semibold text-petrol">{labels.phase}</h3><dl className="mt-4 space-y-5">{(Object.keys(copy.phaseDefinitions) as TrendPhase[]).map((phase) => <div key={phase}><dt className="text-sm font-semibold text-ink">{labels.phases[phase]}</dt><dd className="mt-1 text-sm leading-7 text-muted">{copy.phaseDefinitions[phase]}</dd></div>)}</dl></div><div><h3 className="text-lg font-semibold text-petrol">{labels.evidence}</h3><dl className="mt-4 space-y-5">{(Object.keys(copy.evidenceDefinitions) as TrendEvidence[]).map((evidence) => <div key={evidence}><dt className="text-sm font-semibold text-ink">{labels.evidenceLevels[evidence]}</dt><dd className="mt-1 text-sm leading-7 text-muted">{copy.evidenceDefinitions[evidence]}</dd></div>)}</dl></div></div></section>
      <section id="positions" className={section}><h2 className={heading}>{copy.positions}</h2><p className="mt-3 text-xs leading-6 text-muted">{capitalPeriodLabel(dataset.quarter_end, locale)}</p><p className="mt-4 text-base leading-8 text-muted">{copy.positionNote}</p><ul className="mt-6 list-disc space-y-4 pl-5 text-sm leading-7 text-muted">{copy.positionControls.map((control) => <li key={control}>{control}</li>)}</ul></section>
      <section id="universe" className={section}><h2 className={heading}>{copy.universe}</h2><p className="mt-4 text-base leading-8 text-muted">{copy.universeNote}</p><h3 className="mt-6 text-lg font-semibold text-petrol">{dataset.universe.name}</h3><ul className="mt-4 divide-y divide-line">{dataset.universe.managers.map((manager) => {
        const current = dataset.current.find((quarter) => quarter.manager_id === manager.manager_id);
        return <li key={manager.manager_id} className="py-5"><h4 className="text-base font-semibold text-ink">{manager.display_name}</h4><p className="mt-2 text-sm leading-7 text-muted">{manager.legal_name}</p><p className="mt-2 text-xs leading-6 text-muted">CIK {manager.CIK} · {copy.membership}: <time dateTime={manager.inclusion_date}>{manager.inclusion_date}</time></p><p className="mt-3 text-sm leading-7 text-muted">{manager.inclusion_reason[locale]}</p><p className="mt-3 text-sm font-semibold text-petrol">{current ? capital.states[current.status] : copy.registryStates[manager.status]} · {dataset.quarter_end}</p><p className="mt-2 text-sm leading-7 text-muted">{manager.notes[locale]}</p>{current?.included_report_source && <a className="inline-flex min-h-11 items-center text-sm text-petrol underline underline-offset-4" href={current.included_report_source} target="_blank" rel="noreferrer">{copy.includedReport} →</a>}<a href={manager.source_url} target="_blank" rel="noreferrer" className="mt-2 inline-flex min-h-11 items-center text-sm font-semibold text-petrol underline decoration-line underline-offset-4">SEC EDGAR →</a>{current?.filings.map((filing) => <p key={filing.accession_number} className="mt-2 break-words text-xs leading-6 text-muted"><a href={filing.source_url} target="_blank" rel="noreferrer" className="inline-flex min-h-11 items-center underline underline-offset-4">{filing.form_type} · {filing.filing_date} · {filing.accession_number}</a></p>)}</li>;
      })}</ul></section>
      <section id="movements" className={section}><h2 className={heading}>{copy.movements}</h2>{dataset.movement_publication === "READY" ? <><p className="mt-4 text-base leading-8 text-muted">{copy.movementNote}</p><dl className="mt-6 grid gap-x-7 gap-y-5 md:grid-cols-2">{(Object.keys(copy.states) as Movement[]).map((state) => <div key={state}><dt className="text-xs font-semibold tracking-wide text-petrol">{state}</dt><dd className="mt-2 text-sm leading-7 text-muted">{copy.states[state]}</dd></div>)}</dl><ul className="mt-7 list-disc space-y-4 pl-5 text-sm leading-7 text-muted">{copy.controls.map((control) => <li key={control}>{control}</li>)}</ul></> : <p className="mt-4 text-base leading-8 text-muted">{copy.movementPending}</p>}</section>
      <section className={section}><h2 className={heading}>{copy.coverage}</h2><p className="mt-4 text-base leading-8 text-muted">{copy.coverageNote}</p></section>
      <section id="sources" className={section}><h2 className={heading}>{copy.source}</h2><p className="mt-4 text-base leading-8 text-muted">{copy.sourceNote}</p><ul className="mt-5 space-y-2 text-sm font-semibold text-petrol"><li><a className="inline-flex min-h-11 items-center underline decoration-line underline-offset-4" href="https://www.sec.gov/rules-regulations/staff-guidance/division-investment-management-frequently-asked-questions/frequently-asked-questions-about-form-13f" target="_blank" rel="noreferrer">SEC · Form 13F FAQ →</a></li><li><a className="inline-flex min-h-11 items-center underline decoration-line underline-offset-4" href="https://www.sec.gov/search-filings/edgar-application-programming-interfaces" target="_blank" rel="noreferrer">SEC · EDGAR API →</a></li></ul></section>
    </div>
  </article>;
}
