import type { DiagnosticMode, DiagnosticQuestion } from "@/lib/diagnostic/types";

export const diagnosticQuestions: DiagnosticQuestion[] = [
  {
    id: "life_stage",
    block: "Situación y capacidad",
    prompt: "¿En qué etapa estás construyendo patrimonio?",
    helper: "No necesitamos una fecha exacta; solo entender estabilidad y margen de error.",
    options: [
      { label: "Estoy empezando y mis ingresos aún son variables", scores: { riskCapacityScore: 35, consistencyScore: 60 }, flags: ["early_variable_income"] },
      { label: "Tengo ingresos relativamente estables y margen para planear", scores: { riskCapacityScore: 70, consistencyScore: 75 } },
      { label: "Estoy cerca de usar parte importante del capital", scores: { riskCapacityScore: 35, liquidityPressureScore: 80, timeHorizonScore: 35 }, flags: ["near_capital_use"] },
      { label: "Tengo patrimonio diversificado y varias fuentes de soporte", scores: { riskCapacityScore: 85, consistencyScore: 75 } },
    ],
  },
  {
    id: "income_stability",
    block: "Situación y capacidad",
    prompt: "¿Qué tan estables son tus ingresos principales?",
    helper: "La estabilidad de ingresos condiciona cuánto error financiero puede absorberse.",
    quick: true,
    options: [
      { label: "Dependen bastante de comisiones, negocio o ciclos", scores: { riskCapacityScore: 35, liquidityPressureScore: 75 }, flags: ["variable_income"] },
      { label: "Son estables, aunque dependen de una sola fuente", scores: { riskCapacityScore: 60, liquidityPressureScore: 45 } },
      { label: "Son estables y tengo más de una fuente relevante", scores: { riskCapacityScore: 80, liquidityPressureScore: 25 } },
      { label: "Hoy son inciertos o están en transición", scores: { riskCapacityScore: 25, liquidityPressureScore: 85 }, flags: ["income_transition"] },
    ],
  },
  {
    id: "dependents",
    block: "Situación y capacidad",
    prompt: "¿Cuántas personas dependen económicamente de ti?",
    helper: "No mide ambición; mide margen real para asumir volatilidad sin afectar compromisos.",
    quick: true,
    options: [
      { label: "Nadie depende de mí de forma relevante", scores: { riskCapacityScore: 78, liquidityPressureScore: 25 } },
      { label: "Una persona depende parcialmente", scores: { riskCapacityScore: 62, liquidityPressureScore: 45 } },
      { label: "Varias personas dependen de mis ingresos", scores: { riskCapacityScore: 38, liquidityPressureScore: 78 }, flags: ["high_responsibilities"] },
      { label: "Tengo compromisos familiares altos y poco margen mensual", scores: { riskCapacityScore: 25, liquidityPressureScore: 90 }, flags: ["high_responsibilities", "low_monthly_margin"] },
    ],
  },
  {
    id: "emergency_fund",
    block: "Situación y capacidad",
    prompt: "Si mañana necesitaras cubrir seis meses de gastos, ¿qué tan preparado estás?",
    helper: "El colchón de emergencia separa inversión de supervivencia financiera.",
    quick: true,
    options: [
      { label: "Tengo liquidez suficiente separada de mis inversiones", scores: { riskCapacityScore: 85, liquidityPressureScore: 15 }, flags: ["emergency_full"] },
      { label: "Tengo algo, pero no cubriría seis meses", scores: { riskCapacityScore: 52, liquidityPressureScore: 58 }, flags: ["emergency_partial"] },
      { label: "Dependería de vender inversiones o endeudarme", scores: { riskCapacityScore: 22, liquidityPressureScore: 92 }, flags: ["no_emergency_fund"] },
      { label: "No lo sé con claridad", scores: { riskCapacityScore: 35, liquidityPressureScore: 70, consistencyScore: 55 }, flags: ["unclear_emergency"] },
    ],
  },
  {
    id: "debt_load",
    block: "Situación y capacidad",
    prompt: "¿Cómo describirías tus deudas actuales?",
    helper: "La deuda puede convertir una caída temporal en un problema de liquidez.",
    quick: true,
    options: [
      { label: "No tengo deudas relevantes", scores: { riskCapacityScore: 82, liquidityPressureScore: 20 } },
      { label: "Tengo deuda manejable y pagos predecibles", scores: { riskCapacityScore: 65, liquidityPressureScore: 38 } },
      { label: "Tengo deuda que reduce bastante mi margen mensual", scores: { riskCapacityScore: 35, liquidityPressureScore: 78 }, flags: ["high_debt"] },
      { label: "Uso deuda cara o rotativa con frecuencia", scores: { riskCapacityScore: 18, liquidityPressureScore: 92 }, flags: ["high_debt", "expensive_debt"] },
    ],
  },
  {
    id: "near_liquidity",
    block: "Situación y capacidad",
    prompt: "En los próximos 24 meses, ¿esperas gastos grandes obligatorios?",
    helper: "Un horizonte largo en teoría no sirve si hay una necesidad cercana de caja.",
    quick: true,
    options: [
      { label: "No espero gastos grandes obligatorios", scores: { liquidityPressureScore: 20, timeHorizonScore: 80 } },
      { label: "Podría tener uno, pero está parcialmente cubierto", scores: { liquidityPressureScore: 48, timeHorizonScore: 62 } },
      { label: "Sí, y probablemente usaría parte del capital invertible", scores: { liquidityPressureScore: 85, timeHorizonScore: 35 }, flags: ["near_liquidity_need"] },
      { label: "No tengo visibilidad suficiente", scores: { liquidityPressureScore: 65, timeHorizonScore: 45, consistencyScore: 55 }, flags: ["unclear_liquidity"] },
    ],
  },
  {
    id: "loss_affects_life",
    block: "Situación y capacidad",
    prompt: "Si tus inversiones de largo plazo cayeran 25%, ¿afectaría tu vida diaria?",
    helper: "Aquí distinguimos tolerancia emocional de capacidad financiera real.",
    quick: true,
    options: [
      { label: "No afectaría gastos ni compromisos, aunque sería incómodo", scores: { riskCapacityScore: 82, liquidityPressureScore: 22 } },
      { label: "Me obligaría a pausar algunos planes, pero no compromisos básicos", scores: { riskCapacityScore: 58, liquidityPressureScore: 52 } },
      { label: "Podría afectar pagos o decisiones familiares importantes", scores: { riskCapacityScore: 28, liquidityPressureScore: 84 }, flags: ["loss_affects_life"] },
      { label: "No lo he calculado", scores: { riskCapacityScore: 38, liquidityPressureScore: 65, consistencyScore: 55 }, flags: ["unclear_loss_capacity"] },
    ],
  },
  {
    id: "wealth_share",
    block: "Situación y capacidad",
    prompt: "¿Qué parte de tu patrimonio sería inversión de largo plazo?",
    helper: "No ingreses montos. Solo una proporción aproximada.",
    options: [
      { label: "Una parte pequeña; la mayoría tiene otra función", scores: { riskCapacityScore: 55, liquidityPressureScore: 35 } },
      { label: "Una parte relevante, pero no compromete mi estabilidad", scores: { riskCapacityScore: 75, liquidityPressureScore: 32 } },
      { label: "Una parte muy alta de mi patrimonio total", scores: { riskCapacityScore: 48, liquidityPressureScore: 60 }, flags: ["high_wealth_share"] },
      { label: "No tengo claro mi patrimonio líquido vs. invertido", scores: { riskCapacityScore: 36, liquidityPressureScore: 62, consistencyScore: 52 }, flags: ["unclear_wealth_share"] },
    ],
  },
  {
    id: "job_risk",
    block: "Situación y capacidad",
    prompt: "¿Qué tan probable ves una caída fuerte de ingresos en los próximos 12 meses?",
    helper: "No es pesimismo; es medir resiliencia antes de asumir volatilidad.",
    options: [
      { label: "Poco probable y tengo reservas", scores: { riskCapacityScore: 82, liquidityPressureScore: 22 } },
      { label: "Posible, pero tendría margen para ajustar gastos", scores: { riskCapacityScore: 60, liquidityPressureScore: 48 } },
      { label: "Probable o ya está ocurriendo", scores: { riskCapacityScore: 28, liquidityPressureScore: 85 }, flags: ["income_risk"] },
      { label: "No tengo visibilidad", scores: { riskCapacityScore: 42, liquidityPressureScore: 62, consistencyScore: 55 }, flags: ["unclear_income_risk"] },
    ],
  },
  {
    id: "currency_exposure",
    block: "Situación y capacidad",
    prompt: "¿Tus ingresos, gastos e inversiones están en monedas distintas?",
    helper: "La divisa puede añadir riesgo aunque el activo parezca conservador.",
    options: [
      { label: "Sí, y entiendo cómo me afecta", scores: { knowledgeScore: 72, riskCapacityScore: 65 } },
      { label: "Sí, pero no lo he medido bien", scores: { knowledgeScore: 45, consistencyScore: 55 }, flags: ["unclear_currency_risk"] },
      { label: "Casi todo está en la misma moneda", scores: { riskCapacityScore: 65 } },
      { label: "No estoy seguro", scores: { knowledgeScore: 35, consistencyScore: 50 }, flags: ["unclear_currency_risk"] },
    ],
  },
  {
    id: "main_goal",
    block: "Objetivos",
    prompt: "¿Qué función principal quieres que cumpla este capital?",
    helper: "Si hay varios objetivos, elige el que más condiciona tus decisiones.",
    quick: true,
    options: [
      { label: "Preservar estabilidad y evitar errores grandes", scores: { riskCapacityScore: 45, psychologicalToleranceScore: 42, timeHorizonScore: 45 }, flags: ["preservation_goal"] },
      { label: "Crecer patrimonio con un proceso sostenible", scores: { riskCapacityScore: 72, psychologicalToleranceScore: 68, timeHorizonScore: 78 } },
      { label: "Generar renta o complementar ingresos", scores: { liquidityPressureScore: 52, timeHorizonScore: 55 } },
      { label: "Aprender con una parte limitada del capital", scores: { knowledgeScore: 50, behavioralRiskScore: 55, riskCapacityScore: 58 }, flags: ["learning_goal"] },
    ],
  },
  {
    id: "inflation_goal",
    block: "Objetivos",
    prompt: "Cuando piensas en inflación, ¿qué buscas principalmente?",
    helper: "La protección contra inflación puede requerir paciencia y tolerancia a fluctuaciones.",
    options: [
      { label: "Mantener liquidez aunque pierda algo de poder adquisitivo", scores: { liquidityPressureScore: 45, psychologicalToleranceScore: 42 } },
      { label: "Aceptar fluctuación moderada para preservar poder de compra", scores: { psychologicalToleranceScore: 65, timeHorizonScore: 70 } },
      { label: "Buscar crecimiento real a largo plazo aunque haya caídas", scores: { psychologicalToleranceScore: 78, timeHorizonScore: 86 } },
      { label: "No lo he pensado de forma separada", scores: { knowledgeScore: 38, consistencyScore: 58 } },
    ],
  },
  {
    id: "goal_priority",
    block: "Objetivos",
    prompt: "Si tuvieras que priorizar una cosa durante un mal año de mercado, ¿cuál sería?",
    helper: "La prioridad revela el tipo de plan que suele sostenerse mejor.",
    quick: true,
    options: [
      { label: "Dormir tranquilo y mantener liquidez", scores: { psychologicalToleranceScore: 40, liquidityPressureScore: 50 } },
      { label: "No tocar el plan si la razón original sigue vigente", scores: { psychologicalToleranceScore: 78, behavioralRiskScore: 28 } },
      { label: "Ajustar exposición para reducir ansiedad", scores: { psychologicalToleranceScore: 45, behavioralRiskScore: 62 }, flags: ["anxiety_adjustment"] },
      { label: "Aprovechar caídas solo si ya estaba escrito en el plan", scores: { psychologicalToleranceScore: 82, behavioralRiskScore: 24 } },
    ],
  },
  {
    id: "future_project",
    block: "Objetivos",
    prompt: "¿Hay un proyecto concreto que dependa de este capital?",
    helper: "Casa, educación, negocio o mudanza pueden cambiar el riesgo apropiado.",
    options: [
      { label: "Sí, en menos de 12 meses", scores: { liquidityPressureScore: 92, timeHorizonScore: 20, riskCapacityScore: 25 }, flags: ["liquidity_under_12m"] },
      { label: "Sí, entre 1 y 3 años", scores: { liquidityPressureScore: 70, timeHorizonScore: 45, riskCapacityScore: 45 } },
      { label: "Sí, pero a más de 5 años", scores: { liquidityPressureScore: 35, timeHorizonScore: 78 } },
      { label: "No hay proyecto concreto ligado a este capital", scores: { liquidityPressureScore: 22, timeHorizonScore: 80 } },
    ],
  },
  {
    id: "return_vs_sleep",
    block: "Objetivos",
    prompt: "¿Qué frase se parece más a tu forma de decidir?",
    helper: "No buscamos una etiqueta; buscamos una conducta probable.",
    options: [
      { label: "Prefiero avanzar más lento si eso reduce decisiones impulsivas", scores: { psychologicalToleranceScore: 52, behavioralRiskScore: 25 } },
      { label: "Acepto años malos si el plan tiene fundamento y horizonte", scores: { psychologicalToleranceScore: 82, timeHorizonScore: 85 } },
      { label: "Me cuesta mantener un plan cuando otros parecen avanzar más rápido", scores: { psychologicalToleranceScore: 42, behavioralRiskScore: 78 }, flags: ["comparison_pressure"] },
      { label: "Me concentro en pocos activos si tengo alta convicción", scores: { psychologicalToleranceScore: 72, behavioralRiskScore: 72 }, flags: ["concentration_bias"] },
    ],
  },
  {
    id: "drop_12",
    block: "Tolerancia psicológica",
    prompt: "Tu portafolio cae 12% en tres meses. ¿Qué haces primero?",
    helper: "Escenario moderado: suficiente para incomodar, no necesariamente para invalidar un plan.",
    quick: true,
    options: [
      { label: "Reviso si cambió la razón original antes de tocar nada", scores: { psychologicalToleranceScore: 76, behavioralRiskScore: 22 } },
      { label: "Reduzco una parte para recuperar tranquilidad", scores: { psychologicalToleranceScore: 45, behavioralRiskScore: 58 }, flags: ["sells_mild_drop"] },
      { label: "Aumento exposición porque está más barato", scores: { psychologicalToleranceScore: 75, behavioralRiskScore: 55 }, flags: ["averages_down_fast"] },
      { label: "Evito mirar y espero que pase", scores: { psychologicalToleranceScore: 50, behavioralRiskScore: 68 }, flags: ["avoidance"] },
    ],
  },
  {
    id: "drop_25",
    block: "Tolerancia psicológica",
    prompt: "En una crisis, tu portafolio cae 25%. ¿Cuál sería tu reacción más probable?",
    helper: "Responde lo que crees posible, no lo que suena perfecto.",
    quick: true,
    options: [
      { label: "Congelo decisiones y reviso el plan con calma", scores: { psychologicalToleranceScore: 74, behavioralRiskScore: 28 } },
      { label: "Vendo parte aunque pueda perder la recuperación", scores: { psychologicalToleranceScore: 32, behavioralRiskScore: 78 }, flags: ["sells_crisis"] },
      { label: "Aumento solo si mi plan ya contemplaba ese escenario", scores: { psychologicalToleranceScore: 84, behavioralRiskScore: 22 } },
      { label: "Cambio de estrategia para evitar otra caída similar", scores: { psychologicalToleranceScore: 38, behavioralRiskScore: 72 }, flags: ["strategy_chasing"] },
    ],
  },
  {
    id: "favorite_asset_drop",
    block: "Tolerancia psicológica",
    prompt: "Un activo que te gusta cae 40% sin una explicación clara. ¿Qué haces?",
    helper: "La familiaridad con un activo puede nublar la evaluación del riesgo.",
    quick: true,
    options: [
      { label: "Busco evidencia nueva antes de decidir si la tesis sigue viva", scores: { psychologicalToleranceScore: 68, behavioralRiskScore: 28 } },
      { label: "Compro más para bajar mi precio promedio", scores: { psychologicalToleranceScore: 75, behavioralRiskScore: 76 }, flags: ["anchoring_loss_recovery"] },
      { label: "Salgo para no seguir pensando en la pérdida", scores: { psychologicalToleranceScore: 28, behavioralRiskScore: 82 }, flags: ["panic_exit"] },
      { label: "Mantengo, pero limito el peso máximo de ese activo", scores: { psychologicalToleranceScore: 70, behavioralRiskScore: 30 } },
    ],
  },
  {
    id: "fomo_asset",
    block: "Tolerancia psicológica",
    prompt: "Un activo que no compraste sube 80% y todos hablan de él. ¿Qué haces?",
    helper: "Esta pregunta mide presión social y FOMO, no conocimiento técnico.",
    quick: true,
    options: [
      { label: "Entro con una cantidad pequeña para no quedarme fuera", scores: { behavioralRiskScore: 72, psychologicalToleranceScore: 55 }, flags: ["fomo"] },
      { label: "Lo estudio, pero no cambio mi proceso por ruido externo", scores: { behavioralRiskScore: 20, psychologicalToleranceScore: 72 } },
      { label: "Espero una caída para entrar con más convicción", scores: { behavioralRiskScore: 58, psychologicalToleranceScore: 62 }, flags: ["anchoring_entry"] },
      { label: "Evito mirarlo porque me altera el plan", scores: { behavioralRiskScore: 45, psychologicalToleranceScore: 58 } },
    ],
  },
  {
    id: "market_rebound_after_exit",
    block: "Tolerancia psicológica",
    prompt: "El mercado sube justo después de que redujiste exposición. ¿Qué haces?",
    helper: "El arrepentimiento puede llevar a perseguir movimientos tardíos.",
    options: [
      { label: "Reentro rápido para corregir el error", scores: { behavioralRiskScore: 78, psychologicalToleranceScore: 45 }, flags: ["chases_rebound"] },
      { label: "Reviso si la salida respondió a una regla o a una emoción", scores: { behavioralRiskScore: 25, psychologicalToleranceScore: 70 } },
      { label: "Espero una nueva caída antes de considerar cambios", scores: { behavioralRiskScore: 55, psychologicalToleranceScore: 58 }, flags: ["anchoring_entry"] },
      { label: "Acepto el coste y documento qué aprendí", scores: { behavioralRiskScore: 22, psychologicalToleranceScore: 68 } },
    ],
  },
  {
    id: "three_negative_months",
    block: "Tolerancia psicológica",
    prompt: "Tres meses seguidos son negativos, pero tu plan sigue siendo válido. ¿Qué tan probable es abandonarlo?",
    helper: "La disciplina suele medirse en aburrimiento e incomodidad, no solo en crisis.",
    options: [
      { label: "Poco probable; revisaría datos, no emociones", scores: { psychologicalToleranceScore: 82, behavioralRiskScore: 18 } },
      { label: "Moderadamente probable si me siento estancado", scores: { psychologicalToleranceScore: 52, behavioralRiskScore: 58 }, flags: ["low_discipline"] },
      { label: "Muy probable; tres meses me parecerían una alerta suficiente", scores: { psychologicalToleranceScore: 32, behavioralRiskScore: 82 }, flags: ["low_discipline"] },
      { label: "Depende de si ya tenía reglas escritas", scores: { psychologicalToleranceScore: 62, behavioralRiskScore: 40 } },
    ],
  },
  {
    id: "alarm_news",
    block: "Tolerancia psicológica",
    prompt: "Una noticia alarmista domina los medios durante una caída. ¿Qué haces?",
    helper: "Mide susceptibilidad a narrativa y presión externa.",
    options: [
      { label: "Busco datos primarios antes de actuar", scores: { behavioralRiskScore: 22, psychologicalToleranceScore: 70 } },
      { label: "Reduzco exposición hasta entender mejor", scores: { behavioralRiskScore: 60, psychologicalToleranceScore: 45 }, flags: ["news_reactive"] },
      { label: "Ignoro todo sin revisar si algo cambió", scores: { behavioralRiskScore: 52, psychologicalToleranceScore: 68 }, flags: ["overconfidence"] },
      { label: "Contrasto la noticia con mi horizonte y liquidez", scores: { behavioralRiskScore: 24, psychologicalToleranceScore: 72 } },
    ],
  },
  {
    id: "stock_definition",
    block: "Conocimiento financiero",
    prompt: "Cuando compras una acción, ¿qué estás adquiriendo realmente?",
    helper: "Conocimiento básico de instrumentos antes de evaluar riesgo.",
    quick: true,
    options: [
      { label: "Una participación en la propiedad económica de una empresa", scores: { knowledgeScore: 90 }, flags: ["stock_correct"] },
      { label: "Un préstamo que la empresa debe devolverte con interés fijo", scores: { knowledgeScore: 25 } },
      { label: "Un contrato que garantiza retorno si la empresa crece", scores: { knowledgeScore: 20 } },
      { label: "No estoy seguro", scores: { knowledgeScore: 30 } },
    ],
  },
  {
    id: "bond_definition",
    block: "Conocimiento financiero",
    prompt: "Cuando compras un bono emitido por una empresa, ¿qué relación económica tienes con ella?",
    helper: "Distinguir propiedad de deuda evita malentendidos de riesgo.",
    quick: true,
    options: [
      { label: "Eres acreedor: la empresa promete pagos bajo ciertas condiciones", scores: { knowledgeScore: 90 }, flags: ["bond_correct"] },
      { label: "Eres socio con derecho a voto en decisiones corporativas", scores: { knowledgeScore: 20 } },
      { label: "Tienes garantía de no perder dinero si esperas al vencimiento", scores: { knowledgeScore: 35 } },
      { label: "Es básicamente igual que una acción, pero más estable", scores: { knowledgeScore: 35 } },
    ],
  },
  {
    id: "risk_return",
    block: "Conocimiento financiero",
    prompt: "Si una inversión ofrece más retorno esperado, normalmente también implica…",
    helper: "No siempre, pero suele existir una compensación entre retorno esperado e incertidumbre.",
    quick: true,
    options: [
      { label: "Más incertidumbre, riesgo o condiciones que deben analizarse", scores: { knowledgeScore: 88 } },
      { label: "Una oportunidad mejor si el historial reciente es bueno", scores: { knowledgeScore: 35 } },
      { label: "Menos riesgo porque el gestor encontró una ineficiencia", scores: { knowledgeScore: 20 } },
      { label: "No se puede evaluar sin ver solo la rentabilidad pasada", scores: { knowledgeScore: 40 } },
    ],
  },
  {
    id: "diversification",
    block: "Conocimiento financiero",
    prompt: "¿Qué busca principalmente la diversificación?",
    helper: "Diversificar no elimina todo riesgo, pero cambia su distribución.",
    quick: true,
    options: [
      { label: "Reducir dependencia de un solo activo, sector o escenario", scores: { knowledgeScore: 88 } },
      { label: "Aumentar siempre el retorno esperado", scores: { knowledgeScore: 25 } },
      { label: "Evitar cualquier pérdida temporal", scores: { knowledgeScore: 20 } },
      { label: "Concentrar en los activos que mejor lo hicieron", scores: { knowledgeScore: 30, behavioralRiskScore: 65 }, flags: ["performance_chasing"] },
    ],
  },
  {
    id: "index_funds",
    block: "Conocimiento financiero",
    prompt: "¿Cuál es una ventaja frecuente de un fondo indexado diversificado?",
    helper: "No lo hace perfecto; solo define una característica habitual.",
    options: [
      { label: "Costes bajos y exposición amplia a una regla transparente", scores: { knowledgeScore: 86 } },
      { label: "Garantiza superar a la mayoría de fondos activos cada año", scores: { knowledgeScore: 30 } },
      { label: "Evita caídas cuando el mercado cae", scores: { knowledgeScore: 20 } },
      { label: "Permite ignorar por completo la asignación de activos", scores: { knowledgeScore: 35 } },
    ],
  },
  {
    id: "fees",
    block: "Conocimiento financiero",
    prompt: "¿Por qué importan los costes y comisiones?",
    helper: "Los costes no son el único criterio, pero afectan el resultado acumulado.",
    options: [
      { label: "Porque reducen el retorno neto y se acumulan con el tiempo", scores: { knowledgeScore: 88 } },
      { label: "Solo importan si el mercado cae", scores: { knowledgeScore: 35 } },
      { label: "No importan si el producto tiene buena narrativa", scores: { knowledgeScore: 15, behavioralRiskScore: 70 }, flags: ["narrative_over_cost"] },
      { label: "Importan únicamente en productos conservadores", scores: { knowledgeScore: 35 } },
    ],
  },
  {
    id: "inflation_basic",
    block: "Conocimiento financiero",
    prompt: "Si la inflación supera el retorno de tu liquidez durante años, ¿qué ocurre?",
    helper: "La seguridad nominal no siempre conserva poder de compra.",
    options: [
      { label: "Pierdes poder adquisitivo aunque el saldo nominal no baje", scores: { knowledgeScore: 88 } },
      { label: "No ocurre nada si el dinero está en una cuenta segura", scores: { knowledgeScore: 25 } },
      { label: "La inflación solo afecta a acciones, no a liquidez", scores: { knowledgeScore: 20 } },
      { label: "Depende únicamente del tipo de cambio", scores: { knowledgeScore: 35 } },
    ],
  },
  {
    id: "concentration_risk",
    block: "Conocimiento financiero",
    prompt: "Tener 60% del capital en una sola acción implica principalmente…",
    helper: "Incluso si la empresa es excelente, el peso crea una vulnerabilidad propia.",
    quick: true,
    options: [
      { label: "Dependencia alta de un solo resultado empresarial", scores: { knowledgeScore: 88, behavioralRiskScore: 30 } },
      { label: "Mayor seguridad si conoces bien la empresa", scores: { knowledgeScore: 30, behavioralRiskScore: 70 }, flags: ["concentration_bias"] },
      { label: "Menos volatilidad porque hay más convicción", scores: { knowledgeScore: 20 } },
      { label: "Un riesgo irrelevante si el horizonte es largo", scores: { knowledgeScore: 35 } },
    ],
  },
  {
    id: "margin",
    block: "Conocimiento financiero",
    prompt: "Si compras usando apalancamiento y el activo cae con fuerza, ¿qué puede ocurrir?",
    helper: "El apalancamiento cambia el tamaño y la velocidad de los errores.",
    quick: true,
    options: [
      { label: "Puedes perder más rápido y verte obligado a aportar o cerrar posición", scores: { knowledgeScore: 92 }, flags: ["margin_correct"] },
      { label: "La pérdida se limita automáticamente al interés del préstamo", scores: { knowledgeScore: 20 } },
      { label: "El broker debe esperar a que el activo recupere", scores: { knowledgeScore: 15 } },
      { label: "No estoy seguro", scores: { knowledgeScore: 25 }, flags: ["complex_knowledge_low"] },
    ],
  },
  {
    id: "short_selling",
    block: "Conocimiento financiero",
    prompt: "En una venta en corto, ¿qué riesgo especial existe?",
    helper: "Es un producto difícil incluso para inversores con experiencia.",
    options: [
      { label: "La pérdida puede crecer si el activo sube con fuerza", scores: { knowledgeScore: 90 }, flags: ["short_correct"] },
      { label: "La pérdida máxima siempre es cero si no usas apalancamiento", scores: { knowledgeScore: 20 } },
      { label: "No hay riesgo si la empresa es mala", scores: { knowledgeScore: 15 } },
      { label: "Solo pierdes la comisión de intermediación", scores: { knowledgeScore: 15 } },
    ],
  },
  {
    id: "options_call",
    block: "Conocimiento financiero",
    prompt: "Una opción call fuera del dinero y con vencimiento muy cercano normalmente tiene…",
    helper: "No hace falta operar opciones; sí entender que pueden perder valor rápidamente.",
    options: [
      { label: "Alto riesgo de perder valor si el movimiento no ocurre pronto", scores: { knowledgeScore: 90 }, flags: ["options_correct"] },
      { label: "Protección natural contra cualquier caída", scores: { knowledgeScore: 20 } },
      { label: "Valor garantizado por ser un contrato financiero", scores: { knowledgeScore: 15 } },
      { label: "No estoy seguro", scores: { knowledgeScore: 25 }, flags: ["complex_knowledge_low"] },
    ],
  },
  {
    id: "past_returns",
    block: "Conocimiento financiero",
    prompt: "La rentabilidad pasada de un fondo…",
    helper: "El historial es información, no garantía.",
    quick: true,
    options: [
      { label: "Sirve como referencia, pero no garantiza resultados futuros", scores: { knowledgeScore: 90 } },
      { label: "Es la mejor garantía disponible para elegirlo", scores: { knowledgeScore: 25, behavioralRiskScore: 62 }, flags: ["past_return_chasing"] },
      { label: "Importa solo si fue positiva todos los años", scores: { knowledgeScore: 35 } },
      { label: "No dice nada y debe ignorarse por completo", scores: { knowledgeScore: 50 } },
    ],
  },
  {
    id: "liquidity_risk",
    block: "Conocimiento financiero",
    prompt: "¿Qué es riesgo de liquidez en una inversión?",
    helper: "Importa especialmente si podrías necesitar salir rápido.",
    options: [
      { label: "Dificultad para convertirla en efectivo sin coste o demora relevante", scores: { knowledgeScore: 88 } },
      { label: "Que el activo tenga mucha liquidez disponible", scores: { knowledgeScore: 20 } },
      { label: "Que el precio se mueva poco", scores: { knowledgeScore: 35 } },
      { label: "Que pague intereses bajos", scores: { knowledgeScore: 35 } },
    ],
  },
  {
    id: "bond_rates",
    block: "Conocimiento financiero",
    prompt: "¿Qué suele pasar con el precio de un bono existente si suben los tipos de interés?",
    helper: "Es una fuente frecuente de sorpresa en productos considerados conservadores.",
    options: [
      { label: "Puede bajar, especialmente si tiene duración alta", scores: { knowledgeScore: 90 } },
      { label: "Debe subir porque paga intereses", scores: { knowledgeScore: 25 } },
      { label: "No se mueve porque los bonos son fijos", scores: { knowledgeScore: 20 } },
      { label: "Solo cambia si la empresa quiebra", scores: { knowledgeScore: 35 } },
    ],
  },
  {
    id: "crypto_volatility",
    block: "Conocimiento financiero",
    prompt: "Sobre criptoactivos, ¿qué afirmación es más prudente?",
    helper: "No juzga el activo; mide comprensión de volatilidad, custodia y narrativa.",
    options: [
      { label: "Pueden tener alta volatilidad, riesgos técnicos, regulatorios y de liquidez", scores: { knowledgeScore: 88 } },
      { label: "Son equivalentes a efectivo digital estable", scores: { knowledgeScore: 15 } },
      { label: "Si hay adopción, el riesgo principal desaparece", scores: { knowledgeScore: 30 } },
      { label: "No requieren análisis de custodia ni concentración", scores: { knowledgeScore: 20 } },
    ],
  },
  {
    id: "years_investing",
    block: "Experiencia real",
    prompt: "¿Cuántos años llevas invirtiendo con dinero propio?",
    helper: "Experiencia real no es solo leer; es haber decidido bajo incertidumbre.",
    quick: true,
    options: [
      { label: "Menos de 1 año", scores: { experienceScore: 25 } },
      { label: "1 a 3 años", scores: { experienceScore: 48 } },
      { label: "4 a 8 años", scores: { experienceScore: 72 } },
      { label: "Más de 8 años y he vivido ciclos difíciles", scores: { experienceScore: 90 } },
    ],
  },
  {
    id: "products_used",
    block: "Experiencia real",
    prompt: "¿Qué instrumentos has usado de forma real?",
    helper: "Elige la opción más cercana a tu experiencia, no a tu interés.",
    quick: true,
    options: [
      { label: "Liquidez, fondos simples o bonos básicos", scores: { experienceScore: 35 } },
      { label: "Fondos indexados, ETFs amplios o acciones diversificadas", scores: { experienceScore: 58, knowledgeScore: 55 } },
      { label: "Acciones individuales, ETFs sectoriales o cripto sin apalancamiento", scores: { experienceScore: 72, knowledgeScore: 62 } },
      { label: "Derivados, margen, venta en corto o estrategias complejas", scores: { experienceScore: 88 }, flags: ["claims_complex_experience"] },
    ],
  },
  {
    id: "trading_frequency",
    block: "Experiencia real",
    prompt: "¿Con qué frecuencia haces cambios en tus inversiones?",
    helper: "La frecuencia no es buena o mala por sí sola; debe tener proceso.",
    options: [
      { label: "Pocas veces al año, con reglas claras", scores: { experienceScore: 60, behavioralRiskScore: 22 } },
      { label: "Mensualmente, revisando datos y objetivos", scores: { experienceScore: 65, behavioralRiskScore: 35 } },
      { label: "Semanalmente o más, según noticias y movimientos", scores: { experienceScore: 55, behavioralRiskScore: 78 }, flags: ["excessive_trading"] },
      { label: "Casi nunca reviso lo que tengo", scores: { experienceScore: 35, behavioralRiskScore: 55 }, flags: ["low_monitoring"] },
    ],
  },
  {
    id: "real_drawdown",
    block: "Experiencia real",
    prompt: "¿Has vivido una caída fuerte con dinero propio invertido?",
    helper: "Una caída real enseña cosas que un simulador no enseña.",
    quick: true,
    options: [
      { label: "No, mi experiencia ha sido en mercados relativamente tranquilos", scores: { experienceScore: 35 } },
      { label: "Sí, y vendí por incomodidad", scores: { experienceScore: 55, psychologicalToleranceScore: 35, behavioralRiskScore: 78 }, flags: ["sold_real_drawdown"] },
      { label: "Sí, mantuve el plan y luego revisé aprendizajes", scores: { experienceScore: 82, psychologicalToleranceScore: 78, behavioralRiskScore: 25 } },
      { label: "Sí, aumenté exposición sin un plan escrito", scores: { experienceScore: 62, psychologicalToleranceScore: 70, behavioralRiskScore: 70 }, flags: ["averaged_without_plan"] },
    ],
  },
  {
    id: "relative_size",
    block: "Experiencia real",
    prompt: "El dinero con el que has invertido representa…",
    helper: "No es lo mismo experimentar con poco que decidir con patrimonio relevante.",
    options: [
      { label: "Una cantidad pequeña frente a mi patrimonio", scores: { experienceScore: 42 } },
      { label: "Una cantidad relevante, pero no crítica", scores: { experienceScore: 68, riskCapacityScore: 65 } },
      { label: "Una cantidad muy importante para mi estabilidad", scores: { experienceScore: 70, riskCapacityScore: 35, liquidityPressureScore: 70 }, flags: ["high_wealth_share"] },
      { label: "No lo tengo medido", scores: { experienceScore: 35, consistencyScore: 50 }, flags: ["unclear_wealth_share"] },
    ],
  },
  {
    id: "documents",
    block: "Experiencia real",
    prompt: "Antes de invertir en un producto nuevo, ¿qué sueles revisar?",
    helper: "Mide proceso, no solo conocimiento.",
    options: [
      { label: "Costes, liquidez, riesgo máximo, documento del producto y rol en el plan", scores: { experienceScore: 82, knowledgeScore: 78, behavioralRiskScore: 20 } },
      { label: "Rendimiento reciente y opiniones de personas que sigo", scores: { experienceScore: 42, behavioralRiskScore: 76 }, flags: ["social_following"] },
      { label: "Solo una descripción general si parece simple", scores: { experienceScore: 38, knowledgeScore: 42 } },
      { label: "Depende del tamaño; para montos pequeños reviso menos", scores: { experienceScore: 58, behavioralRiskScore: 45 } },
    ],
  },
  {
    id: "max_loss_understanding",
    block: "Experiencia real",
    prompt: "Cuando usas o evalúas un producto, ¿sabes estimar la pérdida máxima razonable?",
    helper: "En productos complejos, no entender la pérdida máxima es una alerta educativa.",
    options: [
      { label: "Sí, y si no puedo estimarla no lo uso", scores: { experienceScore: 82, knowledgeScore: 78, behavioralRiskScore: 18 } },
      { label: "La estimo solo para inversiones grandes", scores: { experienceScore: 58, knowledgeScore: 55 } },
      { label: "Normalmente no; miro más el potencial positivo", scores: { experienceScore: 35, knowledgeScore: 38, behavioralRiskScore: 82 }, flags: ["upside_focus"] },
      { label: "Confío en que la plataforma limite el riesgo", scores: { experienceScore: 30, knowledgeScore: 28 }, flags: ["complex_knowledge_low"] },
    ],
  },
  {
    id: "fomo_behavior",
    block: "Sesgos y comportamiento",
    prompt: "Cuando mucha gente parece ganar dinero rápido, ¿qué te ocurre?",
    helper: "El objetivo es detectar presión, no juzgarla.",
    quick: true,
    options: [
      { label: "Siento presión, pero espero mi proceso", scores: { behavioralRiskScore: 28, psychologicalToleranceScore: 68 } },
      { label: "Me cuesta no participar aunque sea con poco", scores: { behavioralRiskScore: 78, psychologicalToleranceScore: 48 }, flags: ["fomo"] },
      { label: "Busco argumentos que confirmen que aún estoy a tiempo", scores: { behavioralRiskScore: 82 }, flags: ["confirmation_bias", "fomo"] },
      { label: "Prefiero ignorarlo para no alterar mi plan", scores: { behavioralRiskScore: 35, psychologicalToleranceScore: 62 } },
    ],
  },
  {
    id: "overconfidence",
    block: "Sesgos y comportamiento",
    prompt: "Después de varias decisiones buenas seguidas, ¿qué tiende a pasar?",
    helper: "Las rachas positivas pueden aumentar tamaño y confianza demasiado rápido.",
    options: [
      { label: "Mantengo el tamaño porque una racha no cambia el proceso", scores: { behavioralRiskScore: 18, consistencyScore: 75 } },
      { label: "Aumento tamaño si siento que entendí el patrón", scores: { behavioralRiskScore: 78 }, flags: ["overconfidence"] },
      { label: "Busco más oportunidades parecidas rápidamente", scores: { behavioralRiskScore: 70 }, flags: ["pattern_chasing"] },
      { label: "Reviso si hubo habilidad, suerte o simple mercado favorable", scores: { behavioralRiskScore: 20, consistencyScore: 80 } },
    ],
  },
  {
    id: "loss_recovery",
    block: "Sesgos y comportamiento",
    prompt: "Después de una pérdida incómoda, ¿qué impulso reconoces más?",
    helper: "Recuperar rápido suele ser una fuente fuerte de errores.",
    options: [
      { label: "Reducir tamaño y revisar proceso", scores: { behavioralRiskScore: 25, psychologicalToleranceScore: 62 } },
      { label: "Buscar una operación que recupere la pérdida", scores: { behavioralRiskScore: 88, psychologicalToleranceScore: 42 }, flags: ["loss_recovery_bias"] },
      { label: "No tocar nada y documentar qué pasó", scores: { behavioralRiskScore: 22, psychologicalToleranceScore: 68 } },
      { label: "Cambiar totalmente de estrategia", scores: { behavioralRiskScore: 76, psychologicalToleranceScore: 38 }, flags: ["strategy_chasing"] },
    ],
  },
  {
    id: "social_media",
    block: "Sesgos y comportamiento",
    prompt: "¿Qué peso tienen redes, newsletters o grupos en tus decisiones?",
    helper: "La información externa puede ayudar, pero no reemplaza proceso.",
    quick: true,
    options: [
      { label: "Sirven como insumo, pero decido con criterios propios", scores: { behavioralRiskScore: 28, knowledgeScore: 65 } },
      { label: "A veces ejecuto ideas si la fuente me inspira confianza", scores: { behavioralRiskScore: 72 }, flags: ["social_following"] },
      { label: "Las uso para descubrir temas, luego reviso documentos y riesgos", scores: { behavioralRiskScore: 25, knowledgeScore: 70 } },
      { label: "Me ayudan a decidir cuando no tengo tiempo de investigar", scores: { behavioralRiskScore: 82, knowledgeScore: 38 }, flags: ["social_following"] },
    ],
  },
  {
    id: "confirmation",
    block: "Sesgos y comportamiento",
    prompt: "Cuando te gusta mucho una inversión, ¿qué información buscas primero?",
    helper: "La calidad del proceso depende de buscar también lo que podría estar mal.",
    options: [
      { label: "La tesis contraria y los riesgos que invalidarían mi idea", scores: { behavioralRiskScore: 18, knowledgeScore: 72 } },
      { label: "Más evidencia de por qué puede funcionar", scores: { behavioralRiskScore: 70 }, flags: ["confirmation_bias"] },
      { label: "Opiniones de personas que ya ganaron con ella", scores: { behavioralRiskScore: 78 }, flags: ["confirmation_bias", "social_following"] },
      { label: "Datos de valoración, liquidez, concentración y escenarios", scores: { behavioralRiskScore: 22, knowledgeScore: 78 } },
    ],
  },
  {
    id: "declared_loss_tolerance",
    block: "Consistencia",
    prompt: "Sin pensar en un activo concreto, ¿qué caída temporal crees que tolerarías?",
    helper: "Luego se contrasta con tus respuestas de conducta.",
    quick: true,
    options: [
      { label: "Hasta 5-10% antes de replantear", scores: { psychologicalToleranceScore: 35 }, flags: ["declares_low_tolerance"] },
      { label: "Alrededor de 15-25% si el plan sigue vigente", scores: { psychologicalToleranceScore: 65 }, flags: ["declares_medium_tolerance"] },
      { label: "Más de 30% si el horizonte y la tesis siguen intactos", scores: { psychologicalToleranceScore: 85 }, flags: ["declares_high_tolerance"] },
      { label: "No lo sé; nunca lo he vivido con dinero relevante", scores: { psychologicalToleranceScore: 45, consistencyScore: 55 }, flags: ["unclear_tolerance"] },
    ],
  },
  {
    id: "declared_complex_understanding",
    block: "Consistencia",
    prompt: "¿Qué tan cómodo estás con derivados, margen o venta en corto?",
    helper: "No pasa nada si no los usas; aquí medimos conveniencia educativa.",
    quick: true,
    options: [
      { label: "No los entiendo lo suficiente para usarlos", scores: { knowledgeScore: 35, experienceScore: 25 }, flags: ["complex_knowledge_low"] },
      { label: "Entiendo la idea general, pero no todos los riesgos", scores: { knowledgeScore: 50, experienceScore: 40 }, flags: ["complex_knowledge_low"] },
      { label: "Los he usado y puedo explicar riesgo máximo, margen y liquidez", scores: { knowledgeScore: 82, experienceScore: 82 }, flags: ["claims_complex_knowledge"] },
      { label: "Me parecen útiles si el potencial compensa", scores: { knowledgeScore: 55, behavioralRiskScore: 72 }, flags: ["complex_optimism"] },
    ],
  },
  {
    id: "declared_risk_desire",
    block: "Consistencia",
    prompt: "Si tuvieras más margen financiero, ¿qué cambiarías?",
    helper: "Distingue deseo de asumir riesgo de capacidad actual.",
    options: [
      { label: "Aumentaría exposición de forma gradual y con reglas", scores: { psychologicalToleranceScore: 72, behavioralRiskScore: 28 } },
      { label: "Tomaría posiciones más concentradas", scores: { psychologicalToleranceScore: 82, behavioralRiskScore: 78 }, flags: ["wants_high_risk"] },
      { label: "No cambiaría mucho; prefiero estabilidad", scores: { psychologicalToleranceScore: 42 }, flags: ["prefers_stability"] },
      { label: "Primero fortalecería liquidez y formación", scores: { behavioralRiskScore: 20, riskCapacityScore: 62 } },
    ],
  },
  {
    id: "volatility_preference",
    block: "Consistencia",
    prompt: "¿Qué preferirías si ambos caminos pudieran llegar al mismo objetivo?",
    helper: "La comodidad emocional importa aunque la capacidad financiera sea alta.",
    quick: true,
    options: [
      { label: "Camino más estable, aunque sea más lento", scores: { psychologicalToleranceScore: 38, behavioralRiskScore: 24 }, flags: ["low_vol_preference"] },
      { label: "Camino con altibajos moderados y revisión periódica", scores: { psychologicalToleranceScore: 65, behavioralRiskScore: 25 } },
      { label: "Camino más volátil si el horizonte lo justifica", scores: { psychologicalToleranceScore: 82, behavioralRiskScore: 34 }, flags: ["high_vol_preference"] },
      { label: "Depende de cómo se comportó recientemente", scores: { psychologicalToleranceScore: 48, behavioralRiskScore: 72 }, flags: ["recency_bias"] },
    ],
  },
  {
    id: "plan_written",
    block: "Consistencia",
    prompt: "¿Tienes reglas escritas para decidir cuándo cambiar una inversión?",
    helper: "Un plan escrito reduce decisiones improvisadas bajo estrés.",
    options: [
      { label: "Sí, con criterios de peso, horizonte, tesis y revisión", scores: { consistencyScore: 88, behavioralRiskScore: 18 } },
      { label: "Tengo criterios, pero no están escritos", scores: { consistencyScore: 62, behavioralRiskScore: 38 } },
      { label: "Decido caso por caso según el momento", scores: { consistencyScore: 42, behavioralRiskScore: 70 }, flags: ["no_written_plan"] },
      { label: "Sigo recomendaciones externas si cambian las condiciones", scores: { consistencyScore: 35, behavioralRiskScore: 78 }, flags: ["social_following"] },
    ],
  },
];

export function getQuestionsForMode(mode: DiagnosticMode) {
  return mode === "quick" ? diagnosticQuestions.filter((question) => question.quick).slice(0, 20) : diagnosticQuestions.slice(0, 50);
}
