import type { DiagnosticAnswers, DiagnosticMode, DiagnosticProduct, DiagnosticQuestion } from "@/lib/diagnostic/types";

const both: DiagnosticMode[] = ["quick", "complete"];
const complete: DiagnosticMode[] = ["complete"];
const t = (es: string, en: string) => ({ es, en });

export const diagnosticQuestions: DiagnosticQuestion[] = [
  {
    id: "capital_reference",
    block: "setup",
    mode: both,
    prompt: t("Para que los escenarios sean realistas, elige una cantidad de referencia.", "To make scenarios realistic, choose a reference amount."),
    helper: t("No guardamos este dato. Solo ajusta los ejemplos durante esta sesión.", "We do not store this. It only adjusts examples during this session."),
    options: [
      { id: "1000", label: t("1.000 €", "€1,000") },
      { id: "5000", label: t("5.000 €", "€5,000") },
      { id: "10000", label: t("10.000 €", "€10,000") },
      { id: "25000", label: t("25.000 €", "€25,000") },
      { id: "50000", label: t("50.000 €", "€50,000") },
      { id: "generic", label: t("Prefiero ejemplos genéricos", "I prefer generic examples") },
    ],
  },
  {
    id: "products_known",
    block: "products",
    mode: both,
    multi: true,
    prompt: t("Marca los productos que conoces o considerarías usar con dinero real.", "Select the products you know or would consider using with real money."),
    helper: t("Esto activa preguntas adaptativas. No es una recomendación ni una validación.", "This activates adaptive questions. It is not a recommendation or validation."),
    options: [
      { id: "cash", label: t("Liquidez / fondos monetarios", "Cash / money market funds"), products: ["cash"], scores: { productComplexity: 12 } },
      { id: "bonds", label: t("Bonos simples", "Simple bonds"), products: ["bonds"], scores: { productComplexity: 25 } },
      { id: "indexFunds", label: t("Fondos indexados diversificados", "Diversified index funds"), products: ["indexFunds"], scores: { productComplexity: 35 } },
      { id: "individualStocks", label: t("Acciones individuales", "Individual stocks"), products: ["individualStocks"], scores: { productComplexity: 55 } },
      { id: "sectorEtfs", label: t("ETFs sectoriales o temáticos", "Sector or thematic ETFs"), products: ["sectorEtfs"], scores: { productComplexity: 58 } },
      { id: "crypto", label: t("Criptoactivos", "Cryptoassets"), products: ["crypto"], scores: { productComplexity: 72 }, flags: ["complex_products_selected"] },
      { id: "options", label: t("Opciones", "Options"), products: ["options"], scores: { productComplexity: 90 }, flags: ["complex_products_selected"] },
      { id: "leverage", label: t("Apalancamiento / margen", "Leverage / margin"), products: ["leverage"], scores: { productComplexity: 92 }, flags: ["complex_products_selected"] },
      { id: "shortSelling", label: t("Venta en corto", "Short selling"), products: ["shortSelling"], scores: { productComplexity: 95 }, flags: ["complex_products_selected"] },
    ],
  },
  {
    id: "income_stability",
    block: "financial",
    mode: both,
    prompt: t("¿Cómo describirías tu fuente principal de ingresos?", "How would you describe your main source of income?"),
    helper: t("Ubica la estabilidad de ingresos antes de pensar en asumir más riesgo.", "This places income stability before thinking about taking more risk."),
    options: [
      { id: "very_stable", label: t("Muy estable y previsible", "Very stable and predictable"), scores: { incomeStability: 92, financialCapacity: 78 } },
      { id: "stable", label: t("Bastante estable", "Fairly stable"), scores: { incomeStability: 76, financialCapacity: 68 } },
      { id: "variable_manageable", label: t("Variable, pero manejable", "Variable, but manageable"), scores: { incomeStability: 56, financialCapacity: 56 } },
      { id: "very_variable", label: t("Muy variable", "Very variable"), scores: { incomeStability: 32, financialCapacity: 40 }, flags: ["income_fragility"] },
      { id: "uncertain", label: t("Incierta o dependiente de pocos eventos", "Uncertain or dependent on few events"), scores: { incomeStability: 18, financialCapacity: 28 }, flags: ["income_fragility"] },
    ],
  },
  {
    id: "surplus_cash_flow",
    block: "financial",
    mode: both,
    prompt: t("Después de cubrir tus gastos normales, ¿sueles generar excedente?", "After covering normal expenses, do you usually generate surplus cash flow?"),
    helper: t("El excedente ayuda a separar inversión, imprevistos y gastos cotidianos.", "Surplus cash flow helps separate investing, surprises and daily expenses."),
    options: [
      { id: "consistent", label: t("Sí, de forma consistente", "Yes, consistently"), scores: { surplusCashFlow: 92, financialCapacity: 84, liquidityStrength: 76 } },
      { id: "most_months", label: t("Sí, la mayoría de los meses", "Yes, most months"), scores: { surplusCashFlow: 76, financialCapacity: 72, liquidityStrength: 68 } },
      { id: "sometimes", label: t("A veces", "Sometimes"), scores: { surplusCashFlow: 52, financialCapacity: 54, liquidityStrength: 50 } },
      { id: "rarely", label: t("Rara vez", "Rarely"), scores: { surplusCashFlow: 30, financialCapacity: 36, liquidityStrength: 34 }, flags: ["low_surplus", "liquidity_fragility"] },
      { id: "tight_or_deficit", label: t("No, normalmente quedo justo o en déficit", "No, I usually end up tight or in deficit"), scores: { surplusCashFlow: 14, financialCapacity: 24, liquidityStrength: 22 }, flags: ["low_surplus", "liquidity_fragility"] },
    ],
  },
  {
    id: "expensive_debt",
    block: "financial",
    mode: both,
    prompt: t("¿Tienes deuda de alto coste, como tarjetas, créditos de consumo o préstamos que te presionan mensualmente?", "Do you have high-cost debt, such as credit cards, consumer loans or debt that creates monthly pressure?"),
    helper: t("La deuda cara puede reducir el margen para asumir riesgo, incluso con buen conocimiento.", "High-cost debt can reduce room to take risk, even with strong knowledge."),
    options: [
      { id: "none", label: t("No", "No"), scores: { expensiveDebtControl: 94, financialCapacity: 78, liquidityStrength: 74 } },
      { id: "small_controlled", label: t("Poca y controlada", "Small and controlled"), scores: { expensiveDebtControl: 76, financialCapacity: 68, liquidityStrength: 64 } },
      { id: "relevant_manageable", label: t("Algo relevante, pero manejable", "Some relevant debt, but manageable"), scores: { expensiveDebtControl: 52, financialCapacity: 50, liquidityStrength: 46 } },
      { id: "pressures_me", label: t("Sí, me presiona", "Yes, it pressures me"), scores: { expensiveDebtControl: 24, financialCapacity: 30, liquidityStrength: 28 }, flags: ["expensive_debt", "liquidity_fragility"] },
      { id: "pending_priority", label: t("Sí, es una prioridad pendiente", "Yes, it is a pending priority"), scores: { expensiveDebtControl: 14, financialCapacity: 24, liquidityStrength: 22 }, flags: ["expensive_debt", "liquidity_fragility"] },
    ],
  },
  {
    id: "goal_horizon_clarity",
    block: "financial",
    mode: both,
    prompt: t("¿Tienes claro para qué usarías este dinero y cuándo podrías necesitarlo?", "Are you clear about what this money is for and when you might need it?"),
    helper: t("Objetivo y horizonte ayudan a distinguir dinero de corto plazo de dinero para invertir.", "Goal and horizon help distinguish short-term money from money meant to invest."),
    options: [
      { id: "clear", label: t("Sí, objetivo y horizonte claros", "Yes, clear goal and horizon"), scores: { goalClarity: 92, timeHorizon: 78, consistency: 74 } },
      { id: "fairly_clear", label: t("Bastante claro", "Fairly clear"), scores: { goalClarity: 74, timeHorizon: 68, consistency: 66 } },
      { id: "more_or_less", label: t("Más o menos", "More or less"), scores: { goalClarity: 52, timeHorizon: 50, consistency: 52 } },
      { id: "unclear", label: t("Poco claro", "Not very clear"), scores: { goalClarity: 30, timeHorizon: 36, consistency: 40 }, flags: ["unclear_horizon"] },
      { id: "undefined", label: t("No lo tengo definido", "I have not defined it"), scores: { goalClarity: 16, timeHorizon: 28, consistency: 34 }, flags: ["unclear_horizon", "near_cash_need"] },
    ],
  },
  {
    id: "savings_share",
    block: "financial",
    mode: both,
    prompt: t("¿Qué parte de tus ahorros totales representa el dinero que piensas invertir?", "What share of your total savings does the money you plan to invest represent?"),
    helper: t("Elige la opción que más se parezca a tu situación.", "Choose the option that best resembles your situation."),
    options: [
      { id: "lt10", label: t("Menos del 10%", "Less than 10%"), scores: { financialCapacity: 88, liquidityStrength: 82 } },
      { id: "10_25", label: t("Entre 10% y 25%", "Between 10% and 25%"), scores: { financialCapacity: 74, liquidityStrength: 70 } },
      { id: "25_50", label: t("Entre 25% y 50%", "Between 25% and 50%"), scores: { financialCapacity: 55, liquidityStrength: 52 } },
      { id: "gt50", label: t("Más del 50%", "More than 50%"), scores: { financialCapacity: 34, liquidityStrength: 34 }, flags: ["capital_concentration"] },
      { id: "almost_all", label: t("Prácticamente todo mi ahorro disponible", "Almost all my available savings"), scores: { financialCapacity: 18, liquidityStrength: 18 }, flags: ["capital_concentration", "liquidity_fragility"] },
    ],
  },
  {
    id: "loss_life_effect",
    block: "financial",
    mode: both,
    prompt: t("Tu inversión cae de {amount} a {amountMinus20} aproximadamente (-20%). ¿Qué tanto afectaría tu vida diaria?", "Your investment falls from {amount} to {amountMinus20}, approximately -20%. How much would it affect your daily life?"),
    helper: t("Piensa en pagos, familia, sueño y decisiones obligadas, no solo en el porcentaje.", "Think about payments, family, sleep and forced decisions, not only the percentage."),
    options: [
      { id: "none", label: t("Casi nada; tengo margen suficiente", "Almost nothing; I have enough margin"), scores: { financialCapacity: 88, liquidityStrength: 84, emotionalTolerance: 72 } },
      { id: "annoying", label: t("Me molestaría, pero no cambiaría pagos importantes", "It would bother me, but not change important payments"), scores: { financialCapacity: 68, liquidityStrength: 65, emotionalTolerance: 58 } },
      { id: "adjust", label: t("Tendría que ajustar algunos gastos", "I would need to adjust some expenses"), scores: { financialCapacity: 45, liquidityStrength: 42, emotionalTolerance: 42 }, flags: ["liquidity_fragility"] },
      { id: "uncomfortable", label: t("Me pondría en una situación incómoda", "It would put me in an uncomfortable situation"), scores: { financialCapacity: 28, liquidityStrength: 25, emotionalTolerance: 30 }, flags: ["liquidity_fragility"] },
      { id: "serious", label: t("Me afectaría seriamente", "It would seriously affect me"), scores: { financialCapacity: 12, liquidityStrength: 12, emotionalTolerance: 22 }, flags: ["liquidity_fragility"] },
    ],
  },
  {
    id: "emergency_months",
    block: "financial",
    mode: both,
    prompt: t("¿Cuántos meses de gastos tienes separados fuera de inversiones volátiles?", "How many months of expenses do you keep outside volatile investments?"),
    helper: t("El colchón separa inversión de supervivencia financiera.", "The buffer separates investing from financial survival."),
    options: [
      { id: "gt12", label: t("Más de 12 meses", "More than 12 months"), scores: { liquidityStrength: 92, financialCapacity: 82 } },
      { id: "6_12", label: t("Entre 6 y 12 meses", "Between 6 and 12 months"), scores: { liquidityStrength: 78, financialCapacity: 72 } },
      { id: "3_6", label: t("Entre 3 y 6 meses", "Between 3 and 6 months"), scores: { liquidityStrength: 55, financialCapacity: 58 } },
      { id: "lt3", label: t("Menos de 3 meses", "Less than 3 months"), scores: { liquidityStrength: 28, financialCapacity: 35 }, flags: ["low_emergency_fund", "liquidity_fragility"] },
      { id: "none", label: t("No tengo fondo separado", "I do not have a separate buffer"), scores: { liquidityStrength: 12, financialCapacity: 25 }, flags: ["low_emergency_fund", "liquidity_fragility"] },
    ],
  },
  {
    id: "cash_need_12m",
    block: "financial",
    mode: both,
    prompt: t("¿Qué tan probable es que necesites usar este dinero en los próximos 12 meses?", "How likely are you to need this money in the next 12 months?"),
    helper: t("Un horizonte largo en teoría no sirve si la caja se necesita pronto.", "A long horizon in theory does not help if cash is needed soon."),
    options: [
      { id: "very_low", label: t("Muy poco probable", "Very unlikely"), scores: { timeHorizon: 86, liquidityStrength: 80 } },
      { id: "low", label: t("Poco probable", "Unlikely"), scores: { timeHorizon: 72, liquidityStrength: 68 } },
      { id: "possible", label: t("Posible; no lo descarto", "Possible; I cannot rule it out"), scores: { timeHorizon: 45, liquidityStrength: 44 }, flags: ["near_cash_need"] },
      { id: "likely", label: t("Probable", "Likely"), scores: { timeHorizon: 25, liquidityStrength: 25 }, flags: ["near_cash_need", "liquidity_fragility"] },
      { id: "certain", label: t("Casi seguro", "Almost certain"), scores: { timeHorizon: 12, liquidityStrength: 15 }, flags: ["near_cash_need", "liquidity_fragility"] },
    ],
  },
  {
    id: "declared_drop",
    block: "pressure",
    mode: both,
    prompt: t("En abstracto, ¿qué caída temporal crees que podrías tolerar sin romper el plan?", "In theory, what temporary loss do you think you could tolerate without breaking the plan?"),
    helper: t("Luego lo contrastamos con escenarios concretos.", "We will compare this with concrete scenarios later."),
    options: [
      { id: "5", label: t("Hasta -5%", "Up to -5%"), scores: { emotionalTolerance: 25 } },
      { id: "10", label: t("Hasta -10%", "Up to -10%"), scores: { emotionalTolerance: 42 } },
      { id: "20", label: t("Hasta -20%", "Up to -20%"), scores: { emotionalTolerance: 62 } },
      { id: "35", label: t("Hasta -35%", "Up to -35%"), scores: { emotionalTolerance: 82 }, flags: ["declared_high_tolerance"] },
      { id: "more", label: t("Más de -35% si el plan tiene sentido", "More than -35% if the plan still makes sense"), scores: { emotionalTolerance: 90, overconfidence: 64 }, flags: ["declared_high_tolerance"] },
    ],
  },
  {
    id: "pressure_drop",
    block: "pressure",
    mode: both,
    prompt: t("Invertiste {amount}. Tres meses después ves {amountMinus18} aproximadamente (-18%). Redes y prensa hablan de más caídas. ¿Qué haces primero?", "You invested {amount}. Three months later you see {amountMinus18}, approximately -18%. Social media and news talk about further losses. What do you do first?"),
    helper: t("Elige la opción que más se parezca a lo que harías.", "Choose the option that best resembles what you would do."),
    options: [
      { id: "review", label: t("Reviso si cambió la tesis antes de tocar nada", "I check whether the thesis changed before touching anything"), scores: { emotionalTolerance: 76, consistency: 78, patience: 75 } },
      { id: "sell_part", label: t("Vendo una parte para recuperar tranquilidad", "I sell part to regain calm"), scores: { emotionalTolerance: 35, consistency: 42, patience: 35 }, flags: ["pressure_low_tolerance"] },
      { id: "sell_all", label: t("Salgo y acepto la pérdida para dejar de mirar", "I exit and accept the loss to stop watching"), scores: { emotionalTolerance: 18, consistency: 25, patience: 22 }, flags: ["pressure_low_tolerance", "panic_sell"] },
      { id: "buy_more", label: t("Compro más porque ahora está más barato", "I buy more because it is cheaper now"), scores: { emotionalTolerance: 68, overconfidence: 72, consistency: 42 }, flags: ["overconfidence"] },
      { id: "written_rule", label: t("Solo actuaría si una regla escrita ya lo contemplaba", "I would act only if a written rule already covered it"), scores: { emotionalTolerance: 78, consistency: 88, patience: 80 } },
    ],
  },
  {
    id: "slow_underperformance",
    block: "pressure",
    mode: both,
    prompt: t("Tu inversión no cae mucho, pero durante 18 meses va peor que lo que todos comentan. ¿Qué pesa más?", "Your investment does not fall much, but for 18 months it lags what everyone talks about. What weighs most?"),
    helper: t("La paciencia también se prueba por comparación social.", "Patience is also tested by social comparison."),
    options: [
      { id: "process", label: t("Mantener proceso si las razones siguen vigentes", "Keep the process if the reasons still hold"), scores: { patience: 84, consistency: 82 } },
      { id: "compare", label: t("Me costaría no moverme a lo que está funcionando", "It would be hard not to move to what is working"), scores: { patience: 35, fomoSensitivity: 76 }, flags: ["social_pressure", "fomo_entry"] },
      { id: "split", label: t("Movería una parte para no quedarme atrás", "I would move part so I do not fall behind"), scores: { patience: 42, fomoSensitivity: 68 }, flags: ["social_pressure"] },
      { id: "ignore", label: t("Evitaría mirar comparaciones para no alterar el plan", "I would avoid comparisons so they do not disturb the plan"), scores: { patience: 65, consistency: 65 } },
    ],
  },
  {
    id: "fast_gain",
    block: "bias",
    mode: both,
    prompt: t("Una posición de {amount} sube a {amountPlus45} en pocas semanas y ahora pesa mucho más dentro de tu cartera. ¿Qué haces primero?", "A position of {amount} rises to {amountPlus45} in a few weeks and now represents a much larger part of your portfolio. What do you do first?"),
    helper: t("Elige la opción que más se parezca a lo que harías.", "Choose the option that best resembles what you would do."),
    options: [
      { id: "rebalance", label: t("Reviso peso, riesgo y reglas antes de aumentar", "I review weight, risk and rules before adding"), scores: { euphoriaRisk: 18, consistency: 80 } },
      { id: "take_profit", label: t("Tomo una parte de ganancias y mantengo el plan", "I take some profit and keep the plan"), scores: { euphoriaRisk: 28, consistency: 72, calibration: 70 } },
      { id: "hold", label: t("Mantengo porque todavía puede seguir subiendo", "I hold because it could keep rising"), scores: { euphoriaRisk: 55, overconfidence: 52, consistency: 50 } },
      { id: "increase", label: t("Aumento porque la tesis parece estar funcionando", "I add because the thesis seems to be working"), scores: { euphoriaRisk: 86, overconfidence: 84, consistency: 34 }, flags: ["euphoria_sizing", "overconfidence"] },
      { id: "repeat", label: t("Busco otra oportunidad parecida para repetir", "I look for a similar opportunity to repeat it"), scores: { euphoriaRisk: 90, fomoSensitivity: 82, overconfidence: 78 }, flags: ["euphoria_sizing", "fomo_entry", "overconfidence"] },
    ],
  },
  {
    id: "return_expectation",
    block: "expectations",
    mode: both,
    prompt: t("Para sentir que vale la pena, ¿qué retorno anual esperarías de una inversión con riesgo?", "For it to feel worthwhile, what annual return would you expect from a risky investment?"),
    helper: t("No buscamos precisión; buscamos calibración de expectativas.", "We are not looking for precision; we are looking for expectation calibration."),
    options: [
      { id: "3_6", label: t("3% a 6%", "3% to 6%"), scores: { expectationRealism: 78 } },
      { id: "6_10", label: t("6% a 10%", "6% to 10%"), scores: { expectationRealism: 86 } },
      { id: "10_15", label: t("10% a 15%", "10% to 15%"), scores: { expectationRealism: 58 } },
      { id: "15_25", label: t("15% a 25%", "15% to 25%"), scores: { expectationRealism: 30, overconfidence: 65 }, flags: ["unrealistic_expectations"] },
      { id: "gt25", label: t("Más de 25%", "More than 25%"), scores: { expectationRealism: 12, overconfidence: 82 }, flags: ["unrealistic_expectations"] },
    ],
  },
  {
    id: "bad_year",
    block: "expectations",
    mode: both,
    prompt: t("Si una inversión razonable tiene un año negativo, ¿qué significa para ti?", "If a reasonable investment has a negative year, what does it mean to you?"),
    helper: t("Una expectativa incompatible suele romper el plan antes que el mercado.", "An incompatible expectation often breaks the plan before the market does."),
    options: [
      { id: "normal", label: t("Puede ser normal; reviso si sigue cumpliendo su función", "It can be normal; I check whether it still serves its role"), scores: { expectationRealism: 84, patience: 78 } },
      { id: "mistake", label: t("Probablemente elegí mal", "I probably chose badly"), scores: { expectationRealism: 35, patience: 36 }, flags: ["unrealistic_expectations"] },
      { id: "change", label: t("Buscaría algo que haya aguantado mejor", "I would look for something that held up better"), scores: { expectationRealism: 42, fomoSensitivity: 62 }, flags: ["social_pressure"] },
      { id: "depends", label: t("Depende de si el riesgo estaba contemplado desde el inicio", "It depends on whether the risk was contemplated from the start"), scores: { expectationRealism: 78, consistency: 74 } },
    ],
  },
  {
    id: "stock_basic",
    block: "knowledge",
    mode: both,
    prompt: t("Cuando compras una acción, ¿qué estás adquiriendo realmente?", "When you buy a stock, what are you really acquiring?"),
    helper: t("Conocimiento básico antes de evaluar riesgo.", "Basic knowledge before evaluating risk."),
    options: [
      { id: "ownership", label: t("Una participación económica en una empresa", "An economic ownership stake in a company"), scores: { knowledgeValidated: 90 } },
      { id: "loan", label: t("Un préstamo con interés fijo", "A loan with fixed interest"), scores: { knowledgeValidated: 18 }, flags: ["knowledge_gap_basic"] },
      { id: "guarantee", label: t("Un contrato que garantiza retorno si la empresa crece", "A contract that guarantees return if the company grows"), scores: { knowledgeValidated: 20 }, flags: ["knowledge_gap_basic"] },
      { id: "unsure", label: t("No estoy seguro", "I am not sure"), scores: { knowledgeValidated: 35, calibration: 78 }, flags: ["humble_uncertainty"] },
    ],
  },
  {
    id: "risk_return",
    block: "knowledge",
    mode: both,
    prompt: t("Si una inversión ofrece más retorno esperado, normalmente también implica...", "If an investment offers higher expected return, it usually also implies..."),
    helper: t("No siempre, pero la compensación riesgo-retorno importa.", "Not always, but the risk-return tradeoff matters."),
    options: [
      { id: "risk", label: t("Más incertidumbre, riesgo o condiciones que analizar", "More uncertainty, risk or conditions to analyze"), scores: { knowledgeValidated: 88 } },
      { id: "better", label: t("Una oportunidad mejor si el historial reciente fue bueno", "A better opportunity if recent performance was good"), scores: { knowledgeValidated: 35, fomoSensitivity: 58 }, flags: ["knowledge_gap_basic"] },
      { id: "less_risk", label: t("Menos riesgo porque alguien encontró una ineficiencia", "Less risk because someone found an inefficiency"), scores: { knowledgeValidated: 22, overconfidence: 68 }, flags: ["knowledge_gap_basic"] },
      { id: "past_only", label: t("Solo se puede evaluar mirando rentabilidad pasada", "It can only be evaluated by looking at past return"), scores: { knowledgeValidated: 32 }, flags: ["knowledge_gap_basic"] },
    ],
  },
  {
    id: "diversification",
    block: "knowledge",
    mode: both,
    prompt: t("¿Qué busca principalmente la diversificación?", "What does diversification mainly try to do?"),
    helper: t("No elimina todo riesgo; reduce dependencia de un único resultado.", "It does not remove all risk; it reduces dependence on one outcome."),
    options: [
      { id: "reduce_dependency", label: t("Reducir dependencia de un activo, sector o escenario", "Reduce dependence on one asset, sector or scenario"), scores: { knowledgeValidated: 88 } },
      { id: "increase_return", label: t("Aumentar siempre el retorno esperado", "Always increase expected return"), scores: { knowledgeValidated: 24 }, flags: ["knowledge_gap_basic"] },
      { id: "avoid_loss", label: t("Evitar cualquier pérdida temporal", "Avoid any temporary loss"), scores: { knowledgeValidated: 20 }, flags: ["knowledge_gap_basic"] },
      { id: "winner", label: t("Concentrar en lo que mejor funcionó", "Concentrate in what worked best"), scores: { knowledgeValidated: 28, fomoSensitivity: 65 }, flags: ["concentration_bias"] },
    ],
  },
  {
    id: "bond_rates",
    block: "knowledge",
    mode: both,
    prompt: t("Si suben los tipos de interés, el precio de un bono existente normalmente...", "If interest rates rise, the price of an existing bond usually..."),
    helper: t("Fuente frecuente de sorpresa en productos considerados conservadores.", "A frequent source of surprise in products considered conservative."),
    options: [
      { id: "falls", label: t("Puede bajar, especialmente si tiene duración alta", "Can fall, especially if it has high duration"), scores: { knowledgeValidated: 88 } },
      { id: "rises", label: t("Debe subir porque paga intereses", "Must rise because it pays interest"), scores: { knowledgeValidated: 25 }, flags: ["knowledge_gap_basic"] },
      { id: "fixed", label: t("No se mueve porque los bonos son fijos", "Does not move because bonds are fixed"), scores: { knowledgeValidated: 20 }, flags: ["knowledge_gap_basic"] },
      { id: "default_only", label: t("Solo cambia si el emisor quiebra", "Only changes if the issuer defaults"), scores: { knowledgeValidated: 30 }, flags: ["knowledge_gap_basic"] },
    ],
  },
  {
    id: "claim_vs_validate",
    block: "knowledge",
    mode: both,
    prompt: t("¿Cómo describirías tu conocimiento financiero?", "How would you describe your financial knowledge?"),
    helper: t("Esta respuesta se compara con las preguntas de validación.", "This answer is compared with validation questions."),
    options: [
      { id: "low", label: t("Estoy empezando", "I am starting"), scores: { calibration: 78, overconfidence: 18 } },
      { id: "basic", label: t("Básico, entiendo productos simples", "Basic, I understand simple products"), scores: { calibration: 70, overconfidence: 28 } },
      { id: "medium", label: t("Intermedio, puedo comparar riesgos y costes", "Intermediate, I can compare risks and costs"), scores: { calibration: 58, overconfidence: 45 }, flags: ["claims_knowledge"] },
      { id: "high", label: t("Alto, entiendo productos complejos", "High, I understand complex products"), scores: { calibration: 42, overconfidence: 68 }, flags: ["claims_knowledge"] },
    ],
  },
  {
    id: "years_real",
    block: "experience",
    mode: both,
    prompt: t("¿Cuántos años llevas invirtiendo con dinero propio?", "How many years have you invested with your own money?"),
    helper: t("Experiencia real es decidir bajo incertidumbre, no solo leer.", "Real experience is deciding under uncertainty, not only reading."),
    options: [
      { id: "lt1", label: t("Menos de 1 año", "Less than 1 year"), scores: { experienceReal: 22 } },
      { id: "1_3", label: t("1 a 3 años", "1 to 3 years"), scores: { experienceReal: 45 } },
      { id: "4_8", label: t("4 a 8 años", "4 to 8 years"), scores: { experienceReal: 68 } },
      { id: "gt8", label: t("Más de 8 años y he vivido ciclos difíciles", "More than 8 years and I have lived through difficult cycles"), scores: { experienceReal: 88 } },
    ],
  },
  {
    id: "real_drawdown",
    block: "experience",
    mode: both,
    prompt: t("¿Has vivido una caída fuerte con dinero propio invertido?", "Have you lived through a sharp drawdown with your own invested money?"),
    helper: t("Una caída real enseña cosas que un simulador no enseña.", "A real drawdown teaches things a simulator does not."),
    options: [
      { id: "no", label: t("No, mi experiencia ha sido tranquila", "No, my experience has been calm"), scores: { experienceReal: 34 } },
      { id: "sold", label: t("Sí, y vendí por incomodidad", "Yes, and I sold due to discomfort"), scores: { experienceReal: 52, emotionalTolerance: 30 }, flags: ["pressure_low_tolerance", "panic_sell"] },
      { id: "held", label: t("Sí, mantuve el plan y revisé aprendizajes", "Yes, I kept the plan and reviewed lessons"), scores: { experienceReal: 82, emotionalTolerance: 78, consistency: 80 } },
      { id: "averaged", label: t("Sí, aumenté exposición sin regla escrita", "Yes, I added exposure without a written rule"), scores: { experienceReal: 60, overconfidence: 70, consistency: 38 }, flags: ["no_written_process", "overconfidence"] },
    ],
  },
  {
    id: "process_docs",
    block: "experience",
    mode: both,
    prompt: t("Antes de usar un producto nuevo, ¿qué sueles revisar?", "Before using a new product, what do you usually review?"),
    helper: t("Elige la opción que más se parezca a lo que haces normalmente.", "Choose the option that best resembles what you usually do."),
    options: [
      { id: "full", label: t("Costes, liquidez, pérdida posible, documento del producto y rol en el plan", "Costs, liquidity, possible loss, product document and role in the plan"), scores: { experienceReal: 82, knowledgeValidated: 76, consistency: 82 } },
      { id: "performance", label: t("Rendimiento reciente y opiniones de fuentes que sigo", "Recent performance and opinions from sources I follow"), scores: { experienceReal: 42, fomoSensitivity: 72 }, flags: ["social_pressure"] },
      { id: "summary", label: t("Una descripción general si parece simple", "A general description if it seems simple"), scores: { experienceReal: 38, knowledgeValidated: 42 } },
      { id: "size_dependent", label: t("Depende del tamaño; para montos pequeños reviso menos", "It depends on size; for small amounts I review less"), scores: { experienceReal: 58, consistency: 52 } },
    ],
  },
  {
    id: "fomo_behavior",
    block: "bias",
    mode: both,
    prompt: t("Cuando mucha gente parece ganar dinero rápido, ¿qué te ocurre?", "When many people seem to be making money quickly, what happens to you?"),
    helper: t("Elige la opción que más se parezca a lo que harías.", "Choose the option that best resembles what you would do."),
    options: [
      { id: "wait", label: t("Siento presión, pero espero mi proceso", "I feel pressure, but I wait for my process"), scores: { fomoSensitivity: 25, consistency: 74 } },
      { id: "small", label: t("Me cuesta no participar aunque sea con poco", "It is hard not to participate, even with a little"), scores: { fomoSensitivity: 78, consistency: 42 }, flags: ["fomo_entry"] },
      { id: "confirm", label: t("Busco argumentos de que aún estoy a tiempo", "I look for arguments that I am still in time"), scores: { fomoSensitivity: 86, overconfidence: 62 }, flags: ["fomo_entry", "social_pressure"] },
      { id: "avoid", label: t("Prefiero ignorarlo para no alterar mi plan", "I prefer to ignore it so it does not disturb my plan"), scores: { fomoSensitivity: 35, consistency: 64 } },
    ],
  },
  {
    id: "loss_recovery",
    block: "bias",
    mode: both,
    prompt: t("Después de una pérdida incómoda, ¿qué impulso reconoces más?", "After an uncomfortable loss, which impulse do you recognize most?"),
    helper: t("Recuperar rápido suele ser una fuente fuerte de errores.", "Trying to recover quickly is often a strong source of mistakes."),
    options: [
      { id: "reduce", label: t("Reducir tamaño y revisar proceso", "Reduce size and review process"), scores: { consistency: 72, emotionalTolerance: 58 } },
      { id: "recover", label: t("Buscar una operación que recupere la pérdida", "Look for a trade to recover the loss"), scores: { consistency: 24, fomoSensitivity: 72 }, flags: ["loss_recovery_bias"] },
      { id: "document", label: t("No tocar nada y documentar qué pasó", "Do nothing and document what happened"), scores: { consistency: 82, patience: 72 } },
      { id: "switch", label: t("Cambiar totalmente de estrategia", "Completely change strategy"), scores: { consistency: 28, patience: 25 }, flags: ["loss_recovery_bias"] },
    ],
  },
  {
    id: "concentration",
    block: "bias",
    mode: both,
    prompt: t("Si tienes mucha convicción en una idea, ¿qué peso máximo te parecería razonable?", "If you have strong conviction in an idea, what maximum weight would feel reasonable?"),
    helper: t("Elige la opción que más se parezca a lo que harías.", "Choose the option that best resembles what you would do."),
    options: [
      { id: "lt10", label: t("Menos de 10%", "Less than 10%"), scores: { consistency: 82, overconfidence: 18 } },
      { id: "10_20", label: t("10% a 20%", "10% to 20%"), scores: { consistency: 70, overconfidence: 35 } },
      { id: "20_40", label: t("20% a 40%", "20% to 40%"), scores: { consistency: 45, overconfidence: 65 }, flags: ["concentration_bias"] },
      { id: "gt40", label: t("Más de 40% si la tesis es fuerte", "More than 40% if the thesis is strong"), scores: { consistency: 28, overconfidence: 84 }, flags: ["concentration_bias", "overconfidence"] },
    ],
  },
  {
    id: "plan_written",
    block: "bias",
    mode: both,
    prompt: t("Antes de invertir, ¿sueles definir por escrito qué harías si cae, sube o no se mueve?", "Before investing, do you usually write what you would do if it falls, rises or does not move?"),
    helper: t("Las reglas escritas reducen respuestas impulsivas bajo presión.", "Written rules reduce impulsive responses under pressure."),
    options: [
      { id: "yes", label: t("Sí, con reglas antes de entrar", "Yes, with rules before entering"), scores: { consistency: 88, patience: 78 } },
      { id: "sometimes", label: t("A veces, si el monto es relevante", "Sometimes, if the amount is relevant"), scores: { consistency: 62 } },
      { id: "mental", label: t("Lo tengo en mente, pero no escrito", "I have it in mind, but not written"), scores: { consistency: 42 }, flags: ["no_written_process"] },
      { id: "no", label: t("No; decido según evolucione", "No; I decide as it evolves"), scores: { consistency: 25 }, flags: ["no_written_process"] },
    ],
  },
  {
    id: "real_money_products_complete",
    block: "experience",
    mode: complete,
    prompt: t("¿En qué has invertido con dinero real, aunque haya sido poco?", "What have you invested in with real money, even if the amount was small?"),
    helper: t("La experiencia real pesa distinto a conocer un producto de forma teórica.", "Real experience weighs differently from knowing a product in theory."),
    options: [
      { id: "none", label: t("Aún no he invertido con dinero real", "I have not invested real money yet"), scores: { experienceReal: 15, calibration: 72 } },
      { id: "simple", label: t("Solo productos simples o diversificados", "Only simple or diversified products"), scores: { experienceReal: 48, productComplexity: 32 } },
      { id: "stocks", label: t("Acciones individuales, ETFs sectoriales o bonos", "Individual stocks, sector ETFs or bonds"), scores: { experienceReal: 66, productComplexity: 58 } },
      { id: "complex_small", label: t("Productos complejos, pero con importes pequeños", "Complex products, but with small amounts"), scores: { experienceReal: 58, productComplexity: 78, calibration: 58 }, flags: ["complex_products_selected"] },
      { id: "complex_relevant", label: t("Productos complejos con importes relevantes para mi patrimonio", "Complex products with meaningful amounts for my wealth"), scores: { experienceReal: 74, productComplexity: 90, overconfidence: 58 }, flags: ["complex_products_selected"] },
    ],
  },
  {
    id: "decision_years_complete",
    block: "experience",
    mode: complete,
    prompt: t("¿Cuánto tiempo llevas tomando decisiones de inversión con dinero real?", "How long have you been making investment decisions with real money?"),
    helper: t("Cuenta decisiones propias, no solo tiempo siguiendo mercados.", "Count your own decisions, not only time following markets."),
    options: [
      { id: "none", label: t("Todavía no he tomado decisiones reales", "I have not made real decisions yet"), scores: { experienceReal: 12, calibration: 74 } },
      { id: "lt1", label: t("Menos de 1 año", "Less than 1 year"), scores: { experienceReal: 24 } },
      { id: "1_3", label: t("1 a 3 años", "1 to 3 years"), scores: { experienceReal: 44 } },
      { id: "4_7", label: t("4 a 7 años", "4 to 7 years"), scores: { experienceReal: 66 } },
      { id: "gt7", label: t("Más de 7 años con varias decisiones relevantes", "More than 7 years with several meaningful decisions"), scores: { experienceReal: 86, calibration: 68 } },
    ],
  },
  {
    id: "worst_real_drawdown_complete",
    block: "experience",
    mode: complete,
    prompt: t("La peor caída que has vivido con dinero real invertido fue aproximadamente...", "The worst drawdown you have experienced with real invested money was approximately..."),
    helper: t("Si no tienes experiencia real, elige la opción más honesta.", "If you do not have real experience, choose the most honest option."),
    options: [
      { id: "none", label: t("No he vivido una caída relevante con dinero real", "I have not experienced a relevant drawdown with real money"), scores: { experienceReal: 24, calibration: 70 } },
      { id: "lt10", label: t("Menos de -10%", "Less than -10%"), scores: { experienceReal: 42, emotionalTolerance: 52 } },
      { id: "10_25", label: t("Entre -10% y -25%", "Between -10% and -25%"), scores: { experienceReal: 62, emotionalTolerance: 62 } },
      { id: "25_40", label: t("Entre -25% y -40%", "Between -25% and -40%"), scores: { experienceReal: 76, emotionalTolerance: 70 } },
      { id: "gt40", label: t("Más de -40%", "More than -40%"), scores: { experienceReal: 86, emotionalTolerance: 76 } },
    ],
  },
  {
    id: "drawdown_action_complete",
    block: "experience",
    mode: complete,
    prompt: t("Durante esa caída con dinero real, ¿qué hiciste principalmente?", "During that real-money drawdown, what did you mainly do?"),
    helper: t("Elige lo que más se parezca a tu reacción real.", "Choose what most resembles your real reaction."),
    options: [
      { id: "not_lived", label: t("No he vivido esa situación", "I have not lived through that situation"), scores: { experienceReal: 26, calibration: 72 } },
      { id: "sold_all", label: t("Vendí todo o casi todo para cortar la incomodidad", "I sold all or almost all to stop the discomfort"), scores: { emotionalTolerance: 18, consistency: 24, experienceReal: 44 }, flags: ["panic_sell", "pressure_low_tolerance"] },
      { id: "sold_part", label: t("Reduje parte y después revisé con calma", "I reduced part and reviewed calmly later"), scores: { emotionalTolerance: 42, consistency: 48, experienceReal: 58 }, flags: ["pressure_low_tolerance"] },
      { id: "held_reviewed", label: t("Mantuve y revisé si el motivo original seguía vigente", "I held and reviewed whether the original reason still held"), scores: { emotionalTolerance: 76, consistency: 82, experienceReal: 78 } },
      { id: "added_rule", label: t("Aumenté solo porque una regla previa lo contemplaba", "I added only because a prior rule covered it"), scores: { emotionalTolerance: 82, consistency: 88, experienceReal: 82 } },
      { id: "added_impulse", label: t("Aumenté para intentar recuperar o aprovechar la caída", "I added to try to recover or take advantage of the drop"), scores: { emotionalTolerance: 60, consistency: 32, overconfidence: 72 }, flags: ["loss_recovery_bias", "no_written_process"] },
    ],
  },
  {
    id: "income_stability_complete",
    block: "financial",
    mode: complete,
    prompt: t("Si tus ingresos bajaran durante seis meses, ¿qué pasaría con el dinero invertido?", "If your income fell for six months, what would happen to the invested money?"),
    helper: t("Piensa en la situación completa, no solo en el plan ideal.", "Think about the full situation, not only the ideal plan."),
    options: [
      { id: "untouched", label: t("Probablemente no tendría que tocarlo", "I probably would not need to touch it"), scores: { liquidityStrength: 88, financialCapacity: 82, timeHorizon: 78 } },
      { id: "maybe_small", label: t("Podría necesitar una parte pequeña", "I might need a small part"), scores: { liquidityStrength: 62, financialCapacity: 64, timeHorizon: 58 } },
      { id: "likely", label: t("Probablemente tendría que vender parte", "I would probably need to sell part"), scores: { liquidityStrength: 34, financialCapacity: 42, timeHorizon: 35 }, flags: ["near_cash_need", "liquidity_fragility"] },
      { id: "critical", label: t("Sería una fuente principal de liquidez", "It would be a main source of liquidity"), scores: { liquidityStrength: 18, financialCapacity: 28, timeHorizon: 20 }, flags: ["near_cash_need", "liquidity_fragility"] },
    ],
  },
  {
    id: "known_expenses_complete",
    block: "financial",
    mode: complete,
    prompt: t("En los próximos 24 meses, ¿tienes gastos grandes relativamente probables?", "In the next 24 months, do you have relatively likely large expenses?"),
    helper: t("Incluye vivienda, estudios, negocio, familia o cambios laborales.", "Include housing, education, business, family or job changes."),
    options: [
      { id: "none", label: t("No, no tengo gastos grandes previstos", "No, I have no large expenses planned"), scores: { liquidityStrength: 84, timeHorizon: 82 } },
      { id: "manageable", label: t("Sí, pero ya tengo caja separada para eso", "Yes, but I already have cash set aside for that"), scores: { liquidityStrength: 76, timeHorizon: 70 } },
      { id: "possible", label: t("Podría tenerlos y no está todo cubierto", "I could have them and they are not fully covered"), scores: { liquidityStrength: 42, timeHorizon: 45 }, flags: ["near_cash_need"] },
      { id: "yes_unclear", label: t("Sí, y todavía no tengo claro cómo los cubriría", "Yes, and I am not yet sure how I would cover them"), scores: { liquidityStrength: 24, timeHorizon: 28, financialCapacity: 32 }, flags: ["near_cash_need", "liquidity_fragility"] },
    ],
  },
  {
    id: "horizon_conflict_complete",
    block: "financial",
    mode: complete,
    prompt: t("Si una inversión necesita cinco años para tener sentido, pero tú podrías necesitar el dinero en dos, ¿qué harías?", "If an investment needs five years to make sense, but you might need the money in two, what would you do?"),
    helper: t("Elige la opción más cercana a tu forma habitual de decidir.", "Choose the option closest to how you usually decide."),
    options: [
      { id: "avoid", label: t("No usaría ese dinero para esa inversión", "I would not use that money for that investment"), scores: { timeHorizon: 88, liquidityStrength: 84, consistency: 80 } },
      { id: "smaller", label: t("Invertiría solo una parte que pueda dejar quieta", "I would invest only a part I can leave untouched"), scores: { timeHorizon: 72, liquidityStrength: 70, consistency: 72 } },
      { id: "take_chance", label: t("Lo haría si creo que en dos años puede ir bien", "I would do it if I think it can do well in two years"), scores: { timeHorizon: 36, liquidityStrength: 42, overconfidence: 62 }, flags: ["near_cash_need"] },
      { id: "decide_later", label: t("Invertiría y decidiría luego si necesito vender", "I would invest and decide later if I need to sell"), scores: { timeHorizon: 24, liquidityStrength: 32, consistency: 32 }, flags: ["near_cash_need", "no_written_process"] },
    ],
  },
  {
    id: "single_position_30_complete",
    block: "bias",
    mode: complete,
    prompt: t("¿Qué tan cómodo estarías con una sola posición representando 30% de tu cartera?", "How comfortable would you be with one position representing 30% of your portfolio?"),
    helper: t("Piensa en dinero real y en una semana de mercado difícil.", "Think about real money and a difficult market week."),
    options: [
      { id: "not", label: t("Poco cómodo; preferiría reducir antes", "Not comfortable; I would rather reduce beforehand"), scores: { consistency: 82, overconfidence: 20 } },
      { id: "depends", label: t("Depende, pero exigiría una regla clara de tamaño", "It depends, but I would require a clear sizing rule"), scores: { consistency: 76, overconfidence: 34 } },
      { id: "comfortable", label: t("Cómodo si conozco bien la tesis", "Comfortable if I know the thesis well"), scores: { consistency: 48, overconfidence: 66 }, flags: ["concentration_bias"] },
      { id: "very", label: t("Muy cómodo si la oportunidad es buena", "Very comfortable if the opportunity is good"), scores: { consistency: 28, overconfidence: 86 }, flags: ["concentration_bias", "overconfidence"] },
    ],
  },
  {
    id: "large_position_down_complete",
    block: "bias",
    mode: complete,
    prompt: t("Una posición grande cae 40%, pero el resto de la cartera está estable. ¿Qué haces?", "A large position falls 40%, but the rest of the portfolio is stable. What do you do?"),
    helper: t("Responde como actuarías si el importe importara de verdad.", "Answer as you would act if the amount truly mattered."),
    options: [
      { id: "review_size", label: t("Reviso tesis, tamaño y regla antes de decidir", "I review thesis, size and rule before deciding"), scores: { consistency: 84, emotionalTolerance: 72 } },
      { id: "trim", label: t("Reduzco para que el error no domine la cartera", "I reduce so the mistake does not dominate the portfolio"), scores: { consistency: 70, emotionalTolerance: 58 } },
      { id: "sell", label: t("Vendo porque ya cayó demasiado", "I sell because it has already fallen too much"), scores: { emotionalTolerance: 28, consistency: 34 }, flags: ["pressure_low_tolerance", "panic_sell"] },
      { id: "double", label: t("Aumento mucho para bajar precio medio", "I add a lot to lower the average cost"), scores: { overconfidence: 86, consistency: 24 }, flags: ["overconfidence", "loss_recovery_bias", "concentration_bias"] },
    ],
  },
  {
    id: "winner_too_large_complete",
    block: "bias",
    mode: complete,
    prompt: t("Si una posición sube mucho y pasa a pesar demasiado, ¿qué haces?", "If a position rises a lot and becomes too large, what do you do?"),
    helper: t("Elige lo que más se parezca a tu reacción real.", "Choose what most resembles your real reaction."),
    options: [
      { id: "rebalance_rule", label: t("Rebalanceo según una regla previa", "I rebalance according to a prior rule"), scores: { consistency: 88, euphoriaRisk: 18 } },
      { id: "partial", label: t("Tomo una parte y dejo correr el resto", "I take part off and let the rest run"), scores: { consistency: 72, euphoriaRisk: 32 } },
      { id: "hold", label: t("Mantengo mientras siga subiendo", "I hold while it keeps rising"), scores: { consistency: 46, euphoriaRisk: 66, overconfidence: 58 }, flags: ["euphoria_sizing"] },
      { id: "add", label: t("Aumento porque la tesis quedó validada", "I add because the thesis was validated"), scores: { consistency: 28, euphoriaRisk: 88, overconfidence: 82 }, flags: ["euphoria_sizing", "overconfidence", "concentration_bias"] },
    ],
  },
  {
    id: "social_comparison_complete",
    block: "pressure",
    mode: complete,
    prompt: t("Tu cartera sube 4% mientras gente cercana presume de 35% en otro activo. ¿Qué haces?", "Your portfolio is up 4% while people close to you brag about 35% in another asset. What do you do?"),
    helper: t("Piensa en la reacción durante varias semanas, no solo en el primer día.", "Think about the reaction over several weeks, not just the first day."),
    options: [
      { id: "ignore", label: t("No cambio nada si mi plan sigue cumpliendo su función", "I change nothing if my plan still serves its role"), scores: { patience: 86, fomoSensitivity: 18, consistency: 82 } },
      { id: "study", label: t("Lo estudio, pero no muevo dinero sin encaje claro", "I study it, but move no money without a clear fit"), scores: { patience: 74, fomoSensitivity: 32, consistency: 76 } },
      { id: "small", label: t("Movería una parte pequeña para participar", "I would move a small part to participate"), scores: { patience: 42, fomoSensitivity: 76, consistency: 44 }, flags: ["fomo_entry", "social_pressure"] },
      { id: "switch", label: t("Cambiaría bastante si todos parecen estar ganando", "I would change a lot if everyone seems to be winning"), scores: { patience: 24, fomoSensitivity: 90, consistency: 26 }, flags: ["fomo_entry", "social_pressure"] },
    ],
  },
  {
    id: "headline_stress_complete",
    block: "pressure",
    mode: complete,
    prompt: t("Abres el móvil y ves titulares muy negativos antes de dormir. Tu inversión cae fuerte ese día. ¿Qué haces?", "You open your phone and see very negative headlines before sleeping. Your investment falls sharply that day. What do you do?"),
    helper: t("Elige la respuesta que más se parezca a una noche real.", "Choose the answer that most resembles a real night."),
    options: [
      { id: "wait_rule", label: t("Espero a revisar en horario definido o con una regla previa", "I wait to review at a defined time or with a prior rule"), scores: { emotionalTolerance: 82, consistency: 86, patience: 78 } },
      { id: "check_more", label: t("Leo más para intentar entender si debo hacer algo", "I read more to try to understand whether I should do something"), scores: { emotionalTolerance: 52, consistency: 48, patience: 44 } },
      { id: "sell_order", label: t("Dejo una orden o reduzco para dormir tranquilo", "I place an order or reduce to sleep calmly"), scores: { emotionalTolerance: 24, consistency: 32 }, flags: ["pressure_low_tolerance", "panic_sell"] },
      { id: "buy_dip", label: t("Compro más inmediatamente si la caída parece exagerada", "I buy more immediately if the drop seems exaggerated"), scores: { emotionalTolerance: 62, overconfidence: 78, consistency: 34 }, flags: ["overconfidence", "no_written_process"] },
    ],
  },
  {
    id: "priority_tradeoff_complete",
    block: "expectations",
    mode: complete,
    prompt: t("Si tuvieras que elegir solo una prioridad, ¿cuál sería?", "If you had to choose only one priority, which would it be?"),
    helper: t("No hay respuesta ideal; fuerza una preferencia práctica.", "There is no ideal answer; it forces a practical preference."),
    options: [
      { id: "avoid_forced", label: t("Evitar verme obligado a vender en mal momento", "Avoid being forced to sell at a bad time"), scores: { liquidityStrength: 86, consistency: 76, timeHorizon: 78 } },
      { id: "sleep", label: t("Dormir tranquilo aunque gane menos", "Sleep calmly even if I earn less"), scores: { emotionalTolerance: 52, expectationRealism: 78 } },
      { id: "growth", label: t("Maximizar crecimiento aceptando baches grandes", "Maximize growth while accepting large bumps"), scores: { emotionalTolerance: 78, expectationRealism: 58, overconfidence: 58 } },
      { id: "not_miss", label: t("No quedarme fuera de grandes oportunidades", "Not miss major opportunities"), scores: { fomoSensitivity: 82, expectationRealism: 38, overconfidence: 64 }, flags: ["fomo_entry"] },
    ],
  },
  {
    id: "discomfort_tradeoff_complete",
    block: "expectations",
    mode: complete,
    prompt: t("Si tuvieras que aceptar solo una incomodidad, ¿cuál aceptarías mejor?", "If you had to accept only one discomfort, which would you accept best?"),
    helper: t("Piensa en meses, no en un momento aislado.", "Think in months, not in one isolated moment."),
    options: [
      { id: "slow", label: t("Avanzar más lento que otros", "Move slower than others"), scores: { patience: 82, fomoSensitivity: 24, consistency: 74 } },
      { id: "drawdown", label: t("Ver caídas temporales relevantes", "See relevant temporary drawdowns"), scores: { emotionalTolerance: 76, patience: 64 } },
      { id: "cash", label: t("Mantener caja aunque parezca improductiva", "Hold cash even if it looks unproductive"), scores: { liquidityStrength: 80, expectationRealism: 72 } },
      { id: "miss", label: t("Perder una subida fuerte por esperar confirmación", "Miss a strong rally by waiting for confirmation"), scores: { fomoSensitivity: 30, consistency: 78 } },
    ],
  },
  {
    id: "sacrifice_first_complete",
    block: "expectations",
    mode: complete,
    prompt: t("Si el mercado te obliga a elegir, ¿qué prefieres sacrificar primero?", "If the market forces you to choose, what would you rather sacrifice first?"),
    helper: t("Elige la concesión que te resultaría más aceptable.", "Choose the concession that would feel most acceptable."),
    options: [
      { id: "return", label: t("Retorno esperado, para reducir tensión", "Expected return, to reduce tension"), scores: { expectationRealism: 82, emotionalTolerance: 54 } },
      { id: "liquidity", label: t("Liquidez, si la oportunidad parece clara", "Liquidity, if the opportunity seems clear"), scores: { liquidityStrength: 36, overconfidence: 62 }, flags: ["near_cash_need"] },
      { id: "diversification", label: t("Diversificación, si tengo mucha convicción", "Diversification, if I have high conviction"), scores: { consistency: 34, overconfidence: 80 }, flags: ["concentration_bias", "overconfidence"] },
      { id: "patience", label: t("Paciencia, si algo nuevo funciona mejor", "Patience, if something new works better"), scores: { patience: 28, fomoSensitivity: 76 }, flags: ["fomo_entry", "social_pressure"] },
    ],
  },
  {
    id: "product_costs_complete",
    block: "knowledge",
    mode: complete,
    prompt: t("Antes de entrar en un producto, ¿qué coste mirarías primero?", "Before entering a product, which cost would you check first?"),
    helper: t("Responde con tu proceso habitual.", "Answer with your usual process."),
    options: [
      { id: "all_in", label: t("Coste total: comisiones, spread, financiación, fiscalidad y salida", "Total cost: fees, spread, financing, tax and exit"), scores: { knowledgeValidated: 86, consistency: 80 } },
      { id: "visible_fee", label: t("La comisión visible de compra o gestión", "The visible purchase or management fee"), scores: { knowledgeValidated: 58, consistency: 58 } },
      { id: "return_net", label: t("Solo miro si el retorno esperado lo compensa", "I only check whether expected return compensates it"), scores: { knowledgeValidated: 34, overconfidence: 62 }, flags: ["knowledge_gap_basic"] },
      { id: "rarely", label: t("No suelo mirarlo salvo que parezca caro", "I rarely check it unless it looks expensive"), scores: { knowledgeValidated: 24, consistency: 28 }, flags: ["knowledge_gap_basic", "no_written_process"] },
    ],
  },
  {
    id: "liquidity_product_complete",
    block: "knowledge",
    mode: complete,
    prompt: t("Un producto puede tener buen historial y aun así no ser adecuado si...", "A product may have a good track record and still not be suitable if..."),
    helper: t("Piensa en uso real, no solo en rentabilidad pasada.", "Think about real use, not only past returns."),
    options: [
      { id: "liquidity_mismatch", label: t("Su liquidez, plazo o riesgo no encaja con tu necesidad", "Its liquidity, horizon or risk does not fit your need"), scores: { knowledgeValidated: 90, liquidityStrength: 76 } },
      { id: "short_bad", label: t("Tiene un mes malo reciente", "It has had a recent bad month"), scores: { knowledgeValidated: 46, fomoSensitivity: 50 } },
      { id: "low_return", label: t("No fue el que más subió", "It was not the top performer"), scores: { knowledgeValidated: 28, fomoSensitivity: 72 }, flags: ["fomo_entry"] },
      { id: "popular", label: t("Mucha gente ya lo conoce", "Many people already know it"), scores: { knowledgeValidated: 32 }, flags: ["knowledge_gap_basic"] },
    ],
  },
  {
    id: "knowledge_source_complete",
    block: "knowledge",
    mode: complete,
    prompt: t("Cuando no entiendes bien un producto, ¿qué haces antes de invertir?", "When you do not fully understand a product, what do you do before investing?"),
    helper: t("Responde con tu conducta habitual.", "Answer with your usual behavior."),
    options: [
      { id: "stop", label: t("No invierto hasta entender riesgos, costes y escenarios malos", "I do not invest until I understand risks, costs and bad scenarios"), scores: { knowledgeValidated: 86, calibration: 86, consistency: 82 } },
      { id: "small", label: t("Uso un importe pequeño para aprender", "I use a small amount to learn"), scores: { knowledgeValidated: 58, calibration: 62, productComplexity: 54 } },
      { id: "trusted", label: t("Confío en una fuente o persona que lo explica bien", "I trust a source or person that explains it well"), scores: { knowledgeValidated: 38, calibration: 42 }, flags: ["claims_knowledge"] },
      { id: "performance", label: t("Si el historial es bueno, invierto y aprendo después", "If the history is good, I invest and learn later"), scores: { knowledgeValidated: 22, calibration: 24, fomoSensitivity: 76 }, flags: ["knowledge_gap_basic", "fomo_entry"] },
    ],
  },
  {
    id: "forecast_confidence_complete",
    block: "knowledge",
    mode: complete,
    prompt: t("Cuando una tesis te parece muy clara, ¿qué probabilidad de estar equivocado sueles contemplar?", "When a thesis feels very clear, what probability of being wrong do you usually consider?"),
    helper: t("Elige la opción más cercana a tu forma real de pensar.", "Choose the option closest to your real way of thinking."),
    options: [
      { id: "high", label: t("Alta; incluso buenas tesis fallan", "High; even good theses fail"), scores: { calibration: 88, overconfidence: 18, consistency: 78 } },
      { id: "medium", label: t("Media; depende de cuánto haya contrastado", "Medium; it depends on how much I have checked"), scores: { calibration: 74, overconfidence: 34 } },
      { id: "low", label: t("Baja si los datos parecen sólidos", "Low if the data looks solid"), scores: { calibration: 38, overconfidence: 68 }, flags: ["overconfidence"] },
      { id: "very_low", label: t("Muy baja cuando estoy convencido", "Very low when I am convinced"), scores: { calibration: 20, overconfidence: 88 }, flags: ["overconfidence"] },
    ],
  },
  {
    id: "process_after_mistake_complete",
    block: "experience",
    mode: complete,
    prompt: t("Después de una mala decisión de inversión, ¿qué sueles hacer?", "After a bad investment decision, what do you usually do?"),
    helper: t("Piensa en tu patrón habitual después del error.", "Think about your usual pattern after the mistake."),
    options: [
      { id: "write", label: t("Escribo qué falló y qué regla cambiaría", "I write what failed and what rule I would change"), scores: { experienceReal: 82, consistency: 86, calibration: 78 } },
      { id: "talk", label: t("Lo comento o reviso, pero no siempre cambio reglas", "I discuss or review it, but do not always change rules"), scores: { experienceReal: 62, consistency: 58, calibration: 58 } },
      { id: "move_on", label: t("Lo dejo pasar para no quedarme bloqueado", "I move on so I do not get stuck"), scores: { experienceReal: 42, consistency: 38 } },
      { id: "recover", label: t("Intento compensarlo con otra oportunidad", "I try to offset it with another opportunity"), scores: { experienceReal: 34, consistency: 22, fomoSensitivity: 70 }, flags: ["loss_recovery_bias"] },
    ],
  },
  {
    id: "portfolio_role_complete",
    block: "knowledge",
    mode: complete,
    prompt: t("Antes de comprar algo, ¿qué papel debería tener dentro de la cartera?", "Before buying something, what role should it have inside the portfolio?"),
    helper: t("Responde con tu práctica normal, no con teoría perfecta.", "Answer with your normal practice, not perfect theory."),
    options: [
      { id: "defined", label: t("Un rol definido: liquidez, diversificación, crecimiento, cobertura u otro", "A defined role: liquidity, diversification, growth, hedge or another"), scores: { knowledgeValidated: 86, consistency: 84 } },
      { id: "general", label: t("Una expectativa razonable de aportar retorno", "A reasonable expectation of adding return"), scores: { knowledgeValidated: 56, consistency: 52 } },
      { id: "opportunity", label: t("Aprovechar una oportunidad aunque el rol se defina después", "Take an opportunity even if the role is defined later"), scores: { knowledgeValidated: 34, consistency: 30, fomoSensitivity: 64 }, flags: ["no_written_process"] },
      { id: "winner", label: t("Estar en lo que mejor está funcionando", "Be in what is working best"), scores: { knowledgeValidated: 28, consistency: 24, fomoSensitivity: 78 }, flags: ["fomo_entry", "social_pressure"] },
    ],
  },
  {
    id: "review_frequency_complete",
    block: "experience",
    mode: complete,
    prompt: t("¿Con qué frecuencia revisas inversiones que podrían moverse mucho?", "How often do you review investments that could move a lot?"),
    helper: t("Piensa en lo que haces cuando hay volatilidad.", "Think about what you do when there is volatility."),
    options: [
      { id: "scheduled", label: t("En momentos definidos, salvo eventos relevantes", "At defined times, except for relevant events"), scores: { patience: 82, consistency: 84, emotionalTolerance: 72 } },
      { id: "weekly", label: t("Semanalmente o cuando hay noticias importantes", "Weekly or when there is important news"), scores: { patience: 64, consistency: 66 } },
      { id: "daily", label: t("Casi todos los días si el importe es relevante", "Almost every day if the amount is meaningful"), scores: { patience: 38, emotionalTolerance: 44 } },
      { id: "constant", label: t("Varias veces al día cuando se mueve fuerte", "Several times a day when it moves sharply"), scores: { patience: 22, emotionalTolerance: 28, consistency: 28 }, flags: ["pressure_low_tolerance"] },
    ],
  },
  {
    id: "final_consistency_plan_complete",
    block: "expectations",
    mode: complete,
    prompt: t("Si al final del diagnóstico ves tensiones en tu perfil, ¿qué reacción sería más probable?", "If at the end of the diagnostic you see tensions in your profile, what reaction would be most likely?"),
    helper: t("Responde como sueles reaccionar ante información incómoda.", "Answer as you usually react to uncomfortable information."),
    options: [
      { id: "use", label: t("Usarlas para ajustar tamaño, liquidez o reglas", "Use them to adjust size, liquidity or rules"), scores: { calibration: 88, consistency: 86 } },
      { id: "think", label: t("Pensarlo con calma antes de decidir", "Think calmly before deciding"), scores: { calibration: 74, consistency: 72 } },
      { id: "discount", label: t("Tomarlas como referencia, pero confiar más en mi criterio", "Treat them as reference, but trust my judgment more"), scores: { calibration: 42, overconfidence: 66 }, flags: ["overconfidence"] },
      { id: "ignore", label: t("Seguir igual si yo me siento preparado", "Continue the same if I feel prepared"), scores: { calibration: 24, overconfidence: 84, consistency: 34 }, flags: ["overconfidence"] },
    ],
  },
  {
    id: "options_check",
    block: "products",
    mode: both,
    adaptiveFor: ["options"],
    prompt: t("Una call fuera del dinero con vencimiento cercano normalmente tiene...", "An out-of-the-money call with near expiration usually has..."),
    helper: t("Validación mínima de complejidad en opciones.", "Minimal complexity validation for options."),
    options: [
      { id: "decay", label: t("Alto riesgo de perder valor si el movimiento no ocurre pronto", "High risk of losing value if the move does not happen soon"), scores: { knowledgeValidated: 90, calibration: 76 } },
      { id: "protection", label: t("Protección natural contra cualquier caída", "Natural protection against any fall"), scores: { knowledgeValidated: 18 }, flags: ["knowledge_gap_complex", "product_mismatch"] },
      { id: "guaranteed", label: t("Valor garantizado por ser contrato financiero", "Guaranteed value because it is a financial contract"), scores: { knowledgeValidated: 14 }, flags: ["knowledge_gap_complex", "product_mismatch"] },
      { id: "unsure", label: t("No estoy seguro", "I am not sure"), scores: { knowledgeValidated: 30, calibration: 82 }, flags: ["humble_uncertainty"] },
    ],
  },
  {
    id: "options_confidence_complete",
    block: "products",
    mode: complete,
    adaptiveFor: ["options"],
    prompt: t("Sobre tu respuesta anterior en opciones, ¿qué tan seguro estás?", "About your previous options answer, how sure are you?"),
    helper: t("La seguridad de la respuesta también aporta contexto.", "Confidence in the answer also adds context."),
    options: [
      { id: "very", label: t("Muy seguro", "Very sure"), scores: { calibration: 48, overconfidence: 72 }, flags: ["claims_knowledge"] },
      { id: "fairly", label: t("Bastante seguro", "Fairly sure"), scores: { calibration: 62, overconfidence: 48 } },
      { id: "low", label: t("Poco seguro", "Not very sure"), scores: { calibration: 78, overconfidence: 24 } },
      { id: "unsure", label: t("No estoy seguro", "Not sure"), scores: { calibration: 86, overconfidence: 16 }, flags: ["humble_uncertainty"] },
    ],
  },
  {
    id: "leverage_check",
    block: "products",
    mode: both,
    adaptiveFor: ["leverage"],
    prompt: t("Si usas margen y el activo cae fuerte, ¿qué puede ocurrir?", "If you use margin and the asset falls sharply, what can happen?"),
    helper: t("El apalancamiento cambia velocidad y tamaño del error.", "Leverage changes the speed and size of mistakes."),
    options: [
      { id: "margin_call", label: t("Puedes verte obligado a aportar o cerrar posición", "You may be forced to add funds or close the position"), scores: { knowledgeValidated: 92 } },
      { id: "interest_only", label: t("La pérdida se limita al interés del préstamo", "The loss is limited to the loan interest"), scores: { knowledgeValidated: 15 }, flags: ["knowledge_gap_complex", "product_mismatch"] },
      { id: "broker_waits", label: t("El broker debe esperar a que recupere", "The broker must wait for recovery"), scores: { knowledgeValidated: 12 }, flags: ["knowledge_gap_complex", "product_mismatch"] },
      { id: "unsure", label: t("No estoy seguro", "I am not sure"), scores: { knowledgeValidated: 28, calibration: 80 }, flags: ["humble_uncertainty"] },
    ],
  },
  {
    id: "leverage_confidence_complete",
    block: "products",
    mode: complete,
    adaptiveFor: ["leverage"],
    prompt: t("Sobre tu respuesta anterior en apalancamiento, ¿qué tan seguro estás?", "About your previous leverage answer, how sure are you?"),
    helper: t("La seguridad de la respuesta también aporta contexto.", "Confidence in the answer also adds context."),
    options: [
      { id: "very", label: t("Muy seguro", "Very sure"), scores: { calibration: 48, overconfidence: 74 }, flags: ["claims_knowledge"] },
      { id: "fairly", label: t("Bastante seguro", "Fairly sure"), scores: { calibration: 62, overconfidence: 50 } },
      { id: "low", label: t("Poco seguro", "Not very sure"), scores: { calibration: 78, overconfidence: 24 } },
      { id: "unsure", label: t("No estoy seguro", "Not sure"), scores: { calibration: 86, overconfidence: 16 }, flags: ["humble_uncertainty"] },
    ],
  },
  {
    id: "short_check",
    block: "products",
    mode: both,
    adaptiveFor: ["shortSelling"],
    prompt: t("En una venta en corto, ¿qué riesgo especial existe?", "In short selling, what special risk exists?"),
    helper: t("Producto difícil incluso con experiencia.", "A difficult product even with experience."),
    options: [
      { id: "unbounded", label: t("La pérdida puede crecer si el activo sube con fuerza", "The loss can grow if the asset rises sharply"), scores: { knowledgeValidated: 90 } },
      { id: "zero", label: t("La pérdida máxima siempre es cero si no hay margen", "Maximum loss is always zero if there is no margin"), scores: { knowledgeValidated: 18 }, flags: ["knowledge_gap_complex", "product_mismatch"] },
      { id: "bad_company", label: t("No hay riesgo si la empresa es mala", "There is no risk if the company is bad"), scores: { knowledgeValidated: 14 }, flags: ["knowledge_gap_complex", "product_mismatch"] },
      { id: "fee", label: t("Solo pierdes la comisión", "You only lose the fee"), scores: { knowledgeValidated: 12 }, flags: ["knowledge_gap_complex", "product_mismatch"] },
    ],
  },
  {
    id: "short_confidence_complete",
    block: "products",
    mode: complete,
    adaptiveFor: ["shortSelling"],
    prompt: t("Sobre tu respuesta anterior en venta en corto, ¿qué tan seguro estás?", "About your previous short-selling answer, how sure are you?"),
    helper: t("La seguridad de la respuesta también aporta contexto.", "Confidence in the answer also adds context."),
    options: [
      { id: "very", label: t("Muy seguro", "Very sure"), scores: { calibration: 48, overconfidence: 74 }, flags: ["claims_knowledge"] },
      { id: "fairly", label: t("Bastante seguro", "Fairly sure"), scores: { calibration: 62, overconfidence: 50 } },
      { id: "low", label: t("Poco seguro", "Not very sure"), scores: { calibration: 78, overconfidence: 24 } },
      { id: "unsure", label: t("No estoy seguro", "Not sure"), scores: { calibration: 86, overconfidence: 16 }, flags: ["humble_uncertainty"] },
    ],
  },
  {
    id: "crypto_check",
    block: "products",
    mode: both,
    adaptiveFor: ["crypto"],
    prompt: t("Sobre criptoactivos, ¿qué afirmación es más prudente?", "About cryptoassets, which statement is more prudent?"),
    helper: t("Mide volatilidad, custodia, liquidez y narrativa.", "This measures volatility, custody, liquidity and narrative."),
    options: [
      { id: "risks", label: t("Pueden tener riesgos técnicos, regulatorios, de custodia y liquidez", "They can have technical, regulatory, custody and liquidity risks"), scores: { knowledgeValidated: 86 } },
      { id: "cash", label: t("Son equivalentes a efectivo digital estable", "They are equivalent to stable digital cash"), scores: { knowledgeValidated: 15 }, flags: ["knowledge_gap_complex", "product_mismatch"] },
      { id: "adoption", label: t("Si hay adopción, el riesgo principal desaparece", "If there is adoption, the main risk disappears"), scores: { knowledgeValidated: 28, overconfidence: 68 }, flags: ["knowledge_gap_complex"] },
      { id: "custody_irrelevant", label: t("No requieren análisis de custodia ni concentración", "They do not require custody or concentration analysis"), scores: { knowledgeValidated: 18 }, flags: ["knowledge_gap_complex"] },
    ],
  },
  {
    id: "crypto_confidence_complete",
    block: "products",
    mode: complete,
    adaptiveFor: ["crypto"],
    prompt: t("Sobre tu respuesta anterior en criptoactivos, ¿qué tan seguro estás?", "About your previous cryptoassets answer, how sure are you?"),
    helper: t("La seguridad de la respuesta también aporta contexto.", "Confidence in the answer also adds context."),
    options: [
      { id: "very", label: t("Muy seguro", "Very sure"), scores: { calibration: 50, overconfidence: 70 }, flags: ["claims_knowledge"] },
      { id: "fairly", label: t("Bastante seguro", "Fairly sure"), scores: { calibration: 64, overconfidence: 48 } },
      { id: "low", label: t("Poco seguro", "Not very sure"), scores: { calibration: 78, overconfidence: 24 } },
      { id: "unsure", label: t("No estoy seguro", "Not sure"), scores: { calibration: 86, overconfidence: 16 }, flags: ["humble_uncertainty"] },
    ],
  },
  {
    id: "stocks_check",
    block: "products",
    mode: both,
    adaptiveFor: ["individualStocks", "sectorEtfs"],
    prompt: t("Tener {amount60} de tus {amount} en una sola posición o temática (60% del capital) implica principalmente...", "Having {amount60} of your {amount} in a single position or theme (60% of capital) mainly implies..."),
    helper: t("Incluso una buena idea puede ser un mal tamaño.", "Even a good idea can be a bad size."),
    options: [
      { id: "single_outcome", label: t("Dependencia alta de un único resultado", "High dependence on a single outcome"), scores: { knowledgeValidated: 86, consistency: 74 } },
      { id: "safer", label: t("Más seguridad si conoces bien la posición o temática", "More safety if you know the position or theme well"), scores: { knowledgeValidated: 25, overconfidence: 76 }, flags: ["concentration_bias"] },
      { id: "less_vol", label: t("Menos volatilidad porque hay más convicción", "Less volatility because there is more conviction"), scores: { knowledgeValidated: 20 }, flags: ["knowledge_gap_complex"] },
      { id: "irrelevant", label: t("Riesgo irrelevante si el horizonte es largo", "Irrelevant risk if the horizon is long"), scores: { knowledgeValidated: 30 }, flags: ["knowledge_gap_complex"] },
    ],
  },
  {
    id: "stocks_confidence_complete",
    block: "products",
    mode: complete,
    adaptiveFor: ["individualStocks", "sectorEtfs"],
    prompt: t("Sobre tu respuesta anterior en concentración de acciones o temas, ¿qué tan seguro estás?", "About your previous stock or theme concentration answer, how sure are you?"),
    helper: t("La seguridad de la respuesta también aporta contexto.", "Confidence in the answer also adds context."),
    options: [
      { id: "very", label: t("Muy seguro", "Very sure"), scores: { calibration: 52, overconfidence: 66 }, flags: ["claims_knowledge"] },
      { id: "fairly", label: t("Bastante seguro", "Fairly sure"), scores: { calibration: 66, overconfidence: 44 } },
      { id: "low", label: t("Poco seguro", "Not very sure"), scores: { calibration: 78, overconfidence: 24 } },
      { id: "unsure", label: t("No estoy seguro", "Not sure"), scores: { calibration: 86, overconfidence: 16 }, flags: ["humble_uncertainty"] },
    ],
  },
  {
    id: "bond_check",
    block: "products",
    mode: both,
    adaptiveFor: ["bonds"],
    prompt: t("Cuando compras un bono corporativo, ¿qué relación económica tienes?", "When you buy a corporate bond, what economic relationship do you have?"),
    helper: t("Distinguir propiedad de deuda evita sorpresas.", "Distinguishing ownership from debt avoids surprises."),
    options: [
      { id: "creditor", label: t("Eres acreedor bajo ciertas condiciones", "You are a creditor under certain conditions"), scores: { knowledgeValidated: 88 } },
      { id: "owner", label: t("Eres socio con derecho a voto", "You are an owner with voting rights"), scores: { knowledgeValidated: 22 }, flags: ["knowledge_gap_basic"] },
      { id: "guaranteed", label: t("Tienes garantía de no perder si esperas", "You are guaranteed not to lose if you wait"), scores: { knowledgeValidated: 30 }, flags: ["knowledge_gap_basic"] },
      { id: "same_stock", label: t("Es igual que una acción, pero estable", "It is like a stock, but stable"), scores: { knowledgeValidated: 28 }, flags: ["knowledge_gap_basic"] },
    ],
  },
];

function selectedProductSet(answers: DiagnosticAnswers) {
  const selected = new Set<DiagnosticProduct>();
  const raw = answers.products_known;
  const ids = Array.isArray(raw) ? raw : raw ? [raw] : [];
  const productQuestion = diagnosticQuestions.find((question) => question.id === "products_known");
  for (const id of ids) {
    const option = productQuestion?.options.find((candidate) => candidate.id === id);
    for (const product of option?.products ?? []) selected.add(product);
  }
  return selected;
}

export function getQuestionsForMode(mode: DiagnosticMode, answers: DiagnosticAnswers = {}) {
  const selectedProducts = selectedProductSet(answers);
  const base = diagnosticQuestions.filter((question) => question.mode.includes(mode) && !question.adaptiveFor);
  const adaptive = diagnosticQuestions
    .filter((question) => question.mode.includes(mode) && question.adaptiveFor?.some((product) => selectedProducts.has(product)))
    .slice(0, mode === "quick" ? 12 : 15);
  return [...base, ...adaptive];
}

export function getSelectedProducts(answers: DiagnosticAnswers) {
  return Array.from(selectedProductSet(answers));
}
