import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createAdoptRequestEvidence,auditAdoptRequestEvidence} from '../scripts/adopt-request-evidence.mjs';
import {account} from '../scripts/network-accounting.mjs';
import {canonical,sha} from '../scripts/release-core.mjs';
import {classifyRequestSignals,clickObserverSource} from '../scripts/adopt-causal-bridge.mjs';
// Immutable independently captured Chromium fixture, not generated by this test's implementation.
const captured=JSON.parse(fs.readFileSync(new URL('./fixtures/adopt-independent-positive.json',import.meta.url)));
function positive(){const f=structuredClone(captured);f.origin=f.evidence.requests[0].metadata.origin;f.raw=f.result.ledger.map(x=>({...x.event,url:x.event.origin+'/niveles-estadisticos'}));return f;}
function reindex(e){e.journal.forEach((x,i)=>x.sequence=i+1);for(const r of e.requests)r.event_sequences=e.journal.filter(x=>x.request_id===r.request_id).map(x=>x.sequence);}
const audit=f=>auditAdoptRequestEvidence(f.evidence,f.raw,f.result,f.origin,['T1']);
test('independent complete positive action: browser IDs, receipt, lifecycle and accounting agree',()=>{const f=positive();assert.deepEqual(audit(f),{status:'PASS',issues:[]});assert.equal(f.result.required_application_request_failures,0);assert.equal(f.evidence.actions.length,1);assert.equal(f.evidence.transition_receipts.records.length,1);assert.equal(f.result.ledger.length,1);});
// F24.6-1: mutate an independent captured fixture, preserving the original
// action/receipt/ledger and correcting only structural sequence indexing.
function unsupportedObservation(f,kind='TIMEOUT',scoped=true) {
 const e=f.evidence,r=e.requests[1],before=e.journal.findIndex(x=>x.kind==='FAILED');
 const observation={kind,native_event_type:'Network.loadingFailed',canceled:false,error_code:'net::ERR_TIMED_OUT',
  ...(scoped?{page_id:r.request_evidence.page_id,page_lifecycle:'ACTIVE',request_id:r.request_id,transition_id:r.transition_id}:{})};
 e.journal.splice(before,0,observation);reindex(e);return observation;
}
test('F24.6-1: unsupported timeout cannot bypass receipt and failure accounting',()=>{
 const f=positive();assert.deepEqual(audit(f),{status:'PASS',issues:[]});
 const observation=unsupportedObservation(f),before=structuredClone(f),validation=audit(f);
 assert.equal(validation.status,'FAIL');assert.ok(validation.issues.includes('UNSUPPORTED_JOURNAL_EVENT'));
 assert.deepEqual(f,before,'auditing must retain every observation without normalization');
 assert.ok(f.evidence.journal.includes(observation));assert.equal(f.result.required_application_request_failures,0,'rejection must not depend on a changed aggregate');
});
for(const kind of ['UNKNOWN','timeout','TIMEOUT ','constructor','__proto__','toString','',null,42,{},['FAILED']])
 test('journal vocabulary rejects malformed or unsupported kind '+JSON.stringify(kind),()=>{
  const f=positive();unsupportedObservation(f,kind);const validation=audit(f);
  assert.equal(validation.status,'FAIL');assert.ok(validation.issues.includes('UNSUPPORTED_JOURNAL_EVENT'));
 });
test('journal vocabulary rejects missing kind',()=>{const f=positive();delete unsupportedObservation(f).kind;const validation=audit(f);assert.equal(validation.status,'FAIL');assert.ok(validation.issues.includes('UNSUPPORTED_JOURNAL_EVENT'));});
test('unsupported failure cannot escape by removing request association',()=>{const f=positive();unsupportedObservation(f,'TIMEOUT',false);const validation=audit(f);assert.equal(validation.status,'FAIL');assert.ok(validation.issues.includes('UNSUPPORTED_JOURNAL_EVENT'));});
test('unsupported observation after freeze remains rejected and retained',()=>{const f=positive();const e=unsupportedObservation(f);f.evidence.journal.splice(f.evidence.journal.indexOf(e),1);f.evidence.journal.push(e);reindex(f.evidence);const validation=audit(f);assert.equal(validation.status,'FAIL');assert.ok(validation.issues.includes('UNSUPPORTED_JOURNAL_EVENT'));assert.ok(validation.issues.includes('EVENT_AFTER_FREEZE'));assert.equal(f.evidence.journal.at(-1),e);});
const attacks={
 'receipt order disagrees with observed completion':f=>{const j=f.evidence.journal,a=j.findIndex(x=>x.kind==='FAILED'),b=j.findIndex(x=>x.kind==='TRANSITION_COMPLETE');[j[a],j[b]]=[j[b],j[a]];reindex(f.evidence);},
 'two contradictory final response statuses':f=>{const j=f.evidence.journal,i=j.findIndex(x=>x.kind==='RESPONSE'&&x.request_id===f.evidence.requests[1].request_id);j.splice(i,0,{...j[i],status:201});reindex(f.evidence);},
 'journal exception omitted from ledger and denied by receipt':f=>{const j=f.evidence.journal,i=j.findIndex(x=>x.kind==='FAILED');j.splice(i,0,{kind:'APPLICATION_EXCEPTION',page_id:'page-1',page_lifecycle:'ACTIVE'});reindex(f.evidence);},
 'terminal receipt with pending lifecycle':f=>{f.evidence.requests[1].terminal_state='PENDING';f.evidence.journal=f.evidence.journal.filter(x=>x.kind!=='FAILED');reindex(f.evidence);},
 'completed lifecycle with abort receipt':f=>{f.evidence.requests[1].terminal_state='FINISHED';f.evidence.journal.find(x=>x.kind==='FAILED').kind='FINISHED';},
 'timeout lifecycle with abort receipt':f=>f.evidence.journal.find(x=>x.kind==='FAILED').error_code='net::ERR_TIMED_OUT',
 'terminal lifecycle with missing receipt':f=>f.evidence.transition_receipts.records=[],
 'nonterminal receipt':f=>f.evidence.transition_receipts.records[0].abort_sequence=0,
 'wrong receipt ownership':f=>f.evidence.transition_receipts.records[0].request_instance_id=f.evidence.requests[0].request_id,
 'stale receipt transition':f=>f.evidence.transition_receipts.records[0].transition_id='transition-2',
 'duplicate terminal receipt':f=>f.evidence.transition_receipts.records.push(structuredClone(f.evidence.transition_receipts.records[0])),
 'same receipt reused across transitions':f=>{const p=structuredClone(f.evidence.transition_receipts.records[0]);p.transition_id='transition-2';f.evidence.transition_receipts.records.push(p);},
 'retry claims wrong original parent':f=>{const r=f.evidence.requests[1];r.causal_parent=f.evidence.requests[0].request_id;r.causal_relation='CDP_INITIATOR_REQUEST';},
};
for(const [name,corrupt]of Object.entries(attacks))test('reconciliation rejects '+name,()=>{const f=positive();assert.equal(audit(f).status,'PASS');corrupt(f);assert.equal(audit(f).status,'FAIL');});
test('matching receipt and journal allow completion before abort without weakening original policy',()=>{const f=positive(),j=f.evidence.journal,a=j.findIndex(x=>x.kind==='FAILED'),b=j.findIndex(x=>x.kind==='TRANSITION_COMPLETE');[j[a],j[b]]=[j[b],j[a]];reindex(f.evidence);const p=f.evidence.transition_receipts.records[0];[p.abort_sequence,p.completion_sequence]=[p.completion_sequence,p.abort_sequence];f.result=account(f.raw,false,f.origin,f.evidence.transition_receipts);f.evidence.transition_accounting[0].receipt_ids=[sha(canonical(p))];f.evidence.receipt_decisions[0].receipt_id=sha(canonical(p));f.evidence.ledger_sha256=sha(canonical(f.result.ledger));assert.equal(audit(f).status,'PASS');});
function trace(){const origin='https://independent.invalid',page='page-1',c=createAdoptRequestEvidence(origin),raw=[];c.listenerStart(page);c.pageLifecycle(page,'ACTIVE');
 const request=(id,parent,redirect=false)=>c.request(page,{...(redirect?{redirectResponse:{status:307}}:{}),requestId:id,type:'Fetch',frameId:'frame',loaderId:'document',documentURL:origin+'/',request:{url:origin+'/'+id,method:'GET',headers:{'Next-Router-Prefetch':'0'}},initiator:{type:'script',...(parent?{requestId:parent}:{}),stack:{callFrames:[{scriptId:'independent-script',url:origin+'/app.js'}]}}});
 const exception=(id=17,type='Runtime.exceptionThrown',native)=>{const n=native??(type==='Runtime.exceptionThrown'?{exceptionDetails:{exceptionId:id}}:{}),event={kind:type==='Runtime.exceptionThrown'?'exception':'console_error',url:origin+'/',source:type};const binding=c.exception(page,n,event);if(binding)raw.push({...event,failure_evidence:binding});return n;};
 const close=()=>{c.pageLifecycle(page,'CLOSING');c.listenerDrain(page);};
 const freeze=()=>{c.sourceClosed(page);c.pageLifecycle(page,'CLOSED');c.freeze();};
 const view=()=>{const receipts=c.receipts(raw),result=account(raw,false,origin,receipts),evidence=c.evidence(raw,result,receipts);return {evidence,result,validation:auditAdoptRequestEvidence(evidence,raw,result,origin,[])};};
 return {origin,page,c,raw,request,exception,close,freeze,view};}
for(const where of ['before drain','during drain','after source close','after freeze'])test('captured exception retained '+where,()=>{const f=trace();if(where!=='before drain')f.close();if(where==='after source close'){f.c.sourceClosed(f.page);f.exception();f.c.pageLifecycle(f.page,'CLOSED');f.c.freeze();}else if(where==='after freeze'){f.freeze();f.exception();}else{f.exception();if(where==='before drain')f.close();f.freeze();}const v=f.view();assert.equal(v.result.hydration_errors,1);assert.equal(v.result.ledger.length,1);assert.equal(v.evidence.journal.filter(x=>x.kind==='APPLICATION_EXCEPTION').length,1);assert.equal(v.validation.status,['after source close','after freeze'].includes(where)?'FAIL':'PASS');});
for(const source of ['Runtime.exceptionThrown','Runtime.consoleAPICalled','Log.entryAdded'])test('native exception conversion and duplicate identity '+source,()=>{const f=trace(),n=f.exception(17,source);f.exception(17,source,n);f.close();f.freeze();const v=f.view();assert.equal(v.result.ledger.length,1);assert.equal(v.result.ledger[0].event.source,source);assert.equal(v.evidence.journal.filter(x=>x.kind==='EXCEPTION_DUPLICATE').length,1);assert.equal(v.validation.status,'PASS');assert.equal(v.result.application_console_errors+v.result.hydration_errors,1);});
test('serialized duplicate exception with explicit protocol identity is counted once',()=>{const f=trace();f.exception(21);f.exception(21);f.close();f.freeze();assert.equal(f.view().result.hydration_errors,1);});
test('distinct exceptions are not merged by timing or sanitized URL',()=>{const f=trace();f.exception(21);f.exception(22);f.close();f.freeze();assert.equal(f.view().result.hydration_errors,2);});
test('same native exception identity with contradictory sanitized meaning fails closed and retains conflict',()=>{const f=trace();f.exception(21);f.c.exception(f.page,{exceptionDetails:{exceptionId:21}},{kind:'exception',source:'Runtime.exceptionThrown',url:f.origin+'/different'});f.close();f.freeze();const v=f.view();assert.equal(v.validation.status,'FAIL');assert.equal(v.evidence.journal.find(x=>x.kind==='EXCEPTION_DUPLICATE').safe_event.path,sha('/different'));});
for(const name of ['omitted','invented','duplicated','wrong request','wrong transition','wrong native type'])test('exception accounting rejects '+name,()=>{const f=trace();f.request('parent');f.c.finished(f.page,{requestId:'parent'});f.exception();f.close();f.freeze();let v=f.view();assert.equal(v.validation.status,'PASS');
 if(name==='omitted')f.raw.length=0;
 if(name==='invented')v.evidence.journal=v.evidence.journal.filter(x=>x.kind!=='APPLICATION_EXCEPTION');
 if(name==='duplicated')f.raw.push(structuredClone(f.raw[0]));
 if(name==='wrong request')f.raw[0].failure_evidence.related_request_id=v.evidence.requests[0].request_id;
 if(name==='wrong transition')f.raw[0].failure_evidence.observed_transition_id='transition-99';
 if(name==='wrong native type')f.raw[0].failure_evidence.native_event_type='Runtime.consoleAPICalled';
 // Recompute aggregate/hash to exercise observation reconciliation, not a stale ledger hash.
 const result=account(f.raw,false,f.origin,v.evidence.transition_receipts);v.evidence.ledger_sha256=sha(canonical(result.ledger));reindex(v.evidence);
 assert.equal(auditAdoptRequestEvidence(v.evidence,f.raw,result,f.origin,[]).status,'FAIL');});
test('exception with exact native request reference passes; alternate same-page parent fails',()=>{const f=trace();f.request('parent');f.c.finished(f.page,{requestId:'parent'});f.request('other');f.c.finished(f.page,{requestId:'other'});f.exception(1,'Log.entryAdded',{entry:{networkRequestId:'parent'}});f.close();f.freeze();const v=f.view();assert.equal(v.validation.status,'PASS');assert.equal(v.result.ledger[0].event.failure_evidence.related_request_id,v.evidence.requests[0].request_id);v.evidence.journal.find(x=>x.kind==='APPLICATION_EXCEPTION').failure_evidence.related_request_id=v.evidence.requests[1].request_id;assert.equal(auditAdoptRequestEvidence(v.evidence,f.raw,v.result,f.origin,[]).status,'FAIL');});
for(const continuation of ['retry','successful sibling','partial response','duplicate terminal'])test('retained native failure followed by '+continuation,()=>{const f=trace(),binding=f.request('failed');f.c.response(f.page,{requestId:'failed',timestamp:1,response:{status:200}});const native={requestId:'failed',timestamp:2,canceled:false,errorText:'net::ERR_TIMED_OUT'};
 const failure=()=>{if(f.c.failure(f.page,native,f.raw.length)!==false)f.raw.push({request_evidence:binding,kind:'request_failure',url:f.origin+'/failed',type:'Fetch',rsc:false,prefetch:false,canceled:false,error_code:'net::ERR_TIMED_OUT'});};failure();
 if(continuation==='duplicate terminal')failure();else{const id=continuation==='retry'?'retry':'sibling';f.request(id,continuation==='retry'?'failed':undefined);if(continuation==='partial response')f.c.response(f.page,{requestId:id,response:{status:200}});else f.c.finished(f.page,{requestId:id});}
 f.close();f.freeze();const v=f.view();assert.equal(v.result.required_application_request_failures,1);assert.equal(v.result.ledger.length,1);assert.equal(v.evidence.requests[0].terminal_state,'FAILED');if(continuation==='retry')assert.equal(v.evidence.requests[1].causal_parent,v.evidence.requests[0].request_id);if(continuation==='duplicate terminal')assert.equal(v.evidence.journal.filter(x=>x.kind==='NATIVE_DUPLICATE').length,1);if(continuation==='partial response'){assert.equal(v.evidence.requests[1].terminal_state,'PENDING');assert.equal(v.validation.status,'FAIL');}else assert.equal(v.validation.status,'PASS');});
for(const source of ['Runtime.consoleAPICalled','Runtime.exceptionThrown','Log.entryAdded'])test('later successful request cannot erase '+source,()=>{const f=trace();f.exception(1,source);f.request('later');f.c.response(f.page,{requestId:'later',response:{status:200}});f.c.finished(f.page,{requestId:'later'});f.close();f.freeze();const v=f.view();assert.equal(v.validation.status,'PASS');assert.equal(v.result.application_console_errors+v.result.hydration_errors,1);});
test('combined negative: corrupt lifecycle, recorded exception, apparent success and ambiguous classification',()=>{const f=positive();attacks['receipt order disagrees with observed completion'](f);attacks['journal exception omitted from ledger and denied by receipt'](f);f.evidence.requests[1].terminal_state='FINISHED';f.evidence.requests[1].prefetch_classification='UNKNOWN';assert.equal(audit(f).status,'FAIL');});
for(const [headers,expected]of [[{RSC:'1','Next-Router-Prefetch':'1'},{rsc:'YES',prefetch:'YES'}],[{'Next-Router-Prefetch':'0'},{rsc:'NO',prefetch:'NO'}],[{RSC:'1'},{rsc:'YES',prefetch:'UNKNOWN'}],[{},{rsc:'NO',prefetch:'UNKNOWN'}]])test('native classification remains '+JSON.stringify(expected),()=>assert.deepEqual(classifyRequestSignals(headers),expected));
test('click conversion source preserves string hint and Symbol rejection',()=>{const source=clickObserverSource('fixture');assert.ok(source.includes('const name=`${type}`'));assert.ok(!source.includes("const name=''+type"));});

const browserEnabled=process.env.SL_CAUSAL_BROWSER_TEST==='1';
test('real Chromium native listener conversion, Symbol rejection, and captured listener exception',{skip:!browserEnabled},async()=>{
 const {chromium}=await import('../qa-dependencies/node_modules/playwright/index.mjs');const {once}=await import('node:events');const browser=await chromium.launch({headless:true});
 try {
  const outcomes=[];
  for(const wrapped of [false,true]){const ctx=await browser.newContext();if(wrapped)await ctx.addInitScript({content:clickObserverSource('independentBridge')});const p=await ctx.newPage();await p.goto('data:text/html,<button>test</button>');
   outcomes.push(await p.evaluate(()=>{const b=document.querySelector('button'),hints=[];let count=0;const type={[Symbol.toPrimitive](hint){hints.push(hint);return hint==='string'?'click':'wrong';}},fn=()=>count++;b.addEventListener(type,fn);b.click();b.removeEventListener(type,fn);b.click();let symbol;try{b.addEventListener(Symbol('type'),fn);symbol='accepted';}catch(e){symbol=e.name;}return {count,hints,symbol};}));
   if(wrapped){const cdp=await ctx.newCDPSession(p),f=trace();await cdp.send('Runtime.enable');cdp.on('Runtime.exceptionThrown',e=>f.exception(undefined,'Runtime.exceptionThrown',e));const observed=once(cdp,'Runtime.exceptionThrown');await p.evaluate(()=>{document.querySelector('button').addEventListener('click',()=>{throw new Error('independent native listener failure');});document.querySelector('button').click();});await observed;f.close();f.freeze();const v=f.view();assert.equal(v.result.hydration_errors,1);assert.equal(v.result.ledger[0].event.failure_evidence.identity_basis,'PROTOCOL_ID');assert.equal(v.validation.status,'PASS');}
   await ctx.close();
  }
  assert.deepEqual(outcomes[0],{count:1,hints:['string','string'],symbol:'TypeError'});assert.deepEqual(outcomes[1],outcomes[0]);
 }finally{await browser.close();}
});

import {EventEmitter} from 'node:events';
import os from 'node:os';
import path from 'node:path';
for(const timing of ['before drain','during drain','queued at close','duplicate exception','later success','duplicate failure'])test('shared harness durable retention '+timing,async()=>{
 const origin='https://harness.invalid',cdp=new EventEmitter();cdp.send=async()=>({result:{value:true}});
 const failure=()=>cdp.emit('Network.loadingFailed',{requestId:'failed',type:'Fetch',timestamp:2,canceled:false,errorText:'net::ERR_TIMED_OUT'});
 const exception=()=>cdp.emit('Runtime.exceptionThrown',{exceptionDetails:{exceptionId:39,url:origin+'/native-listener'}});
 const start=id=>cdp.emit('Network.requestWillBeSent',{requestId:id,type:'Fetch',frameId:'frame',loaderId:'doc',documentURL:origin+'/',request:{url:origin+'/'+id,method:'GET',headers:{'Next-Router-Prefetch':'0'}},initiator:{type:'script',stack:{callFrames:[{scriptId:'native',url:origin+'/app.js'}]}}});
 const context={newPage:async()=>({url:()=>origin}),newCDPSession:async()=>cdp,close:async()=>{if(timing==='during drain'){failure();exception();}cdp.emit('close');if(timing==='queued at close')setImmediate(()=>{failure();exception();});}};
 globalThis.__SL_RECON_PLAYWRIGHT={launch:async()=>({newContext:async()=>context,close:async()=>{}})};
 const url=new URL('../scripts/browser-harness-base.mjs',import.meta.url);let source=fs.readFileSync(url,'utf8');source=source.replace(/(['"])(\.\/[^'"]+\.mjs)\1/g,(_,q,v)=>JSON.stringify(new URL(v,url).href)).replace("await import('../qa-dependencies/node_modules/playwright/index.mjs')",'{chromium:globalThis.__SL_RECON_PLAYWRIGHT}');
 const {createReadOnlyHarness}=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
 const out=fs.mkdtempSync(path.join(os.tmpdir(),'sl-recon-retention-'));
 try{const h=await createReadOnlyHarness({origin},undefined,out,true),p=await h.createPage();start('failed');
 if(!['during drain','queued at close'].includes(timing)){failure();exception();if(timing==='duplicate exception')exception();if(timing==='duplicate failure')failure();if(timing==='later success'){start('later');cdp.emit('Network.responseReceived',{requestId:'later',response:{status:200,url:origin+'/later'},type:'Fetch'});cdp.emit('Network.loadingFinished',{requestId:'later'});}}
 await p.close();await assert.rejects(h.finish(true),/ADOPT_REQUEST_EVIDENCE_INVALID/);
 const e=JSON.parse(fs.readFileSync(out+'/adopt-request-evidence.json')),n=JSON.parse(fs.readFileSync(out+'/network-accounting.json'));
 assert.equal(n.required_application_request_failures,1);assert.equal(n.hydration_errors,1);assert.equal(n.ledger.length,2);assert.equal(e.journal.filter(x=>x.kind==='APPLICATION_EXCEPTION').length,1);assert.equal(e.journal.filter(x=>x.kind==='FAILED').length,1);assert.equal(e.validation.status,'FAIL');assert.equal(e.journal.filter(x=>x.kind==='ACCOUNTING_FREEZE').length,1);
 }finally{fs.rmSync(out,{recursive:true,force:true});}
});
test('missing terminal receipt cannot pass after all derived accounting is consistently recomputed',()=>{const f=positive();f.evidence.transition_receipts.records=[];f.evidence.receipt_decisions=[];f.evidence.transition_accounting[0].receipt_ids=[];f.result=account(f.raw,false,f.origin,f.evidence.transition_receipts);f.evidence.ledger_sha256=sha(canonical(f.result.ledger));assert.equal(f.result.required_application_request_failures,1);assert.ok(audit(f).issues.includes('MISSING_TERMINAL_RECEIPT'));});
test('caller mutation cannot rewrite the captured exception identity',()=>{const f=trace(),native={exceptionDetails:{exceptionId:91}},raw={kind:'exception',source:'Runtime.exceptionThrown',url:f.origin+'/'};const b=f.c.exception(f.page,native,raw),original=b.native_event_id;b.native_event_id='f'.repeat(64);b.failure_id='failure-'+sha(f.page+':'+b.native_event_id);f.raw.push({...raw,failure_evidence:b});f.close();f.freeze();const v=f.view();assert.equal(v.evidence.journal.find(x=>x.kind==='APPLICATION_EXCEPTION').failure_evidence.native_event_id,original);assert.equal(v.validation.status,'FAIL');});

test('exception cannot bind to a stale redirect hop with the same native protocol ID',()=>{const f=trace();f.request('hop');f.request('hop',undefined,true);f.c.finished(f.page,{requestId:'hop'});f.exception(1,'Log.entryAdded',{entry:{networkRequestId:'hop'}});f.close();f.freeze();const v=f.view();assert.equal(v.validation.status,'PASS');assert.equal(v.result.ledger[0].event.failure_evidence.related_request_id,v.evidence.requests[1].request_id);const stale=v.evidence.requests[0].request_id;f.raw[0].failure_evidence.related_request_id=stale;v.evidence.journal.find(x=>x.kind==='APPLICATION_EXCEPTION').failure_evidence.related_request_id=stale;const result=account(f.raw,false,f.origin,v.evidence.transition_receipts);v.evidence.ledger_sha256=sha(canonical(result.ledger));assert.ok(auditAdoptRequestEvidence(v.evidence,f.raw,result,f.origin,[]).issues.includes('EXCEPTION_OWNERSHIP_MISMATCH'));});
for(const id of [null,'17',{},-1])test('invalid native exception ID cannot collapse separate observations '+JSON.stringify(id),()=>{const f=trace();f.exception(id);f.exception(id);f.close();f.freeze();const v=f.view();assert.equal(v.result.hydration_errors,2);assert.ok(v.evidence.capture_issues.includes('NATIVE_EXCEPTION_ID_INVALID'));assert.equal(v.validation.status,'FAIL');});

// F24.8-1: supported network kinds must never evade ownership by losing an ID.
const unresolvedKinds=['REQUEST','RESPONSE','FAILED','FINISHED','REDIRECTED'];
function nativeUnresolved(kind,requestId) {
 return {...(requestId===undefined?{}:{requestId}),type:'Fetch',timestamp:17,
  ...(kind==='REQUEST'?{request:{url:'https://independent.invalid/missing',method:'GET',headers:{RSC:'1'}}}:{}),
  ...(kind==='RESPONSE'?{response:{status:503}}:{}),
  ...(kind==='FAILED'?{canceled:false,errorText:'net::ERR_TIMED_OUT'}:{}),
  ...(kind==='REDIRECTED'?{redirectResponse:{status:307}}:{})};
}
function acceptUnresolved(f,kind,native){const r=f.c.unresolvedNative(f.page,kind,native,f.raw.length);if(r?.event)f.raw.push(r.event);return r;}
for(const kind of unresolvedKinds)for(const id of [undefined,'',null,false,0,{},' ','unknown-native-id'])test('unresolved native '+kind+' identity '+JSON.stringify(id),()=>{
 const f=trace(),native=nativeUnresolved(kind,id);
 // A new REQUEST with a nonempty native ID is legitimately a new binding.
 if(kind==='REQUEST'&&id==='unknown-native-id'){assert.equal(acceptUnresolved(f,kind,native),null);return;}
 acceptUnresolved(f,kind,native);f.close();f.freeze();const v=f.view();
 assert.equal(v.result.ledger.length,1);assert.equal(v.result.unclassified_failures.length,1);
 const row=v.result.ledger[0],u=row.event.unresolved_evidence;
 assert.equal(row.classification,'unclassified');assert.equal(u.request_id,'UNKNOWN');assert.equal(u.event_type,kind);
 assert.match(u.event_id,/^network-event-[a-f0-9]{64}$/);assert.notEqual(u.event_id,u.request_id);
 assert.equal(u.identity_resolution_status,'UNRESOLVED');assert.equal(u.gate_effect,'BLOCK');
 assert.equal(v.evidence.requests.length,0);assert.equal(v.validation.status,'FAIL');
 assert.equal(v.validation.unresolved_identity_accounting.length,1);assert.equal(v.validation.unresolved_identity_accounting[0].accounting_status,'EXACTLY_ONCE');
 assert.ok(v.validation.issues.includes('UNRESOLVED_REQUEST_IDENTITY'));assert.ok(!v.validation.issues.includes('UNRESOLVED_ACCOUNTING_MISMATCH'));
 if(kind==='FAILED'){assert.equal(u.error_code,'net::ERR_TIMED_OUT');assert.equal(u.canceled,false);assert.equal(u.observed_state,'FAILED');}
 if(kind==='REQUEST'){assert.equal(u.observed_state,'PENDING');assert.equal(u.rsc,true);assert.equal(u.prefetch,'UNKNOWN');}
});
for(const kind of unresolvedKinds)test('independent captured fixture rejects missing ownership for '+kind,()=>{
 const f=positive(),j=f.evidence.journal;const observation={kind,page_id:'page-1',page_lifecycle:'ACTIVE',canceled:false,error_code:'net::ERR_TIMED_OUT',status:503};
 j.splice(j.findIndex(x=>x.kind==='FAILED'),0,observation);reindex(f.evidence);const before=structuredClone(f),v=audit(f);
 assert.equal(v.status,'FAIL');assert.equal(v.unresolved_identity_accounting.length,1);assert.equal(v.unresolved_identity_accounting[0].request_id,'UNKNOWN');assert.equal(v.unresolved_identity_accounting[0].accounting_status,'MISSING');assert.ok(v.issues.includes('UNRESOLVED_ACCOUNTING_MISMATCH'));assert.deepEqual(f,before);
});
test('valid native identity retains normal reconciliation and no unresolved entry',()=>{const f=trace();f.request('normal');const e={requestId:'normal',response:{status:200}};assert.equal(acceptUnresolved(f,'RESPONSE',e),null);f.c.response(f.page,e);f.c.finished(f.page,{requestId:'normal'});f.close();f.freeze();const v=f.view();assert.equal(v.validation.status,'PASS');assert.equal(v.result.ledger.length,0);assert.equal(v.validation.unresolved_identity_accounting,undefined);});
for(const [headers,type,rsc,prefetch]of [[{RSC:'1'},'Fetch',true,'UNKNOWN'],[{RSC:'1','Next-Router-Prefetch':'1'},'Fetch',true,true],[{RSC:'0','Next-Router-Prefetch':'0'},'Fetch',false,false],[undefined,'Fetch','UNKNOWN','UNKNOWN'],[undefined,'Prefetch','UNKNOWN',true]])test('unresolved identity preserves independent classifications '+JSON.stringify([rsc,prefetch]),()=>{const f=trace(),e=nativeUnresolved('REQUEST');e.request.headers=headers;e.type=type;acceptUnresolved(f,'REQUEST',e);f.close();f.freeze();const v=f.view(),u=v.result.ledger[0].event.unresolved_evidence;assert.equal(u.rsc,rsc);assert.equal(u.prefetch,prefetch);assert.equal(v.result.ledger[0].event.rsc,rsc);assert.equal(v.result.ledger[0].event.prefetch,prefetch);assert.equal(u.request_id,'UNKNOWN');assert.equal(v.validation.status,'FAIL');});
for(const when of ['immediate','during drain','after matching request'])test('same unresolved native delivery counted once '+when,()=>{
 const f=trace(),e=nativeUnresolved('FAILED','later');acceptUnresolved(f,'FAILED',e);
 if(when==='during drain')f.close();if(when==='after matching request'){f.request('later');f.c.finished(f.page,{requestId:'later'});}
 acceptUnresolved(f,'FAILED',e);if(when!=='during drain')f.close();f.freeze();const v=f.view();assert.equal(v.result.ledger.length,1);assert.equal(v.evidence.journal.filter(x=>x.kind==='NATIVE_DUPLICATE').length,1);assert.equal(v.validation.unresolved_identity_accounting.length,1);assert.equal(v.validation.unresolved_identity_accounting[0].accounting_status,'EXACTLY_ONCE');assert.ok(!v.validation.issues.includes('NATIVE_DUPLICATE_MISMATCH'));assert.equal(v.validation.status,'FAIL');
});
test('distinct native objects with same missing ID/time are not guessed to be duplicates',()=>{const f=trace(),e=nativeUnresolved('FAILED');acceptUnresolved(f,'FAILED',e);acceptUnresolved(f,'FAILED',structuredClone(e));f.close();f.freeze();const v=f.view();assert.equal(v.result.ledger.length,2);assert.equal(new Set(v.result.ledger.map(x=>x.event.unresolved_evidence.event_id)).size,2);});
test('changed semantics on a redelivered native object remain recorded',()=>{const f=trace(),e=nativeUnresolved('FAILED');acceptUnresolved(f,'FAILED',e);e.errorText='net::ERR_ABORTED';acceptUnresolved(f,'FAILED',e);f.close();f.freeze();const v=f.view();assert.equal(v.result.ledger.length,2);assert.deepEqual(v.result.ledger.map(x=>x.event.error_code),['net::ERR_TIMED_OUT','net::ERR_ABORTED']);assert.ok(v.evidence.capture_issues.includes('CONTRADICTORY_UNRESOLVED_DELIVERY'));});
for(const corrupt of ['omit','duplicate','wrong request','convert to success','invent'])test('unresolved ledger reconciliation rejects '+corrupt,()=>{
 const f=trace();acceptUnresolved(f,'FAILED',nativeUnresolved('FAILED'));const b=f.request('other');f.c.finished(f.page,{requestId:'other'});f.close();f.freeze();let v=f.view();
 if(corrupt==='omit')f.raw=[];if(corrupt==='duplicate')f.raw.push(structuredClone(f.raw[0]));
 if(corrupt==='wrong request')v.evidence.journal.find(x=>x.kind==='FAILED').request_id=b.request_instance_id;
 if(corrupt==='convert to success')v.evidence.journal.find(x=>x.kind==='FAILED').kind='FINISHED';
 if(corrupt==='invent'){v.evidence.journal=v.evidence.journal.filter(x=>x.kind!=='FAILED');reindex(v.evidence);}
 const n=account(f.raw,false,f.origin,v.evidence.transition_receipts);v.evidence.ledger_sha256=sha(canonical(n.ledger));const validation=auditAdoptRequestEvidence(v.evidence,f.raw,n,f.origin,[]);assert.equal(validation.status,'FAIL');
 if(corrupt==='omit')assert.equal(validation.unresolved_identity_accounting[0].accounting_status,'MISSING');if(corrupt==='duplicate')assert.equal(validation.unresolved_identity_accounting[0].accounting_status,'DUPLICATE');
});
for(const continuation of ['success','redirect','pending sibling'])test('later '+continuation+' cannot erase unresolved observation',()=>{const f=trace();acceptUnresolved(f,'FAILED',nativeUnresolved('FAILED'));f.request('later');if(continuation==='redirect')f.request('later',undefined,true);if(continuation!=='pending sibling')f.c.finished(f.page,{requestId:'later'});f.close();f.freeze();const v=f.view();assert.equal(v.result.ledger.length,1);assert.equal(v.result.ledger[0].event.unresolved_evidence.request_id,'UNKNOWN');assert.equal(v.result.unclassified_failures.length,1);assert.equal(v.validation.status,'FAIL');if(continuation==='pending sibling')assert.equal(v.evidence.requests[0].terminal_state,'PENDING');});
for(const timing of ['before drain','during drain','queued at close'])test('native harness durably accounts missing request identity '+timing,async()=>{
 const origin='https://harness.invalid',cdp=new EventEmitter();cdp.send=async()=>({result:{value:true}});
 const failure={type:'Fetch',canceled:false,errorText:'net::ERR_TIMED_OUT'},emit=()=>{cdp.emit('Network.loadingFailed',failure);cdp.emit('Network.loadingFailed',failure);};
 const context={newPage:async()=>({url:()=>origin}),newCDPSession:async()=>cdp,close:async()=>{if(timing==='during drain')emit();cdp.emit('close');if(timing==='queued at close')setImmediate(emit);}};
 globalThis.__SL_UNRESOLVED_PLAYWRIGHT={launch:async()=>({newContext:async()=>context,close:async()=>{}})};
 const url=new URL('../scripts/browser-harness-base.mjs',import.meta.url);let source=fs.readFileSync(url,'utf8');source=source.replace(/(['"])(\.\/[^'"]+\.mjs)\1/g,(_,q,v)=>JSON.stringify(new URL(v,url).href)).replace("await import('../qa-dependencies/node_modules/playwright/index.mjs')",'{chromium:globalThis.__SL_UNRESOLVED_PLAYWRIGHT}');
 const {createReadOnlyHarness}=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));const out=fs.mkdtempSync(path.join(os.tmpdir(),'sl-unresolved-native-'));
 try{const h=await createReadOnlyHarness({origin},undefined,out,true),p=await h.createPage();cdp.emit('Network.dataReceived',{dataLength:100});if(timing==='before drain')emit();await p.close();await assert.rejects(h.finish(true),/ADOPT_REQUEST_EVIDENCE_INVALID/);
 const e=JSON.parse(fs.readFileSync(out+'/adopt-request-evidence.json')),n=JSON.parse(fs.readFileSync(out+'/network-accounting.json'));assert.equal(n.ledger.length,1);assert.equal(n.unclassified_failures.length,1);assert.equal(e.journal.filter(x=>x.kind==='FAILED').length,1);assert.equal(e.journal.filter(x=>x.kind==='NATIVE_DUPLICATE').length,1);assert.equal(n.ledger[0].event.unresolved_evidence.request_id,'UNKNOWN');assert.equal(e.validation.status,'FAIL');assert.equal(e.validation.unresolved_identity_accounting[0].accounting_status,'EXACTLY_ONCE');
 }finally{fs.rmSync(out,{recursive:true,force:true});}
});
test('unresolved Prefetch with contradictory explicit NO remains UNKNOWN',()=>{const f=trace(),e=nativeUnresolved('REQUEST');e.type='Prefetch';e.request.headers={'Next-Router-Prefetch':'0'};acceptUnresolved(f,'REQUEST',e);f.close();f.freeze();const v=f.view();assert.equal(v.result.ledger[0].event.prefetch,'UNKNOWN');assert.equal(v.validation.status,'FAIL');});
test('changed timestamp is not silently deduplicated as the same missing-ID event',()=>{const f=trace(),e=nativeUnresolved('FAILED');acceptUnresolved(f,'FAILED',e);e.timestamp++;acceptUnresolved(f,'FAILED',e);f.close();f.freeze();assert.equal(f.view().result.ledger.length,2);});
test('unresolved identity cannot receive a platform exclusion or a forged known request binding',()=>{const f=trace();acceptUnresolved(f,'FAILED',nativeUnresolved('FAILED'));f.raw[0].url='https://vercel.live/_next-live/feedback/example';f.close();f.freeze();const v=f.view();assert.equal(v.result.ledger[0].classification,'unclassified');assert.equal(v.result.unclassified_failures.length,1);assert.equal(v.validation.status,'FAIL');const other=trace(),binding=other.request('other');f.raw[0].request_evidence=binding;assert.throws(()=>account(f.raw,false,f.origin),/UNRESOLVED_EVENT_INVALID/);});
test('all native entry callbacks retain unresolved semantics before identifier-dependent handling',async()=>{
 const origin='https://native-entry.invalid',cdp=new EventEmitter();cdp.send=async()=>({result:{value:true}});
 const context={newPage:async()=>({url:()=>origin}),newCDPSession:async()=>cdp,close:async()=>cdp.emit('close')};
 globalThis.__SL_UNRESOLVED_ENTRIES={launch:async()=>({newContext:async()=>context,close:async()=>{}})};
 const url=new URL('../scripts/browser-harness-base.mjs',import.meta.url);let source=fs.readFileSync(url,'utf8');source=source.replace(/(['"])(\.\/[^'"]+\.mjs)\1/g,(_,q,v)=>JSON.stringify(new URL(v,url).href)).replace("await import('../qa-dependencies/node_modules/playwright/index.mjs')",'{chromium:globalThis.__SL_UNRESOLVED_ENTRIES}');
 const {createReadOnlyHarness}=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));const out=fs.mkdtempSync(path.join(os.tmpdir(),'sl-unresolved-entries-'));
 try{const h=await createReadOnlyHarness({origin},undefined,out,true),p=await h.createPage();
 cdp.emit('Network.requestWillBeSent',{type:'Fetch',request:{url:origin+'/',method:'GET',headers:{RSC:'1','Next-Router-Prefetch':'1'}}});
 cdp.emit('Network.requestWillBeSent',{type:'Fetch',redirectResponse:{status:307},request:{url:origin+'/redirect',method:'GET',headers:{RSC:'1'}}});
 cdp.emit('Network.responseReceived',{type:'Fetch',response:{status:503}});
 cdp.emit('Network.loadingFinished',{timestamp:21});
 cdp.emit('Network.loadingFailed',{type:'Prefetch',errorText:'net::ERR_TIMED_OUT',canceled:false});
 await p.close();await assert.rejects(h.finish(true),/ADOPT_REQUEST_EVIDENCE_INVALID/);
 const e=JSON.parse(fs.readFileSync(out+'/adopt-request-evidence.json')),n=JSON.parse(fs.readFileSync(out+'/network-accounting.json')),rows=n.ledger.map(x=>x.event.unresolved_evidence);
 assert.equal(n.unclassified_failures.length,5);assert.equal(new Set(rows.map(x=>x.event_id)).size,5);assert.ok(rows.every(x=>x.request_id==='UNKNOWN'));assert.deepEqual(rows.map(x=>x.event_type),['REQUEST','REQUEST','RESPONSE','FINISHED','FAILED']);
 assert.equal(rows[0].rsc,true);assert.equal(rows[0].prefetch,true);assert.equal(rows[0].observed_state,'PENDING');assert.equal(rows[1].redirect_status,307);assert.equal(rows[1].prefetch,'UNKNOWN');assert.equal(rows[2].status,503);assert.equal(rows[3].rsc,'UNKNOWN');assert.equal(rows[4].prefetch,true);assert.equal(rows[4].rsc,'UNKNOWN');assert.equal(rows[4].error_code,'net::ERR_TIMED_OUT');assert.ok(e.validation.unresolved_identity_accounting.every(x=>x.accounting_status==='EXACTLY_ONCE'));
 if(process.env.SL_CAUSAL_TEST_EVIDENCE){fs.mkdirSync(process.env.SL_CAUSAL_TEST_EVIDENCE,{recursive:true});fs.writeFileSync(path.join(process.env.SL_CAUSAL_TEST_EVIDENCE,'unresolved-native-entry.json'),JSON.stringify({evidence:e,accounting:n},null,2));}
 }finally{fs.rmSync(out,{recursive:true,force:true});}
});

// F24.10-1: native source labels are independently supplied, never synthesized
// from the normalizer's output. Relative script labels have no proven base here.
function sourceFailure(f,url,native={exceptionDetails:{exceptionId:73}},source='Runtime.exceptionThrown',extra={}) {
 const raw={kind:source==='Runtime.exceptionThrown'?'exception':'console_error',source,url,...extra};
 const binding=f.c.exception(f.page,native,raw);if(binding)f.raw.push({...raw,failure_evidence:binding});return native;
}
for(const value of ['independent-relative.js','/path','./path','../path','?query=private-fixture-value','#fragment'])test('F24.10-1 retains unresolved relative source '+value,()=>{
 const f=trace();sourceFailure(f,value);f.close();f.freeze();const v=f.view(),row=v.result.ledger[0];
 assert.equal(v.result.ledger.length,1);assert.equal(v.result.unclassified_failures.length,1);assert.equal(v.validation.status,'FAIL');assert.ok(v.validation.issues.includes('SOURCE_URL_UNRESOLVED'));
 assert.equal(row.event.failure_evidence.related_request_id,'UNKNOWN');assert.equal(row.event.origin,'');assert.equal(row.event.path,'');assert.equal(row.event.source_url_evidence.raw_sha256,sha(value));
 assert.equal(row.event.source_url_evidence.normalization_status,'UNRESOLVED');assert.equal(row.event.source_url_evidence.normalization_failure,'MISSING_AUTHORITATIVE_BASE');
 assert.equal(v.evidence.journal.filter(j=>j.kind==='APPLICATION_EXCEPTION').length,1);assert.ok(!JSON.stringify(v).includes('private-fixture-value'));
});
for(const value of ['http://[','https://','http://%zz',42,{}])test('F24.10-1 malformed source is blocking evidence '+JSON.stringify(value),()=>{
 const f=trace();sourceFailure(f,value);f.close();f.freeze();const v=f.view(),u=v.result.ledger[0].event.source_url_evidence;
 assert.equal(v.result.ledger.length,1);assert.equal(v.result.unclassified_failures.length,1);assert.equal(u.normalization_status,'FAILED');assert.equal(u.normalization_failure,'INVALID_URL');assert.equal(v.validation.status,'FAIL');
});
test('F24.10-1 valid absolute source preserves established accounting',()=>{const f=trace();sourceFailure(f,'https://independent.invalid/app.js?private-fixture-value');f.close();f.freeze();const v=f.view();assert.equal(v.validation.status,'PASS');assert.equal(v.result.hydration_errors,1);assert.equal(v.result.ledger[0].event.path,sha('/app.js'));assert.equal(v.result.ledger[0].event.source_url_evidence,undefined);assert.ok(!JSON.stringify(v).includes('private-fixture-value'));});
for(const proposedBase of ['https://independent.invalid/folder/page','https://vercel.live/_next-live/feedback/','http://['])test('unwitnessed base cannot resolve a native script label '+proposedBase,()=>{
 const f=trace();sourceFailure(f,'./app.js',undefined,undefined,{baseURL:proposedBase,source_base_url:proposedBase});f.close();f.freeze();const v=f.view();assert.equal(v.result.ledger[0].event.source_url_evidence.base_identity,'UNKNOWN');assert.equal(v.result.ledger[0].classification,'unclassified');assert.equal(v.result.ledger[0].event.origin,'');assert.equal(v.validation.status,'FAIL');
});
test('failure identity and safe source are recorded before URL constructor executes or throws',()=>{
 const f=trace(),OriginalURL=globalThis.URL;let observed=false;
 try{globalThis.URL=new Proxy(OriginalURL,{construct(){const e=f.c.evidence([],{ledger:[]},{records:[]});const j=e.journal.find(j=>j.kind==='APPLICATION_EXCEPTION');assert.match(j.failure_evidence.failure_id,/^failure-[a-f0-9]{64}$/);assert.equal(j.failure_evidence.related_request_id,'UNKNOWN');assert.equal(j.source_observation.raw_sha256,sha('https://independent.invalid/app.js'));assert.equal(j.safe_event,undefined);observed=true;throw new TypeError('independent parser fault');}});sourceFailure(f,'https://independent.invalid/app.js');}finally{globalThis.URL=OriginalURL;}
 assert.equal(observed,true);const e=f.c.evidence([],{ledger:[]},{records:[]});assert.equal(e.journal.find(j=>j.kind==='APPLICATION_EXCEPTION').safe_event.source_url_evidence.normalization_failure,'INVALID_URL');
});
for(const where of ['before drain','during drain','after source close','after freeze'])test('URL failure retained at '+where,()=>{
 const f=trace();if(where==='before drain')sourceFailure(f,'http://[');f.close();if(where==='during drain')sourceFailure(f,'http://[');
 if(where==='after source close'){f.c.sourceClosed(f.page);sourceFailure(f,'http://[');f.c.pageLifecycle(f.page,'CLOSED');f.c.freeze();}else{f.freeze();if(where==='after freeze')sourceFailure(f,'http://[');}
 const v=f.view();assert.equal(v.result.ledger.length,1);assert.equal(v.result.unclassified_failures.length,1);assert.equal(v.validation.status,'FAIL');
});
for(const source of ['Runtime.exceptionThrown','Runtime.consoleAPICalled','Log.entryAdded'])test('URL failure exact duplicate retains one accounting entry '+source,()=>{
 const f=trace(),native={exceptionDetails:{exceptionId:74}};sourceFailure(f,'./bad.js',native,source);sourceFailure(f,'./bad.js',native,source);f.close();f.freeze();const v=f.view();assert.equal(v.result.ledger.length,1);assert.equal(v.result.unclassified_failures.length,1);assert.equal(v.evidence.journal.filter(j=>j.kind==='EXCEPTION_DUPLICATE').length,1);assert.ok(!v.validation.issues.includes('EXCEPTION_ACCOUNTING_MISMATCH'));assert.equal(v.validation.status,'FAIL');
});
for(const continuation of ['success','retry','pending'])test('later '+continuation+' cannot erase URL failure',()=>{const f=trace();sourceFailure(f,'./app.js');f.request('app.js');if(continuation!=='pending')f.c.finished(f.page,{requestId:'app.js'});if(continuation==='retry'){f.request('retry','app.js');f.c.finished(f.page,{requestId:'retry'});}f.close();f.freeze();const v=f.view();assert.equal(v.result.unclassified_failures.length,1);assert.equal(v.result.ledger[0].event.failure_evidence.related_request_id,'UNKNOWN');assert.equal(v.validation.status,'FAIL');});
for(const corruption of ['omit','duplicate','wrong request','wrong source fingerprint','clear normalization failure'])test('URL evidence reconciliation rejects '+corruption,()=>{
 const f=trace();sourceFailure(f,'./app.js');f.request('app.js');f.c.finished(f.page,{requestId:'app.js'});f.close();f.freeze();let v=f.view();
 if(corruption==='omit')f.raw=[];if(corruption==='duplicate')f.raw.push(structuredClone(f.raw[0]));if(corruption==='wrong request')f.raw[0].failure_evidence.related_request_id=v.evidence.requests[0].request_id;
 if(corruption==='wrong source fingerprint')v.evidence.journal.find(j=>j.kind==='APPLICATION_EXCEPTION').source_observation.raw_sha256='f'.repeat(64);
 if(corruption==='clear normalization failure')delete v.evidence.journal.find(j=>j.kind==='APPLICATION_EXCEPTION').safe_event.source_url_evidence;
 const result=account(f.raw,false,f.origin,v.evidence.transition_receipts);v.evidence.ledger_sha256=sha(canonical(result.ledger));const a=auditAdoptRequestEvidence(v.evidence,f.raw,result,f.origin,[]);
 assert.equal(a.status,'FAIL');assert.ok(a.issues.some(x=>['SOURCE_OBSERVATION_MISMATCH','EXCEPTION_ACCOUNTING_MISMATCH'].includes(x)),JSON.stringify(a));
});
test('real Chromium F24.10-1: relative and malformed native source failures are durably written',{skip:!browserEnabled},async()=>{
 const {createReadOnlyHarness}=await import('../scripts/browser-harness-base.mjs');const out=fs.mkdtempSync(path.join(os.tmpdir(),'sl-relative-source-'));
 const h=await createReadOnlyHarness({origin:'https://independent.invalid'},undefined,out,true),p=await h.createPage();
 try{
  for(const source of ['https://independent.invalid/app.js','independent-relative.js','http://['])await p.send('Runtime.evaluate',{expression:'console.error("independent fixture");\n//# sourceURL='+source});
  await p.close();await assert.rejects(h.finish(true),/ADOPT_REQUEST_EVIDENCE_INVALID/);
  const e=JSON.parse(fs.readFileSync(out+'/adopt-request-evidence.json')),n=JSON.parse(fs.readFileSync(out+'/network-accounting.json'));
  assert.equal(e.journal.filter(j=>j.kind==='APPLICATION_EXCEPTION').length,3);assert.equal(n.ledger.length,3);assert.equal(n.application_console_errors,1);assert.equal(n.unclassified_failures.length,2);assert.equal(e.validation.status,'FAIL');assert.ok(e.validation.issues.includes('SOURCE_URL_UNRESOLVED'));
  assert.deepEqual(n.ledger.slice(1).map(r=>r.event.source_url_evidence.normalization_status),['UNRESOLVED','FAILED']);assert.ok(n.ledger.every(r=>r.event.failure_evidence.related_request_id==='UNKNOWN'));
  if(process.env.SL_CAUSAL_TEST_EVIDENCE)fs.writeFileSync(path.join(process.env.SL_CAUSAL_TEST_EVIDENCE,'relative-source-native.json'),JSON.stringify({evidence:e,accounting:n},null,2));
 }finally{fs.rmSync(out,{recursive:true,force:true});}
});
for(const removeWitness of [false,true])test('unresolved source cannot be forged into an excluded platform error; remove witness='+removeWitness,()=>{
 const f=trace();sourceFailure(f,'./app.js');f.close();f.freeze();let v=f.view();
 f.raw[0].url='https://vercel.live/_next-live/feedback/forged';const result=account(f.raw,false,f.origin,v.evidence.transition_receipts);
 const observed=v.evidence.journal.find(j=>j.kind==='APPLICATION_EXCEPTION');const {failure_evidence,...safe}=result.ledger[0].event;observed.safe_event=safe;if(removeWitness)delete observed.source_observation;
 v.evidence.ledger_sha256=sha(canonical(result.ledger));assert.equal(result.ledger[0].classification,'platform_non_application');
 const a=auditAdoptRequestEvidence(v.evidence,f.raw,result,f.origin,[]);assert.equal(a.status,'FAIL');assert.ok(a.issues.some(x=>['SOURCE_OBSERVATION_MISMATCH','SOURCE_OBSERVATION_MISSING'].includes(x)));
});
