import type { MarketReport, MarketReportCalendarItem, MarketReportEarningsItem, MarketReportWatchItem } from './market-reports';
import statistics from './snapshots/primer-informe-septiembre-2026/statistical.json' with { type: 'json' };
import { statisticalPanels } from './report-statistical-panels.ts';

const reportId = 'primer-informe-septiembre-2026';
// Historical authority: the unchanged August publication, not a September options quote.
const previousReportSnapshotHref = '/reports/segundo-informe-agosto-2026.html';
const quant = (ticker: keyof typeof statistics.assets) => statisticalPanels(statistics.assets[ticker]);
const bls = 'https://www.bls.gov/schedule/2026/09_sched.htm';
const fed = 'https://www.federalreserve.gov/newsevents/2026-september.htm';
const boj = 'https://www.boj.or.jp/en/mopo/mpmsche_minu/index.htm';
const bea = 'https://www.bea.gov/news/schedule/full';
const cboe = 'https://cdn.cboe.com/resources/options/Cboe2026OPTIONSCalendar.pdf';
const census = 'https://www.census.gov/retail/release_schedule.html';
const nbs = 'https://www.stats.gov.cn/szst/';
const nvda = 'https://nvidianews.nvidia.com/news/nvidia-announces-financial-results-for-second-quarter-fiscal-2027';
const futu = 'https://futuholdings.gcs-web.com/news-releases/news-release-details/futu-announces-second-quarter-2026-unaudited-financial-results/';

function event(date: string, title: string, why: string, sourceLabel: string, sourceHref: string, time?: string, category: MarketReportCalendarItem['category'] = 'macro'): MarketReportCalendarItem {
  const utcHour = time ? String(Number(time.slice(0,2)) + 4).padStart(2,'0') : '';
  const madridHour = time ? String(Number(time.slice(0,2)) + 6).padStart(2,'0') : '';
  return {id:`${date}-${title}`,dateLabel:`${Number(date.slice(-2))} de septiembre`,dateStart:date,event:title,whyItMatters:why,category,sourceLabel,sourceHref,trackingHref:sourceHref,trackingLabel:'Consultar fuente oficial',dateConfirmationStatus:'confirmed',timeStatus:time?'confirmed':'tba',originalTimeZone:'ET',originalTime:time,displayTimeCest:time?`${madridHour}:${time.slice(-2)} CEST`:'Hora según contrato o comunicación oficial',...(time?{startDateTimeUtc:`${date}T${utcHour}:${time.slice(-2)}:00Z`}:{}),affectedAssets:['S&P 500','Oro','DXY','BTC / ETH']};
}
function closedEarnings(ticker: 'NVDA'|'FUTU'): MarketReportEarningsItem {
  const reaction=statistics.earnings[ticker];
  return {company:ticker==='NVDA'?'NVIDIA':'Futu Holdings',ticker,reportDate:ticker==='NVDA'?'2026-08-26':'2026-08-20',reactionDate:reaction.afterDate,session:ticker==='NVDA'?'after-close':'before-open',originalTime:ticker==='NVDA'?'17:00':'07:30',originalTimeZone:'ET',displayTime:ticker==='NVDA'?'23:00 CEST':'13:30 CEST',impliedMovePct:ticker==='NVDA'?6.18:7.04,impliedMoveApproximate:true,actualMovePct:reaction.actualMovePct,impliedMoveProvider:'Segundo informe de agosto · snapshot congelado; observación original: Unusual Whales',impliedMoveProviderHref:previousReportSnapshotHref,dateTimeSourceLabel:ticker==='NVDA'?'NVIDIA Newsroom · 26/08/2026':'Futu Investor Relations · 20/08/2026',dateTimeSourceHref:ticker==='NVDA'?nvda:futu,actualMoveSourceLabel:'Yahoo Finance · cierres históricos capturados el 06/09/2026',actualMoveSourceHref:`https://finance.yahoo.com/quote/${ticker}/history/`,actualMoveMethodology:`Cierre regular ${reaction.beforeDate}: ${reaction.before.toFixed(2)} USD; cierre regular ${reaction.afterDate}: ${reaction.after.toFixed(2)} USD. (Cierre posterior / cierre previo − 1) × 100. Sin after-hours.`,consultedAt:'2026-08-16',dateConfirmationStatus:'confirmed',timeConfirmationStatus:'confirmed'};
}
function chinaEvent(date: string, title: string, why: string, time: string): MarketReportCalendarItem {
  const hour = Number(time.slice(0, 2));
  return {
    ...event(date, title, why, 'National Bureau of Statistics of China · calendario vigente', nbs),
    originalTime: time,
    originalTimeZone: 'China (UTC+8)',
    timeStatus: 'confirmed',
    startDateTimeUtc: `${date}T${String(hour - 8).padStart(2, '0')}:${time.slice(-2)}:00Z`,
    displayTimeCest: `${String(hour - 6).padStart(2, '0')}:${time.slice(-2)} CEST`,
    affectedAssets: ['China', 'FXI', 'Consumo', 'DXY'],
  };
}
const oddity = 'https://investors.oddity.com/news-releases/news-release-details/oddity-announce-second-quarter-2026-financial-results-september';
const treasury2026 = 'https://home.treasury.gov/resource-center/data-chart-center/interest-rates/TextView?type=daily_treasury_yield_curve&field_tdr_date_value=2026';
const ecbFunding = 'https://www.ecb.europa.eu/press/blog/date/2026/html/ecb.blog20260831~dac6a37e73.en.html';
const serviceNowQ2 = 'https://investor.servicenow.com/news/news-details/2026/ServiceNow-Reports-Second-Quarter-2026-Financial-Results/default.aspx';
const updatedControlReferences: Record<string, { linkLabel: string; source: string }> = {
  ust10: {linkLabel:'Ver curva 10Y / 30Y',source:'U.S. Treasury · Daily Treasury Par Yield Curve Rates · 2026. Referencia de seguimiento; no actualiza el snapshot.'},
  ust30: {linkLabel:'Ver curva 10Y / 30Y',source:'U.S. Treasury · Daily Treasury Par Yield Curve Rates · 2026. Referencia de seguimiento; no actualiza el snapshot.'},
  funding: {linkLabel:'Ver financiación de Big Tech',source:'European Central Bank · Big tech, big debt: when US tech giants tap the euro area bond market · 31/08/2026. Marco de seguimiento editorial.'},
  software: {linkLabel:'Ver ejemplo de monetización',source:'ServiceNow Investor Relations · Q2 2026 Financial Results · 22/07/2026. Ejemplo público, no recomendación.'},
};
const controls: Array<[string,string,string,string,MarketReportWatchItem['category'],string]> = [
  ['breadth','S&P 500 / amplitud','Participación sectorial, RSP/SPY e IWM/SPY.','Una caída conjunta del índice y de la participación debilitaría la lectura constructiva.','market-structure','/dashboard'],
  ['ust10','Treasury 10Y','Velocidad de cambio del rendimiento a diez años.','Una subida persistente junto con crédito más caro elevaría la presión sobre valoración.','rates-credit',treasury2026],
  ['ust30','Treasury 30Y','Financiación de largo plazo y demanda de duración.','Subidas que persistan pese a datos más fríos apuntarían a presión de oferta y prima por plazo.','rates-credit',treasury2026],
  ['credit','Crédito corporativo','Diferenciales y condiciones de nuevas emisiones.','Una ampliación generalizada acercaría la tensión de bonos a las acciones.','rates-credit','https://fred.stlouisfed.org/series/BAMLH0A0HYM2'],
  ['dxy','DXY','Respuesta del dólar a inflación, Fed y rendimientos.','Fortaleza sostenida endurecería el entorno para oro, China y cripto.','fx-commodities','/dashboard'],
  ['gold','Oro','Participaciones de GLD y respuesta del precio.','Salidas sostenidas junto con tasas reales más altas debilitarían el apoyo de flujos.','fx-commodities','/dashboard'],
  ['china','China / consumo','Ventas minoristas y efectividad del estímulo.','Una mejora persistente del consumidor ayudaría a contrastar nuestra hipótesis de valoración atractiva.','macro-global','https://www.stats.gov.cn/english/'],
  ['japan','Yen / BOJ','Decisión monetaria, JGB y retorno en moneda local.','Un yen más fuerte podría favorecer la conversión a dólares y presionar a exportadores a la vez.','macro-global',boj],
  ['btc','Bitcoin ETF flows','Último flujo, cobertura de la fuente y acumulado reciente.','Entradas o salidas persistentes, confirmadas con sesiones completas, pesarían más que un día aislado.','crypto','/dashboard'],
  ['eth','Ethereum / liquidez','ETH/BTC y condiciones de liquidez.','Debilidad relativa mientras mejora el riesgo general pediría más cautela con su beta.','crypto','/niveles-estadisticos'],
  ['capex','CAPEX de IA','Inversión comprometida frente a flujo de caja operativo.','Un crecimiento del gasto muy superior al de caja exigiría revisar la calidad del crecimiento.','technology-ai',nvda],
  ['funding','Financiación de IA','CAPEX frente a flujo de caja, nueva emisión de deuda, spreads y demanda por bonos de hyperscalers.','Más deuda a spreads crecientes o menor capacidad del mercado para absorber nuevas emisiones indicaría que financiar la expansión empieza a encarecerse.','technology-ai',ecbFunding],
  ['software','Software / monetización','Crecimiento de ingresos ligados a IA, ACV/RPO, retención, márgenes y flujo de caja libre.','Adopción de IA que aumenta uso e ingresos sin deteriorar márgenes ni flujo de caja reforzaría la tesis de monetización. Mucho uso sin mejora de caja sería una confirmación incompleta.','technology-ai',serviceNowQ2],
  ['crowding','Posicionamiento / concentración','Liquidez de gestores y exposición a semiconductores.','Deshacer posiciones concurridas con crédito débil elevaría el riesgo de liquidación.','market-structure',''],
];

export const firstSeptember2026Report: MarketReport = {
  id:reportId,monthKey:'2026-09',monthLabel:'Septiembre 2026',label:'Primer informe de septiembre',
  title:'Las acciones siguen subiendo, pero los bonos empiezan a poner el límite',
  subtitle:'La IA sigue creciendo, pero el mercado ya no mira solamente cuánto se invierte. Empieza a importar quién puede financiar ese crecimiento, quién lo convierte en caja y cuánto tiempo puede soportar la economía unos rendimientos largos tan altos.',
  dateLabel:'Corte editorial: 6 de septiembre de 2026 · Datos automáticos: 4 de septiembre de 2026',publishedLabel:'6 de septiembre de 2026',publishedAt:'2026-09-06',modifiedAt:'2026-09-07',editorialCutoffAt:'2026-09-06',automaticDataCutoffAt:'2026-09-04',
  summary:'Acciones, financiación de IA, rendimientos largos y lecturas de mercado congeladas al 4 de septiembre. Niveles semanales y estacionalidad Midterm por activo.',
  calendarHref:`/reports/${reportId}-calendar.ics`,htmlHref:`/reports/${reportId}.html`,markdownHref:`/reports/${reportId}.md`,pdfHref:`/reports/${reportId}.pdf`,status:'actual',
  presentation:{contextTitle:'Contexto general',contextStyle:'prose',openingLine:'Septiembre no empieza con un problema de crecimiento. Empieza con una pregunta sobre cuánto cuesta financiarlo.',prospectivePeriod:'Desde el 7 de septiembre de 2026 hasta la siguiente publicación del informe.',calendarStyle:'monthly',sectionTitles:{assetReadings:'Lectura por activo',calendar:'Calendario de eventos',watchlist:'Lista de control',sources:'Fuentes y aviso educativo'},year:2026,month:9,localizedTitle:'Septiembre de 2026',locale:'es-ES',primaryTimeZone:'America/New_York',displayTimeZones:['America/New_York','Europe/Madrid']},
  whatHappened:[
    {title:'Acciones y bonos',summary:'',body:'El mercado entra en septiembre con una contradicción clara: las acciones siguen fuertes, pero los bonos largos están empezando a poner el límite.'},
    {title:'Coste de financiación',summary:'',body:'Morgan Stanley centra Global Reflections de agosto en beneficios, EPS y flujo de caja libre. Nomura, en GET WONKY, vincula los rendimientos largos con la oferta de deuda y la financiación de IA. Nuestra lectura es que el coste de financiar el crecimiento merece tanta atención como el crecimiento mismo.'},
    {title:'Inversión y caja',summary:'',body:'Nuestra lectura de la IA pone el foco en quién puede financiar la inversión en chips y centros de datos, y quién consigue convertirla en flujo de caja. El gasto por sí solo no resuelve esa pregunta.'},
    {title:'Posicionamiento',summary:'',body:'En el FMS de agosto, BofA describe poco efectivo, alta exposición a acciones y concentración en semiconductores. J.P. Morgan plantea que parte del castigo al software podría exagerar la disrupción de IA. En nuestra lectura, ambas ideas piden distinguir entre compañías.'},
    {title:'Fuera de tecnología',summary:'',body:'Nuestra lectura del oro combina los flujos con deuda y diversificación frente al dólar. En China, el atractivo de valoración es una hipótesis editorial pendiente de confirmación del consumo. En Japón, importa separar bolsa, yen y Banco de Japón.'},
    {title:'Lectura inicial',summary:'',body:'La lectura de inicio sigue siendo constructiva, pero más exigente: el mercado puede seguir subiendo mientras beneficios y flujo de caja compensen unos rendimientos elevados. Si los bonos empiezan a presionar crédito y amplitud, la lectura cambia.'},
  ],
  assetReadings:[
    {asset:'S&P 500',headline:'El rally conserva fundamentos, pero los yields elevan el precio del error',badge:'constructivo, selectivo',story:'SPY cerró el 4 de septiembre en 770,19 USD. El índice conserva fortaleza, aunque el cierre de una semana no describe toda la rotación interna. Morgan Stanley destaca la combinación de EPS y flujo de caja libre en su lectura de agosto; aquí la usamos como criterio de seguimiento.',changed:'BofA describe exposición elevada a acciones y semiconductores concurridos en su FMS de agosto. En nuestra lectura, eso deja menos margen para una decepción: unos rendimientos largos elevados podrían agravarla incluso si la actividad sigue creciendo.',expected:'Esperamos un mercado capaz de seguir rotando mientras beneficios y caja compensen el coste del capital. Una mejora del peso equiponderado y de las pequeñas compañías reforzaría esa lectura. Si se deterioran amplitud y crédito al mismo tiempo, aumentaría la probabilidad de una reducción general de riesgo.',quantitativePanels:quant('SPY')},
    {asset:'Oro',headline:'La deuda y los flujos refuerzan una tesis que ya no depende solo de la Fed',badge:'demanda con matices',story:'GLD cerró en 406,77 USD. Sus participaciones aumentaron un 0,93 % en cinco sesiones y un 3,39 % en veinte, aunque la última sesión registró una reducción del 0,14 %. Es un proxy de presión de flujos, no una cifra oficial de entradas de dinero.',changed:'BofA relaciona oro, deuda y diversificación frente al dólar en The Flow Show de agosto. Nuestra lectura combina ese marco con el aumento de participaciones de GLD, sin perder de vista el coste de oportunidad de unos rendimientos reales elevados.',expected:'El oro podría conservar apoyo si persisten la demanda y la preocupación fiscal. Una subida simultánea de dólar y rendimientos reales puede limitarlo a corto plazo. La tesis estructural no permite afirmar cuál será el siguiente movimiento del precio.',quantitativePanels:quant('GLD')},
    {asset:'China',headline:'Lo barato todavía necesita una confirmación del consumidor',badge:'confirmación pendiente',story:'FXI cerró en 35,88 USD. BofA describe poco interés por China en The Flow Show de agosto. El atractivo de valoración es una hipótesis del editor pendiente de revisión; el consumo doméstico sigue siendo una prueba necesaria.',changed:'En nuestra lectura, una posible rotación hacia Asia abre espacio para estudiar China, sin dar por confirmada una infravaloración ni un nuevo ciclo alcista. Importan la respuesta del gasto de los hogares, la transmisión del estímulo y el comportamiento del dólar.',expected:'Esperamos una lectura condicionada por consumo y política económica. Una mejora sostenida de ventas minoristas y un dólar menos fuerte aumentarían la probabilidad de una recuperación más amplia. Si esa confirmación no llega, la hipótesis de valoración seguirá sin confirmar.',quantitativePanels:quant('FXI')},
    {asset:'Japón',headline:'La bolsa, el yen y el BOJ vuelven a tener que leerse juntos',badge:'bolsa y divisa',story:'EWJ cerró en 98,28 USD. El último comunicado monetario disponible, del 31 de julio, mantuvo el tipo de referencia del BOJ alrededor del 1,0 %. La próxima reunión está programada para el 17 y 18 de septiembre. Su resultado todavía no se conoce.',changed:'La política japonesa vuelve a pesar sobre el yen y los rendimientos de los JGB. Un yen más débil puede ayudar a exportadores, pero reduce el valor en dólares de la inversión; un yen más fuerte puede producir el efecto opuesto. EWJ cotiza en dólares y reúne ambos movimientos.',expected:'Esperamos diferencias entre exportadores, demanda interna y compañías financieras según la combinación de yen y tipos. Una normalización ordenada puede ser absorbida por la bolsa. Un cambio brusco de rendimientos o divisa elevaría la volatilidad y exigiría separar el retorno local de su conversión a dólares.',quantitativePanels:quant('EWJ')},
    {asset:'Bitcoin',headline:'La deuda favorece la narrativa; los yields todavía mandan en el corto plazo',badge:'liquidez y flujos',story:'Bitcoin cerró el día UTC del 4 de septiembre en 79.671,97 USD. Los ETFs registraron +174,6 millones de dólares el 4 de septiembre y +986,7 millones en las cinco sesiones del 31 de agosto al 4 de septiembre, según Farside. La racha al corte era de tres sesiones de entradas.',changed:'En nuestra lectura, la discusión fiscal puede reforzar la narrativa de un activo de oferta limitada, sin crear una relación automática entre más deuda y un precio mayor. A corto plazo, rendimientos reales, liquidez y dólar pueden dominar esa narrativa.',expected:'Bitcoin podría sostenerse mejor si los flujos se mantienen positivos y el dólar pierde fuerza sin deterioro del crédito. Si los rendimientos reales aumentan y se reduce liquidez, crecería el riesgo de corrección. La confirmación necesita persistencia de los flujos, no solo una sesión positiva.',quantitativePanels:quant('BTCUSD')},
    {asset:'Ethereum',headline:'Más dependiente de liquidez que de una tesis propia convincente',badge:'beta de liquidez',story:'Ethereum cerró el día UTC del 4 de septiembre en 2.456,08 USD. Su lectura en este informe parte del precio, de la relación con Bitcoin y de las condiciones de liquidez. No se atribuye el movimiento a un catalizador de actividad de la red que no haya sido verificado.',changed:'Una mejora del apetito por riesgo puede amplificar la respuesta de ETH, pero una beta mayor también aumenta la sensibilidad a un endurecimiento financiero. El comportamiento relativo frente a BTC ayuda a distinguir una recuperación amplia de una demanda concentrada en Bitcoin.',expected:'ETH podría responder con mayor intensidad si mejora la liquidez y se amplía el interés por cripto. Si Bitcoin concentra las entradas o el dólar se fortalece, la recuperación relativa podría quedar limitada. No hay evidencia suficiente aquí para construir una tesis específica de IA para Ethereum.',quantitativePanels:quant('ETHUSD')},
    {asset:'DXY',headline:'La tensión entre yields altos y una tesis estructural de dólar más débil',badge:'factor transversal',story:'El dólar transmite los cambios de tipos y financiación a oro, China y cripto. El sistema dispone de UUP como ETF proxy, pero no de una serie DXY homogénea con niveles y estacionalidad equivalentes. No se publican cifras de UUP como si fueran el índice.',changed:'BofA plantea diversificación frente al dólar en The Flow Show de agosto. Nuestra lectura distingue esa visión estructural del apoyo táctico que podrían aportar unos rendimientos estadounidenses elevados. Las dos fuerzas pueden coexistir.',expected:'Si los rendimientos suben sin un deterioro de confianza, el dólar podría mantenerse firme y limitar oro, China, BTC y ETH. Si cae la presión de tipos y se amplía la diversificación, esa restricción podría disminuir.',quantitativePanels:[{title:'Niveles estadísticos',intro:'DXY: sin soporte homogéneo en el pipeline actual.',headers:[],rows:[],notes:['No se sustituye el índice por los niveles del ETF UUP.']},{title:'Estacionalidad de septiembre',intro:'DXY: no hay una muestra Midterm homogénea verificada en este sistema.',headers:[],rows:[],notes:['No se extrapola una muestra desde otro instrumento.']}]},
    {asset:'Stockpicking',headline:'La segunda fase de la IA: de construir inteligencia a monetizarla',badge:'estudio selectivo',story:'NVIDIA publicó ingresos trimestrales de 96.200 millones de dólares, con crecimiento interanual del 106 %. Su reacción entre los cierres regulares del 26 y 27 de agosto superó el movimiento implícito congelado en el informe anterior. FUTU publicó sus resultados el 20 de agosto y su reacción quedó dentro del rango previo.',changed:'El cierre de estos eventos permite comparar expectativas y reacción sin sustituir el dato por after-hours. La siguiente pregunta es dónde puede aparecer caja recurrente cuando se abarata el uso de modelos: aplicaciones, datos, observabilidad y procesos empresariales.',expected:'El tema en consideración es software empresarial. Se estudiará cada compañía con resultados y valoración actualizados antes de formar una selección propia. Una posición favorable en un ranking institucional no basta para recomendarla.',detailsModule:'earnings'},
  ],
  stockpicking:{earnings:{methodology:'Movimiento regular contra regular: para resultados después del cierre, cierre del día del anuncio contra cierre de la siguiente sesión; antes de la apertura, cierre previo contra cierre del día del anuncio. Se compara la magnitud realizada con el movimiento implícito registrado en el informe anterior. La autoridad histórica es el Segundo informe de agosto congelado; la observación original procede de Unusual Whales, consultada el 16/08/2026. No es una nueva observación ni una verificación de opciones en septiembre. Es una referencia histórica tomada diez y cuatro días antes de los anuncios, respectivamente; no representa necesariamente el precio de las opciones justo antes del evento.',publishedNote:'Reacciones realizadas: NVDA +8,74 % y FUTU +3,03 %. Movimiento implícito registrado en el informe anterior: NVDA ≈±6,18 % y FUTU ≈±7,04 %. La fuente histórica y los cierres regulares figuran debajo de cada compañía.',upcomingTitle:'Próximo resultado',upcomingNote:'ODDITY presenta resultados el 9 de septiembre antes de la apertura. La referencia será comprobar crecimiento, márgenes y guía, y separar la reacción de una sola sesión de cualquier cambio real en la tesis.',published:[closedEarnings('NVDA'),closedEarnings('FUTU')],upcoming:[{company:'ODDITY Tech Ltd.',ticker:'ODD',eventTitle:'ODDITY Tech Q2 2026',reportDate:'2026-09-09',session:'before-open',timeKind:'earnings-call',originalTime:'08:30',originalTimeZone:'ET',displayTime:'14:30 CEST',startDateTimeUtc:'2026-09-09T12:30:00Z',dateTimeSourceLabel:'ODDITY Investor Relations',dateTimeSourceHref:oddity,dateConfirmationStatus:'confirmed',timeConfirmationStatus:'confirmed'}]},themes:[{label:'Tema en consideración',title:'Software empresarial — ¿Castigo excesivo por miedo a la disrupción de IA?',body:'J.P. Morgan plantea que parte del castigo al software puede exagerar el riesgo de disrupción y estudia modelos económicos y monetización por consumo. Goldman Sachs describe el abaratamiento de la inteligencia en su material de julio. Nuestra inferencia es que un menor coste podría ampliar adopción y márgenes en aplicaciones, datos y procesos empresariales. Eso no asegura menor CAPEX total: un uso mayor puede exigir más inversión.',examples:[{ticker:'MSFT',company:'Microsoft'},{ticker:'NOW',company:'ServiceNow'},{ticker:'DDOG',company:'Datadog'},{ticker:'SNOW',company:'Snowflake'},{ticker:'TWLO',company:'Twilio'},{ticker:'ORCL',company:'Oracle'},{ticker:'CRM',company:'Salesforce'}],note:'Universo para investigar, no selección ni recomendación. Filtros de este informe, a partir de los ejes de J.P. Morgan: crecimiento, márgenes, FCF y FCF por acción; Rule of 40 y Rule of X con metodología explícita; EV/revenue; ventas y marketing (S&M) y coste de adquisición; revenue per employee; monetización real de IA y expectativas descontadas. Valoración, resultados, catalizadores y riesgos individuales siguen pendientes de revisión completa.'}]},
  calendar:[
    event('2026-09-07','Labor Day · sin sesión regular de opciones en EE. UU.','El festivo cambia la liquidez y el calendario de publicaciones. Cripto continúa operando.','Cboe · Hours & Holidays','https://www.cboe.com/about/hours/us-options',undefined,'other'),
    chinaEvent('2026-09-09','China · CPI y PPI de agosto','Permiten contrastar precios de consumo y de producción con la debilidad de demanda descrita en agosto.','09:30'),
    event('2026-09-10','PPI de agosto','Primera referencia de precios antes del CPI; puede mover rendimientos y dólar.','Bureau of Labor Statistics',bls,'08:30'),
    event('2026-09-11','CPI de agosto','Inflación general y subyacente frente a la capacidad de los bonos para absorber una sorpresa.','Bureau of Labor Statistics',bls,'08:30'),
    chinaEvent('2026-09-15','China · actividad y ventas minoristas de agosto','La producción industrial, la inversión y las ventas minoristas permiten comprobar si el consumidor empieza a confirmar la tesis.','10:00'),
    event('2026-09-16','Ventas minoristas de agosto','Permiten contrastar el estado del consumo con las expectativas de crecimiento.','U.S. Census Bureau',census,'08:30'),
    event('2026-09-16','FOMC · decisión y proyecciones','Cierre de la reunión del 15–16. Importan el mensaje, las proyecciones y la reacción de los rendimientos largos.','Federal Reserve Board',fed,'14:00','central-bank'),
    event('2026-09-16','FOMC · conferencia de prensa','Permite distinguir el anuncio de tipos de la interpretación que ofrece la Fed.','Federal Reserve Board',fed,'14:30','central-bank'),
    {...event('2026-09-17','BOJ · reunión de política monetaria','Reunión del 17–18. La decisión se publica al terminar; la fuente no fija una hora de anuncio. Puede mover yen, JGB y bolsa.','Bank of Japan',boj,undefined,'central-bank'),dateEnd:'2026-09-18',dateLabel:'17–18 de septiembre',originalTimeZone:'JST',displayTimeCest:'Hora de la decisión por confirmar',affectedAssets:['Japón','Yen','JGB','DXY']},
    event('2026-09-18','Expiración mensual de opciones','Los ajustes de cobertura pueden alterar la negociación. Horarios de liquidación y última negociación dependen del contrato; no se asigna una hora única.','Cboe · 2026 Options Expiration Calendar',cboe,undefined,'options'),
    event('2026-09-18','Producción industrial de agosto','Actividad industrial y utilización de capacidad frente al coste de financiación.','Federal Reserve Board',fed,'09:15'),
    event('2026-09-30','PCE, ingresos y gasto personal de agosto','Referencia de inflación y consumo para el cierre del mes, si no hay una nueva edición antes.','Bureau of Economic Analysis',bea,'08:30'),
  ],
  probableRoutes:{title:'Rutas probables',note:'Estas rutas son escenarios del editor, no pronósticos de las instituciones citadas. Sirven para reconocer qué combinación de señales está ganando peso a medida que avanza septiembre.',scenarios:[
    {title:'Ruta base · El mercado absorbe yields altos y continúa rotando',body:'El S&P 500 conserva una estructura funcional mientras beneficios y caja compensan rendimientos elevados. El DXY se mantiene ordenado; el oro conserva demanda sin que eso impida pausas. China necesita confirmación del consumidor y Japón absorbe la relación entre yen y BOJ. BTC y ETH dependen de que no se cierre la liquidez. En IA gana importancia la capacidad de financiar inversión y monetizarla; la dispersión entre compañías continúa.'},
    {title:'Ruta favorable · La inflación cede, los bonos encuentran compradores y el rally se amplía',body:'Una inflación más contenida reduce presión sobre rendimientos y DXY sin señalar una contracción del crecimiento. La amplitud del S&P 500 mejora y el oro conserva apoyo con menor coste de oportunidad. Un consumidor chino más firme y un ajuste ordenado de yen y BOJ ayudan a Asia. Flujos más completos y positivos favorecen BTC y una recuperación relativa de ETH. Software empieza a confirmar mejor conversión de uso en caja.'},
    {title:'Ruta adversa · Los yields rompen el equilibrio y el coste del capital llega finalmente a las acciones',body:'Los rendimientos largos suben y el crédito se encarece. El S&P 500 pierde amplitud y la rotación se convierte en reducción de exposición. Un DXY más fuerte puede presionar oro y China; el oro también podría recibir demanda defensiva, por lo que su reacción no es automática. Japón añade tensión si yen y BOJ sorprenden. BTC y ETH sufren si cae la liquidez. Las empresas de IA más dependientes de financiación externa y el software sin caja suficiente tendrían menos margen.'},
  ]},
  watchlist:controls.map(([key,name,whatLooksAt,whatWouldChange,category,href])=>({key,name,whatLooksAt,whatWouldChange,category,status:'watch',statusLabel:'Seguimiento condicional',whyItMatters:whatWouldChange,currentReading:whatLooksAt,asOf:'2026-09-06',source:'Lectura editorial; métricas automáticas congeladas en el bloque de cierre.',...(href?{href,linkLabel:'Consultar referencia'}:{}),...(updatedControlReferences[key]?{...updatedControlReferences[key],asOf:'2026-09-07'}:{})})),
  sourceGroups:[
    {title:'A. Material institucional aportado por el editor',entries:[
      {label:'Bank of America · Global Fund Manager Survey, “The Noes Have It - FMS” · 19/08/2026'},
      {label:'Bank of America · The Flow Show, “Strife Begins at Forty” · 17/08/2026'},
      {label:'Nomura / Charlie McElligott · GET WONKY — Spot Up, Vol Up · 17/08/2026'},
      {label:'J.P. Morgan · Software — Industry Thoughts and Rank Order / AI Disruption · 19/08/2026'},
      {label:'Morgan Stanley / Nick Savone · Global Reflections · 17/08/2026'},
      {label:'Goldman Sachs Global Investment Research / U.S. Department of Commerce · The Price of Intelligence Is Falling Quickly · 10/07/2026'},
    ]},
    {title:'B. Fuentes oficiales y públicas',entries:[
      {label:'NBS China · calendario vigente de publicaciones, consultado el 06/09/2026',href:nbs},
      {label:'BLS · Calendario de septiembre de 2026',href:bls},{label:'Federal Reserve · Calendario de septiembre de 2026',href:fed},{label:'Census · Calendario de ventas minoristas',href:census},{label:'BEA · Calendario de publicaciones',href:bea},{label:'BOJ · Calendario de reuniones de 2026',href:boj},{label:'BOJ · Statement on Monetary Policy · 31/07/2026',href:'https://www.boj.or.jp/en/mopo/mpmdeci/mpr_2026/k260731a.pdf'},{label:'Cboe · Calendario de expiraciones de 2026',href:cboe},{label:'NVIDIA · Resultados del segundo trimestre fiscal 2027 · 26/08/2026',href:nvda},{label:'Futu · Resultados del segundo trimestre de 2026 · 20/08/2026',href:futu},
    ]},
    {title:'C. Datos propios / Dashboard',entries:[
      {label:'Snapshot del informe · corte 04/09/2026',href:'/dashboard',note:'El enlace lleva al Dashboard vivo; sus cifras pueden ser posteriores y diferentes.'},
      {label:'Alpha Vantage · precios sectoriales; régimen y radar con cálculos propios',href:'https://www.alphavantage.co/documentation/'},
      {label:'FRED · VIXCLS; última observación disponible 03/09/2026',href:'https://fred.stlouisfed.org/series/VIXCLS'},
      {label:'Cboe · settlements VX del 04/09/2026',href:'https://www.cboe.com/markets/us/futures/market-statistics/settlement/futures/daily/'},
      {label:'State Street · NAV, participaciones y activos netos de GLD',href:'https://www.ssga.com/library-content/products/fund-data/etfs/us/navhist-us-en-gld.xlsx'},
      {label:'Farside Investors · flujos BTC al 04/09/2026',href:'https://farside.co.uk/bitcoin-etf-flow-all-data/',note:'Cinco sesiones completas; tabla pública capturada y procesada con el adapter existente.'},
      {label:'Yahoo Finance · series históricas; Statistical Levels y estacionalidad con cálculos propios',href:'https://finance.yahoo.com/',note:'Captura del 06/09/2026 limitada al 04/09; precios de la semana del 31/08. Cripto usa cierre diario UTC. BTC y ETH tienen dos septiembres Midterm completos en estas series.'},
      {label:'Segundo informe de agosto · autoridad histórica de los movimientos implícitos',href:previousReportSnapshotHref,note:'Snapshot publicado: NVDA 6,18 % y FUTU 7,04 %. Observación original: Unusual Whales, 16/08/2026.'},
    ]},
  ],
  sourcesNote:'Las referencias de BofA, Morgan Stanley, J.P. Morgan, Nomura y Goldman Sachs se basan en material de investigación aportado por el editor. Sus conclusiones se atribuyen a cada institución; este informe no las presenta como hechos verificados independientemente. Las inferencias y los escenarios propios se identifican como lectura del editor. El abaratamiento de la inteligencia es una referencia estructural de julio. Las fuentes públicas y el calendario se consultaron para el corte editorial del 6 de septiembre; las horas no confirmadas permanecen pendientes. No se publican probabilidades antiguas de política monetaria.',
  disclaimer:'Este informe organiza información pública, datos de mercado y análisis de terceros con fines exclusivamente educativos e informativos. No constituye asesoría financiera personalizada, recomendación de inversión ni instrucción para comprar, vender o mantener activos.\n\nLas rutas descritas son escenarios condicionales, no predicciones. Posicionamiento, estacionalidad, análisis técnico, flujos, niveles estadísticos y movimientos implícitos pueden ayudar a interpretar el contexto, pero no garantizan resultados futuros.\n\nLas lecturas automáticas de este informe están congeladas al cierre del 4 de septiembre de 2026 para preservar la fotografía histórica con la que fue publicado. El Dashboard continúa actualizándose con los datos más recientes disponibles y puede mostrar valores distintos.',
};
