import type {
  AllocationCategory,
  CurrentAllocationStatus,
} from "@/lib/personal-finance/budget/target-types";
import type { BudgetLocale } from "@/lib/personal-finance/budget/types";

type CategoryCopy = {
  description: string;
  name: string;
  subtitle: string;
  limit?: string;
};

const categories: Record<BudgetLocale, Record<AllocationCategory, CategoryCopy>> = {
  es: {
    essentials: {
      description: "Incluye lo necesario para sostener tu vida actual y cumplir las obligaciones que has registrado: vivienda, alimentación, transporte, servicios, seguros, salud indispensable y pagos mínimos de deuda.",
      name: "Básicos y compromisos",
      subtitle: "Vida actual y obligaciones",
    },
    alp: {
      description: "Prepara gastos no mensuales, pequeños imprevistos y la construcción o reposición de tu fondo de emergencia.",
      name: "ALP — Previsión y estabilidad",
      subtitle: "Gastos no mensuales, imprevistos y fondo de emergencia",
    },
    enjoyment: {
      description: "Reserva una parte para ocio, experiencias, aficiones y compras elegidas. Esta categoría no juzga el consumo: ayuda a distinguir lo que decides disfrutar de los gastos que pasan inadvertidos.",
      name: "Disfrute consciente",
      subtitle: "Ocio, experiencias y compras elegidas",
    },
    clf: {
      description: "Representa el capital que decides orientar a inversión, vivienda, negocio, adquisición de activos y otras metas patrimoniales.",
      limit: "No existe un porcentaje mínimo universal. Una aportación pequeña puede representar el inicio de un hábito, pero la herramienta no estima ni promete rentabilidad.",
      name: "CLF — Patrimonio y libertad futura",
      subtitle: "Inversión, vivienda, negocio y metas patrimoniales",
    },
    education: {
      description: "Reserva recursos para formación, certificaciones, idiomas, libros técnicos, herramientas profesionales y otras capacidades que quieras desarrollar.",
      limit: "La formación puede ampliar capacidades y oportunidades, pero no garantiza un aumento de ingresos.",
      name: "Educación",
      subtitle: "Capacidades y desarrollo profesional",
    },
    serAndGiving: {
      description: "Reserva recursos para cuidar o fortalecer tu bienestar y, si forma parte de tus valores o compromisos, contribuir a otras personas, comunidades o causas.",
      name: "SER y Donación — Bienestar y contribución",
      subtitle: "Cuidado personal y aportación voluntaria",
    },
  },
  en: {
    essentials: {
      description: "Include the amount needed to support your current life and meet the obligations you entered, such as housing, food, transportation, utilities, insurance, essential health costs, and minimum debt payments.",
      name: "Essentials and commitments",
      subtitle: "Current needs and obligations",
    },
    alp: {
      description: "Prepare for non-monthly expenses, small contingencies, and building or restoring your emergency fund.",
      name: "ALP — Planning and stability",
      subtitle: "Non-monthly expenses, contingencies, and emergency fund",
    },
    enjoyment: {
      description: "Set aside part of your income for leisure, experiences, hobbies, and chosen purchases. This category does not judge spending; it helps separate intentional enjoyment from expenses that go unnoticed.",
      name: "Intentional enjoyment",
      subtitle: "Leisure, experiences, and chosen purchases",
    },
    clf: {
      description: "Represents the amount you choose to direct toward investing, housing, a business, asset purchases, and other long-term wealth goals.",
      limit: "There is no universal minimum percentage. A small contribution can represent the beginning of a habit, but the tool does not estimate or promise returns.",
      name: "CLF — Wealth and future freedom",
      subtitle: "Investing, housing, business, and long-term assets",
    },
    education: {
      description: "Set aside resources for courses, certifications, languages, technical books, professional tools, and other skills you want to develop.",
      limit: "Education may expand skills and opportunities, but it does not guarantee higher income.",
      name: "Education",
      subtitle: "Skills and professional development",
    },
    serAndGiving: {
      description: "Set aside resources to support or strengthen your well-being and, when it reflects your values or commitments, contribute to other people, communities, or causes.",
      name: "SER and Giving — Well-being and contribution",
      subtitle: "Personal well-being and voluntary giving",
    },
  },
};

const faq = {
  es: [
    ["¿Existe una distribución ideal para todos?", "No. La distribución depende de tus ingresos, obligaciones, etapa vital y prioridades. El simulador no impone porcentajes: muestra cómo cada asignación utiliza una parte del mismo ingreso y te permite construir un objetivo propio."],
    ["¿Qué diferencia hay entre ALP y CLF?", "ALP se orienta a previsión y estabilidad: gastos no mensuales, imprevistos y construcción o reposición del fondo de emergencia. CLF se orienta a patrimonio y libertad futura: inversión, vivienda, negocio, adquisición de activos y otras metas patrimoniales."],
    ["¿Qué incluye ALP?", "La base mensual de ALP puede incluir los gastos no mensuales prorrateados, la reserva mensual para imprevistos que definas y, cuando hayas elegido un objetivo y un plazo, la aportación equivalente para avanzar hacia tu fondo de emergencia."],
    ["¿Cómo se calcula el objetivo del fondo de emergencia?", "La herramienta multiplica tus gastos básicos y pagos mínimos de deuda por el número de meses que elijas. No existe una cantidad seleccionada automáticamente ni un objetivo único válido para todas las personas."],
    ["¿Qué ocurre si mi distribución supera el 100 %?", "Puedes explorar una distribución superior al 100 %, pero no se presentará como una distribución final viable porque supera el ingreso disponible. La herramienta muestra el exceso para que decidas qué categorías ajustar."],
    ["¿Qué diferencia hay entre Educación y SER?", "Educación agrupa recursos destinados a desarrollar capacidades profesionales, como formación, idiomas o herramientas de trabajo. SER agrupa recursos destinados a cuidar, recuperar o fortalecer tu bienestar personal. Ninguna de las dos categorías garantiza un resultado concreto."],
    ["¿Qué incluye SER y Donación?", "SER y Donación permite reservar recursos para bienestar personal y, cuando forme parte de tus valores o compromisos, para contribuir a otras personas, comunidades o causas. El desglose es opcional y no existe un porcentaje mínimo universal."],
    ["¿Puedo dejar una categoría en cero?", "Sí. La herramienta no obliga a asignar dinero a todas las categorías. Sin embargo, mostrará una advertencia matemática si Básicos y compromisos no cubre los gastos y pagos mínimos introducidos, o si ALP queda por debajo de la base mensual calculada según los datos y objetivos que hayas definido."],
    ["¿Se guardan mis porcentajes y objetivos?", "No. Los datos financieros y objetivos se procesan directamente en tu navegador. No los guardamos ni los enviamos a nuestros servidores. Al recargar la página, el estado del simulador se reinicia."],
    ["¿El simulador decide qué distribución debo elegir?", "No. El simulador calcula importes, equivalencias, límites y diferencias. Tú decides la distribución objetivo. El resultado es educativo y no constituye asesoramiento financiero personalizado."],
  ],
  en: [
    ["Is there an ideal allocation for everyone?", "No. An allocation depends on your income, obligations, stage of life, and priorities. The simulator does not impose percentages. It shows how every allocation uses part of the same income and lets you build your own target."],
    ["What is the difference between ALP and CLF?", "ALP focuses on planning and stability: non-monthly expenses, contingencies, and building or restoring an emergency fund. CLF focuses on wealth and future freedom: investing, housing, a business, asset purchases, and other long-term wealth goals."],
    ["What is included in ALP?", "The monthly ALP amount may include prorated non-monthly expenses, the monthly contingency reserve you define, and, when you select a target and deadline, the equivalent contribution toward your emergency fund."],
    ["How is the emergency fund target calculated?", "The tool multiplies your essential expenses and minimum debt payments by the number of months you choose. No target is selected automatically, and there is no single amount that is right for everyone."],
    ["What happens if my allocation exceeds 100%?", "You can explore an allocation above 100%, but it will not be presented as a viable final allocation because it exceeds the available income. The tool shows the excess so you can decide which categories to adjust."],
    ["What is the difference between Education and SER?", "Education covers resources used to develop professional skills, such as courses, languages, or work tools. SER covers resources used to support, restore, or strengthen personal well-being. Neither category guarantees a specific outcome."],
    ["What is included in SER and Giving?", "SER and Giving lets you set aside resources for personal well-being and, when it reflects your values or commitments, for contributing to other people, communities, or causes. The breakdown is optional, and there is no universal minimum percentage."],
    ["Can I leave a category at zero?", "Yes. The tool does not require an allocation to every category. It will, however, show a mathematical warning when Essentials and commitments does not cover the expenses and minimum payments entered, or when ALP is below the monthly amount calculated from the data and targets you defined."],
    ["Are my percentages and targets stored?", "No. Your financial data and targets are processed directly in your browser. We do not store them or send them to our servers. Reloading the page resets the simulator."],
    ["Does the simulator decide which allocation I should choose?", "No. The simulator calculates amounts, equivalents, constraints, and differences. You choose the target allocation. The result is educational and does not constitute personalized financial advice."],
  ],
} satisfies Record<BudgetLocale, Array<[string, string]>>;

const statusLabels: Record<BudgetLocale, Record<CurrentAllocationStatus, string>> = {
  es: {
    known: "",
    notAsked: "No informada",
    notDifferentiated: "No diferenciada con los datos actuales",
    partial: "Información parcial",
  },
  en: {
    known: "",
    notAsked: "Not entered",
    notDifferentiated: "Not differentiated with the current information",
    partial: "Partial information",
  },
};

export const budgetTargetCopy = {
  es: {
    allocationHelp: "Cada categoría utiliza una parte del mismo ingreso. Aumentar una reduce el espacio disponible para las demás, pero la herramienta no moverá dinero automáticamente ni decidirá por ti.",
    allocationIntro: "Explora cómo distribuir tu ingreso entre necesidades actuales, estabilidad, disfrute, patrimonio, educación y bienestar. Tú defines los porcentajes; la herramienta muestra sus importes, límites y efectos sobre el conjunto.",
    allocationStartingPoint: "Hemos utilizado los datos de tu punto de partida como base editable. Puedes cambiar cualquier porcentaje; esta distribución no es una recomendación.",
    backToStep3: "Volver al Paso 3",
    alpBaseHelp: "Incluye los gastos no mensuales prorrateados, la reserva para imprevistos que hayas definido y, cuando exista un plazo, la aportación necesaria para alcanzar tu objetivo de cobertura.",
    alpBaseLabel: "Base mensual calculada según tus datos",
    alpShortfall: (amount: string) => `La asignación de ALP queda ${amount} por debajo de la base mensual calculada según tus datos y objetivos.`,
    amount: "Importe",
    amountAboveIncome: "El importe de una categoría no puede superar el ingreso.",
    applyClassification: "Aplicar clasificación",
    applySerGiving: "Aplicar desglose",
    categories: categories.es,
    classificationDescription: "El importe que registraste combina previsión e inversión. Puedes repartirlo entre ALP y CLF para comparar mejor tu punto de partida con la distribución objetivo.",
    classificationHelp: "El resto se mostrará como CLF. Este reparto no cambia el importe total ni los cálculos de tu punto de partida; solo permite clasificarlo para la comparación.",
    classificationOpen: "Diferenciar ALP y CLF",
    classificationPrivacy: "Esta clasificación solo se utiliza mientras mantienes esta página abierta. No se guarda y se reinicia al recargarla.",
    classificationQuestion: "¿Qué parte corresponde hoy a ALP?",
    classificationTitle: "Aclara tu ahorro e inversión actual",
    classificationTotal: "Ahorro e inversión registrados",
    classificationUnclassified: "No diferenciada con los datos actuales",
    clfLabel: "CLF — Patrimonio y libertad futura",
    comparisonChange: "Cambio",
    comparisonCurrent: "Actual",
    comparisonTarget: "Objetivo",
    comparisonTitle: "Situación actual y distribución objetivo",
    conclusionExact: "La distribución utiliza todo el ingreso mensual indicado. Puedes seguir ajustándola si cambian tus prioridades o tus datos.",
    conclusionOver: "La distribución representa un objetivo superior al ingreso mensual indicado. El exceso se mantiene visible para que puedas revisarlo.",
    conclusionUnder: "La distribución conserva una parte del ingreso sin asignar. Puedes mantenerla así o seguir ajustando las categorías.",
    conclusionTitle: "Conclusión",
    contingencyAmount: "Definir un importe",
    contingencyCopy: "Define una cantidad adicional para pequeños imprevistos que no hayas incluido en los gastos no mensuales ni en el fondo de emergencia.",
    contingencyExamples: "Por ejemplo: una reparación menor inesperada, una sustitución puntual o un copago o gasto imprevisto no recurrente.",
    contingencyNone: "No reservar por ahora",
    contingencyPercentage: "Definir un porcentaje",
    contingencyTitle: "Reserva mensual para imprevistos",
    contingencyUnset: "Todavía no quiero definirla",
    coverageCovered: "Tu fondo alcanza el objetivo de cobertura que has definido. Puedes revisarlo cuando cambien tus gastos, compromisos o prioridades.",
    coverageDeadline: "Plazo para completar el objetivo (meses)",
    coverageDeadlineHelp: "Déjalo vacío para ver únicamente el faltante.",
    coverageHelp: "Elige cuántos meses de gastos básicos y pagos mínimos quieres que pueda cubrir tu fondo. No existe un objetivo único válido para todas las personas.",
    coverageMessage: (current: string, target: number, amount: string) => `Tu fondo cubre ${current} meses de los ${target} que has elegido. Faltan ${amount} para alcanzar ese objetivo con los datos actuales.`,
    coverageMessageWithDeadline: (current: string, target: number, period: number, amount: string) => `Tu fondo cubre ${current} meses de los ${target} que has elegido. Para completar la diferencia en ${period} meses, la aportación mensual equivalente sería de ${amount}.`,
    coverageOptions: ["Todavía no quiero definirlo", "3 meses", "6 meses", "9 meses", "12 meses", "Personalizado"],
    coverageTitle: "Objetivo de cobertura",
    customMonths: "Meses personalizados",
    categoryDetails: "Qué incluye",
    cancel: "Cancelar",
    confirmReset: "Restablecer",
    distributedAmount: "Importe distribuido",
    essentialsShortfall: (amount: string, percentage: string) => `Esta asignación no cubre los gastos básicos y pagos mínimos que has introducido. Faltan ${amount}, equivalentes al ${percentage} del ingreso.`,
    equivalentAmount: "Importe equivalente",
    equivalentPercentage: "Porcentaje equivalente",
    faq,
    faqTitle: "Preguntas frecuentes sobre la distribución",
    keepCombined: "Mantener sin desglosar",
    keepAdjusting: "Seguir ajustando",
    keepUndifferentiated: "Mantener sin diferenciar",
    percentage: "Porcentaje",
    percentageError: "Introduce un porcentaje entre 0 y 100 con un máximo de dos decimales.",
    privacy: "Tus datos se procesan en este dispositivo. No se guardan ni se envían.",
    protectionTitle: "Protección y cobertura",
    resetDialogDescription: "Se descartarán los cambios realizados en tu objetivo y se recuperarán los valores iniciales del Paso 4.",
    resetDialogTitle: "¿Restablecer la distribución?",
    resetToStartingPoint: "Restablecer al punto de partida",
    reviewAllocation: "Revisar mi distribución",
    reviewConclusion: "Esta lectura organiza los datos y objetivos que has introducido. No constituye una recomendación financiera.",
    reviewTitle: "Tu distribución objetivo",
    removeBreakdown: "Quitar desglose",
    serGivingHelp: "El desglose es opcional. No existe un mínimo universal para ninguna de las dos asignaciones.",
    serGivingSummary: "Desglosar SER y Donación",
    serGivingZero: "Asigna primero un porcentaje o importe a SER y Donación para poder repartirlo.",
    statusExact: "Has distribuido todo el ingreso mensual",
    statusOver: "La distribución supera tu ingreso mensual",
    statusUnder: "Te queda parte del ingreso sin asignar",
    summaryCoverage: "Cobertura",
    summaryCurrentCoverage: "Cobertura actual",
    summaryExcess: "Exceso",
    summaryNotDefined: "Sin definir",
    summaryPending: "Pendiente",
    summaryReserve: "Reserva mensual",
    summaryStatus: "Estado",
    summaryTargetCoverage: "Objetivo de cobertura",
    summaryTitle: "Resumen del objetivo",
    summaryTotal: "Total",
    statusLabels: statusLabels.es,
    sumExact: ["Has asignado el 100 % del ingreso.", "La distribución utiliza todo el ingreso disponible."],
    sumOver: (allocated: string, excess: string) => [`Has asignado el ${allocated} %. La distribución supera el ingreso disponible en un ${excess} %.`, "Ajusta una o varias categorías para que el total no supere el ingreso disponible."],
    sumUnder: (allocated: string, remaining: string) => [`Has asignado el ${allocated} %. Queda un ${remaining} % pendiente de asignar.`, "Puedes conservarlo pendiente o distribuirlo entre las categorías."],
    unclassifiedSmall: "Gastos pequeños sin clasificar",
    viewSummary: "Ver resumen",
    zeroBase: "La cobertura no puede calcularse sin gastos básicos o pagos mínimos informados.",
  },
  en: {
    allocationHelp: "Every category uses part of the same income. Increasing one leaves less room for the others, but the tool will not move money automatically or make the decision for you.",
    allocationIntro: "Explore how to allocate your income across current needs, stability, enjoyment, wealth building, education, and well-being. You choose the percentages; the tool shows the equivalent amounts, constraints, and effect on the overall allocation.",
    allocationStartingPoint: "We used the information from your starting point as an editable base. You can change any percentage; this allocation is not a recommendation.",
    backToStep3: "Back to Step 3",
    alpBaseHelp: "It includes prorated non-monthly expenses, the contingency reserve you defined, and, when a deadline exists, the contribution needed to reach your coverage target.",
    alpBaseLabel: "Monthly amount calculated from your inputs",
    alpShortfall: (amount: string) => `Your ALP allocation is ${amount} below the monthly amount calculated from your inputs and selected goals.`,
    amount: "Amount",
    amountAboveIncome: "A category amount cannot exceed your income.",
    applyClassification: "Apply classification",
    applySerGiving: "Apply breakdown",
    categories: categories.en,
    classificationDescription: "The amount you entered combines planning and investing. You can split it between ALP and CLF to compare your starting point with the target allocation more clearly.",
    classificationHelp: "The remainder will be shown as CLF. This split does not change the total amount or the calculations in your starting point; it only classifies the amount for comparison.",
    classificationOpen: "Differentiate ALP and CLF",
    classificationPrivacy: "This classification is used only while you keep this page open. It is not stored and resets when the page is reloaded.",
    classificationQuestion: "What share currently belongs to ALP?",
    classificationTitle: "Clarify your current saving and investing",
    classificationTotal: "Saving and investing entered",
    classificationUnclassified: "Not differentiated with the current information",
    clfLabel: "CLF — Wealth and future freedom",
    comparisonChange: "Change",
    comparisonCurrent: "Current",
    comparisonTarget: "Target",
    comparisonTitle: "Current and target allocation",
    conclusionExact: "The allocation uses all of the monthly income entered. You can keep adjusting it as your priorities or inputs change.",
    conclusionOver: "The allocation represents a target above the monthly income entered. The excess remains visible so you can review it.",
    conclusionUnder: "The allocation leaves part of your income unallocated. You can keep it that way or continue adjusting the categories.",
    conclusionTitle: "Conclusion",
    contingencyAmount: "Set an amount",
    contingencyCopy: "Define an additional amount for small unexpected expenses that are not already included in your non-monthly expenses or emergency fund.",
    contingencyExamples: "For example: an unexpected minor repair, a one-time replacement, or a copay or unexpected non-recurring expense.",
    contingencyNone: "No reserve for now",
    contingencyPercentage: "Set a percentage",
    contingencyTitle: "Monthly contingency reserve",
    contingencyUnset: "I do not want to define it yet",
    coverageCovered: "Your fund reaches the coverage target you selected. You can review it when your expenses, commitments, or priorities change.",
    coverageDeadline: "Time to reach the target (months)",
    coverageDeadlineHelp: "Leave it blank to see only the shortfall.",
    coverageHelp: "Choose how many months of essential expenses and minimum payments you want your emergency fund to cover. There is no single target that is right for everyone.",
    coverageMessage: (current: string, target: number, amount: string) => `Your fund covers ${current} of the ${target} months you selected. Based on your current inputs, another ${amount} is needed to reach that target.`,
    coverageMessageWithDeadline: (current: string, target: number, period: number, amount: string) => `Your fund covers ${current} of the ${target} months you selected. To close the gap within ${period} months, the equivalent monthly contribution would be ${amount}.`,
    coverageOptions: ["I do not want to set a target yet", "3 months", "6 months", "9 months", "12 months", "Custom"],
    coverageTitle: "Coverage target",
    customMonths: "Custom months",
    categoryDetails: "What this includes",
    cancel: "Cancel",
    confirmReset: "Reset",
    distributedAmount: "Amount allocated",
    essentialsShortfall: (amount: string, percentage: string) => `This allocation does not cover the essential expenses and minimum payments you entered. The shortfall is ${amount}, equal to ${percentage} of your income.`,
    equivalentAmount: "Equivalent amount",
    equivalentPercentage: "Equivalent percentage",
    faq,
    faqTitle: "Target allocation questions",
    keepCombined: "Keep it combined",
    keepAdjusting: "Keep adjusting",
    keepUndifferentiated: "Keep it undifferentiated",
    percentage: "Percentage",
    percentageError: "Enter a percentage from 0 to 100 with no more than two decimal places.",
    privacy: "Your data is processed on this device. It is not stored or sent anywhere.",
    protectionTitle: "Protection and coverage",
    resetDialogDescription: "Your changes to the target allocation will be discarded and the initial Step 4 values will be restored.",
    resetDialogTitle: "Reset your allocation?",
    resetToStartingPoint: "Reset to starting point",
    reviewAllocation: "Review my allocation",
    reviewConclusion: "This overview organizes the information and targets you entered. It is not financial advice.",
    reviewTitle: "Your target allocation",
    removeBreakdown: "Remove breakdown",
    serGivingHelp: "The breakdown is optional. There is no universal minimum for either allocation.",
    serGivingSummary: "Break down SER and Giving",
    serGivingZero: "Assign a percentage or amount to SER and Giving before breaking it down.",
    statusExact: "You have allocated all of your monthly income",
    statusOver: "Your allocation exceeds your monthly income",
    statusUnder: "Part of your income is still unallocated",
    summaryCoverage: "Coverage",
    summaryCurrentCoverage: "Current coverage",
    summaryExcess: "Excess",
    summaryNotDefined: "Not set",
    summaryPending: "Unallocated",
    summaryReserve: "Monthly reserve",
    summaryStatus: "Status",
    summaryTargetCoverage: "Coverage target",
    summaryTitle: "Target summary",
    summaryTotal: "Total",
    statusLabels: statusLabels.en,
    sumExact: ["You have allocated 100% of your income.", "The allocation uses all available income."],
    sumOver: (allocated: string, excess: string) => [`You have allocated ${allocated}%. The allocation exceeds your available income by ${excess}%.`, "Adjust one or more categories so the total does not exceed your available income."],
    sumUnder: (allocated: string, remaining: string) => [`You have allocated ${allocated}%. Another ${remaining}% remains unallocated.`, "You can leave it unallocated or distribute it across the categories."],
    unclassifiedSmall: "Unclassified small everyday expenses",
    viewSummary: "View summary",
    zeroBase: "Coverage cannot be calculated without entered essential expenses or minimum payments.",
  },
} as const;
