import type {
  BudgetLocale,
  BudgetPriority,
  NonMonthlyFrequency,
  SmallExpenseFrequency,
} from "@/lib/personal-finance/budget/types";

const shared = {
  es: {
    addNonMonthly: "Añadir gasto no mensual",
    addSmall: "Añadir gasto pequeño",
    amount: "Importe",
    back: "Volver",
    basicExpenses: "Gastos básicos",
    basicExpensesHelp: "Vivienda, alimentación, servicios, transporte y seguros necesarios. No incluyas aquí la deuda.",
    calculationRange: "Los importes combinados superan el rango que puede calcularse con seguridad.",
    continue: "Continuar",
    coverage: "Cobertura estimada",
    coverageHelp: "Fondo de emergencia dividido entre gastos básicos y pagos mínimos de deuda.",
    coverageUnavailable: "No calculable sin gastos básicos o deuda mínima.",
    currency: "Moneda",
    currencyHelp: "Cambiar la moneda modifica el formato, pero no convierte los importes.",
    debt: "Pagos mínimos de deuda",
    education: "Educación / crecimiento profesional",
    emergencyFund: "Fondo de emergencia actual",
    enjoyment: "Disfrute consciente",
    errorSummary: "Revisa los siguientes campos:",
    fieldOptional: "Opcional",
    focusQuestion: "¿Qué quieres proteger o construir?",
    frequency: "Frecuencia",
    income: "Ingreso mensual neto",
    incomeRequired: "Introduce un ingreso mensual mayor que cero.",
    invalidMoney: "Introduce un importe válido con el formato de la moneda seleccionada.",
    invalidMonths: "Introduce un número de meses mayor que cero.",
    invalidTimes: "Introduce un número de veces igual o mayor que cero.",
    margin: "Margen mensual",
    maxRows: "Máximo de 20 filas en esta sección.",
    months: "Meses",
    monthlyEquivalent: "Equivalente mensual",
    monthlyIncomeHelp: "Utiliza el importe que recibes normalmente en un mes.",
    negativeMoney: "Los importes negativos no están permitidos.",
    nextResult: "Ver punto de partida",
    noDataSaved: "No guardamos los datos financieros que introduces.",
    nonMonthlyCopy: "Añade gastos que no llegan cada mes para repartir su impacto mensual.",
    nonMonthlyExpenses: "Gastos no mensuales",
    optionalDetails: "Gastos opcionales",
    personalDevelopment: "Desarrollo personal",
    precisionMoney: "El importe tiene más decimales de los permitidos para esta moneda.",
    privacyLong: "Los datos financieros y objetivos que introduces se procesan en tu navegador. No los guardamos ni los enviamos a nuestros servidores.",
    rangeMoney: "El importe supera el rango numérico admitido.",
    remove: "Eliminar",
    repeatsEveryMonths: "Se repite cada cuántos meses",
    resultIncome: "Ingreso mensual",
    resultTitle: "Tu punto de partida",
    resultExplanation: "Estos resultados describen los datos que has introducido. No representan una distribución recomendada.",
    savingInvestment: "Ahorro e inversión",
    smallCopy: "Incluye únicamente gastos pequeños que todavía no hayas sumado en otras categorías.",
    staticExpenseContextTitle: "Gastos que no siguen el ritmo mensual",
    staticNonMonthlyCopy: "Algunos gastos no llegan cada mes, pero siguen formando parte del presupuesto. Convertirlos en una cantidad mensual ayuda a reservar espacio para cuando aparezcan.",
    staticNonMonthlyTitle: "Gastos no mensuales",
    staticSmallCopy: "Los gastos pequeños no son necesariamente un problema. Registrarlos por separado permite ver cuánto espacio ocupan cuando todavía no están incluidos en otras categorías.",
    staticSmallTitle: "Gastos pequeños",
    smallExpenses: "Gastos pequeños (gastos hormiga)",
    step: "Paso",
    step1Label: "Ingresos",
    step1Title: "Define el punto de partida",
    step2Label: "Gastos",
    step2Title: "Ordena las salidas mensuales",
    step3Label: "Punto de partida",
    step3Title: "Tu punto de partida",
    step4Label: "Distribución objetivo",
    timesPerMonth: "Veces al mes",
    totalAssigned: "Total asignado",
  },
  en: {
    addNonMonthly: "Add non-monthly expense",
    addSmall: "Add small expense",
    amount: "Amount",
    back: "Back",
    basicExpenses: "Essential expenses",
    basicExpensesHelp: "Housing, food, utilities, transport, and necessary insurance. Do not include debt here.",
    calculationRange: "The combined amounts exceed the range that can be calculated safely.",
    continue: "Continue",
    coverage: "Estimated coverage",
    coverageHelp: "Emergency fund divided by essential expenses and minimum debt payments.",
    coverageUnavailable: "Not available without essential expenses or minimum debt payments.",
    currency: "Currency",
    currencyHelp: "Changing currency changes the format, but it does not convert amounts.",
    debt: "Minimum debt payments",
    education: "Education / professional growth",
    emergencyFund: "Current emergency fund",
    enjoyment: "Conscious enjoyment",
    errorSummary: "Review the following fields:",
    fieldOptional: "Optional",
    focusQuestion: "What do you want to protect or build?",
    frequency: "Frequency",
    income: "Monthly net income",
    incomeRequired: "Enter monthly income greater than zero.",
    invalidMoney: "Enter a valid amount using the format of the selected currency.",
    invalidMonths: "Enter a number of months greater than zero.",
    invalidTimes: "Enter a number of times equal to or greater than zero.",
    margin: "Monthly margin",
    maxRows: "Maximum of 20 rows in this section.",
    months: "Months",
    monthlyEquivalent: "Monthly equivalent",
    monthlyIncomeHelp: "Use the amount you normally receive in one month.",
    negativeMoney: "Negative amounts are not allowed.",
    nextResult: "View starting point",
    noDataSaved: "We do not store the financial data you enter.",
    nonMonthlyCopy: "Add expenses that do not arrive every month to spread their monthly impact.",
    nonMonthlyExpenses: "Non-monthly expenses",
    optionalDetails: "Optional expenses",
    personalDevelopment: "Personal development",
    precisionMoney: "The amount has more decimal places than this currency allows.",
    privacyLong: "The financial data and targets you enter are processed in your browser. We do not store them or send them to our servers.",
    rangeMoney: "The amount exceeds the supported numeric range.",
    remove: "Remove",
    repeatsEveryMonths: "Repeats every how many months",
    resultIncome: "Monthly income",
    resultTitle: "Your starting point",
    resultExplanation: "These results describe the information you entered. They do not represent a recommended allocation.",
    savingInvestment: "Saving and investing",
    smallCopy: "Only include small everyday expenses that you have not already counted elsewhere.",
    staticExpenseContextTitle: "Expenses beyond the monthly rhythm",
    staticNonMonthlyCopy: "Some expenses do not arrive every month, but they still belong in the budget. Converting them into a monthly amount helps reserve room for when they appear.",
    staticNonMonthlyTitle: "Non-monthly expenses",
    staticSmallCopy: "Small expenses are not necessarily a problem. Tracking them separately shows how much room they take when they are not already included in another category.",
    staticSmallTitle: "Small expenses",
    smallExpenses: "Small everyday expenses",
    step: "Step",
    step1Label: "Income",
    step1Title: "Define the starting point",
    step2Label: "Expenses",
    step2Title: "Organize monthly outflows",
    step3Label: "Starting point",
    step3Title: "Your starting point",
    step4Label: "Target allocation",
    timesPerMonth: "Times per month",
    totalAssigned: "Total assigned",
  },
} as const;

export const budgetCopy = {
  es: {
    ...shared.es,
    disclaimer: "Esta herramienta es educativa. No reemplaza asesoría financiera, fiscal, legal ni de planificación patrimonial.",
    educationalFocusBody: "Es dormir con menos ruido en la cabeza. Es poder decir que no. Es dejar de correr detrás de cada gasto. Es construir margen para cuidar lo importante, invertir mejor y tomar decisiones sin que la urgencia mande.",
    educationalFocusTitle: "Ordenar el dinero no es solo tener más dinero",
    heroBody: "El punto no es cumplir porcentajes perfectos desde el primer mes. El punto es entender dónde está tu dinero, qué bloque está absorbiendo tu libertad y cuál sería el siguiente ajuste razonable.",
    heroSubtitle: "Un mapa para ordenar tu dinero sin convertir tu vida en una cárcel.",
    heroTitle: "Presupuesto personal",
    separateBuckets: "Básicos, protección, disfrute consciente, libertad financiera, educación y desarrollo personal.",
    separateCopy: "Cumplir un presupuesto es más fácil cuando el dinero se separa al recibirlo, no cuando se intenta rescatar al final del mes. Una cuenta, bolsillo o sobre por bloque reduce la fricción y evita que todo compita contra todo.",
    separateTitle: "Sepáralo cuando entra",
  },
  en: {
    ...shared.en,
    disclaimer: "This tool is educational. It does not replace financial, tax, legal, or estate planning advice.",
    educationalFocusBody: "It means sleeping with less noise in your head. It means being able to say no. It means no longer chasing every expense. It means building margin to protect what matters, invest better, and make decisions without urgency running the show.",
    educationalFocusTitle: "Organizing money is not only about having more money",
    heroBody: "The point is not to hit perfect percentages in the first month. The point is to understand where your money is going, which block is absorbing your freedom, and what the next reasonable adjustment could be.",
    heroSubtitle: "A map for organizing money without turning life into a cage.",
    heroTitle: "Personal budget",
    separateBuckets: "Essentials, protection, conscious enjoyment, financial freedom, education, and personal development.",
    separateCopy: "Following a budget is easier when money is separated as it arrives, not when you try to rescue it at the end of the month. One account, pocket, or envelope per block reduces friction and prevents everything from competing with everything.",
    separateTitle: "Separate it when it arrives",
  },
} as const;

export const priorityOptions: Array<{
  label: Record<BudgetLocale, string>;
  value: BudgetPriority;
}> = [
  { value: "understand", label: { es: "Entender mi situación actual", en: "Understand my current situation" } },
  { value: "peace", label: { es: "Tranquilidad", en: "Peace of mind" } },
  { value: "family", label: { es: "Hogar", en: "Household" } },
  { value: "debt", label: { es: "Salir de deudas", en: "Getting out of debt" } },
  { value: "emergency", label: { es: "Fondo de emergencia", en: "Emergency fund" } },
  { value: "investing", label: { es: "Invertir con más orden", en: "Investing with more order" } },
  { value: "education", label: { es: "Estudiar / crecer profesionalmente", en: "Study / professional growth" } },
  { value: "independence", label: { es: "Independencia", en: "Independence" } },
  { value: "other", label: { es: "Otro", en: "Other" } },
];

export const nonMonthlyFrequencyOptions: Array<{
  label: Record<BudgetLocale, string>;
  value: NonMonthlyFrequency;
}> = [
  { value: "monthly", label: { es: "Mensual", en: "Monthly" } },
  { value: "quarterly", label: { es: "Trimestral", en: "Quarterly" } },
  { value: "semiannual", label: { es: "Semestral", en: "Semiannual" } },
  { value: "annual", label: { es: "Anual", en: "Annual" } },
  { value: "custom", label: { es: "Cada X meses", en: "Every X months" } },
];

export const smallExpenseFrequencyOptions: Array<{
  label: Record<BudgetLocale, string>;
  value: SmallExpenseFrequency;
}> = [
  { value: "daily", label: { es: "Diario", en: "Daily" } },
  { value: "weekly", label: { es: "Semanal", en: "Weekly" } },
  { value: "monthly", label: { es: "Mensual", en: "Monthly" } },
  { value: "occasional", label: { es: "Ocasional / veces al mes", en: "Occasional / times per month" } },
];
