import type { DataStatus, RegimeBias } from "@/lib/dashboard/types";

const phraseMap: Array<[RegExp, string]> = [
  [/El mercado muestra deterioro en varias lecturas, pero todavía no hay confirmación suficiente para clasificarlo como estrés\./g, "The market shows deterioration across several readings, but there is not enough confirmation to classify it as stress."],
  [/El mercado muestra deterioro en varias lecturas[^.]*estrés\./g, "The market shows deterioration across several readings, but there is not enough confirmation to classify it as stress."],
  [/Ponderación actual: rotación sectorial 45%, VIX 40% y BTC ETF flows 15%\./g, "Current weighting: sector rotation 45%, VIX 40%, and BTC ETF flows 15%."],
  [/Última actualización disponible por módulo/g, "Latest available update by module"],
  [/Última actualización disponible:/g, "Latest available update:"],
  [/Este régimen no anticipa el mercado\. Organiza lecturas de volatilidad, rotación y flujos para leer el contexto\./g, "This regime does not predict the market. It organizes volatility, rotation, and flow readings to interpret the current context."],
  [/La confianza se ajusta según la disponibilidad y calidad de rotación sectorial, VIX y BTC ETF flows\./g, "Confidence adjusts to the availability and quality of sector rotation, VIX, and BTC ETF flow data."],
  [/Rotación mixta; no domina una lectura defensiva extrema\./g, "Mixed rotation; no extreme defensive reading dominates."],
  [/Mixed flows aportan lectura neutral\./g, "Mixed flows add a neutral read."],
  [/Flujos mixtos aportan lectura neutral\./g, "Mixed flows add a neutral read."],
  [/VIX subiendo rápido; aumenta la cautela\./g, "VIX is rising fast; caution increases."],
  [/Racha BTC ETF/g, "BTC ETF streak"],
  [/Datos automáticos no disponibles temporalmente\. Mostrando datos demo para mantener la estructura visual\./g, "Automated data is temporarily unavailable. Demo data keeps the visual structure active."],
  [/Cálculos propios sobre ETFs sectoriales vía proveedor de precios/g, "Own calculations on sector ETF proxies via price provider"],
  [/Los modelos cuantitativos requieren historial suficiente\. Datos demo visibles mientras la fuente automatizada no esté disponible\. No implica dirección futura del mercado\./g, "Quantitative models require sufficient history. Demo data is visible while the automated source is unavailable. It does not predict market direction."],
  [/Los modelos cuantitativos requieren historial suficiente\. Demo data visibles mientras la fuente automática no está disponible\. No predicen dirección de mercado\./g, "Quantitative models require sufficient history. Demo data is visible while the automated source is unavailable. It does not predict market direction."],
  [/Volatilidad todavía moderada, pero moviéndose hacia zona de vigilancia\./g, "Volatility remains moderate, but is moving toward a watch zone."],
  [/Volatility todavía moderada, pero acercándose a watch zone\./g, "Volatility remains moderate, but is moving toward a watch zone."],
  [/Volatilidad todavía moderada, pero acercándose a zona de vigilancia\./g, "Volatility remains moderate, but is moving toward a watch zone."],
  [/Volatilidad acercándose a zona de tensión\./g, "Volatility is moving toward a tension zone."],
  [/Lectura compuesta basada en nivel absoluto, percentil histórico y momentum reciente\./g, "Composite read based on absolute level, historical percentile and recent momentum."],
  [/Composite read based on absolute level, historical percentile and recent momentum\. Niveles más altos suelen sugerir más tensión de volatilidad\./g, "Composite read based on absolute level, historical percentile and recent momentum. Higher levels usually suggest more volatility pressure."],
  [/Lectura compuesta basada en nivel absoluto, percentil histórico y momentum reciente\. Niveles más altos suelen sugerir más tensión de volatilidad\./g, "Composite read based on absolute level, historical percentile and recent momentum. Higher levels usually suggest more volatility pressure."],
  [/Un VIX alto no significa automáticamente caída futura del mercado\. Un VIX bajo tampoco elimina el riesgo\. Mide expectativas implícitas de volatilidad, no dirección ni retorno esperado\./g, "A high VIX does not automatically mean a future market decline. A low VIX does not remove risk either. It measures implied volatility expectations, not direction or expected return."],
  [/Último cierre disponible/g, "Latest available close"],
  [/Actualización diaria con último cierre disponible/g, "Daily update with the latest available close"],
  [/Dato diario de cierre publicado por FRED\. Puede tener rezago, revisiones u observaciones faltantes; no es cotización intradía\./g, "Daily closing data published by FRED. It may lag, be revised, or have missing observations; it is not an intraday quote."],
  [/Dato diario de cierre publicado por FRED\. Puede tener retraso, revisiones o días sin observación; no representa cotización intradía\./g, "Daily closing data published by FRED. It may lag, be revised, or have missing observations; it is not an intraday quote."],
  [/Lectura aproximada basada en flujos netos diarios y acumulados recientes\. Ventanas positivas sugieren demanda vía ETF; ventanas negativas sugieren reducción de exposición vía ETF\./g, "Approximate read based on daily net flows and recent cumulative flows. Positive windows suggest ETF demand; negative windows suggest reduced ETF exposure."],
  [/Lectura aproximada basada en flujos netos diarios y acumulados recientes\. Ventanas positivas sugieren demanda vía ETFs; ventanas negativas sugieren reducción de exposición vía ETFs\./g, "Approximate read based on daily net flows and recent cumulative flows. Positive windows suggest ETF demand; negative windows suggest reduced ETF exposure."],
  [/ventanas positivas/gi, "positive windows"],
  [/ventanas negativas/gi, "negative windows"],
  [/flujos netos diarios/gi, "daily net flows"],
  [/acumulados recientes/gi, "recent cumulative flows"],
  [/demanda vía ETF/gi, "ETF demand"],
  [/reducción de exposición vía ETF/gi, "reduced ETF exposure"],
  [/con entrada/gi, "with inflow"],
  [/con salida/gi, "with outflow"],
  [/sin dato o sin cambio/gi, "flat or missing"],
  [/Pendiente de fuente/g, "Source pending"],
  [/No disponible/g, "Unavailable"],
  [/No identificado/g, "Unidentified"],
  [/Baja \/ dispersa/g, "Low / dispersed"],
  [/Ejemplo educativo/g, "Educational example"],
  [/Estructura educativa/g, "Educational structure"],
  [/Diaria \/ según disponibilidad de la fuente/g, "Daily / depending on source availability"],
  [/según disponibilidad de la fuente/gi, "depending on source availability"],
  [/ETF amplio con tenencia institucional reportada vía 13F/g, "Broad ETF with institutional holdings reported through 13F filings"],
  [/ETF amplio con exposición growth\/tecnología reportada con retraso/g, "Broad ETF with growth/technology exposure reported with a delay"],
  [/Datos parciales vía informes institucionales con retraso/g, "Partial data through delayed institutional reports"],
  [/ETF de oro con presencia reportada en formularios 13F/g, "Gold ETF with reported presence in 13F filings"],
  [/Defensivos lideran mientras growth\/cíclicos quedan débiles\./g, "Defensives lead while growth/cyclical sectors remain weak."],
  [/Defensivos lideran mientras growth\/cíclicos quedan débiles/g, "Defensives lead while growth/cyclical sectors remain weak"],
  [/Defensivos lideran mientras growth\/cíclicos quedan rezagados\.?/g, "Defensives lead while growth/cyclical sectors lag."],
  [/Datos automáticos no disponibles temporalmente\. Datos demo mantienen activa la estructura visual\./g, "Automated data temporarily unavailable. Demo data keeps the visual structure active."],
  [/Racha de (\d+) días de salidas/g, "$1-day outflow streak"],
  [/No hay una dirección dominante clara en los flujos recientes\./g, "Recent flows do not show a clear dominant direction."],
  [/Volatilidad implícita pendiente de actualización\./g, "Implied volatility pending update."],
  [/En rango habitual/g, "Normal range"],
  [/Referencia amplia de mercado; lectura contextual, no señal operativa\./g, "Broad market reference; contextual reading, not an execution signal."],
  [/Punto de partida para observar concentración temática y exposición institucional diferida\./g, "Starting point to observe thematic concentration and delayed institutional exposure."],
  [/Lectura parcial de exposición vía ETF spot de Bitcoin; no implica dirección de precio\./g, "Partial exposure read through a spot Bitcoin ETF; it does not imply price direction."],
  [/Los contratos más largos cotizan por encima[^.]*\./g, "Longer contracts trade above the near-term contract. This is a common structure in calmer volatility regimes."],
  [/Settlements diarios oficiales de Cboe CFE\. La curva muestra hasta los nueve primeros contratos mensuales VX no vencidos y excluye contratos semanales\./g, "Official daily Cboe CFE settlements. The curve shows up to the first nine unexpired monthly VX contracts and excludes weekly contracts."],
  [/La lectura sugiere una rotación mixta\.?/g, "The reading suggests mixed rotation."],
  [/Volatilidad: vigilancia: zona de vigilancia\.?/gi, "Volatility: watch zone."],
  [/Momentum VIX: VIX subiendo rápido; aumenta la cautela\.?/gi, "VIX momentum: VIX rising fast; caution increases."],
  [/Curva VIX: Fuerte contango/g, "VIX curve: strong contango"],
  [/Flujos BTC ETF: Flujos mixtos/g, "BTC ETF flows: mixed flows"],
  [/BTC ETF flows: Flujos mixtos aportan lectura neutral\./g, "BTC ETF flows: mixed flows add a neutral read."],
  [/Rotación: Rotación mixta; no domina una lectura defensiva extrema\./g, "Rotation: mixed rotation; no extreme defensive reading dominates."],
  [/Dispersión 1W de ([\d.,]+)%; reduce la confianza del régimen\./g, "1W dispersion of $1%; lowers confidence in the regime."],
  [/Dispersión sectorial/g, "Sector dispersion"],
  [/Cautela/g, "Caution"],
  [/Neutral \/ mixto/g, "Neutral / mixed"],
  [/Estrés/g, "Stress"],
  [/Expansivo/g, "Expansion"],
  [/Defensivo/g, "Defensive"],
  [/Vigilancia/g, "Watch"],
  [/zona de vigilancia/gi, "watch zone"],
  [/Rotación sectorial/g, "Sector rotation"],
  [/Rotación mixta/g, "Mixed rotation"],
  [/rotación mixta/gi, "mixed rotation"],
  [/Rotación/g, "Rotation"],
  [/Volatilidad/g, "Volatility"],
  [/Curva VIX/g, "VIX curve"],
  [/Flujos BTC ETF/g, "BTC ETF flows"],
  [/Flujos mixtos/g, "Mixed flows"],
  [/Fuerte contango/g, "Strong contango"],
  [/No implica dirección futura del mercado\./g, "It does not imply future market direction."],
  [/Datos automatizados/g, "Automated data"],
  [/Datos disponibles · actualización según fuente/g, "Data available · source-based update"],
  [/Datos demo/g, "Demo data"],
  [/Datos manuales/g, "Manual data"],
  [/Actualización manual/g, "Manual update"],
  [/Actualización pendiente/g, "Update pending"],
  [/Pendiente de automatización/g, "Automation pending"],
  [/Ponderación actual/g, "Current weighting"],
  [/ponderación actual/g, "current weighting"],
  [/Confianza/g, "Confidence"],
  [/Sesgo/g, "Bias"],
  [/Régimen actual/g, "Current regime"],
  [/Tecnología/g, "Technology"],
  [/Salud/g, "Health Care"],
  [/Energía/g, "Energy"],
  [/Financieras/g, "Financials"],
  [/Industriales/g, "Industrials"],
  [/Materiales/g, "Materials"],
  [/Inmobiliario/g, "Real Estate"],
  [/Comunicación/g, "Communication Services"],
  [/Consumo básico\/defensivo/g, "Consumer Staples / defensive"],
  [/Consumo discrecional/g, "Consumer Discretionary"],
  [/Defensivos/g, "Defensives"],
  [/Semana/g, "Week"],
  [/semana/g, "week"],
  [/Subiendo rápido/g, "Rising fast"],
  [/Subiendo/g, "Rising"],
  [/Bajando/g, "Falling"],
  [/Estable/g, "Stable"],
  [/Pendiente/g, "Pending"],
  [/Racha pendiente/g, "Streak pending"],
  [/Último cierre/g, "Latest close"],
  [/Dato pendiente/g, "Pending data"],
  [/Fuente temporalmente no disponible/g, "Source temporarily unavailable"],
  [/historial insuficiente/gi, "not enough history"],
  [/Fragilidad/g, "Fragility"],
  [/fragilidad/g, "fragility"],
  [/Baja/g, "Low"],
  [/Media/g, "Medium"],
  [/Alta/g, "High"],
  [/Alerta/g, "Alert"],
  [/Normal/g, "Normal"],
  [/Mixto/g, "Mixed"],
  [/sin entradas positivas/gi, "no positive inflows"],
  [/sin salidas negativas/gi, "no negative outflows"],
  [/entrada fuerte/gi, "strong inflow"],
  [/entrada moderada/gi, "moderate inflow"],
  [/salida moderada/gi, "moderate outflow"],
  [/salida fuerte/gi, "strong outflow"],
  [/salidas/gi, "outflows"],
  [/entradas/gi, "inflows"],
  [/outflows moderadas/gi, "moderate outflows"],
  [/inflows moderadas/gi, "moderate inflows"],
  [/presión de outflows/gi, "outflow pressure"],
  [/datos pendientes/gi, "pending data"],
  [/acumulación sostenida/gi, "sustained accumulation"],
  [/entradas moderadas/gi, "moderate inflows"],
  [/salidas moderadas/gi, "moderate outflows"],
  [/presión de salidas/gi, "outflow pressure"],
  [/positivo/gi, "positive"],
  [/negativo/gi, "negative"],
];

export function translateDashboardText(value: string | null | undefined) {
  if (!value) return value ?? "";
  return phraseMap.reduce((text, [pattern, replacement]) => text.replace(pattern, replacement), value);
}

export function translateRegimeLabel(value: string) {
  return translateDashboardText(value);
}

export function translateBiasLabel(value: RegimeBias) {
  const labels: Record<RegimeBias, string> = {
    favorable: "Favorable",
    neutral: "Neutral",
    cautious: "Cautious",
    stress: "Stress",
  };
  return labels[value];
}

export function translateDataStatusLabel(label: string | DataStatus) {
  return translateDashboardText(label);
}
