import type { DataStatus, RegimeBias } from "@/lib/dashboard/types";

const phraseMap: Array<[RegExp, string]> = [
  [/Lectura compuesta no disponible: falta el pilar gobernado de rotación sectorial\. No se renormalizan los pesos restantes\./g, "Composite read unavailable: the governed sector-rotation pillar is missing. Remaining weights are not renormalized."],
  [/Pilar sectorial temporalmente no disponible; score y confianza quedan sin calcular\./g, "The sector pillar is temporarily unavailable; score and confidence remain uncalculated."],
  [/Incompleto/g, "Incomplete"],
  [/Pendiente de un snapshot sectorial real y completo/g, "Waiting for a complete real sector snapshot"],
  [/Fuente sectorial temporalmente no disponible/g, "Sector source temporarily unavailable"],
  [/Los modelos no se calculan sin historiales sectoriales reales y completos\./g, "Models are not calculated without complete real sector histories."],
  [/Automático con fuente pública: ([\d-]+)/g, "Automated from public source: $1"],
  [/Alpha Vantage: precios diarios de ETFs sectoriales/g, "Alpha Vantage: daily sector ETF prices"],
  [/ETFs sectoriales como proxies/g, "Sector ETFs used as proxies"],
  [/No es una recomendación de inversión, no elige activos y no anticipa retornos futuros\./g, "It is not investment advice, does not select assets, and does not forecast future returns."],
  [/Lectura compuesta de volatilidad, rotación y flujos\./g, "Composite read of volatility, rotation, and flows."],
  [/presión de volatilidad contenida\./g, "contained volatility pressure."],
  [/Entradas sostenidas favorecen apetito por riesgo cripto\/institucional\./g, "Sustained inflows support crypto and institutional risk appetite."],
  [/Sectores growth\/cíclicos lideran y defensivos quedan rezagados\./g, "Growth/cyclical sectors lead while defensives lag."],
  [/(\d{1,2}) de ene de (\d{4})/gi, "Jan $1, $2"],
  [/(\d{1,2}) de feb de (\d{4})/gi, "Feb $1, $2"],
  [/(\d{1,2}) de mar de (\d{4})/gi, "Mar $1, $2"],
  [/(\d{1,2}) de abr de (\d{4})/gi, "Apr $1, $2"],
  [/(\d{1,2}) de may de (\d{4})/gi, "May $1, $2"],
  [/(\d{1,2}) de jun de (\d{4})/gi, "Jun $1, $2"],
  [/(\d{1,2}) de jul de (\d{4})/gi, "Jul $1, $2"],
  [/(\d{1,2}) de ago de (\d{4})/gi, "Aug $1, $2"],
  [/(\d{1,2}) de sep de (\d{4})/gi, "Sep $1, $2"],
  [/(\d{1,2}) de oct de (\d{4})/gi, "Oct $1, $2"],
  [/(\d{1,2}) de nov de (\d{4})/gi, "Nov $1, $2"],
  [/(\d{1,2}) de dic de (\d{4})/gi, "Dec $1, $2"],
  [/Automática server-side con caché diaria; revisión periódica sugerida/g, "Automated server-side with a daily cache; periodic review recommended"],
  [/Automática server-side con caché diaria cuando exista fuente disponible/g, "Automated server-side with a daily cache when a source is available"],
  [/La rotación se estima mediante ETFs sectoriales líquidos como proxies\. Puede diferir de índices o grupos sectoriales de otros proveedores\./g, "Rotation is estimated through liquid sector ETFs used as proxies. It may differ from sector indexes or groups from other providers."],
  [/La lectura cuantitativa muestra fragilidad baja\. Estos modelos estiman condiciones estadísticas de riesgo bajo supuestos históricos; no implican dirección futura del mercado\./g, "The quantitative reading shows low fragility. These models estimate statistical risk conditions under historical assumptions; they do not imply future market direction."],
  [/La lectura cuantitativa muestra fragilidad media\. Estos modelos estiman condiciones estadísticas de riesgo bajo supuestos históricos; no implican dirección futura del mercado\./g, "The quantitative reading shows medium fragility. These models estimate statistical risk conditions under historical assumptions; they do not imply future market direction."],
  [/La lectura cuantitativa muestra fragilidad alta\. Estos modelos estiman condiciones estadísticas de riesgo bajo supuestos históricos; no implican dirección futura del mercado\./g, "The quantitative reading shows high fragility. These models estimate statistical risk conditions under historical assumptions; they do not imply future market direction."],
  [/Los modelos cuantitativos son sensibles a ventanas, supuestos y calidad de datos\. No predicen dirección de mercado\./g, "Quantitative models are sensitive to windows, assumptions, and data quality. They do not predict market direction."],
  [/La fuente aún no ha publicado o completado la actualización diaria\./g, "The source has not yet published or completed its daily update."],
  [/La ventana reciente muestra demanda neta positiva; historial insuficiente para 20D\./g, "The recent window shows positive net demand; there is not enough history for the 20D reading."],
  [/Los ETFs spot de Bitcoin muestran demanda neta positiva en la ventana reciente\./g, "Spot Bitcoin ETFs show positive net demand in the recent window."],
  [/La ventana reciente mantiene demanda neta positiva vía ETFs\./g, "The recent window maintains positive net demand through ETFs."],
  [/La ventana reciente muestra reducción neta de exposición; historial insuficiente para 20D\./g, "The recent window shows a net reduction in exposure; there is not enough history for the 20D reading."],
  [/Los flujos recientes muestran reducción neta de exposición vía ETFs\./g, "Recent flows show a net reduction in exposure through ETFs."],
  [/Entradas sostenidas/g, "Sustained inflows"],
  [/Sin racha clara/g, "No clear streak"],
  [/Racha de (\d+) días de entradas/g, "$1-day inflow streak"],
  [/Racha de entradas/g, "Inflow streak"],
  [/Racha de salidas/g, "Outflow streak"],
  [/Sin aportante dominante/g, "No dominant contributor"],
  [/Datos obtenidos desde tabla pública de Bitbo\. El historial visible puede estar limitado a las filas publicadas en la página\./g, "Data obtained from Bitbo's public table. Visible history may be limited to the rows published on the page."],
  [/Fallback experimental sobre tabla pública de Farside Investors\. La fuente puede bloquear solicitudes server-side o cambiar estructura\./g, "Experimental fallback using Farside Investors' public table. The source may block server-side requests or change its structure."],
  [/Datos automáticos no disponibles temporalmente\. Mostrando lectura demo para mantener la estructura visual\./g, "Automated data is temporarily unavailable. A demo reading keeps the visual structure active."],
  [/Detalle técnico disponible solo en logs server-side\./g, "Technical detail is available only in server-side logs."],
  [/Flujos netos hacia o desde ETFs spot de Bitcoin de EE\. UU\. como proxy de demanda vía vehículos regulados\./g, "Net flows into or out of US spot Bitcoin ETFs as a proxy for demand through regulated vehicles."],
  [/Ayuda a observar presión de flujos y absorción institucional separada del movimiento diario del precio spot\./g, "It helps observe flow pressure and institutional absorption separately from the daily spot-price move."],
  [/Entradas netas no garantizan subidas del precio de Bitcoin\. Salidas netas tampoco implican caídas futuras\. Los flujos son una pieza de contexto junto con precio, liquidez, volatilidad y régimen macro\./g, "Net inflows do not guarantee a rise in Bitcoin's price. Net outflows do not imply future declines either. Flows are one piece of context alongside price, liquidity, volatility, and the macro regime."],
  [/Lectura excepcionalmente elevada de volatilidad implícita\./g, "Exceptionally high implied-volatility reading."],
  [/Volatilidad implícita alta, normalmente asociada a mayor demanda de protección\./g, "High implied volatility, usually associated with greater demand for protection."],
  [/Presión de volatilidad elevada frente a condiciones normales\./g, "Elevated volatility pressure relative to normal conditions."],
  [/La volatilidad entra en una zona donde suele aumentar la sensibilidad del mercado\./g, "Volatility is entering a range where market sensitivity often increases."],
  [/Entorno de volatilidad contenido\./g, "Contained volatility environment."],
  [/Cálculo propio con datos diarios de NAV, participaciones y activos netos publicados por State Street\. No representa flujos oficiales reportados por el fondo\./g, "Own calculation using daily NAV, shares outstanding, and net assets published by State Street. It does not represent official flows reported by the fund."],
  [/Proxy de presión de flujos: prioriza cambios en participaciones en circulación\. NAV y activos netos se usan solo como control de coherencia; no se interpreta el cambio de AUM como flujo\./g, "Flow-pressure proxy: it prioritizes changes in shares outstanding. NAV and net assets are used only as consistency checks; changes in AUM are not interpreted as flows."],
  [/El mercado muestra deterioro en varias lecturas, pero todavía no hay confirmación suficiente para clasificarlo como estrés\./g, "The market shows deterioration across several readings, but there is not enough confirmation to classify it as stress."],
  [/El mercado muestra deterioro en varias lecturas[^.]*estrés\./g, "The market shows deterioration across several readings, but there is not enough confirmation to classify it as stress."],
  [/Ponderación actual: rotación sectorial 45%, VIX 40% y BTC ETF flows 15%\./g, "Current weighting: sector rotation 45%, VIX 40%, and BTC ETF flows 15%."],
  [/Última actualización disponible por módulo/g, "Latest available update by module"],
  [/Última actualización disponible:/g, "Latest available update:"],
  [/Este régimen no anticipa el mercado\. Organiza lecturas de volatilidad, rotación y flujos para leer el contexto\./g, "This regime does not predict the market. It organizes volatility, rotation, and flow readings to interpret the current context."],
  [/La confianza se ajusta según la disponibilidad y calidad de rotación sectorial, VIX y BTC ETF flows\./g, "Confidence adjusts to the availability and quality of sector rotation, VIX, and BTC ETF flow data."],
  [/Rotación mixta; no domina una lectura defensiva extrema\./g, "Mixed rotation; no extreme defensive reading dominates."],
  [/Mixed flows aportan lectura neutral\./g, "Mixed flows add a neutral read."],
  [/Flujos mixtos aportan lectura neutral\./g, "Mixed flows add a neutral read."],
  [/VIX subiendo rápido; aumenta la cautela\./g, "VIX is rising fast; caution increases."],
  [/Racha BTC ETF/g, "BTC ETF streak"],
  [/Datos automáticos no disponibles temporalmente\. Mostrando datos demo para mantener la estructura visual\./g, "Automated data is temporarily unavailable. Demo data keeps the visual structure active."],
  [/Cálculos propios sobre ETFs sectoriales vía proveedor de precios/g, "Own calculations on sector ETF proxies via price provider"],
  [/Los modelos cuantitativos requieren historial suficiente\. Datos demo visibles mientras la fuente automatizada no esté disponible\. No implica dirección futura del mercado\./g, "Quantitative models require sufficient history. Demo data is visible while the automated source is unavailable. It does not predict market direction."],
  [/Los modelos cuantitativos requieren historial suficiente\. Demo data visibles mientras la fuente automática no está disponible\. No predicen dirección de mercado\./g, "Quantitative models require sufficient history. Demo data is visible while the automated source is unavailable. It does not predict market direction."],
  [/Volatilidad todavía moderada, pero moviéndose hacia zona de vigilancia\./g, "Volatility remains moderate, but is moving toward a watch zone."],
  [/Volatility todavía moderada, pero acercándose a watch zone\./g, "Volatility remains moderate, but is moving toward a watch zone."],
  [/Volatilidad todavía moderada, pero acercándose a zona de vigilancia\./g, "Volatility remains moderate, but is moving toward a watch zone."],
  [/Volatilidad acercándose a zona de tensión\./g, "Volatility is moving toward a tension zone."],
  [/Lectura compuesta basada en nivel absoluto, percentil histórico y momentum reciente\./g, "Composite read based on absolute level, historical percentile and recent momentum."],
  [/Composite read based on absolute level, historical percentile and recent momentum\. Niveles más altos suelen sugerir más tensión de volatilidad\./g, "Composite read based on absolute level, historical percentile and recent momentum. Higher levels usually suggest more volatility pressure."],
  [/Lectura compuesta basada en nivel absoluto, percentil histórico y momentum reciente\. Niveles más altos suelen sugerir más tensión de volatilidad\./g, "Composite read based on absolute level, historical percentile and recent momentum. Higher levels usually suggest more volatility pressure."],
  [/Un VIX alto no significa automáticamente caída futura del mercado\. Un VIX bajo tampoco elimina el riesgo\. Mide expectativas implícitas de volatilidad, no dirección ni retorno esperado\./g, "A high VIX does not automatically mean a future market decline. A low VIX does not remove risk either. It measures implied volatility expectations, not direction or expected return."],
  [/Datos temporalmente no disponibles\. La lectura se reanudará cuando FRED publique un historial válido\./g, "Data is temporarily unavailable. The reading will resume when FRED publishes a valid history."],
  [/Datos temporalmente no disponibles\./g, "Data is temporarily unavailable."],
  [/Datos temporalmente no disponibles/g, "Data temporarily unavailable"],
  [/Datos con retraso/g, "Delayed data"],
  [/Sin observación válida disponible/g, "No valid observation available"],
  [/Diaria · último cierre disponible/g, "Daily · latest available close"],
  [/La fuente oficial no devolvió un historial válido\. No se sustituyen valores, métricas ni gráficos con datos fabricados\./g, "The official source did not return a valid history. Values, metrics, and charts are not replaced with fabricated data."],
  [/Último cierre oficial preservado, pero la observación tiene más de siete días naturales\. No representa una cotización intradía\./g, "The latest official close is preserved, but the observation is more than seven calendar days old. It is not an intraday quote."],
  [/La lectura permanece no disponible mientras no exista un historial oficial válido\./g, "The reading remains unavailable until a valid official history is available."],
  [/La ausencia temporal del dato no permite inferir un nivel, tendencia o dirección de mercado\./g, "A temporary lack of data does not support inferring a level, trend, or market direction."],
  [/Estrés extremo/g, "Extreme stress"],
  [/Normal alto/g, "High-normal"],
  [/Normal bajo/g, "Low-normal"],
  [/Complacencia/g, "Complacency"],
  [/Tensión/g, "Elevated"],
  [/Extremo frente a su historia/g, "Extreme relative to history"],
  [/Alto frente a su historia/g, "High relative to history"],
  [/Por encima de lo habitual/g, "Above its usual range"],
  [/Bajo frente a su historia reciente/g, "Low relative to recent history"],
  [/Presión de volatilidad contenida\./g, "Contained volatility pressure."],
  [/Volatilidad implícita muy contenida\./g, "Very contained implied volatility."],
  [/Cerca de zona de vigilancia\./g, "Near the watch zone."],
  [/Volatilidad en zona de mayor sensibilidad\./g, "Volatility is in a more sensitive range."],
  [/Presión de volatilidad en aumento\./g, "Volatility pressure is increasing."],
  [/Último cierre disponible/g, "Latest available close"],
  [/Actualización diaria con último cierre disponible/g, "Daily update with the latest available close"],
  [/Dato diario de cierre publicado por FRED\. Puede tener rezago, revisiones u observaciones faltantes; no es cotización intradía\./g, "Daily closing data published by FRED. It may lag, be revised, or have missing observations; it is not an intraday quote."],
  [/Dato diario de cierre publicado por FRED\. Puede tener retraso, revisiones o días sin observación; no representa cotización intradía\./g, "Daily closing data published by FRED. It may lag, be revised, or have missing observations; it is not an intraday quote."],
  [/Lectura aproximada basada en flujos netos diarios y acumulados recientes\. Ventanas positivas sugieren demanda vía ETF; ventanas negativas sugieren reducción de exposición vía ETF\./g, "Approximate read based on daily net flows and recent cumulative flows. Positive windows suggest ETF demand; negative windows suggest reduced ETF exposure."],
  [/Lectura aproximada basada en flujos netos diarios y acumulados recientes\. Ventanas positivas sugieren demanda vía ETFs; ventanas negativas sugieren reducción de exposición vía ETFs\./g, "Approximate read based on daily net flows and recent cumulative flows. Positive windows suggest ETF demand; negative windows suggest reduced ETF exposure."],
  [/ventanas positivas/gi, "positive windows"],
  [/ventanas negativas/gi, "negative windows"],
  [/flujos netos diarios/gi, "daily net flows"],
  [/acumulados recientes/gi, "recent cumulative flows"],
  [/demanda vía ETF/gi, "ETF demand"],
  [/reducción de exposición vía ETF/gi, "reduced ETF exposure"],
  [/con entrada/gi, "with inflow"],
  [/con salida/gi, "with outflow"],
  [/sin dato o sin cambio/gi, "flat or missing"],
  [/Pendiente de fuente/g, "Source pending"],
  [/No disponible/g, "Unavailable"],
  [/No identificado/g, "Unidentified"],
  [/Baja \/ dispersa/g, "Low / dispersed"],
  [/Ejemplo educativo/g, "Educational example"],
  [/Estructura educativa/g, "Educational structure"],
  [/Diaria \/ según disponibilidad de la fuente/g, "Daily / depending on source availability"],
  [/según disponibilidad de la fuente/gi, "depending on source availability"],
  [/ETF amplio con tenencia institucional reportada vía 13F/g, "Broad ETF with institutional holdings reported through 13F filings"],
  [/ETF amplio con exposición growth\/tecnología reportada con retraso/g, "Broad ETF with growth/technology exposure reported with a delay"],
  [/Datos parciales vía informes institucionales con retraso/g, "Partial data through delayed institutional reports"],
  [/ETF de oro con presencia reportada en formularios 13F/g, "Gold ETF with reported presence in 13F filings"],
  [/Defensivos lideran mientras growth\/cíclicos quedan débiles\./g, "Defensives lead while growth/cyclical sectors remain weak."],
  [/Defensivos lideran mientras growth\/cíclicos quedan débiles/g, "Defensives lead while growth/cyclical sectors remain weak"],
  [/Defensivos lideran mientras growth\/cíclicos quedan rezagados\.?/g, "Defensives lead while growth/cyclical sectors lag."],
  [/Datos automáticos no disponibles temporalmente\. Datos demo mantienen activa la estructura visual\./g, "Automated data temporarily unavailable. Demo data keeps the visual structure active."],
  [/Racha de (\d+) días de salidas/g, "$1-day outflow streak"],
  [/No hay una dirección dominante clara en los flujos recientes\./g, "Recent flows do not show a clear dominant direction."],
  [/Volatilidad implícita pendiente de actualización\./g, "Implied volatility pending update."],
  [/En rango habitual/g, "Normal range"],
  [/Referencia amplia de mercado; lectura contextual, no señal operativa\./g, "Broad market reference; contextual reading, not an execution signal."],
  [/Punto de partida para observar concentración temática y exposición institucional diferida\./g, "Starting point to observe thematic concentration and delayed institutional exposure."],
  [/Lectura parcial de exposición vía ETF spot de Bitcoin; no implica dirección de precio\./g, "Partial exposure read through a spot Bitcoin ETF; it does not imply price direction."],
  [/La estructura temporal del VIX no predice por sí sola la dirección del mercado y no representa una señal de compra o venta\./g, "The VIX term structure does not predict market direction on its own and is not a buy or sell signal."],
  [/Los contratos más largos cotizan por encima del vencimiento cercano\. Es una estructura habitual en entornos de volatilidad más ordenada\./g, "More distant expirations trade above the near contract. This is a common structure in calmer volatility regimes."],
  [/Settlements diarios oficiales de Cboe CFE\. La curva muestra hasta los nueve primeros contratos mensuales VX no vencidos y excluye contratos semanales\./g, "Official daily Cboe CFE settlements. The curve shows up to the first nine unexpired monthly VX contracts and excludes weekly contracts."],
  [/La lectura sugiere una rotación mixta\.?/g, "The reading suggests mixed rotation."],
  [/Volatilidad: vigilancia: zona de vigilancia\.?/gi, "Volatility: watch zone."],
  [/Momentum VIX: VIX subiendo rápido; aumenta la cautela\.?/gi, "VIX momentum: VIX rising fast; caution increases."],
  [/Curva VIX: Fuerte contango/g, "VIX curve: strong contango"],
  [/Flujos BTC ETF: Flujos mixtos/g, "BTC ETF flows: mixed flows"],
  [/BTC ETF flows: Flujos mixtos aportan lectura neutral\./g, "BTC ETF flows: mixed flows add a neutral read."],
  [/Rotación: Rotación mixta; no domina una lectura defensiva extrema\./g, "Rotation: mixed rotation; no extreme defensive reading dominates."],
  [/Dispersión 1W de ([\d.,]+)%; reduce la confianza del régimen\./g, "1W dispersion of $1%; lowers confidence in the regime."],
  [/Dispersión sectorial/g, "Sector dispersion"],
  [/Cautela/g, "Caution"],
  [/Neutral \/ mixto/g, "Neutral / mixed"],
  [/Estrés/g, "Stress"],
  [/Expansivo/g, "Expansion"],
  [/Defensivo/g, "Defensive"],
  [/Vigilancia/g, "Watch"],
  [/zona de vigilancia/gi, "watch zone"],
  [/Rotación sectorial/g, "Sector rotation"],
  [/Rotación mixta/g, "Mixed rotation"],
  [/rotación mixta/gi, "mixed rotation"],
  [/Rotación/g, "Rotation"],
  [/Volatilidad/g, "Volatility"],
  [/Curva VIX/g, "VIX curve"],
  [/Flujos BTC ETF/g, "BTC ETF flows"],
  [/Flujos mixtos/g, "Mixed flows"],
  [/Fuerte contango/g, "Strong contango"],
  [/No implica dirección futura del mercado\./g, "It does not imply future market direction."],
  [/Datos automatizados/g, "Automated data"],
  [/Datos disponibles · actualización según fuente/g, "Data available · source-based update"],
  [/Datos demo/g, "Demo data"],
  [/Datos manuales/g, "Manual data"],
  [/Actualización manual/g, "Manual update"],
  [/Actualización pendiente/g, "Update pending"],
  [/Pendiente de automatización/g, "Automation pending"],
  [/Ponderación actual/g, "Current weighting"],
  [/ponderación actual/g, "current weighting"],
  [/Confianza/g, "Confidence"],
  [/Sesgo/g, "Bias"],
  [/Régimen actual/g, "Current regime"],
  [/Tecnología/g, "Technology"],
  [/Salud/g, "Health Care"],
  [/Energía/g, "Energy"],
  [/Financieras/g, "Financials"],
  [/Industriales/g, "Industrials"],
  [/Materiales/g, "Materials"],
  [/Inmobiliario/g, "Real Estate"],
  [/Comunicación/g, "Communication Services"],
  [/Consumo básico\/defensivo/g, "Consumer Staples / defensive"],
  [/Consumo discrecional/g, "Consumer Discretionary"],
  [/Defensivos/g, "Defensives"],
  [/Semana/g, "Week"],
  [/semana/g, "week"],
  [/Subiendo rápido/g, "Rising fast"],
  [/Subiendo/g, "Rising"],
  [/Bajando/g, "Falling"],
  [/Estable/g, "Stable"],
  [/Pendiente/g, "Pending"],
  [/Racha pendiente/g, "Streak pending"],
  [/Último cierre/g, "Latest close"],
  [/Dato pendiente/g, "Pending data"],
  [/Fuente temporalmente no disponible/g, "Source temporarily unavailable"],
  [/historial insuficiente/gi, "not enough history"],
  [/Fragilidad/g, "Fragility"],
  [/fragilidad/g, "fragility"],
  [/Baja/g, "Low"],
  [/Media/g, "Medium"],
  [/Alta/g, "High"],
  [/Alerta/g, "Alert"],
  [/Normal/g, "Normal"],
  [/Mixto/g, "Mixed"],
  [/sin entradas positivas/gi, "no positive inflows"],
  [/sin salidas negativas/gi, "no negative outflows"],
  [/entrada fuerte/gi, "strong inflow"],
  [/entrada moderada/gi, "moderate inflow"],
  [/salida moderada/gi, "moderate outflow"],
  [/salida fuerte/gi, "strong outflow"],
  [/salidas/gi, "outflows"],
  [/entradas/gi, "inflows"],
  [/outflows moderadas/gi, "moderate outflows"],
  [/inflows moderadas/gi, "moderate inflows"],
  [/presión de outflows/gi, "outflow pressure"],
  [/datos pendientes/gi, "pending data"],
  [/acumulación sostenida/gi, "sustained accumulation"],
  [/entradas moderadas/gi, "moderate inflows"],
  [/salidas moderadas/gi, "moderate outflows"],
  [/presión de salidas/gi, "outflow pressure"],
  [/positivo/gi, "positive"],
  [/negativo/gi, "negative"],
];

export function translateDashboardText(value: string | null | undefined) {
  if (!value) return value ?? "";
  return phraseMap.reduce((text, [pattern, replacement]) => text.replace(pattern, replacement), value);
}

export function translateRegimeLabel(value: string) {
  return translateDashboardText(value);
}

export function translateBiasLabel(value: RegimeBias) {
  const labels: Record<RegimeBias, string> = {
    favorable: "Favorable",
    neutral: "Neutral",
    cautious: "Cautious",
    stress: "Stress",
    unavailable: "Unavailable",
  };
  return labels[value];
}

export function translateDataStatusLabel(label: string | DataStatus) {
  return translateDashboardText(label);
}
