export type PracticeLocale = "es" | "en";
export type ControlLevel = "control" | "balance" | "exposure";

export type Decision = {
  title: string;
  description?: string;
  immediate: string;
  secondary: string;
  reading: string;
  review: string[];
  alert: string;
  learning: string;
  level: ControlLevel;
  tradeoff: { protect: string; sacrifice: string; depend: string };
};

export type PracticeCase = {
  slug: string;
  category: string;
  title: string;
  situation: string;
  facts: { label: string; value: string }[];
  metric: { title: string; rows: { label: string; value: string; status?: "known" | "expected" | "verified" | "incomplete" | "unknown" }[] };
  decisions: Decision[];
};

const es: PracticeCase[] = [
  {
    slug: "liquidez-deuda", category: "Liquidez y deuda", title: "Una oportunidad mientras pagas deuda cara",
    situation: "Tienes COP 25 millones ahorrados y COP 20 millones en deuda de tarjeta y libre inversión. Un conocido te muestra una inversión que podría rendir 15% anual. Tu flujo mensual está ajustado y actualmente solo tienes un mes de gastos como reserva.",
    facts: [
      { label: "Ahorro", value: "COP 25 millones" }, { label: "Deuda", value: "COP 20 millones" },
      { label: "Tasa promedio de la deuda", value: "27% E.A." }, { label: "Cuota mensual", value: "COP 1,1 millones" },
      { label: "Gastos esenciales", value: "COP 5 millones al mes" }, { label: "Fondo de emergencia", value: "Un mes" },
      { label: "Flujo libre mensual", value: "COP 600.000" }, { label: "Rendimiento mencionado", value: "15% esperado" },
      { label: "Salida de la inversión", value: "Hasta 90 días" },
    ],
    metric: { title: "Costo conocido frente a rendimiento esperado", rows: [
      { label: "Costo de la deuda", value: "27% E.A. conocido", status: "known" },
      { label: "Rendimiento mencionado", value: "15% E.A. esperado", status: "expected" },
      { label: "Diferencia nominal", value: "12 puntos" }, { label: "Disponibilidad del ahorro", value: "Inmediata" },
      { label: "Disponibilidad de inversión", value: "Hasta 90 días" },
    ] },
    decisions: [
      { title: "Pagar toda la deuda", immediate: "Eliminas un costo financiero alto y liberas la cuota mensual. Quedas con COP 5 millones, aproximadamente un mes de gastos esenciales.", secondary: "El flujo mejora, pero una emergencia grande puede obligarte a utilizar nuevamente crédito. El resultado depende de reconstruir la reserva antes de asumir nuevos compromisos.", reading: "Pagar deuda cara reduce un costo conocido. Sin embargo, utilizar casi toda la liquidez puede trasladar el problema desde los intereses hacia la falta de reserva.", review: ["Estabilidad de los ingresos", "Reserva mínima necesaria", "Condiciones de prepago", "Tiempo para reconstruir el fondo", "Riesgo de volver a endeudarse"], alert: "La deuda desaparece, pero la liquidez queda en el mínimo.", learning: "Una mejora del balance puede crear una vulnerabilidad temporal en el flujo.", level: "balance", tradeoff: { protect: "El flujo frente a intereses altos.", sacrifice: "Reserva para imprevistos.", depend: "Reconstruir el fondo sin usar nueva deuda." } },
      { title: "Invertir todo y seguir pagando", immediate: "Mantienes una deuda que cuesta 27% y expones el ahorro a una rentabilidad esperada de 15%. El dinero invertido no estaría disponible de inmediato.", secondary: "Un gasto inesperado podría obligarte a utilizar más crédito. Incluso si la inversión alcanza el resultado esperado, el costo de la deuda puede continuar siendo superior.", reading: "Las dos tasas no son directamente comparables. El interés de la deuda es contractual; el rendimiento de la inversión es incierto y puede incluir costos, impuestos o pérdidas.", review: ["Costo efectivo de la deuda", "Incertidumbre del rendimiento", "Liquidez del producto", "Fondo de emergencia", "Flujo mensual después de la cuota"], alert: "Se mantiene un costo alto para perseguir un resultado menor e incierto.", learning: "Una inversión no compensa necesariamente un flujo debilitado por deuda costosa.", level: "exposure", tradeoff: { protect: "Acceso a la oportunidad.", sacrifice: "Liquidez y reducción de deuda.", depend: "Que la inversión funcione y no aparezcan imprevistos." } },
      { title: "Reservar y amortizar lo más caro", description: "Mantienes COP 15 millones como reserva de tres meses y utilizas COP 10 millones para reducir primero la deuda de mayor tasa.", immediate: "No eliminas toda la deuda, pero reduces intereses y conservas capacidad para afrontar imprevistos.", secondary: "El flujo liberado puede utilizarse para terminar de pagar la deuda y después iniciar aportes de inversión. La oportunidad actual podría pasar.", reading: "La decisión no tiene que ser todo a deuda o todo a inversión. El orden de las acciones puede reducir la probabilidad de volver a endeudarse.", review: ["Tamaño adecuado de la reserva", "Orden de las deudas por tasa", "Flujo liberado", "Plazo para terminar de pagar", "Momento realista para comenzar a invertir"], alert: "El plan pierde efectividad si se toma nueva deuda mientras se ejecuta.", learning: "La capacidad sostenible de invertir comienza con liquidez suficiente y deuda controlada.", level: "control", tradeoff: { protect: "La reserva y parte del flujo.", sacrifice: "Inversión inmediata y eliminación total de la deuda.", depend: "Mantener el plan de pagos." } },
    ],
  },
  {
    slug: "producto-dudoso", category: "Producto dudoso", title: "24% anual, referidos y cupos limitados",
    situation: "Un conocido te invita a una comunidad privada de inversión. La propuesta ofrece 24% anual, pagos mensuales y un bono por invitar a otras personas. Te explican que no es necesario entender todos los detalles porque el equipo ya opera el dinero y quedan pocos cupos para entrar esta semana.",
    facts: [
      { label: "Rentabilidad ofrecida", value: "24% anual" }, { label: "Pago prometido", value: "Mensual" },
      { label: "Inversión mínima", value: "{money:20000}" }, { label: "Bono por referido directo", value: "3%" },
      { label: "Bonos por red/equipo", value: "Mencionados, sin fórmula clara" }, { label: "Retiro", value: "Solicitud con 60 días de anticipación" },
      { label: "Regulación", value: "No explicada" }, { label: "Custodia", value: "La misma empresa" },
      { label: "Documentación", value: "Presentación y contrato breve" }, { label: "Fuente del rendimiento", value: "“Operaciones internas”, sin detalle verificable" },
    ],
    metric: { title: "Radiografía de la oferta", rows: [
      { label: "Rentabilidad", value: "Prometida", status: "incomplete" }, { label: "Fuente del rendimiento", value: "Incompleta", status: "incomplete" },
      { label: "Custodia", value: "Sin separación", status: "incomplete" }, { label: "Salida", value: "Condicionada", status: "incomplete" },
      { label: "Incentivo por referidos", value: "Presente", status: "incomplete" }, { label: "Regulación", value: "No informada", status: "unknown" },
    ] },
    decisions: [
      { title: "Pedir documentos y verificar fuera del grupo", immediate: "El equipo entrega más material o evita algunas preguntas. El cupo puede cerrarse mientras contrastas la información fuera de la comunidad.", secondary: "Los documentos y testimonios del grupo no prueban por sí solos que la información sea completa o verificable. Todavía falta entender quién custodia el dinero y quién absorbe las pérdidas.", reading: "La documentación es necesaria, pero no equivale a verificación independiente. La comisión por referidos no vuelve malo un producto por sí sola, pero cambia los incentivos de quien lo recomienda.", review: ["Entidad legal y responsables", "Supervisión aplicable", "Estados financieros verificables", "Custodio independiente", "Fuente del rendimiento", "Escenario de incumplimiento"], alert: "La información debe poder comprobarse fuera del grupo y del material comercial.", learning: "Testimonios y documentos internos son un punto de partida, no una verificación independiente.", level: "balance", tradeoff: { protect: "Parte del proceso de análisis.", sacrifice: "Tiempo frente al supuesto cupo.", depend: "Contrastar la información con fuentes independientes." } },
      { title: "Entrar con el mínimo por recomendación", immediate: "Obtienes acceso, y quien te invitó puede recibir una comisión. El equipo puede comenzar a realizar los pagos prometidos.", secondary: "Los primeros pagos no demuestran que la fuente del rendimiento sea sostenible ni que el capital esté protegido. La recuperación depende de contratos, custodia y derechos de salida todavía poco claros.", reading: "Una relación personal puede reducir la sensación de riesgo, pero no cambia la estructura del producto. Los incentivos de la red conviene analizarlos junto con la fuente económica del rendimiento.", review: ["Fuente económica del rendimiento", "Custodia del dinero", "Regulación", "Derechos de salida", "Bonos de la red", "Evidencia independiente"], alert: "La recomendación y los pagos iniciales están sustituyendo parte de la verificación.", learning: "Conocer a quien recomienda no permite explicar dónde queda el dinero ni cómo se recupera.", level: "exposure", tradeoff: { protect: "Acceso al supuesto cupo.", sacrifice: "Control, liquidez y verificabilidad.", depend: "Promesas y pagos que todavía no prueban sostenibilidad." } },
      { title: "No transferir sin verificación independiente", immediate: "Puedes perder el cupo y un resultado que finalmente podría materializarse. El capital permanece disponible.", secondary: "Renuncias a una oportunidad posible, pero evitas asumir por ahora un riesgo cuya fuente de rendimiento, custodia y salida todavía no puedes medir.", reading: "No hace falta llegar a una conclusión legal sobre la oferta para decidir que la información disponible es insuficiente. “No puedo medir este riesgo” es una razón válida para no entrar.", review: ["Evidencia independiente", "Separación entre emisor y custodio", "Coherencia entre retorno, riesgo y liquidez", "Incentivos comerciales", "Procedimiento si se suspenden retiros", "Jurisdicción y mecanismo de reclamación"], alert: "La urgencia comercial beneficia principalmente a quien recibe el dinero.", learning: "Si no puedes explicar cómo se genera, custodia y devuelve el capital, todavía no puedes evaluar la propuesta.", level: "control", tradeoff: { protect: "Capital, liquidez y capacidad de verificación.", sacrifice: "Acceso inmediato.", depend: "Mantener el criterio aunque exista presión del grupo." } },
    ],
  },
  {
    slug: "finca-raiz", category: "Finca raíz", title: "¿Comprar porque la finca raíz nunca baja?",
    situation: "Tienes COP 280 millones ahorrados y estás considerando un apartamento de COP 600 millones. El vendedor afirma que conviene comprar pronto y que el inmueble prácticamente se pagará con el arriendo. Después de la compra, la mayor parte de tu patrimonio quedaría concentrada en esa propiedad.",
    facts: [
      { label: "Precio", value: "COP 600 millones" }, { label: "Cuota inicial", value: "COP 240 millones" },
      { label: "Crédito", value: "COP 360 millones" }, { label: "Cuota estimada", value: "COP 4,2 millones al mes" },
      { label: "Arriendo esperado", value: "COP 3,6 millones" }, { label: "Administración", value: "COP 450.000 al mes" },
      { label: "Vacancia estimada", value: "Un mes al año" }, { label: "Impuestos y mantenimiento", value: "COP 7 millones al año" },
      { label: "Liquidez restante", value: "COP 40 millones" }, { label: "Tiempo de venta estimado", value: "4–12 meses" },
    ],
    metric: { title: "Flujo mensual del inmueble", rows: [
      { label: "Arriendo esperado", value: "+ COP 3,6 M" }, { label: "Vacancia prorrateada", value: "− COP 0,3 M" },
      { label: "Administración", value: "− COP 0,45 M" }, { label: "Impuestos y mantenimiento", value: "− COP 0,58 M" },
      { label: "Cuota del crédito", value: "− COP 4,2 M" }, { label: "Aporte mensual requerido", value: "− COP 1,93 M" },
    ] },
    decisions: [
      { title: "Comprar ahora", immediate: "Obtienes el inmueble, pero el arriendo no cubre completamente la cuota, la administración, la vacancia y los demás costos. Tendrías que aportar alrededor de COP 1,9 millones mensuales en un escenario normal.", secondary: "Una reparación, varios meses sin inquilino o una reducción de ingresos puede obligarte a usar la reserva. Si necesitas recuperar el capital, vender puede tomar varios meses.", reading: "Un inmueble puede valorizarse y aun así generar un flujo débil. El arriendo bruto no representa lo que realmente queda después de financiación, vacancia, mantenimiento e impuestos.", review: ["Flujo neto mensual", "Capacidad para sostener una vacancia", "Liquidez después de comprar", "Concentración patrimonial", "Tiempo y costos de venta"], alert: "El inmueble no se paga solo con los datos disponibles.", learning: "El valor del activo y la capacidad para sostenerlo son dos preguntas distintas.", level: "exposure", tradeoff: { protect: "Acceso inmediato al inmueble.", sacrifice: "Liquidez y diversificación.", depend: "Ingresos estables, ocupación y valorización futura." } },
      { title: "Comprar con mayor reserva", immediate: "La compra tarda más o la financiación puede cambiar. A cambio, conservas recursos para cubrir vacancia, reparaciones y gastos personales.", secondary: "La reserva reduce la probabilidad de vender bajo presión, pero no corrige por sí sola un flujo mensual negativo. La concentración patrimonial continúa siendo alta.", reading: "Conservar liquidez mejora la resistencia de la compra. No determina si el precio, el crédito o el rendimiento neto son adecuados.", review: ["Cuántos meses cubre la reserva", "Costo de financiar un monto mayor", "Flujo neto después de todos los gastos", "Peso del inmueble en el patrimonio", "Condiciones de prepago"], alert: "Una reserva protege el flujo, pero no transforma una operación costosa en rentable.", learning: "Resolver la liquidez es necesario, pero el precio y la financiación siguen importando.", level: "balance", tradeoff: { protect: "Capacidad para absorber imprevistos.", sacrifice: "Velocidad o mejores condiciones de financiación.", depend: "Que el déficit mensual sea sostenible." } },
      { title: "Posponer y comparar", immediate: "Puedes perder esta propiedad o verla subir de precio. Conservas liquidez y capacidad de negociación.", secondary: "El análisis puede mostrar que la compra solo funciona con un precio menor, otra estructura de deuda o un arriendo superior. También puede confirmar que la compra resulta sostenible.", reading: "Esperar no garantiza un mejor resultado. Su utilidad consiste en no asumir una obligación grande antes de entender cómo se sostiene y cómo se puede deshacer.", review: ["Rentabilidad neta", "Escenario con vacancia prolongada", "Escenario de ingresos personales más bajos", "Costo de oportunidad del capital", "Plazo real de salida"], alert: "La urgencia del vendedor no determina tu plazo financiero.", learning: "Antes de preguntar cuánto puede subir, conviene calcular cuánto cuesta mantenerlo.", level: "control", tradeoff: { protect: "Liquidez y capacidad de comparación.", sacrifice: "Acceso inmediato al inmueble.", depend: "Usar la espera para analizar, no para aplazar indefinidamente." } },
    ],
  },
  {
    slug: "bolsa-etf", category: "Bolsa / ETF", title: "Entrar después de una gran subida",
    situation: "Un ETF de renta variable ha subido con fuerza durante el último año. Tienes COP 80 millones disponibles y te preocupa quedarte por fuera si continúa avanzando. Tu horizonte declarado es de cinco años, pero una caída grande podría hacerte reconsiderar la decisión.",
    facts: [
      { label: "Capital disponible", value: "COP 80 millones" }, { label: "Fondo de emergencia", value: "Separado" },
      { label: "Horizonte declarado", value: "5 años" }, { label: "Subida durante el último año", value: "28%" },
      { label: "Caída histórica ilustrativa", value: "−35%" }, { label: "Pérdida que dices tolerar", value: "−15%" },
      { label: "Exposición actual a bolsa", value: "Baja" }, { label: "Aportes futuros", value: "COP 2 millones al mes" },
      { label: "Contexto", value: "La caída histórica dimensiona volatilidad; no es un pronóstico" },
    ],
    metric: { title: "Impacto de una caída ilustrativa de 30%", rows: [
      { label: "Capital invertido", value: "COP 80 millones" }, { label: "Caída temporal", value: "COP 24 millones" },
      { label: "Valor restante", value: "COP 56 millones" }, { label: "Pérdida declarada como tolerable", value: "COP 12 millones" },
    ] },
    decisions: [
      { title: "Entrar gradualmente", immediate: "Una parte del capital comienza a participar y otra permanece disponible. Si el mercado continúa subiendo, no todo el dinero recibe esa subida.", secondary: "La estrategia solo funciona como control conductual si mantienes el calendario. Suspender compras durante una caída o acelerarlas después de otra subida convertiría el plan en improvisación.", reading: "Invertir gradualmente no garantiza un mejor precio. Puede ayudar a distribuir el momento de entrada y a comprobar cómo reaccionas ante movimientos reales.", review: ["Calendario y monto de los aportes", "Peso máximo del ETF", "Destino del efectivo pendiente", "Regla de rebalanceo", "Condiciones para suspender el plan"], alert: "Un plan gradual sin reglas puede terminar siguiendo las emociones del mercado.", learning: "El valor de una entrada gradual está en la disciplina, no en adivinar el precio más bajo.", level: "control", tradeoff: { protect: "El punto de entrada y la adaptación emocional.", sacrifice: "Participación completa si el mercado sigue subiendo.", depend: "Cumplir el calendario." } },
      { title: "Invertir todo ahora", immediate: "Obtienes exposición completa desde el primer día. Si el mercado continúa subiendo, todo el capital participa.", secondary: "Una caída de 30% reduciría temporalmente el valor en COP 24 millones. Esa pérdida supera los COP 12 millones correspondientes a la tolerancia declarada de 15%.", reading: "Invertir de una vez puede ser coherente con algunos planes. La fragilidad aparece cuando el tamaño de la posición no coincide con la capacidad real de mantenerla durante una caída.", review: ["Pérdida posible en pesos", "Peso dentro del patrimonio total", "Horizonte efectivo", "Necesidades de liquidez", "Reacción probable ante una caída"], alert: "La pérdida plausible supera la tolerancia que declaraste.", learning: "La tolerancia al riesgo se entiende mejor en dinero y comportamiento que en un porcentaje abstracto.", level: "exposure", tradeoff: { protect: "Participación inmediata.", sacrifice: "Margen para ajustar la entrada.", depend: "Mantener la posición durante una caída significativa." } },
      { title: "Esperar una corrección", immediate: "Evitas comprar después de una subida y conservas el capital líquido.", secondary: "La corrección puede no llegar o puede ocurrir desde un precio mucho más alto. Sin una valoración o fecha límite, esperar puede convertirse en una decisión indefinida.", reading: "“Comprar cuando baje” no es todavía un plan. Hace falta definir cuánto, bajo qué condiciones y qué ocurrirá si el mercado no ofrece ese precio.", review: ["Fundamento del nivel de entrada", "Plazo máximo de espera", "Uso del efectivo mientras esperas", "Alternativa si no ocurre la caída", "Diferencia entre valoración y miedo"], alert: "Esperar una cifra concreta sin un criterio adicional también es intentar anticipar el mercado.", learning: "No perseguir una subida puede ser prudente; depender de una caída futura puede ser incompleto.", level: "balance", tradeoff: { protect: "El capital frente a una entrada impulsiva.", sacrifice: "Exposición mientras esperas.", depend: "Que ocurra una caída específica." } },
    ],
  },
  {
    slug: "portafolio-familiar", category: "Portafolio familiar", title: "Muchos activos, una meta cercana",
    situation: "Formas parte de una familia que organiza un portafolio ilustrativo de {money:500000}. Una meta de {money:150000} podría necesitarse dentro de dos años. Algunos quieren proteger esa parte; otros quieren mantener la exposición al crecimiento.",
    facts: [
      { label: "Portafolio total", value: "{money:500000}" }, { label: "S&P 500", value: "25% — {money:125000}" },
      { label: "Economías emergentes", value: "10% — {money:50000}" }, { label: "Oro", value: "15% — {money:75000}" },
      { label: "BTC/ETH", value: "10% — {money:50000}" }, { label: "Bonos", value: "25% — {money:125000}" },
      { label: "REIT", value: "5% — {money:25000}" }, { label: "Efectivo", value: "10% — {money:50000}" },
      { label: "Necesidad probable en 24 meses", value: "{money:150000}" },
      { label: "Caída familiar declarada como tolerable", value: "18%" },
    ],
    metric: { title: "Activo vs función del dinero", rows: [
      { label: "Meta a 24 meses", value: "{money:150000}" }, { label: "Liquidez actual", value: "{money:50000}" },
      { label: "Bonos y activos defensivos", value: "{money:125000}" }, { label: "Capital expuesto a variación de mercado", value: "{money:450000}" },
      { label: "Lectura", value: "Una lista amplia de activos puede esconder una pregunta más simple: qué parte del dinero tiene una fecha de uso cercana." },
    ] },
    decisions: [
      { title: "Separar la meta y rebalancear", description: "La familia reserva {money:150000} en instrumentos líquidos acordes con el plazo y define límites para las demás posiciones.", immediate: "El dinero de la meta queda menos expuesto a una caída de mercado. Una parte del portafolio deja de participar plenamente en futuras subidas.", secondary: "El capital restante todavía puede fluctuar, pero la familia tiene menos probabilidad de vender activos volátiles para cumplir una necesidad prevista.", reading: "Reducir exposición no implica pronosticar una caída. Puede responder simplemente a que una parte del dinero cambió de función.", review: ["Monto y fecha de la meta", "Liquidez necesaria", "Riesgo del capital que permanece invertido", "Límites por activo", "Regla de rebalanceo"], alert: "Proteger una meta no significa que el resto del portafolio quede libre de riesgo.", learning: "El plazo de cada objetivo puede ser más importante que la rentabilidad reciente del portafolio.", level: "control", tradeoff: { protect: "La meta cercana.", sacrifice: "Potencial de crecimiento sobre el capital reservado.", depend: "Que la estimación de {money:150000} sea suficiente." } },
      { title: "Mantener la composición actual", immediate: "Evitas ventas y conservas la exposición que ha producido buenos resultados. El efectivo actual cubre solo una parte de la meta.", secondary: "Todavía faltan {money:100000} para completar la meta. Si los mercados caen cerca de la fecha de uso, la familia podría vender activos con pérdidas o aplazar la decisión.", reading: "Tener varios activos no garantiza que una meta cercana esté protegida. Durante momentos de estrés, posiciones diferentes pueden caer al mismo tiempo.", review: ["Capital líquido frente a la meta", "Correlación en periodos de caída", "Riesgo conjunto de bolsa y criptoactivos", "Flexibilidad de la fecha de uso", "Acuerdo familiar ante una pérdida"], alert: "La liquidez actual no cubre completamente la necesidad prevista.", learning: "La diversificación se mide por fuentes de riesgo y funciones, no solo por cantidad de activos.", level: "balance", tradeoff: { protect: "Continuidad del portafolio.", sacrifice: "Certeza sobre la meta cercana.", depend: "Mercados estables o flexibilidad para aplazar la decisión." } },
      { title: "Aumentar bolsa y cripto", description: "La familia usa parte del oro, bonos y efectivo para aumentar los activos con mayor expectativa de crecimiento.", immediate: "El portafolio gana exposición a los activos con mayor expectativa de crecimiento para la familia. La liquidez disponible disminuye.", secondary: "Una caída simultánea puede afectar tanto el patrimonio como la capacidad de cumplir la meta cercana. La familia puede terminar realizando pérdidas para cubrir una necesidad conocida.", reading: "Buscar más rentabilidad no es un objetivo suficiente. Debe acompañarse de un plazo, una pérdida tolerable y una definición de qué dinero no puede asumir ese riesgo.", review: ["Peso conjunto de activos volátiles", "Pérdida potencial en la moneda seleccionada", "Necesidades dentro de dos años", "Motivo para aumentar posiciones que han subido", "Consecuencias de vender bajo presión"], alert: "Se eleva el riesgo sin resolver primero la necesidad de liquidez.", learning: "Más potencial de crecimiento también amplía el rango de resultados posibles.", level: "exposure", tradeoff: { protect: "Participación en una posible subida.", sacrifice: "Liquidez y estabilidad de la meta.", depend: "Mercados favorables durante un plazo corto." } },
    ],
  },
];

const en: PracticeCase[] = es.map((item) => item); // Replaced below with adapted English content.

en[0] = {
  ...es[0], category: "Liquidity and debt", title: "An opportunity while carrying expensive debt",
  situation: "You have COP 25 million in savings and COP 20 million in credit-card and personal-loan debt. Someone you know presents an investment that may return 15% a year. Monthly cash flow is tight, and your reserve currently covers only one month of expenses.",
  facts: [{label:"Savings",value:"COP 25 million"},{label:"Debt",value:"COP 20 million"},{label:"Average debt rate",value:"27% E.A."},{label:"Monthly payment",value:"COP 1.1 million"},{label:"Essential spending",value:"COP 5 million a month"},{label:"Emergency fund",value:"One month"},{label:"Monthly free cash flow",value:"COP 600,000"},{label:"Stated return",value:"15% expected"},{label:"Investment exit",value:"Up to 90 days"}],
  metric: { title: "Known cost versus expected return", rows: [{label:"Debt cost",value:"27% E.A. known",status:"known"},{label:"Stated return",value:"15% E.A. expected",status:"expected"},{label:"Nominal gap",value:"12 points"},{label:"Savings availability",value:"Immediate"},{label:"Investment availability",value:"Up to 90 days"}] },
  decisions: [
    { title:"Pay off all debt", immediate:"You remove a high financing cost and free the monthly payment. COP 5 million remains—about one month of essential expenses.", secondary:"Cash flow improves, but a large emergency could force you to borrow again. The outcome depends on rebuilding the reserve before taking on new commitments.", reading:"Paying expensive debt removes a known cost. Using nearly all available cash, however, may shift the problem from interest expense to a thin reserve.", review:["Income stability","Minimum reserve needed","Prepayment terms","Time needed to rebuild the fund","Risk of borrowing again"], alert:"The debt disappears, but liquidity falls to the minimum.", learning:"A stronger balance sheet can create a temporary cash-flow vulnerability.", level:"balance", tradeoff:{protect:"Cash flow from high interest costs.",sacrifice:"Your emergency reserve.",depend:"Rebuilding the fund without new debt."}},
    { title:"Invest everything and keep paying", immediate:"You keep debt costing 27% while exposing savings to an expected 15% return. The invested money would not be immediately available.", secondary:"An unexpected expense could require more credit. Even if the investment meets expectations, the debt may continue to cost more.", reading:"The rates are not directly comparable. Debt interest is contractual; investment return is uncertain and may be reduced by fees, taxes, or losses.", review:["Effective debt cost","Return uncertainty","Product liquidity","Emergency fund","Cash flow after the payment"], alert:"A high known cost remains in pursuit of a lower, uncertain result.", learning:"An investment does not necessarily offset cash flow weakened by expensive debt.", level:"exposure", tradeoff:{protect:"Access to the opportunity.",sacrifice:"Liquidity and debt reduction.",depend:"The investment working and no surprises occurring."}},
    { title:"Keep a reserve and reduce the costliest debt", description:"You keep COP 15 million as a three-month reserve and use COP 10 million to reduce the highest-rate debt first.", immediate:"You do not remove all debt, but you lower interest expense and retain capacity for unexpected costs.", secondary:"Freed-up cash flow can finish paying the debt and later fund investments. The current opportunity may pass.", reading:"The choice need not be all debt or all investment. Sequencing can reduce the chance of having to borrow again.", review:["Appropriate reserve size","Debt order by rate","Cash flow released","Payoff timeline","A realistic point to begin investing"], alert:"The plan loses effectiveness if new debt is added while it is underway.", learning:"Sustainable investing capacity starts with adequate liquidity and controlled debt.", level:"control", tradeoff:{protect:"The reserve and part of cash flow.",sacrifice:"Immediate investing and full debt elimination.",depend:"Following the payment plan."}},
  ],
};

en[1] = {
  ...es[1], category:"Questionable product", title:"24% yearly return, referrals and limited spots",
  situation:"An acquaintance invites you to a private investment community. The offer mentions a 24% yearly return, monthly payments and a bonus for bringing in other people. You are told that you do not need to understand every detail because the team manages the money and only a few spots are available this week.",
  facts:[{label:"Offered return",value:"24% a year"},{label:"Promised payment",value:"Monthly"},{label:"Minimum investment",value:"{money:20000}"},{label:"Direct referral bonus",value:"3%"},{label:"Network/team bonuses",value:"Mentioned, with no clear formula"},{label:"Withdrawal",value:"60 days’ notice required"},{label:"Regulation",value:"Not explained"},{label:"Custody",value:"The same company receives the money"},{label:"Documents",value:"Presentation and short contract"},{label:"Source of return",value:"“Internal operations,” without verifiable detail"}],
  metric:{title:"Offer snapshot",rows:[{label:"Return",value:"Promised",status:"incomplete"},{label:"Source of return",value:"Incomplete",status:"incomplete"},{label:"Custody",value:"Not separated",status:"incomplete"},{label:"Exit",value:"Conditional",status:"incomplete"},{label:"Referral incentive",value:"Present",status:"incomplete"},{label:"Regulation",value:"Not disclosed",status:"unknown"}]},
  decisions:[
    {title:"Request documents and verify outside the group",immediate:"The team provides more material or avoids some questions. The opening may close while you check the information outside the community.",secondary:"Documents and group testimonials do not independently prove that the information is complete or verifiable. You still need to understand custody and who absorbs losses.",reading:"Documentation is necessary, but it is not independent verification. A referral commission does not automatically make a product bad, but it changes the incentives of the person recommending it.",review:["Legal entity and responsible parties","Applicable supervision","Verifiable financial statements","Independent custodian","Source of return","Default scenario"],alert:"The information must be verifiable outside the group and its sales material.",learning:"Internal documents and testimonials are a starting point, not independent verification.",level:"balance",tradeoff:{protect:"Part of the review process.",sacrifice:"Time against the claimed deadline.",depend:"Checking the information through independent sources."}},
    {title:"Enter with the minimum based on the referral",immediate:"You gain access, and the person who invited you may receive a commission. The team may begin making the promised payments.",secondary:"Early payments do not prove that the source of return is sustainable or the principal protected. Recovery depends on contracts, custody, and exit rights that remain unclear.",reading:"A personal relationship can lower the feeling of risk, but it does not change the product structure. Network incentives should be reviewed alongside the economic source of return.",review:["Economic source of return","Custody of funds","Regulation","Exit rights","Network bonuses","Independent evidence"],alert:"The recommendation and early payments are replacing part of the verification process.",learning:"Knowing the referrer does not explain where the money sits or how it can be recovered.",level:"exposure",tradeoff:{protect:"Access to the claimed opening.",sacrifice:"Control, liquidity, and verifiability.",depend:"Promises and payments that do not yet prove sustainability."}},
    {title:"Do not transfer without independent verification",immediate:"You may lose the opening and an outcome that could ultimately materialize. Your capital remains available.",secondary:"You give up a possible opportunity, but for now avoid a risk whose source of return, custody, and exit you still cannot measure.",reading:"You do not need to reach a legal conclusion about the offer to decide that the available information is insufficient. “I cannot measure this risk” is a valid reason not to enter.",review:["Independent evidence","Separation of issuer and custodian","Consistency of return, risk, and liquidity","Commercial incentives","Process if withdrawals stop","Jurisdiction and claims mechanism"],alert:"Commercial urgency mainly benefits the party receiving the money.",learning:"If you cannot explain how capital is generated, held, and returned, you cannot yet assess the proposal.",level:"control",tradeoff:{protect:"Capital, liquidity, and the ability to verify.",sacrifice:"Immediate access.",depend:"Keeping your standards under group pressure."}},
  ],
};

en[2] = {
  ...es[2], category: "Real estate", title: "Buying because real estate never goes down?",
  situation: "You have USD 70,000 in savings and are considering a USD 150,000 apartment. The seller says you should move quickly and that rent will practically pay for the property. After the purchase, most of your net worth would be concentrated in it.",
  facts: [{label:"Price",value:"USD 150,000"},{label:"Down payment",value:"USD 60,000"},{label:"Mortgage",value:"USD 90,000"},{label:"Estimated monthly payment",value:"USD 1,050"},{label:"Expected rent",value:"USD 900"},{label:"HOA / building fee",value:"USD 110 a month"},{label:"Estimated vacancy",value:"One month a year"},{label:"Taxes and maintenance",value:"USD 1,750 a year"},{label:"Remaining liquidity",value:"USD 10,000"},{label:"Estimated sale time",value:"4–12 months"}],
  metric:{title:"Monthly property cash flow",rows:[{label:"Expected rent",value:"+ USD 900"},{label:"Prorated vacancy",value:"− USD 75"},{label:"HOA / building fee",value:"− USD 110"},{label:"Taxes and maintenance",value:"− USD 145"},{label:"Mortgage payment",value:"− USD 1,050"},{label:"Estimated required monthly contribution",value:"About USD 480"}]},
  decisions:[
    {title:"Buy now",immediate:"You acquire the property, but rent does not fully cover the mortgage, building fee, vacancy, and other costs. A normal scenario requires roughly USD 480 from you each month.",secondary:"A repair, several vacant months, or lower personal income could force you to use the reserve. Selling to recover capital may take months.",reading:"A property can appreciate and still produce weak cash flow. Gross rent is not what remains after financing, vacancy, maintenance, and taxes.",review:["Monthly net cash flow","Capacity to withstand vacancy","Liquidity after purchase","Net-worth concentration","Time and cost to sell"],alert:"The property does not pay for itself with the available figures.",learning:"The asset’s value and your ability to carry it are separate questions.",level:"exposure",tradeoff:{protect:"Immediate access to the property.",sacrifice:"Liquidity and diversification.",depend:"Stable income, occupancy, and future appreciation."}},
    {title:"Buy with a larger reserve",immediate:"The purchase takes longer or financing terms may change. In exchange, you retain resources for vacancy, repairs, and personal expenses.",secondary:"The reserve lowers the chance of a pressured sale, but it does not fix negative monthly cash flow. Net-worth concentration remains high.",reading:"Keeping liquidity makes the purchase more resilient. It does not determine whether the price, financing, or net return is suitable.",review:["Months covered by the reserve","Cost of financing a larger amount","Net flow after all expenses","Property weight in net worth","Prepayment terms"],alert:"A reserve protects cash flow, but it does not turn an expensive deal into a profitable one.",learning:"Liquidity is necessary, but price and financing still matter.",level:"balance",tradeoff:{protect:"Capacity to absorb surprises.",sacrifice:"Speed or more favorable financing terms.",depend:"The monthly shortfall staying manageable."}},
    {title:"Postpone and compare",immediate:"You may lose this property or see its price rise. You retain liquidity and bargaining power.",secondary:"Analysis may show that the purchase only works at a lower price, with different debt, or with higher rent. It may also confirm that it is sustainable.",reading:"Waiting does not guarantee a better outcome. Its value is avoiding a major obligation before understanding how it is carried and unwound.",review:["Net return","Extended-vacancy scenario","Lower personal-income scenario","Opportunity cost of capital","Realistic exit timeline"],alert:"The seller’s urgency does not set your financial timeline.",learning:"Before asking how much it may rise, calculate what it costs to carry.",level:"control",tradeoff:{protect:"Liquidity and the ability to compare.",sacrifice:"Immediate access to the property.",depend:"Using the wait to analyze rather than delay indefinitely."}},
  ],
};

en[3] = {
  ...es[3], category: "Stocks / ETFs", title: "Entering after a strong run",
  situation: "An equity ETF has risen sharply over the past year. You have USD 20,000 available and worry about missing out if it keeps climbing. Your stated horizon is five years, but a large decline might make you reconsider.",
  facts:[{label:"Available capital",value:"USD 20,000"},{label:"Emergency fund",value:"Separate"},{label:"Stated horizon",value:"5 years"},{label:"Last-year gain",value:"28%"},{label:"Illustrative historical drawdown",value:"−35%"},{label:"Loss you say you can tolerate",value:"−15%"},{label:"Current equity exposure",value:"Low"},{label:"Future contributions",value:"USD 500 a month"},{label:"Context",value:"The historical decline illustrates volatility; it is not a forecast"}],
  metric:{title:"Impact of an illustrative 30% decline",rows:[{label:"Capital invested",value:"USD 20,000"},{label:"Temporary decline",value:"USD 6,000"},{label:"Remaining value",value:"USD 14,000"},{label:"Declared tolerable loss",value:"USD 3,000"}]},
  decisions:[
    {title:"Enter gradually",immediate:"Part of the capital begins participating while the rest remains available. If the market keeps rising, not all of the money captures that gain.",secondary:"This only works as behavioral control if you keep the schedule. Pausing purchases during a decline or accelerating them after another rise turns the plan into improvisation.",reading:"Gradual investing does not guarantee a better price. It can spread entry timing and show how you respond to real market moves.",review:["Contribution schedule and amount","Maximum ETF weight","Use of pending cash","Rebalancing rule","Conditions for pausing the plan"],alert:"A gradual plan without rules can end up following market emotions.",learning:"The value of gradual entry lies in discipline, not guessing the lowest price.",level:"control",tradeoff:{protect:"Entry timing and emotional adjustment.",sacrifice:"Full participation if the market keeps rising.",depend:"Following the schedule."}},
    {title:"Invest everything now",immediate:"You obtain full exposure from day one. If the market keeps rising, all capital participates.",secondary:"A 30% decline would temporarily reduce value by USD 6,000. That exceeds the USD 3,000 represented by your stated 15% tolerance.",reading:"Investing all at once is not inherently wrong. Fragility appears when position size does not match your real ability to hold through a decline.",review:["Possible loss in dollars","Weight within total net worth","Effective horizon","Liquidity needs","Likely response to a decline"],alert:"The plausible loss exceeds your stated tolerance.",learning:"Risk tolerance is clearer in money and behavior than as an abstract percentage.",level:"exposure",tradeoff:{protect:"Immediate participation.",sacrifice:"Room to adjust the entry.",depend:"Holding through a significant decline."}},
    {title:"Wait for a correction",immediate:"You avoid buying after a rise and keep the capital liquid.",secondary:"The correction may not arrive, or may come from a much higher price. Without a valuation or deadline, waiting can become indefinite.",reading:"“Buy when it drops” is not yet a plan. You need to define how much, under what conditions, and what happens if the market never offers that price.",review:["Basis for the entry level","Maximum waiting period","Use of cash while waiting","Alternative if no decline occurs","Difference between valuation and fear"],alert:"Waiting for one specific figure without another criterion is also market timing.",learning:"Not chasing a rally can be prudent; depending on a future drop can be incomplete.",level:"balance",tradeoff:{protect:"Capital from an impulsive entry.",sacrifice:"Exposure while waiting.",depend:"A specific decline occurring."}},
  ],
};

en[4] = {
  ...es[4], category: "Family portfolio", title: "Many assets, one near-term goal",
  situation: "You are part of a family reviewing an illustrative portfolio of {money:500000}. A {money:150000} goal may be needed within two years. Some want to protect that part; others want to keep growth exposure.",
  facts: [{label:"Portfolio total",value:"{money:500000}"},{label:"S&P 500",value:"25% — {money:125000}"},{label:"Emerging markets",value:"10% — {money:50000}"},{label:"Gold",value:"15% — {money:75000}"},{label:"BTC/ETH",value:"10% — {money:50000}"},{label:"Bonds",value:"25% — {money:125000}"},{label:"REIT",value:"5% — {money:25000}"},{label:"Cash",value:"10% — {money:50000}"},{label:"Likely need in 24 months",value:"{money:150000}"},{label:"Stated family drawdown tolerance",value:"18%"}],
  metric:{title:"Assets vs money function",rows:[
    {label:"24-month goal",value:"{money:150000}"},{label:"Current liquidity",value:"{money:50000}"},{label:"Bonds and defensive assets",value:"{money:125000}"},{label:"Capital exposed to market movement",value:"{money:450000}"},
    {label:"Reading",value:"A broad list of assets can hide a simpler question: which part of the money has a near-term use date?"},
  ]},
  decisions:[
    {title:"Separate the goal and rebalance",description:"The family reserves {money:150000} in liquid instruments suited to the time frame and sets limits for the other positions.",immediate:"The near-term goal becomes less exposed to a market decline. Part of the portfolio no longer participates fully in future gains.",secondary:"The remaining capital can still fluctuate, but the family is less likely to sell volatile assets to meet a planned need.",reading:"Reducing exposure does not require forecasting a decline. It may simply reflect that part of the money now has a different function.",review:["Goal amount and date","Liquidity needed","Risk in the capital that remains invested","Limits by asset","Rebalancing rule"],alert:"Protecting one goal does not remove risk from the rest of the portfolio.",learning:"The time frame of each goal may matter more than the portfolio’s recent return.",level:"control",tradeoff:{protect:"The near-term goal.",sacrifice:"Growth potential on the reserved capital.",depend:"The {money:150000} estimate being enough."}},
    {title:"Keep the current mix",immediate:"You avoid sales and retain the exposure that produced strong results. Current cash covers only part of the goal.",secondary:"The family is still {money:100000} short. If markets fall near the use date, it may have to sell at a loss or delay the decision.",reading:"Holding several assets does not guarantee that a near-term goal is protected. Different positions can decline together during stressed markets.",review:["Liquid capital against the goal","Correlation during declines","Combined equity and crypto risk","Flexibility of the use date","Family agreement after a loss"],alert:"Current liquidity does not fully cover the expected need.",learning:"Diversification is measured by risk sources and functions, not only by the number of assets.",level:"balance",tradeoff:{protect:"Continuity of the portfolio.",sacrifice:"Certainty around the near-term goal.",depend:"Stable markets or flexibility to delay the decision."}},
    {title:"Increase equities and crypto",description:"The family uses part of its gold, bonds, and cash to add to the assets it expects to grow most.",immediate:"The portfolio gains more exposure to the family’s highest-growth expectations. Available liquidity falls.",secondary:"A simultaneous decline can affect both net worth and the ability to meet the near-term goal. The family may end up realizing losses to cover a known need.",reading:"Seeking more return is not a sufficient objective. It needs a time frame, a tolerable loss, and a definition of which money cannot carry that risk.",review:["Combined weight of volatile assets","Potential loss in the selected currency","Needs within two years","Reason for adding to positions after gains","Consequences of selling under pressure"],alert:"Risk rises before the liquidity need is resolved.",learning:"More growth potential also widens the range of possible outcomes.",level:"exposure",tradeoff:{protect:"Participation in a possible upside move.",sacrifice:"Liquidity and stability for the goal.",depend:"Favorable markets over a short time frame."}},
  ],
};

export const investmentPracticeCases: Record<PracticeLocale, PracticeCase[]> = { es, en };
