export type PracticeLocale = "es" | "en";
export type ControlLevel = "control" | "balance" | "exposure";

export type Decision = {
  title: string;
  description?: string;
  immediate: string;
  secondary: string;
  reading: string;
  review: string[];
  alert: string;
  learning: string;
  level: ControlLevel;
  tradeoff: { protect: string; sacrifice: string; depend: string };
};

export type PracticeCase = {
  slug: string;
  category: string;
  title: string;
  situation: string;
  facts: { label: string; value: string }[];
  metric: { title: string; rows: { label: string; value: string; status?: "known" | "expected" | "verified" | "incomplete" | "unknown" }[] };
  decisions: Decision[];
};

const es: PracticeCase[] = [
  {
    slug: "liquidez-deuda", category: "Liquidez y deuda", title: "Una oportunidad mientras pagas deuda cara",
    situation: "Tienes COP 25 millones ahorrados y COP 20 millones en deuda de tarjeta y libre inversión. Un conocido te muestra una inversión que podría rendir 15% anual. Tu flujo mensual está ajustado y actualmente solo tienes un mes de gastos como reserva.",
    facts: [
      { label: "Ahorro", value: "COP 25 millones" }, { label: "Deuda", value: "COP 20 millones" },
      { label: "Tasa promedio de la deuda", value: "27% E.A." }, { label: "Cuota mensual", value: "COP 1,1 millones" },
      { label: "Gastos esenciales", value: "COP 5 millones al mes" }, { label: "Fondo de emergencia", value: "Un mes" },
      { label: "Flujo libre mensual", value: "COP 600.000" }, { label: "Rendimiento mencionado", value: "15% esperado" },
      { label: "Salida de la inversión", value: "Hasta 90 días" },
    ],
    metric: { title: "Costo conocido frente a rendimiento esperado", rows: [
      { label: "Costo de la deuda", value: "27% E.A. conocido", status: "known" },
      { label: "Rendimiento mencionado", value: "15% E.A. esperado", status: "expected" },
      { label: "Diferencia nominal", value: "12 puntos" }, { label: "Disponibilidad del ahorro", value: "Inmediata" },
      { label: "Disponibilidad de inversión", value: "Hasta 90 días" },
    ] },
    decisions: [
      { title: "Pagar toda la deuda", immediate: "Eliminas un costo financiero alto y liberas la cuota mensual. Quedas con COP 5 millones, equivalentes a aproximadamente un mes de gastos esenciales.", secondary: "El flujo mejora, pero una emergencia grande puede obligarte a utilizar nuevamente crédito. El resultado depende de reconstruir la reserva antes de asumir nuevos compromisos.", reading: "Pagar deuda cara reduce un costo conocido. Sin embargo, utilizar casi toda la liquidez puede trasladar el problema desde los intereses hacia la falta de reserva.", review: ["Estabilidad de los ingresos", "Reserva mínima necesaria", "Condiciones de prepago", "Tiempo para reconstruir el fondo", "Riesgo de volver a endeudarse"], alert: "La deuda desaparece, pero la liquidez queda en el mínimo.", learning: "Una mejora del balance puede crear una vulnerabilidad temporal en el flujo.", level: "balance", tradeoff: { protect: "El flujo frente a intereses altos.", sacrifice: "Reserva para imprevistos.", depend: "Reconstruir el fondo sin usar nueva deuda." } },
      { title: "Invertir todo y seguir pagando", immediate: "Mantienes una deuda que cuesta 27% y expones el ahorro a una rentabilidad esperada de 15%. El dinero invertido no estaría disponible de inmediato.", secondary: "Un gasto inesperado podría obligarte a utilizar más crédito. Incluso si la inversión alcanza el resultado esperado, el costo de la deuda puede continuar siendo superior.", reading: "Las dos tasas no son equivalentes. El interés de la deuda es contractual; el rendimiento de la inversión es incierto y puede incluir costos, impuestos o pérdidas.", review: ["Costo efectivo de la deuda", "Incertidumbre del rendimiento", "Liquidez del producto", "Fondo de emergencia", "Flujo mensual después de la cuota"], alert: "Se mantiene un costo alto para perseguir un resultado menor e incierto.", learning: "Una inversión no compensa necesariamente un flujo debilitado por deuda costosa.", level: "exposure", tradeoff: { protect: "Acceso a la oportunidad.", sacrifice: "Liquidez y reducción de deuda.", depend: "Que la inversión funcione y no aparezcan imprevistos." } },
      { title: "Reservar y amortizar lo más caro", description: "Mantienes COP 15 millones como reserva de tres meses y utilizas COP 10 millones para reducir primero la deuda de mayor tasa.", immediate: "No eliminas toda la deuda, pero reduces intereses y conservas capacidad para afrontar imprevistos.", secondary: "El flujo liberado puede utilizarse para terminar de pagar la deuda y después iniciar aportes de inversión. La oportunidad actual podría pasar.", reading: "La decisión no tiene que ser todo a deuda o todo a inversión. El orden de las acciones puede reducir la probabilidad de volver a endeudarse.", review: ["Tamaño adecuado de la reserva", "Orden de las deudas por tasa", "Flujo liberado", "Plazo para terminar de pagar", "Momento realista para comenzar a invertir"], alert: "El plan pierde efectividad si se toma nueva deuda mientras se ejecuta.", learning: "La capacidad sostenible de invertir comienza con liquidez suficiente y deuda controlada.", level: "control", tradeoff: { protect: "La reserva y parte del flujo.", sacrifice: "Inversión inmediata y eliminación total de la deuda.", depend: "Mantener el plan de pagos." } },
    ],
  },
  {
    slug: "producto-dudoso", category: "Producto dudoso", title: "24% anual, bajo riesgo y cupos limitados",
    situation: "Un amigo te recomienda una inversión privada que ofrece 24% anual. La empresa afirma que el riesgo es bajo, que paga mensualmente y que quedan pocos cupos. Para participar debes transferir al menos COP 20 millones esta semana.",
    facts: [
      { label: "Rentabilidad ofrecida", value: "24% anual" }, { label: "Riesgo descrito", value: "“Bajo”" },
      { label: "Inversión mínima", value: "COP 20 millones" }, { label: "Retiro", value: "60 días de anticipación" },
      { label: "Regulación", value: "No explicada" }, { label: "Custodia", value: "La misma empresa" },
      { label: "Documentación", value: "Presentación y contrato breve" }, { label: "Comisión por referidos", value: "3%" },
      { label: "Respaldo mencionado", value: "“Activos reales”, sin detalle verificable" },
    ],
    metric: { title: "Estado de verificación", rows: [
      { label: "Regulación", value: "No informada", status: "unknown" }, { label: "Custodia", value: "Sin separación", status: "incomplete" },
      { label: "Fuente del rendimiento", value: "Incompleta", status: "incomplete" }, { label: "Salida", value: "Condicionada", status: "incomplete" },
      { label: "Conflicto de interés", value: "Presente", status: "incomplete" },
    ] },
    decisions: [
      { title: "Pedir documentos y revisar", immediate: "La empresa entrega más información o evita responder algunas preguntas. El cupo puede cerrarse mientras revisas.", secondary: "Tener documentos no significa que sean auténticos, suficientes o favorables. Todavía falta comprobar la información y entender quién absorbe las pérdidas.", reading: "La documentación es necesaria, pero no equivale a verificación. Un documento comercial puede explicar el producto sin demostrar que los activos, garantías o resultados existen.", review: ["Entidad legal y responsables", "Supervisión aplicable", "Estados financieros verificables", "Custodio independiente", "Uso del dinero", "Escenario de incumplimiento"], alert: "La información debe poder comprobarse fuera del material comercial.", learning: "Recibir una respuesta no es lo mismo que verificarla.", level: "balance", tradeoff: { protect: "Parte del proceso de análisis.", sacrifice: "Tiempo frente al supuesto cupo.", depend: "Verificar los documentos de forma independiente." } },
      { title: "Invertir el mínimo por recomendación", immediate: "Obtienes acceso al producto y tu amigo recibe una comisión. La empresa puede comenzar a realizar los pagos prometidos.", secondary: "Los primeros pagos no demuestran que el modelo sea sostenible ni que el capital esté protegido. Si aparecen problemas, la recuperación dependerá de contratos, custodia y activos todavía poco claros.", reading: "Una relación personal puede reducir la sensación de riesgo, pero no cambia la estructura del producto. La comisión también crea un incentivo que conviene reconocer.", review: ["Fuente económica del rendimiento", "Custodia del dinero", "Regulación", "Derechos de salida", "Incentivos de quien recomienda", "Evidencia del supuesto respaldo"], alert: "La confianza personal está sustituyendo parte de la verificación.", learning: "Conocer a quien recomienda no significa comprender dónde queda el dinero ni cómo se recupera.", level: "exposure", tradeoff: { protect: "Acceso al supuesto cupo.", sacrifice: "Control, liquidez y verificabilidad.", depend: "Promesas que todavía no han sido comprobadas." } },
      { title: "No transferir sin verificar", immediate: "Puedes perder el cupo y una rentabilidad que finalmente podría materializarse. El capital permanece disponible.", secondary: "Si el producto fuera legítimo, habrás renunciado a una oportunidad. Si no lo fuera, evitaste asumir un riesgo difícil de medir y posiblemente difícil de recuperar.", reading: "No es necesario demostrar que un producto es fraudulento para decidir que la información disponible es insuficiente. “No puedo medir este riesgo” es una conclusión válida.", review: ["Evidencia independiente", "Separación entre emisor y custodio", "Coherencia entre retorno, riesgo y liquidez", "Incentivos comerciales", "Procedimiento si se suspenden los retiros", "Jurisdicción y mecanismo de reclamación"], alert: "La urgencia comercial beneficia principalmente a quien recibe el dinero.", learning: "Si no puedes explicar cómo se genera, protege y devuelve el capital, todavía no puedes evaluar la inversión.", level: "control", tradeoff: { protect: "Capital, liquidez y capacidad de verificación.", sacrifice: "Acceso inmediato.", depend: "Mantener el criterio aunque exista presión social." } },
    ],
  },
  {
    slug: "finca-raiz", category: "Finca raíz", title: "¿Comprar porque la finca raíz nunca baja?",
    situation: "Tienes COP 280 millones ahorrados y estás considerando un apartamento de COP 600 millones. El vendedor afirma que conviene comprar pronto y que el inmueble prácticamente se pagará con el arriendo. Después de la compra, la mayor parte de tu patrimonio quedaría concentrada en esa propiedad.",
    facts: [
      { label: "Precio", value: "COP 600 millones" }, { label: "Cuota inicial", value: "COP 240 millones" },
      { label: "Crédito", value: "COP 360 millones" }, { label: "Cuota estimada", value: "COP 4,2 millones al mes" },
      { label: "Arriendo esperado", value: "COP 3,6 millones" }, { label: "Administración", value: "COP 450.000 al mes" },
      { label: "Vacancia estimada", value: "Un mes al año" }, { label: "Impuestos y mantenimiento", value: "COP 7 millones al año" },
      { label: "Liquidez restante", value: "COP 40 millones" }, { label: "Tiempo de venta estimado", value: "4–12 meses" },
    ],
    metric: { title: "Flujo mensual del inmueble", rows: [
      { label: "Arriendo esperado", value: "+ COP 3,6 M" }, { label: "Vacancia prorrateada", value: "− COP 0,3 M" },
      { label: "Administración", value: "− COP 0,45 M" }, { label: "Impuestos y mantenimiento", value: "− COP 0,58 M" },
      { label: "Cuota del crédito", value: "− COP 4,2 M" }, { label: "Aporte mensual requerido", value: "− COP 1,93 M" },
    ] },
    decisions: [
      { title: "Comprar ahora", immediate: "Obtienes el inmueble, pero el arriendo no cubre completamente la cuota, la administración, la vacancia y los demás costos. Tendrías que aportar alrededor de COP 1,9 millones mensuales en un escenario normal.", secondary: "Una reparación, varios meses sin inquilino o una reducción de ingresos puede obligarte a usar la reserva. Si necesitas recuperar el capital, vender puede tomar varios meses.", reading: "Un inmueble puede valorizarse y aun así generar un flujo débil. El arriendo bruto no representa lo que realmente queda después de financiación, vacancia, mantenimiento e impuestos.", review: ["Flujo neto mensual", "Capacidad para sostener una vacancia", "Liquidez después de comprar", "Concentración patrimonial", "Tiempo y costos de venta"], alert: "El inmueble no se paga solo con los datos disponibles.", learning: "El valor del activo y la capacidad para sostenerlo son dos preguntas distintas.", level: "exposure", tradeoff: { protect: "Acceso inmediato al inmueble.", sacrifice: "Liquidez y diversificación.", depend: "Ingresos estables, ocupación y valorización futura." } },
      { title: "Comprar con mayor reserva", immediate: "La compra tarda más o la financiación puede cambiar. A cambio, conservas recursos para cubrir vacancia, reparaciones y gastos personales.", secondary: "La reserva reduce la probabilidad de vender bajo presión, pero no corrige por sí sola un flujo mensual negativo. La concentración patrimonial continúa siendo alta.", reading: "Conservar liquidez mejora la resistencia de la compra. No determina si el precio, el crédito o el rendimiento neto son adecuados.", review: ["Cuántos meses cubre la reserva", "Costo de financiar un monto mayor", "Flujo neto después de todos los gastos", "Peso del inmueble en el patrimonio", "Condiciones de prepago"], alert: "Una reserva protege el flujo, pero no transforma una operación costosa en rentable.", learning: "Resolver la liquidez es necesario, pero el precio y la financiación siguen importando.", level: "balance", tradeoff: { protect: "Capacidad para absorber imprevistos.", sacrifice: "Velocidad o mejores condiciones de financiación.", depend: "Que el déficit mensual sea sostenible." } },
      { title: "Posponer y comparar", immediate: "Puedes perder esta propiedad o verla subir de precio. Conservas liquidez y capacidad de negociación.", secondary: "El análisis puede mostrar que la compra solo funciona con un precio menor, otra estructura de deuda o un arriendo superior. También puede confirmar que la compra resulta sostenible.", reading: "Esperar no garantiza un mejor resultado. Su utilidad consiste en no asumir una obligación grande antes de entender cómo se sostiene y cómo se puede deshacer.", review: ["Rentabilidad neta", "Escenario con vacancia prolongada", "Escenario de ingresos personales más bajos", "Costo de oportunidad del capital", "Plazo real de salida"], alert: "La urgencia del vendedor no determina tu plazo financiero.", learning: "Antes de preguntar cuánto puede subir, conviene calcular cuánto cuesta mantenerlo.", level: "control", tradeoff: { protect: "Liquidez y capacidad de comparación.", sacrifice: "Acceso inmediato al inmueble.", depend: "Usar la espera para analizar, no para aplazar indefinidamente." } },
    ],
  },
  {
    slug: "bolsa-etf", category: "Bolsa / ETF", title: "Entrar después de una gran subida",
    situation: "Un ETF de renta variable ha subido con fuerza durante el último año. Tienes COP 80 millones disponibles y te preocupa quedarte por fuera si continúa avanzando. Tu horizonte declarado es de cinco años, pero una caída grande podría hacerte reconsiderar la decisión.",
    facts: [
      { label: "Capital disponible", value: "COP 80 millones" }, { label: "Fondo de emergencia", value: "Separado" },
      { label: "Horizonte declarado", value: "5 años" }, { label: "Subida durante el último año", value: "28%" },
      { label: "Caída histórica ilustrativa", value: "−35%" }, { label: "Pérdida que dices tolerar", value: "−15%" },
      { label: "Exposición actual a bolsa", value: "Baja" }, { label: "Aportes futuros", value: "COP 2 millones al mes" },
      { label: "Contexto", value: "La caída histórica dimensiona volatilidad; no es un pronóstico" },
    ],
    metric: { title: "Impacto de una caída ilustrativa de 30%", rows: [
      { label: "Capital invertido", value: "COP 80 millones" }, { label: "Caída temporal", value: "COP 24 millones" },
      { label: "Valor restante", value: "COP 56 millones" }, { label: "Pérdida declarada como tolerable", value: "COP 12 millones" },
    ] },
    decisions: [
      { title: "Entrar gradualmente", immediate: "Una parte del capital comienza a participar y otra permanece disponible. Si el mercado continúa subiendo, no todo el dinero recibe esa subida.", secondary: "La estrategia solo funciona como control conductual si mantienes el calendario. Suspender compras durante una caída o acelerarlas después de otra subida convertiría el plan en improvisación.", reading: "Invertir gradualmente no garantiza un mejor precio. Puede ayudar a distribuir el momento de entrada y a comprobar cómo reaccionas ante movimientos reales.", review: ["Calendario y monto de los aportes", "Peso máximo del ETF", "Destino del efectivo pendiente", "Regla de rebalanceo", "Condiciones para suspender el plan"], alert: "Un plan gradual sin reglas puede terminar siguiendo las emociones del mercado.", learning: "El valor de una entrada gradual está en la disciplina, no en adivinar el precio más bajo.", level: "control", tradeoff: { protect: "El punto de entrada y la adaptación emocional.", sacrifice: "Participación completa si el mercado sigue subiendo.", depend: "Cumplir el calendario." } },
      { title: "Invertir todo ahora", immediate: "Obtienes exposición completa desde el primer día. Si el mercado continúa subiendo, todo el capital participa.", secondary: "Una caída de 30% reduciría temporalmente el valor en COP 24 millones. Esa pérdida supera los COP 12 millones correspondientes a la tolerancia declarada de 15%.", reading: "Invertir de una vez puede ser coherente con algunos planes. La fragilidad aparece cuando el tamaño de la posición no coincide con la capacidad real de mantenerla durante una caída.", review: ["Pérdida posible en pesos", "Peso dentro del patrimonio total", "Horizonte efectivo", "Necesidades de liquidez", "Reacción probable ante una caída"], alert: "La pérdida plausible supera la tolerancia que declaraste.", learning: "La tolerancia al riesgo se entiende mejor en dinero y comportamiento que en un porcentaje abstracto.", level: "exposure", tradeoff: { protect: "Participación inmediata.", sacrifice: "Margen para ajustar la entrada.", depend: "Mantener la posición durante una caída significativa." } },
      { title: "Esperar una corrección", immediate: "Evitas comprar después de una subida y conservas el capital líquido.", secondary: "La corrección puede no llegar o puede ocurrir desde un precio mucho más alto. Sin una valoración o fecha límite, esperar puede convertirse en una decisión indefinida.", reading: "“Comprar cuando baje” no es todavía un plan. Hace falta definir cuánto, bajo qué condiciones y qué ocurrirá si el mercado no ofrece ese precio.", review: ["Fundamento del nivel de entrada", "Plazo máximo de espera", "Uso del efectivo mientras esperas", "Alternativa si no ocurre la caída", "Diferencia entre valoración y miedo"], alert: "Esperar una cifra concreta sin un criterio adicional también es intentar anticipar el mercado.", learning: "No perseguir una subida puede ser prudente; depender de una caída futura puede ser incompleto.", level: "balance", tradeoff: { protect: "El capital frente a una entrada impulsiva.", sacrifice: "Exposición mientras esperas.", depend: "Que ocurra una caída específica." } },
    ],
  },
];

const en: PracticeCase[] = es.map((item) => item); // Replaced below with adapted English content.

en[0] = {
  ...es[0], category: "Liquidity and debt", title: "An opportunity while carrying expensive debt",
  situation: "You have COP 25 million in savings and COP 20 million in credit-card and personal-loan debt. Someone you know presents an investment that may return 15% a year. Monthly cash flow is tight, and your reserve currently covers only one month of expenses.",
  facts: [{label:"Savings",value:"COP 25 million"},{label:"Debt",value:"COP 20 million"},{label:"Average debt rate",value:"27% E.A."},{label:"Monthly payment",value:"COP 1.1 million"},{label:"Essential spending",value:"COP 5 million a month"},{label:"Emergency fund",value:"One month"},{label:"Monthly free cash flow",value:"COP 600,000"},{label:"Stated return",value:"15% expected"},{label:"Investment exit",value:"Up to 90 days"}],
  metric: { title: "Known cost versus expected return", rows: [{label:"Debt cost",value:"27% E.A. known",status:"known"},{label:"Stated return",value:"15% E.A. expected",status:"expected"},{label:"Nominal gap",value:"12 points"},{label:"Savings availability",value:"Immediate"},{label:"Investment availability",value:"Up to 90 days"}] },
  decisions: [
    { title:"Pay off all debt", immediate:"You remove a high financing cost and free the monthly payment. COP 5 million remains—about one month of essential expenses.", secondary:"Cash flow improves, but a large emergency could force you to borrow again. The outcome depends on rebuilding the reserve before taking on new commitments.", reading:"Paying expensive debt removes a known cost. Using nearly all available cash, however, may shift the problem from interest expense to a thin reserve.", review:["Income stability","Minimum reserve needed","Prepayment terms","Time needed to rebuild the fund","Risk of borrowing again"], alert:"The debt disappears, but liquidity falls to the minimum.", learning:"A stronger balance sheet can create a temporary cash-flow vulnerability.", level:"balance", tradeoff:{protect:"Cash flow from high interest costs.",sacrifice:"Your emergency reserve.",depend:"Rebuilding the fund without new debt."}},
    { title:"Invest everything and keep paying", immediate:"You keep debt costing 27% while exposing savings to an expected 15% return. The invested money would not be immediately available.", secondary:"An unexpected expense could require more credit. Even if the investment meets expectations, the debt may continue to cost more.", reading:"The rates are not equivalent. Debt interest is contractual; investment return is uncertain and may be reduced by fees, taxes, or losses.", review:["Effective debt cost","Return uncertainty","Product liquidity","Emergency fund","Cash flow after the payment"], alert:"A high known cost remains in pursuit of a lower, uncertain result.", learning:"An investment does not necessarily offset cash flow weakened by expensive debt.", level:"exposure", tradeoff:{protect:"Access to the opportunity.",sacrifice:"Liquidity and debt reduction.",depend:"The investment working and no surprises occurring."}},
    { title:"Keep a reserve and reduce the costliest debt", description:"You keep COP 15 million as a three-month reserve and use COP 10 million to reduce the highest-rate debt first.", immediate:"You do not remove all debt, but you lower interest expense and retain capacity for unexpected costs.", secondary:"Freed-up cash flow can finish paying the debt and later fund investments. The current opportunity may pass.", reading:"The choice need not be all debt or all investment. Sequencing can reduce the chance of having to borrow again.", review:["Appropriate reserve size","Debt order by rate","Cash flow released","Payoff timeline","A realistic point to begin investing"], alert:"The plan loses effectiveness if new debt is added while it is underway.", learning:"Sustainable investing capacity starts with adequate liquidity and controlled debt.", level:"control", tradeoff:{protect:"The reserve and part of cash flow.",sacrifice:"Immediate investing and full debt elimination.",depend:"Following the payment plan."}},
  ],
};

en[1] = {
  ...es[1], category:"Questionable product", title:"24% a year, low risk, and limited availability",
  situation:"A friend recommends a private investment offering 24% a year. The company calls the risk low, says it pays monthly, and claims few spots remain. Participation requires transferring at least COP 20 million this week.",
  facts:[{label:"Offered return",value:"24% a year"},{label:"Stated risk",value:"“Low”"},{label:"Minimum investment",value:"COP 20 million"},{label:"Withdrawal",value:"60 days’ notice"},{label:"Regulation",value:"Not explained"},{label:"Custody",value:"The same company"},{label:"Documents",value:"Presentation and short contract"},{label:"Referral fee",value:"3%"},{label:"Stated backing",value:"“Real assets,” without verifiable detail"}],
  metric:{title:"Verification status",rows:[{label:"Regulation",value:"Not disclosed",status:"unknown"},{label:"Custody",value:"Not separated",status:"incomplete"},{label:"Source of return",value:"Incomplete",status:"incomplete"},{label:"Exit",value:"Conditional",status:"incomplete"},{label:"Conflict of interest",value:"Present",status:"incomplete"}]},
  decisions:[
    {title:"Request documents and review",immediate:"The company provides more information or avoids some questions. The offer may close while you review it.",secondary:"Having documents does not make them authentic, sufficient, or favorable. You still need to verify the information and understand who absorbs losses.",reading:"Documentation is necessary, but it is not verification. Marketing material can describe a product without proving that its assets, guarantees, or results exist.",review:["Legal entity and responsible parties","Applicable supervision","Verifiable financial statements","Independent custodian","Use of funds","Default scenario"],alert:"The information must be verifiable outside the sales material.",learning:"Receiving an answer is not the same as verifying it.",level:"balance",tradeoff:{protect:"Part of the review process.",sacrifice:"Time against the claimed deadline.",depend:"Independent verification of the documents."}},
    {title:"Invest the minimum based on the referral",immediate:"You gain access and your friend receives a commission. The company may begin making the promised payments.",secondary:"Early payments do not prove the model is sustainable or the principal protected. Recovery would depend on contracts, custody, and assets that remain unclear.",reading:"A personal relationship can lower the feeling of risk, but it does not change the product structure. The commission is also an incentive worth recognizing.",review:["Economic source of return","Custody of funds","Regulation","Exit rights","Referrer incentives","Evidence of the stated backing"],alert:"Personal trust is replacing part of the verification process.",learning:"Knowing the referrer does not explain where the money sits or how it can be recovered.",level:"exposure",tradeoff:{protect:"Access to the claimed opening.",sacrifice:"Control, liquidity, and verifiability.",depend:"Promises that have not been independently checked."}},
    {title:"Do not transfer without verification",immediate:"You may lose the opening and a return that could ultimately materialize. Your capital remains available.",secondary:"If the product is legitimate, you gave up an opportunity. If it is not, you avoided a risk that was hard to measure and potentially hard to recover from.",reading:"You do not need to prove a product fraudulent to decide that the available information is insufficient. “I cannot measure this risk” is a valid conclusion.",review:["Independent evidence","Separation of issuer and custodian","Consistency of return, risk, and liquidity","Commercial incentives","Process if withdrawals stop","Jurisdiction and claims mechanism"],alert:"Commercial urgency mainly benefits the party receiving the money.",learning:"If you cannot explain how capital is generated, protected, and returned, you cannot yet assess the investment.",level:"control",tradeoff:{protect:"Capital, liquidity, and the ability to verify.",sacrifice:"Immediate access.",depend:"Keeping your standards under social pressure."}},
  ],
};

en[2] = {
  ...es[2], category: "Real estate", title: "Buying because real estate never goes down?",
  situation: "You have USD 70,000 in savings and are considering a USD 150,000 apartment. The seller says you should move quickly and that rent will practically pay for the property. After the purchase, most of your net worth would be concentrated in it.",
  facts: [{label:"Price",value:"USD 150,000"},{label:"Down payment",value:"USD 60,000"},{label:"Mortgage",value:"USD 90,000"},{label:"Estimated monthly payment",value:"USD 1,050"},{label:"Expected rent",value:"USD 900"},{label:"HOA / building fee",value:"USD 110 a month"},{label:"Estimated vacancy",value:"One month a year"},{label:"Taxes and maintenance",value:"USD 1,750 a year"},{label:"Remaining liquidity",value:"USD 10,000"},{label:"Estimated sale time",value:"4–12 months"}],
  metric:{title:"Monthly property cash flow",rows:[{label:"Expected rent",value:"+ USD 900"},{label:"Prorated vacancy",value:"− USD 75"},{label:"HOA / building fee",value:"− USD 110"},{label:"Taxes and maintenance",value:"− USD 145"},{label:"Mortgage payment",value:"− USD 1,050"},{label:"Estimated required monthly contribution",value:"About USD 480"}]},
  decisions:[
    {title:"Buy now",immediate:"You acquire the property, but rent does not fully cover the mortgage, building fee, vacancy, and other costs. A normal scenario requires roughly USD 480 from you each month.",secondary:"A repair, several vacant months, or lower personal income could force you to use the reserve. Selling to recover capital may take months.",reading:"A property can appreciate and still produce weak cash flow. Gross rent is not what remains after financing, vacancy, maintenance, and taxes.",review:["Monthly net cash flow","Capacity to withstand vacancy","Liquidity after purchase","Net-worth concentration","Time and cost to sell"],alert:"The property does not pay for itself with the available figures.",learning:"The asset’s value and your ability to carry it are separate questions.",level:"exposure",tradeoff:{protect:"Immediate access to the property.",sacrifice:"Liquidity and diversification.",depend:"Stable income, occupancy, and future appreciation."}},
    {title:"Buy with a larger reserve",immediate:"The purchase takes longer or financing terms may change. In exchange, you retain resources for vacancy, repairs, and personal expenses.",secondary:"The reserve lowers the chance of a pressured sale, but it does not fix negative monthly cash flow. Net-worth concentration remains high.",reading:"Keeping liquidity makes the purchase more resilient. It does not determine whether the price, financing, or net return is suitable.",review:["Months covered by the reserve","Cost of financing a larger amount","Net flow after all expenses","Property weight in net worth","Prepayment terms"],alert:"A reserve protects cash flow, but it does not turn an expensive deal into a profitable one.",learning:"Liquidity is necessary, but price and financing still matter.",level:"balance",tradeoff:{protect:"Capacity to absorb surprises.",sacrifice:"Speed or more favorable financing terms.",depend:"The monthly shortfall staying manageable."}},
    {title:"Postpone and compare",immediate:"You may lose this property or see its price rise. You retain liquidity and bargaining power.",secondary:"Analysis may show that the purchase only works at a lower price, with different debt, or with higher rent. It may also confirm that it is sustainable.",reading:"Waiting does not guarantee a better outcome. Its value is avoiding a major obligation before understanding how it is carried and unwound.",review:["Net return","Extended-vacancy scenario","Lower personal-income scenario","Opportunity cost of capital","Realistic exit timeline"],alert:"The seller’s urgency does not set your financial timeline.",learning:"Before asking how much it may rise, calculate what it costs to carry.",level:"control",tradeoff:{protect:"Liquidity and the ability to compare.",sacrifice:"Immediate access to the property.",depend:"Using the wait to analyze rather than delay indefinitely."}},
  ],
};

en[3] = {
  ...es[3], category: "Stocks / ETFs", title: "Entering after a strong run",
  situation: "An equity ETF has risen sharply over the past year. You have USD 20,000 available and worry about missing out if it keeps climbing. Your stated horizon is five years, but a large decline might make you reconsider.",
  facts:[{label:"Available capital",value:"USD 20,000"},{label:"Emergency fund",value:"Separate"},{label:"Stated horizon",value:"5 years"},{label:"Last-year gain",value:"28%"},{label:"Illustrative historical drawdown",value:"−35%"},{label:"Loss you say you can tolerate",value:"−15%"},{label:"Current equity exposure",value:"Low"},{label:"Future contributions",value:"USD 500 a month"},{label:"Context",value:"The historical decline illustrates volatility; it is not a forecast"}],
  metric:{title:"Impact of an illustrative 30% decline",rows:[{label:"Capital invested",value:"USD 20,000"},{label:"Temporary decline",value:"USD 6,000"},{label:"Remaining value",value:"USD 14,000"},{label:"Declared tolerable loss",value:"USD 3,000"}]},
  decisions:[
    {title:"Enter gradually",immediate:"Part of the capital begins participating while the rest remains available. If the market keeps rising, not all of the money captures that gain.",secondary:"This only works as behavioral control if you keep the schedule. Pausing purchases during a decline or accelerating them after another rise turns the plan into improvisation.",reading:"Gradual investing does not guarantee a better price. It can spread entry timing and show how you respond to real market moves.",review:["Contribution schedule and amount","Maximum ETF weight","Use of pending cash","Rebalancing rule","Conditions for pausing the plan"],alert:"A gradual plan without rules can end up following market emotions.",learning:"The value of gradual entry lies in discipline, not guessing the lowest price.",level:"control",tradeoff:{protect:"Entry timing and emotional adjustment.",sacrifice:"Full participation if the market keeps rising.",depend:"Following the schedule."}},
    {title:"Invest everything now",immediate:"You obtain full exposure from day one. If the market keeps rising, all capital participates.",secondary:"A 30% decline would temporarily reduce value by USD 6,000. That exceeds the USD 3,000 represented by your stated 15% tolerance.",reading:"Investing all at once is not inherently wrong. Fragility appears when position size does not match your real ability to hold through a decline.",review:["Possible loss in dollars","Weight within total net worth","Effective horizon","Liquidity needs","Likely response to a decline"],alert:"The plausible loss exceeds your stated tolerance.",learning:"Risk tolerance is clearer in money and behavior than as an abstract percentage.",level:"exposure",tradeoff:{protect:"Immediate participation.",sacrifice:"Room to adjust the entry.",depend:"Holding through a significant decline."}},
    {title:"Wait for a correction",immediate:"You avoid buying after a rise and keep the capital liquid.",secondary:"The correction may not arrive, or may come from a much higher price. Without a valuation or deadline, waiting can become indefinite.",reading:"“Buy when it drops” is not yet a plan. You need to define how much, under what conditions, and what happens if the market never offers that price.",review:["Basis for the entry level","Maximum waiting period","Use of cash while waiting","Alternative if no decline occurs","Difference between valuation and fear"],alert:"Waiting for one specific figure without another criterion is also market timing.",learning:"Not chasing a rally can be prudent; depending on a future drop can be incomplete.",level:"balance",tradeoff:{protect:"Capital from an impulsive entry.",sacrifice:"Exposure while waiting.",depend:"A specific decline occurring."}},
  ],
};

export const investmentPracticeCases: Record<PracticeLocale, PracticeCase[]> = { es, en };
