import type { TrendRisk, TrendObservableVehicleKind } from './trends-content.ts';
type DetailCopy = {
  home: string; back: string; methodology: string; reviewed: string; changing: string; evidence: string; evidenceLimit: string; valueChain: string; capture: string; capital: string; capitalPending: string; capitalEmpty: string; capitalLink: string; companies: string; companiesNote: string; vehicles: string; vehiclesNote: string; noVehicles: string; levels: string; bull: string; bear: string; invalidation: string; risks: string; next: string; market: string;
  riskLabels: Record<TrendRisk, string>; vehicleLabels: Record<TrendObservableVehicleKind, string>;
};
export const trendDetailCopy: Record<'es' | 'en', DetailCopy> = {
  es: {
    home: 'Inicio', back: 'Tendencias', methodology: 'Metodología', reviewed: 'Revisión editorial', changing: 'Qué está cambiando', evidence: 'Evidencia', evidenceLimit: 'Límite de la evidencia', valueChain: 'Cadena de valor', capture: 'Quién podría capturar valor', capital: 'Capital divulgado', capitalPending: 'Las posiciones aún no están disponibles para este trimestre.', capitalEmpty: 'No hay vínculos de compañías verificados para esta tendencia dentro del universo consultado. Esto no implica ausencia de exposición.', capitalLink: 'Consultar el capital divulgado', companies: 'Empresas observables', companiesNote: 'Relación editorial por actividad económica. La posición divulgada no demuestra la tesis del gestor.', vehicles: 'Vehículos para observar', vehiclesNote: 'Ejemplos educativos, no recomendaciones. Revisa composición, costes, concentración y disponibilidad antes de estudiar un vehículo.', noVehicles: 'La exposición depende del eslabón de la cadena. Aún no se ha verificado un vehículo específico para esta ficha.', levels: 'Ver niveles', bull: 'Argumento a favor', bear: 'Argumento en contra', invalidation: 'Qué invalidaría la hipótesis', risks: 'Riesgos', next: 'Conectar con el mercado', market: 'Ver contexto de mercado',
    riskLabels: { valoracion: 'Valoración', hype: 'Expectativas excesivas', regulacion: 'Regulación', competencia: 'Competencia', concentracion: 'Concentración', timing: 'Plazos y ciclo', liquidez: 'Liquidez' },
    vehicleLabels: { 'indice amplio': 'Índice amplio', 'ETF dedicado': 'ETF dedicado', 'ETF sectorial': 'ETF sectorial', 'ETF tematico': 'ETF temático', 'accion liquida': 'Acción líquida', infraestructura: 'Infraestructura', observacion: 'Observación' },
  },
  en: {
    home: 'Home', back: 'Trends', methodology: 'Methodology', reviewed: 'Editorial review', changing: 'What is changing', evidence: 'Evidence', evidenceLimit: 'Limits of the evidence', valueChain: 'Value chain', capture: 'Who could capture value', capital: 'Disclosed capital', capitalPending: 'Holdings are not yet available for this quarter.', capitalEmpty: 'No company links have been verified for this trend within the observed universe. This does not imply a lack of exposure.', capitalLink: 'Explore disclosed capital', companies: 'Observable companies', companiesNote: "Editorial connection based on economic activity. A disclosed holding does not establish the manager's thesis.", vehicles: 'Vehicles to observe', vehiclesNote: 'Educational examples, not recommendations. Review holdings, costs, concentration and availability before studying a vehicle.', noVehicles: 'Exposure depends on the link in the value chain. A specific vehicle has not yet been verified for this profile.', levels: 'View levels', bull: 'Argument in favor', bear: 'Argument against', invalidation: 'What would invalidate the hypothesis', risks: 'Risks', next: 'Connect with the market', market: 'View market context',
    riskLabels: { valoracion: 'Valuation', hype: 'Excessive expectations', regulacion: 'Regulation', competencia: 'Competition', concentracion: 'Concentration', timing: 'Timelines and cycle', liquidez: 'Liquidity' },
    vehicleLabels: { 'indice amplio': 'Broad index', 'ETF dedicado': 'Dedicated ETF', 'ETF sectorial': 'Sector ETF', 'ETF tematico': 'Thematic ETF', 'accion liquida': 'Liquid stock', infraestructura: 'Infrastructure', observacion: 'Observation' },
  },
};
