export type TrendEvidenceNote = { label: string; url: string; observation: { es: string; en: string }; limit: { es: string; en: string } };
// The source establishes the scope of the observation. Phase/evidence remain
// editorial judgments, with their definitions and limitations on methodology.
export const trendEvidence: Record<string, TrendEvidenceNote> = {
  ai: { label: "Stanford HAI · AI Index 2026", url: "https://hai.stanford.edu/ai-index/2026-ai-index-report", observation: { es: "El AI Index documenta expansión de la adopción, inversión e infraestructura. La monetización debe comprobarse por producto y por empresa.", en: "The AI Index documents expanding adoption, investment and infrastructure. Monetization needs verification at product and company level." }, limit: { es: "Uso declarado y resultados en benchmarks no equivalen a productividad ni a beneficios sostenibles.", en: "Reported usage and benchmark results do not establish productivity or sustainable profits." } },
  automation: { label: "IFR · World Robotics 2025", url: "https://ifr.org/worldrobotics/report-2025", observation: { es: "La serie de instalaciones industriales muestra despliegue comercial recurrente. Aquí se estudian procesos, integración y retorno operativo.", en: "Industrial installation data show recurring commercial deployment. This thesis focuses on processes, integration and operating returns." }, limit: { es: "La evidencia industrial no se extrapola automáticamente a toda automatización administrativa.", en: "Industrial evidence cannot automatically be extended to all administrative automation." } },
  energy: { label: "IEA · Energy and AI 2025", url: "https://www.iea.org/reports/energy-and-ai/executive-summary", observation: { es: "La IEA vincula el crecimiento de centros de datos con necesidades de electricidad, redes y capacidad firme.", en: "The IEA connects data center growth with electricity, grid and firm capacity requirements." }, limit: { es: "Las proyecciones dependen de eficiencia, adopción y disponibilidad de red. No son contratos asegurados.", en: "Projections depend on efficiency, adoption and grid availability. They are not guaranteed contracts." } },
  longevity: { label: "WHO · Ageing and health", url: "https://www.who.int/news-room/fact-sheets/detail/ageing-and-health", observation: { es: "La OMS documenta el envejecimiento de la población y la necesidad de adaptar los sistemas de cuidados.", en: "WHO documents population ageing and the need to adapt care systems." }, limit: { es: "La demografía no valida una terapia. La evidencia clínica y la capacidad de pago requieren análisis separado.", en: "Demographics do not validate a treatment. Clinical evidence and ability to pay require separate analysis." } },
  cybersecurity: { label: "ENISA · Threat Landscape 2025", url: "https://www.enisa.europa.eu/publications/enisa-threat-landscape-2025", observation: { es: "El registro de incidentes muestra riesgos persistentes para datos, servicios e infraestructuras europeas.", en: "The incident record shows persistent risks to European data, services and infrastructure." }, limit: { es: "La frecuencia de ataques no determina qué proveedor ganará cuota o conservará márgenes.", en: "Attack frequency does not determine which vendor will gain share or preserve margins." } },
  defense: { label: "SIPRI · Military Expenditure Database, 1949–2025", url: "https://www.sipri.org/databases/milex", observation: { es: "Las series de gasto militar permiten contrastar compromisos presupuestarios con la narrativa de seguridad.", en: "Military expenditure series allow budget commitments to be compared with the security narrative." }, limit: { es: "Presupuesto, adjudicación, entrega e ingresos de una empresa son etapas distintas.", en: "Budgets, contract awards, deliveries and company revenue are separate stages." } },
  fintech: { label: "World Bank · Global Findex 2025", url: "https://www.worldbank.org/en/publication/globalfindex/report", observation: { es: "La encuesta documenta el uso de cuentas, pagos y servicios financieros digitales en múltiples economías.", en: "The survey documents the use of accounts, payments and digital financial services across economies." }, limit: { es: "Los datos corresponden a encuestas de 2024. Más uso no implica mejores márgenes para cada intermediario.", en: "The data come from 2024 surveys. More usage does not imply better margins for every intermediary." } },
  "premium-consumption": { label: "LVMH · Full-year results 2025", url: "https://www.lvmh.com/en/publications/solid-performance-in-a-disrupted-global-economic-and-geopolitical-environment", observation: { es: "Los resultados por segmento muestran diferencias de demanda entre categorías y regiones. Se conserva el foco original en consumo premium y aspiracional.", en: "Segment results show differences in demand across categories and regions. The original focus on premium and aspirational consumption is retained." }, limit: { es: "Un emisor no representa a todo el consumo; es evidencia corporativa parcial y cíclica.", en: "One issuer does not represent all consumption; this is partial, cyclical company evidence." } },
  "water-food": { label: "UNESCO · World Water Development Report 2025", url: "https://www.unesco.org/reports/wwdr/en/2025", observation: { es: "El informe relaciona disponibilidad de agua, agricultura, seguridad alimentaria y resiliencia económica.", en: "The report connects water availability, agriculture, food security and economic resilience." }, limit: { es: "Una necesidad social no asegura capacidad de pago ni retornos para el operador.", en: "A social need does not guarantee the ability to pay or returns for an operator." } },
  space: { label: "ESA · Space Economy Report 2026", url: "https://www.esa.int/About_Us/Business_with_ESA/ESA_releases_2026_Space_Economy_Report", observation: { es: "La ESA sigue inversión pública y privada, lanzamientos y mercados de aplicaciones espaciales.", en: "ESA tracks public and private investment, launches and markets for space applications." }, limit: { es: "La madurez de comunicaciones por satélite no se extiende a todas las nuevas actividades espaciales.", en: "The maturity of satellite communications does not extend to every new space activity." } },
  "critical-materials": { label: "IEA · Global Critical Minerals Outlook 2026", url: "https://www.iea.org/reports/global-critical-minerals-outlook-2026", observation: { es: "La IEA analiza demanda, inversión y concentración de suministro en minerales relevantes para energía y tecnología.", en: "The IEA examines demand, investment and supply concentration in minerals relevant to energy and technology." }, limit: { es: "Una demanda estructural creciente puede coexistir con exceso de oferta y caídas de precios.", en: "Growing structural demand can coexist with oversupply and falling prices." } },
  "digital-education": { label: "Stanford HAI · AI Index 2026, Education", url: "https://hai.stanford.edu/ai-index/2026-ai-index-report", observation: { es: "El AI Index documenta uso de IA en educación y cambios en las habilidades demandadas.", en: "The AI Index documents AI use in education and shifts in skill demand." }, limit: { es: "Adopción de software no demuestra aprendizaje, empleabilidad ni disposición a pagar.", en: "Software adoption does not establish learning, employability or willingness to pay." } },
  infrastructure: { label: "World Bank · Private Participation in Infrastructure", url: "https://ppi.worldbank.org/en/ppi", observation: { es: "El registro de proyectos permite observar compromisos de capital en transporte, energía, agua y otras infraestructuras.", en: "Project records show capital commitments across transport, energy, water and other infrastructure." }, limit: { es: "La base cubre un ámbito de países y proyectos específico; compromiso financiero no equivale a obra terminada.", en: "The database covers a specific set of countries and projects; a financial commitment is not a completed asset." } },
  robotics: { label: "IFR · World Robotics 2025", url: "https://ifr.org/worldrobotics/report-2025", observation: { es: "La IFR distingue robots industriales, de servicio y médicos. Esta ficha estudia máquinas físicas y usos fuera de procesos industriales establecidos.", en: "IFR distinguishes industrial, service and medical robots. This thesis studies physical machines and uses beyond established industrial processes." }, limit: { es: "El tamaño de muestra y la madurez difieren entre categorías. Un prototipo no es despliegue comercial.", en: "Sample size and maturity vary by category. A prototype is not commercial deployment." } },
  crypto: { label: "BIS · Annual Economic Report 2025, Chapter III", url: "https://www.bis.org/publications/aer-2025", observation: { es: "El BIS analiza tokenización, liquidación y stablecoins, junto con sus restricciones monetarias y operativas.", en: "BIS examines tokenization, settlement and stablecoins alongside their monetary and operational constraints." }, limit: { es: "La adopción de una infraestructura no garantiza demanda de un token específico ni seguridad de custodia.", en: "Infrastructure adoption does not guarantee demand for a particular token or safe custody." } },
};
