import type { Movement, ManagerStatus } from './capital/types.ts';
import type { TrendPhase, TrendEvidence } from './catalog.ts';
type MethodologyCopy = {
  registryStates: Record<ManagerStatus, string>; includedReport: string; title: string; intro: string; editorial: string; editorialNote: string; phaseDefinitions: Record<TrendPhase, string>; evidenceDefinitions: Record<TrendEvidence, string>;
  positions: string; positionNote: string; positionControls: string[]; movementPending: string; universe: string; universeNote: string; membership: string; movements: string; movementNote: string; states: Record<Movement, string>; controls: string[]; coverage: string; coverageNote: string; source: string; sourceNote: string; back: string;
};
export const trendsMethodologyCopy: Record<'es' | 'en', MethodologyCopy> = {
  es: {
    registryStates: { ACTIVE: "Activo", NOTICE_ONLY: "Aviso sin recuento separado", TEMPORARILY_UNAVAILABLE: "Temporalmente no disponible", EXCLUDED: "Excluido", RETIRED: "Retirado" }, includedReport: "Reporte que incluye las posiciones",
    title: 'Cómo se construye Tendencias', intro: 'Un marco editorial para conectar cambios estructurales con evidencia, captura de valor y riesgos. El capital divulgado es una observación limitada de posiciones históricas.',
    editorial: 'Fase y evidencia', editorialNote: 'La fase describe la madurez de la aplicación que se analiza; la evidencia describe cuánto respalda el cambio observado. Son juicios editoriales fechados, no mediciones de rentabilidad, valoraciones de una empresa ni una secuencia inevitable. Sectores maduros pueden contener aplicaciones emergentes. Cada ficha enlaza su fuente y delimita qué demuestra.',
    phaseDefinitions: { emerging: 'Pruebas y prototipos; adopción comercial todavía acotada.', adoption: 'Despliegue fuera del piloto, con difusión desigual y modelos económicos por contrastar.', monetization: 'Ingresos y usos comerciales observables; márgenes y retorno del capital todavía en evaluación.', scale: 'Uso comercial extendido y cadenas de suministro operativas. La competencia y los ciclos siguen importando.', mature: 'Actividad consolidada, con crecimiento más ligado a renovación, penetración o ciclo que a una tecnología recién desplegada.' },
    evidenceDefinitions: { limited: 'Casos aislados o evidencia difícil de contrastar; extrapolación elevada.', growing: 'Datos observables, pero alcance parcial, resultados heterogéneos o vínculo económico todavía incierto.', strong: 'Series o registros sistemáticos con alcance amplio en la dimensión estudiada. No demuestra retornos futuros ni valida cada subsegmento.' },
    positions: 'Cómo se calculan las coincidencias', positionNote: 'Las coincidencias se calculan desde las posiciones del trimestre indicado con tablas utilizables. Ordenan compañías por presencia entre gestores, con clases de acciones separadas. No describen decisiones recientes de compra o venta.',
    positionControls: [
      'Cada grupo declarante cuenta una vez por valor, independientemente de los dólares divulgados. El porcentaje divide ese recuento por los grupos con tablas utilizables. La cobertura del universo divide esos grupos divulgados por los esperados. Las carteras amplias tienen más oportunidades de coincidir; este recuento no mide convicción ni peso en cartera.',
      'GOOG y GOOGL se muestran por separado. Cualquier recuento por emisor requiere una correspondencia verificada y la unión de gestores; nunca suma ambas clases. Las opciones y el principal de deuda se excluyen de las coincidencias de acciones.',
      'Una enmienda que sustituye el reporte reemplaza las posiciones anteriores. Si una enmienda adicional se solapa de forma ambigua, el miembro sigue siendo esperado, pero su tabla no aporta posiciones ni entra en el denominador divulgado. No se interpreta como una cartera vacía.',
      'Los avisos 13F-NT no son carteras independientes. Cuando ambas portadas acreditan un reporte receptor, las posiciones se cuentan desde ese reporte una vez. El registro conserva avisos, miembros no disponibles y entidades excluidas con su estado.',
      'Los empates se resuelven por nombre e identificador del valor; se muestran hasta ocho valores. Los tickers requieren una correspondencia verificada con emisor y clase. Los vínculos con tendencias son editoriales y no revelan la tesis del gestor. Cada enlace SEC de la tabla abre uno de los filings que respalda esa presencia; la evidencia conservada permite reconstruir el recuento completo.',
    ],
    movementPending: 'El sistema de comparación entre trimestres existe, pero sus resultados todavía no se publican. Requiere controles adicionales de enmiendas, eventos corporativos, cambios de identificador y perímetro del declarante. Hasta completar la revisión del conjunto, las vistas agregadas de movimientos permanecen fuera de la página.',
    universe: 'Un universo explícito y versionado', universeNote: 'LHI Superinvestor Universe v1 es una selección editorial de grupos declarantes, no una muestra representativa de todos los gestores ni una clasificación de habilidad. Se exige identidad legal SEC, ocho trimestres de historial —o continuidad documentada hacia una matriz—, una estructura interpretable y ausencia de duplicación entre grupos. Combina carteras concentradas y diversificadas y distintos estilos. La membresía se fija antes de calcular coincidencias. Las entidades excluidas y los avisos permanecen en el registro para hacer visible el alcance.', membership: 'Incluido',
    movements: 'Comparaciones entre trimestres', movementNote: 'Se comparan cantidades de una misma exposición, no variaciones del valor de mercado. Cada comparación requiere revisar los dos filings y los eventos corporativos. Sin esa revisión se conserva INDETERMINATE. Un cambio de acciones no demuestra una compra o venta ejecutada en una fecha o precio concreto.',
    states: { NEW: 'Aparece una posición tras comprobar una ausencia comparable en el trimestre previo.', INCREASED: 'La cantidad aumenta después de aplicar los ajustes documentados.', UNCHANGED: 'La cantidad ajustada coincide; no implica que no hubiera operaciones intratrimestre.', REDUCED: 'La cantidad disminuye después de aplicar los ajustes documentados.', EXITED: 'Desaparece una posición tras verificar comparabilidad, identidad y posibles omisiones.', INDETERMINATE: 'Falta información o revisión suficiente para clasificar el cambio.' },
    controls: [
      'Cada accession se procesa una vez. Una enmienda de restatement sustituye el contenido anterior; una de nuevas posiciones se añade solo cuando no hay solapamientos ambiguos. Enmiendas incompletas o de tipo desconocido bloquean la comparación.',
      'Splits, reverse splits, conversiones y cambios de CUSIP o clase requieren un ajuste documentado. La clave de valor es CUSIP más tipo de instrumento: distintas abreviaturas de una clase no crean valores nuevos. GOOG y GOOGL permanecen separados. El recuento por emisor, cuando se usa, requiere un mapping explícito y la unión de gestores, nunca la suma de ambas clases.',
      'Puts, calls, posiciones largas y principal de deuda se mantienen separados. Esta tabla muestra exposición larga; no mezcla opciones con acciones.',
      'Filings ausentes, tablas que no cuadran con la portada, avisos 13F-NT, tratamiento confidencial y cambios de declarante no se convierten en salidas. Un aviso solo enlaza al reporte receptor cuando ambas portadas acreditan la relación; las posiciones se cuentan desde ese reporte una vez. Un cambio de perímetro entre trimestres bloquea movimientos. Las omisiones permitidas y los eventos de identificador necesitan revisión.',
      'El denominador principal es el número de grupos elegibles con tablas divulgadas y validadas en el trimestre. La cobertura divide esos filings disponibles por los esperados; avisos, pendientes y fallos se muestran por separado. Cada grupo cuenta una vez, independientemente de sus dólares. Las carteras más amplias tienen más oportunidades de coincidir; el recuento no mide convicción ni elimina ese sesgo. Una tabla validada permite observar presencia; no garantiza que no existan posiciones confidenciales u omisiones permitidas.',
      'Más compartidas ordena por coincidencia; las vistas de movimientos ordenan por su recuento. Mayor desacuerdo usa el menor entre gestores que aumentan o inician y gestores que reducen o salen. No mide intensidad ni convicción. Las vistas de movimientos permanecen pendientes mientras la revisión del conjunto sea incompleta: una muestra revisada no puede presentarse como las mayores variaciones. Empates por nombre y clase; hasta ocho valores por vista.',
      'Los tickers se publican solo con correspondencia verificada entre emisor y clase. Los vínculos con tendencias describen actividades económicas de forma editorial; nunca las motivaciones del gestor.',
    ],
    coverage: 'Fechas, cobertura y disponibilidad', coverageNote: 'El trimestre de las posiciones, la fecha del filing y la consulta a SEC son fechas distintas. Form 13F divulga valores de la lista SEC, principalmente acciones cotizadas en EE. UU., ETF y ciertos instrumentos convertibles u opciones. No muestra efectivo, toda la deuda, activos privados, todas las acciones extranjeras ni posiciones cortas. Se presenta normalmente hasta 45 días después del trimestre, con ajustes de calendario. No es una cartera completa ni actual. La cobertura de posiciones cuenta únicamente tablas verificadas; localizar un filing no valida su contenido. Una actualización fallida conserva el último snapshot válido con su fecha original y señala el fallo; si no existe un snapshot verificable, muestra No disponible; cobertura incompleta muestra Cobertura parcial. Tras 14 días sin consulta o al vencer el siguiente periodo de divulgación se muestra Actualización pendiente. Nunca se presenta otro trimestre como si fuera el solicitado.',
    source: 'Fuente y trazabilidad', sourceNote: 'SEC EDGAR es la fuente primaria de los filings. Se conservan documentos de origen, identificadores, fecha de consulta y hashes para reproducir el snapshot. Las tablas se validan contra el total de entradas y valor de la portada. No se utilizan agregadores como autoridad. Las fuentes editoriales figuran en cada tendencia.', back: 'Volver al radar',
  },
  en: {
    registryStates: { ACTIVE: "Active", NOTICE_ONLY: "Notice without separate counting", TEMPORARILY_UNAVAILABLE: "Temporarily unavailable", EXCLUDED: "Excluded", RETIRED: "Retired" }, includedReport: "Report including the holdings",
    title: 'How Trends is built', intro: 'An editorial framework connecting structural change with evidence, value capture and risks. Disclosed capital is a limited observation of historical holdings.',
    editorial: 'Phase and evidence', editorialNote: 'Phase describes the maturity of the application under study; evidence describes the support for the observed change. These are dated editorial judgments, not return measurements, company valuations or an inevitable sequence. Mature sectors can contain emerging applications. Each profile links its source and states what it establishes.',
    phaseDefinitions: { emerging: 'Tests and prototypes; commercial adoption remains narrow.', adoption: 'Deployment beyond pilots, with uneven diffusion and economic models still to be tested.', monetization: 'Observable revenue and commercial use; margins and capital returns remain under evaluation.', scale: 'Widespread commercial use and operating supply chains. Competition and cycles still matter.', mature: 'Established activity, with growth more closely tied to renewal, penetration or cycles than to a newly deployed technology.' },
    evidenceDefinitions: { limited: 'Isolated cases or evidence that is hard to verify; substantial extrapolation.', growing: 'Observable data, but partial scope, mixed outcomes or an uncertain economic connection.', strong: 'Systematic series or records with broad coverage of the dimension studied. This does not establish future returns or validate every subsegment.' },
    positions: 'How holdings overlap is calculated', positionNote: 'Overlap is calculated from usable holdings tables for the stated quarter. Companies are ordered by presence across managers, with share classes kept separate. It does not describe recent buying or selling decisions.',
    positionControls: [
      'Each reporting group counts once per security, regardless of disclosed dollars. The percentage divides that count by groups with usable tables. Universe coverage divides those disclosed groups by expected groups. Broader portfolios have more opportunities to overlap; this count does not measure conviction or portfolio weight.',
      'GOOG and GOOGL are shown separately. Any issuer count requires a verified mapping and the union of managers; it never adds the two classes. Options and debt principal are excluded from share overlap.',
      'A restatement replaces the preceding holdings. If an additive amendment has ambiguous overlaps, the member remains expected, but its table contributes neither positions nor a place in the disclosed denominator. It is not interpreted as an empty portfolio.',
      '13F-NT notices are not independent portfolios. When both covers substantiate a receiving report, holdings count once from that report. The registry retains notices, unavailable members and excluded entities with their status.',
      'Ties use company name and security identifier; up to eight securities are shown. Tickers require a verified issuer and share-class match. Trend links are editorial and do not reveal a manager’s thesis. Each table SEC link opens one filing supporting that presence; retained evidence can reconstruct the complete count.',
    ],
    movementPending: 'The quarterly comparison system exists, but its results are not yet published. It requires additional checks for amendments, corporate actions, identifier changes and the reporting perimeter. Until the whole set has sufficient review, aggregate movement views remain outside the page.',
    universe: 'An explicit, versioned universe', universeNote: 'LHI Superinvestor Universe v1 is an editorial selection of reporting groups, not a representative sample of all managers or a skill ranking. Eligibility requires a verifiable SEC legal identity, eight quarters of history—or documented continuity into a parent—an interpretable structure and no duplicate groups. It includes concentrated and diversified portfolios and different styles. Membership is fixed before calculating overlap. Excluded entities and notices remain in the registry to make the scope visible.', membership: 'Included',
    movements: 'Quarterly comparisons', movementNote: 'We compare quantities of the same exposure, not changes in market value. Every comparison requires reviewing both filings and corporate actions. Without that review, INDETERMINATE is preserved. A share change does not establish a purchase or sale at a specific time or price.',
    states: { NEW: 'A position appears after confirming a comparable absence in the preceding quarter.', INCREASED: 'Quantity increases after documented adjustments.', UNCHANGED: 'Adjusted quantities match; this does not imply no trading within the quarter.', REDUCED: 'Quantity decreases after documented adjustments.', EXITED: 'A position disappears after checking comparability, identity and possible omissions.', INDETERMINATE: 'Information or review is insufficient to classify the change.' },
    controls: [
      'Each accession is processed once. A restatement replaces the preceding content; a new-holdings amendment is added only without ambiguous overlaps. Incomplete amendments and unknown amendment types block comparisons.',
      'Splits, reverse splits, conversions and CUSIP or class changes require a documented adjustment. The security key is CUSIP plus instrument type: different class abbreviations do not create new securities. GOOG and GOOGL stay separate. Issuer-level counts, when used, require an explicit mapping and the union of managers, never the sum of both classes.',
      'Puts, calls, long positions and debt principal remain separate. This table shows long exposure; it does not mix options with shares.',
      'Missing filings, tables that do not reconcile with the cover, 13F-NT notices, confidential treatment and reporting-manager changes do not become exits. A notice links to a receiving report only when both covers substantiate the relationship; holdings are counted once from that report. A reporting-perimeter change between quarters blocks movements. Permitted omissions and identifier events need review.',
      'The main denominator is the number of eligible groups with disclosed, validated tables for the quarter. Coverage divides available filings by expected filings; notices, pending filings and failures are shown separately. Each group counts once, regardless of dollars. Broader portfolios have more opportunities to overlap; the count neither measures conviction nor removes that bias. A validated table establishes observed presence, not the absence of confidential holdings or permitted omissions.',
      'Most shared orders by overlap; movement views order by their counts. Most disagreement uses the smaller of managers increasing or initiating and managers reducing or exiting. It does not measure intensity or conviction. Movement views remain pending while review of the whole set is incomplete: a reviewed subset cannot be presented as the largest changes. Ties use name and class; up to eight securities per view.',
      'Tickers appear only after the issuer and share class have been matched confidently. Trend links describe economic activities editorially; they never describe a manager’s motives.',
    ],
    coverage: 'Dates, coverage and availability', coverageNote: 'The holdings quarter, filing date and SEC retrieval time are different dates. Form 13F discloses SEC-listed securities, primarily US-listed shares, ETFs and certain convertible instruments or options. It does not show cash, all debt, private assets, all foreign shares or short positions. Filing is normally due within 45 days of quarter-end, adjusted for the calendar. It is neither a complete nor a current portfolio. Holdings coverage counts only verified tables; locating a filing does not validate its contents. A failed refresh retains the last valid snapshot with its original date and marks the failure; without a verifiable snapshot, it shows Unavailable; incomplete coverage shows Partial coverage. After 14 days without retrieval or when the next disclosure period becomes due, Update pending appears. A different quarter is never presented as the requested one.',
    source: 'Sources and traceability', sourceNote: 'SEC EDGAR is the primary filing source. Original documents, identifiers, retrieval dates and hashes are retained to reproduce the snapshot. Tables are reconciled with cover-page entry and value totals. Aggregators are not used as authorities. Editorial sources appear in each trend.', back: 'Back to the radar',
  },
};
