"""Explicit post-result interpretation; never changes the preregistered protocol."""
import json
from pathlib import Path

BASE=Path(__file__).resolve().parent
def read(name): return json.loads((BASE/name).read_text())
def save(name,x): (BASE/name).write_text(json.dumps(x,ensure_ascii=False,indent=2,allow_nan=False)+'\n')

d=read('dimension-value.json')
d['concordance']['verdict']='PASS'
d['concordance']['interpretation']='All three categories occur: HIGH488/MEDIUM1317/LOW125. LOW identifies125 opposed-family observations, all TRANSITION; HIGH includes both favorable agreement and adverse/stress agreement. It adds a descriptive type of agreement, not direction, certainty, probability or predictive skill. MEDIUM dominance68.24% limits granularity; prospective user comprehension remains unmeasured.'
d['uncertainty']['verdict']='PASS'
d['uncertainty']['interpretation']='LOW794/MEDIUM367/HIGH769; only813/1930 observations follow the nominal inverse of concordance. All125 LOW-concordance observations have LOW uncertainty: conflicting families can still select one unambiguous regime. HIGH is conditional rule ambiguity, not market uncertainty or error probability. It changes28.41% of pairs; preserve qualitative context and assess presentation prospectively.'
d['value_scope']='PASS means demonstrated distinct descriptive information with existing evidence; it does not certify user benefit or predictive validity.'
save('dimension-value.json',d)

r=read('redundancy-analysis.json');r['status']='PASS'
r['pairs']['participation_vs_leadership'].update(classification='MODERATE_INCREMENTAL',reason='Breadth and relative group leadership encode different equity structure; removing either loses the selective branch.452/649 changed sessions include46/243 disjoint effects. This is structural contribution within the same equity family; independent economic utility remains unestablished.')
r['pairs']['volatility_level_vs_momentum'].update(classification='MODERATE_INCREMENTAL',reason='Fast moves occur below VIX20 on93 sessions, while VIX>=25 persists without fast momentum on248. Removing both momentum horizons removes12 contractual STRESS sessions and changes34 additional non-overlapping outcomes. These are distinct level/change semantics within one volatility family, not a new vote.')
r['pairs']['correlation_level_vs_deterioration'].update(classification='WEAK_INCREMENTAL',reason='Removing correlation deterioration changes32/1930 decisions; removing correlation level changes142, with no overlap in changed decisions. High correlation appears without high delta240 times and high delta below high correlation125 times. Deterioration is structurally distinct but has little direct adjudication effect; no evidence supports removal or a new independent family.')
ab=read('ablation.json')
classes={'positive_5':'MODERATE_INCREMENTAL','positive_21':'MODERATE_INCREMENTAL','leadership_gap':'MODERATE_INCREMENTAL','vix_level':'MODERATE_INCREMENTAL','jump_1':'WEAK_INCREMENTAL','jump_5':'WEAK_INCREMENTAL','vx_slope':'MODERATE_INCREMENTAL','correlation_level':'MODERATE_INCREMENTAL','correlation_deterioration':'WEAK_INCREMENTAL','participation':'MODERATE_INCREMENTAL','volatility_momentum':'MODERATE_INCREMENTAL'}
r['condition_assessment']={k:{'classification':v,'regimes_changed':ab['reduced'][k]['periods']['ALL']['regimes_changed'],'stress_not_retained':ab['reduced'][k]['periods']['ALL']['stress_state_not_retained'],'pillar_states_changed':ab['reduced'][k]['pillar_states_changed'],'economic_utility':'INDETERMINATE','action':'RETAIN_CANONICAL; no independent utility or safe-removal conclusion follows from structural contribution'} for k,v in classes.items()}
r['classifications_are_post_result_interpretation']=True
r['minimum_sufficient_engine']='C03 unchanged is the smallest currently justified complete product contract. No tested reduction establishes preservation of practically all valuable information because utility is not independently labelled. This is a conservative delivery decision, not proof of unique mathematical minimality.'
save('redundancy-analysis.json',r)

s=read('threshold-sensitivity.json')
s['interpretation']={'largest_observed_boundary':'k_broad +/-1 changes108/97 of1930 states (5.60%/5.03%); in already-seen F3_TEST41/31 of420 (9.76%/7.38%). This is the priority boundary for prospective adjudication of breadth, not automatic retuning.',
 'continuous_thresholds':'Each single +/-5% continuous perturbation changes at most48/1930 decisions (2.49%, v_watch lower). Low aggregate disagreement does not prove safety at rare events.',
 'zero_effect_does_not_mean_unreachable':'curve_flat upper, curve_adverse lower and rho_floor lower have zero historical regime effect for this perturbation. Branch activity, overlapping predicates and limited sample matter; canonical conditions remain intact.',
 'scale_caution':'One sector is12.5% of k_broad=8; integer and continuous perturbation elasticities are not directly comparable.',
 'decision':'NO_RECALIBRATION. No predefined external utility/noise labels justify selecting any tested setting; all26 results retained.'}
save('threshold-sensitivity.json',s)

b=read('benchmarks.json')
b['missing_robustness']={'evidence':'challengers.test.mjs: explicit missing/undefined/nonfinite and calendar-gap witnesses; no missing rows occur in the1930 eligible core baseline.',
 'B0':'Only actual archived observations; no interpolation.', 'B1':'Requires current finite VIX only; valid volatility namespace may exist while C03 is incomplete.',
 'B2':'Requires VIX and admissible participation before any stress override.', 'B3':'Requires both named lineage descriptors before STRESS override. Immediate means no temporal confirmation after input eligibility; not bypass of missing core evidence.',
 'B4':'No prior fill at first row, absent prior regime or non-adjacent session.', 'B5':'Unchanged public input contract and110 Sweeper adversarial checks.'}
b['conclusion']='B1 is smoother but supplies volatility only. B2 and B3 discard equity leadership/breadth distinctions; B3 retains all source maintenance. B4 simply delays481 canonical changes, including18 stress entries. None establishes preservation of the complete descriptive contract at lower cost. V1 cannot be ranked on missing historical evidence. Keep C03; do not claim statistically proven superiority.'
save('benchmarks.json',b)

def cost(candidate,gain,stability,source,dependency,state,rule,threshold,maintenance,failure,verdict):
 return {'candidate':candidate,'information_gain':gain,'stability_gain':stability,'new_data_source':source,'new_runtime_dependency':dependency,'new_state':state,'new_rule':rule,'new_threshold':threshold,'maintenance_obligation':maintenance,'new_failure_modes':failure,'verdict':verdict}
matrix=[
 cost('C03 unchanged','Retains full accepted equity/volatility evidence contract','Baseline observed24.94% turnover',False,False,False,False,False,'Existing source/calendars/version contracts','Existing explicit INCOMPLETE boundary','KEEP'),
 cost('B1 VIX only','Loses all equity structure; descriptive volatility only','13.17% turnover',False,False,False,'Simplified4 volatility labels','3 retained VIX boundaries','Lower acquisition cost','CALM_VOL could be misread as broad equity participation','BENCHMARK_ONLY'),
 cost('B2 VIX+breadth','Loses leadership/fragility/curve and selective reachability','21.31% turnover',False,False,False,'Coarse4-state adjudication','Retained levels/counts','Two existing provider families','Breadth alone can mask defensive leadership or curve stress','BENCHMARK_ONLY'),
 cost('B3 family vote','Collapses useful internal risk-on structure','14.77% turnover',False,False,False,'4 final rules','Retains all core thresholds','No upstream reduction','Same acquisition cost with coarser meaning','BENCHMARK_ONLY'),
 cost('B4 previous state','No new information; delays current evidence','24.95% turnover on1928 pairs',False,False,'One prior-state memory','Lag current output',False,'Canonical plus memory lifecycle','Stress delay and stale display','REJECT_FOR_PRODUCT'),
 cost('11 reduced engines','Documented lost conditions; utility loss unlabelled','See all/year/F3 in ablation.json',False,False,False,'Explicit condition removal','No new threshold','Separate methodology versions and golden fixtures','Silent change in regime meaning if promoted','CHALLENGER_ONLY'),
 cost('26 threshold perturbations','No new information source','Variable; no selection target',False,False,False,False,'One altered existing parameter each','Calibration governance','Overfitting already-seen history','SENSITIVITY_ONLY'),
 cost('H1 confirmation','No new evidence;138 episodes withheld','12.13% turnover,356 contradicted holds',False,False,'Held state + pending candidate','One additional non-stress confirmation','Confirmation length2 observations','State reset, calendar/version/missing lifecycle','Delayed legitimate changes;77 stale risk-on sessions; prolonged stress exits','CHALLENGER_ONLY'),
 cost('P1 observed persistence','Adds descriptive observed age and named recovery duration','Does not alter transitions',False,False,'Diagnostic counters only','No adjudication rule',False,'Censoring and prospective reset semantics if later promoted','Users may misread long duration as confidence; batch output not live-ready','DIAGNOSTIC_ONLY'),
 cost('Cross-asset credit/rates/USD/commodities','Plausible distinct economics; no admitted paired PIT evidence','Not established','Would need admitted source/vintage contract','No selected package','No proposed taxonomy','Would require methodology proposal','Not selected','Licensing, calendars, revisions, adjusted-price basis','Credit ETF duration contamination; USD quote ambiguity; retrospective revisions','PARK_RESEARCH_ONLY'),
 cost('PFL component diagnostic','Portfolio topology within same equity family; no independent family','96 cluster-count changes; not a regime filter',False,'Existing PFL code if promoted','Diagnostic only','No canonical proposal','Existing PFL clustering/window assumptions','Portfolio weights/universe/252-return provenance','Portfolio-specific component could be mistaken for market state','RESEARCH_ONLY'),
 cost('BTC/GLD retained satellites','Native contextual flows; limited25/20 rows','Not a stability rule',False,False,False,False,False,'Existing optional-source calendar/unit contracts','Missing fund cells, GLD flow proxy and warmup; narrative utility unmeasured','KEEP_CONTEXTUAL_ONLY'),
 cost('Concordance/uncertainty/data-quality retained','Distinct agreement, rule ambiguity and evidence eligibility','No smoothing claim',False,False,False,False,False,'Existing dimension definitions','Ordinal names mistaken for probability or future risk','KEEP')]
save('complexity-matrix.json',{'scope':'Post-result qualitative accounting; no fabricated benefit decimals','canonical_changes':0,'matrix':matrix,'minimum_sufficient_engine':r['minimum_sufficient_engine']})

catalog=[]
for name in ['B1_VIX_ONLY','B2_VIX_BREADTH','B3_FAMILY_VOTE','B4_PREVIOUS']:catalog.append({'id':name,'type':'benchmark'})
for name in ab['reduced']:catalog.append({'id':'R_MINUS_'+name.upper(),'type':'reduced_condition_engine'})
for name in s['variants']:catalog.append({'id':'S_'+name,'type':'single_parameter_sensitivity'})
catalog += [{'id':'H1_CONFIRM_ONE_ADDITIONAL_OBSERVATION','type':'temporal_challenger'},{'id':'P1_OBSERVED_EVIDENCE_PERSISTENCE','type':'diagnostic_challenger'},{'id':'PFL_EQUAL_WEIGHT_11_SECTOR_COMPONENTS','type':'diagnostic_challenger'}]
assert len(catalog)==44
save('challenger-catalog.json',{'count':len(catalog),'counting_rule':'4 simple comparators +11 reduced engines +26 single-parameter configurations +H1 +P1 +1 PFL component configuration. Canonical B5, archived B0 and11 mechanical INCOMPLETE checks are excluded. Reapplying the same26 parameter settings to comparator/H1 outputs does not add identities.','runtime_integrations':0,'catalog':catalog})
save('prospective-validation-design.json',{'status':'DESIGN_ONLY_NOT_ACTIVATED','canonical_candidate':'Accepted Sweeper C03 unchanged','start_condition':'New Control Tower authorization; Maintainer/Designer/cutover not executed by Groweer',
 'capture_contract':['Preserve raw response bytes and SHA, observation time, source publication/availability evidence, retrieval/ingestion time, asOf cutoff, source/schema/calendar/engine/parameter versions.','Log unavailable and revised observations; never relabel R2 as point-in-time. R0 admission only with actual preserved contemporaneous vintage evidence.','Shadow C03 and frozen H1/P1 on identical admitted observations; no product-route wiring or live trades.'],
 'evidence_stopping_conditions':{'distinct_adjudicable_regime_transitions':100,'distinct_conflicting_family_episodes':100,'distinct_material_volatility_episodes':60,'stress_branch_coverage':'Both absolute-level and joint level/momentum/curve branches must have real admissible observations. Rare subtypes remain unresolved until observed; no calendar timeout converts absence to PASS.',
 'rationale':'100 independent binary adjudications gives worst-case standard error0.5/sqrt(100)=0.05; a rough two-standard-error range is0.10. For60 independent zero-miss events, the one-sided95% binomial upper rate1-0.05**(1/60) is about4.87%. These are planning calculations, not performance guarantees. Serial dependence and clustered stress reduce effective evidence; count distinct episodes and report dependence/sensitivity instead of claiming these bounds blindly.',
 'calendar_duration':'Report elapsed calendar span and variety of conditions; do not stop because an arbitrary number of months passed.'},
 'adjudication':['Predefine contemporaneous semantic questions: broad versus selective participation, genuine level/change disagreement, stale held state, correct missingness. Do not judge by future PnL/returns.','Two independent reviews of raw evidence with candidate names hidden where feasible; record disagreement and rationale, no forced true-regime label.','For each H1 suppression, determine whether omitted information was useful; report all delays and stale risk-on labels, stress exits, first-admissible and missing/gap/version cases.','Measure P1 comprehension versus H1 retention in an separately authorized product study before any UI decision.','For satellites, record actual authorized narrative-block changes, comprehension and missingness; current sign proxies do not establish narrative utility.'],
 'promotion_gate':'No stress-entry delay or missing-data masking; demonstrated semantic benefit and acceptable independently adjudicated delay cost with all relevant failure modes. If unmet, retain C03 and park challengers. Require Control Tower approval for any methodology change.',
 'cross_asset_reopening':'Admitted licensed data with fixed field basis and vintages, paired eligible dates, explicit economic role distinct from equity/implied-vol lineage, and ablation against C03 before proposing a new core family.',
 'PFL_reopening':'Explicit portfolio/universe/weights and fixed minimum windows; same-family diagnostics only unless independent economic parents are demonstrated. Never import fragilityScore wholesale.'})
save('growth-findings.json',{'status':'CLOSED','unresolved':[], 'findings':[
 {'id':'G-HARNESS-01','severity':'MEDIUM','issue':'Native benchmark labels initially compared directly with C03, overstating disagreements and dropping matrix rows.','repair':'Keep native persistence, compare B1-B3 on explicit common coarse namespace and union matrix labels.','verification':'Independent recomputation735/767/551 coarse disagreements and12/12/0 unmatched contractual stress observations.','status':'CLOSED'},
 {'id':'G-HARNESS-02','severity':'MEDIUM','issue':'B2 null/omitted participation initially bypassed the explicit missing sentinel.','repair':'Require an admissible participation enum before classification.','verification':'challengers.test.mjs missing/undefined/invalid participation cases.','status':'CLOSED'},
 {'id':'G-HARNESS-03','severity':'MEDIUM','issue':'B3 empty/single-family map could pass vacuous vote predicates.','repair':'Require both named eligible family descriptors before stress/vote rules.','verification':'challengers.test.mjs empty/partial/unavailable family cases.','status':'CLOSED'},
 {'id':'G-HARNESS-04','severity':'LOW','issue':'P1 censored recovery duration initially mixed observed-session count and elapsed intervals.','repair':'Use final_index-start for elapsed and separately label observed_sessions.','verification':'Read-only review plus explicit censored duration accounting.','status':'CLOSED'}],
 'accepted_candidate_repairs_modified':0,'parked_research_limitations':['No daily comparable V1 historical archive','No fresh/PIT/OOS validation','No independent regime-noise truth or user-utility labels','Short BTC/GLD native windows; actual V2 narrative frequency unmeasurable','Cross-asset vintage/licensing/field-basis gaps','PFL same-family and portfolio-dependent;117 early windows below252 returns'],
 'gate_policy':'These limitations prevent challenger promotion claims; they do not block stabilization of the accepted unchanged canonical candidate. Maintainer authorization remains NO.'})
print(json.dumps({'status':'PASS','canonical':'KEEP','hysteresis':'CHALLENGER_ONLY','persistence':'DIAGNOSTIC_ONLY','challengers':44,'unresolved':[]}))
